### ISSUE TITLE
Feature Request - Sub Warehouses

### ISSUE THREAD

**Issue by ptnw** [frappe/erpnext#1008]
As ERPNext does not have the "Bin or Location" feature, can you create a sub-warehouse feature. Sub-warehouses should fall under the default warehouse so when extracting report for default warehouse it will contain all inventory including inventory in all sub-warehouses.

**Comment by David-at-GitHub** [comment]
@rmehta Good day, I would like to follow-up on this Issue. Is there meanwhile a Bin Location feature available for ERPNext? By Bin Location I mean sub-hierarchies for the Main-Warehouses. So multiple Bins would be created below a Warehouse. Bins could contain attributes, such as exact location within the Warehouse (e.g. row 3, shelf 5, level 10). They also could have special characters, such as Validations not to store any Items from Item Group ABC.

When creating any Stock Movement Transactions (e.g. Delivery, Goods Issue, ...), user would need to select the Bin Location(s) per Warehouse. Also movements from one into another Bin Location would be possible.

Thanks, David

**Comment by rmehta** [comment]
@cgpurbaugh started something https://github.com/frappe/erpnext/pull/3983 but I think its not developed.

Not on our list as of now, would you be interested in sponsoring this?

**Comment by David-at-GitHub** [comment]
Thanks. It's not top priority right now, still in evaluation for everything. But it would be interesting in future. I know that this might be important for Distributors.

**Comment by alikhoja** [comment]
Hey ! any plans of developing the BIN feature.. How much it will cost in the sponsor development ?

**Comment by rmehta** [comment]
$500 ?

**Comment by cgpurbaugh** [comment]
We are looking to contribute to this, can anyone else help split the cost?

**Comment by rmehta** [comment]
@alikhoja @cgpurbaugh ready to split?

**Comment by alikhoja** [comment]
@rmehta @cgpurbaugh We have already customized that in-house :)

**Comment by rmehta** [comment]
@alikhoja can you share it?

**Comment by spiralni** [comment]
Please, I need a feature like this too. Can somebody help me?

**Comment by rmehta** [comment]
@spiralni are you looking for help to develop?

**Comment by cgpurbaugh** [comment]
Our company is willing to sponsor, but we don't have the budget for the full $500.  If anyone else can help split, we can get this going!

**Comment by jayants1-code** [comment]
**We would be willing to pitch in to sponsor this change - assuming the change supports our requirements. **Here is what we need

1. Ability to create/define  multiple warehouses  where warehouse ID has a 2-level structure  for example
 geo-region-specifier/warehouseNum . Each warehouse is associated with a physical delivery address  AND we can assign managers,workers etc to a warehouse . This allows transactions such as : Deliver items to warehouseId X or transfer items from WarehouseX to WarehouseY

2. Each ITEM has-a LOCATION attribute (ie Where is it located)? LOCATION  consists of a WarehouseID/BINNbr composite key.  The naming /numbering scheme for BINNbr can be any String the user chooses. <ROW>_<COL> , <brand>_REJECTS etc. We should be able to do queries such as : What items exist in warehouseX / BIN@<ROW>_<COL> . LIKE searches allowed. The BINNbr is really just a INDEXable attribute for the ITEM. **We really do not need a table for BINS.. as we are not going to assign any attributes to the BIN.  **

**Comment by cgpurbaugh** [comment]
Our company is willing to sponsor $200 worth.  @rmehta, what do you think of the requirements listed by @jayants1-code  ?

**Comment by rmehta** [comment]
$200, is certainly not do-able by us? Do you want to post it on the job board? https://community.erpnext.com/jobs

**Comment by cgpurbaugh** [comment]
I was saying that $200 would be our company's share.  I'm hoping that jayants1-code and possibly others will contribute as well.

**Comment by cgpurbaugh** [comment]
As we have previously discussed, the “bin feature” is something that is greatly needed in ERPNext.  I’m going to try to document our use case, which is something that will probably match up with other companies.  
 
We have several places where stock is stored and transferred:
•	Stock Room
•	Pre-Engineered Systems Department
•	Engineered Systems Department
•	Portable Systems Department
•	Electronics Department
•	Product Development & Engineering
 
In the manufacturing environment, majority of businesses will have similar inventory structures.  The necessity to accommodate this structure will be paramount to the consideration of many manufacturing establishments to implement ERPNext.
 
Each of these places has sublocations, resulting in approx. 900 locations total, so far (Our inventory system isn’t finished, we have completed the stock room and portable systems) The first solution that I tried was to make every location a warehouse, so we had 900 warehouses.  This works, but there are some drawbacks:
 
•	Since each location is a warehouse, and every warehouse is an account, we created 900 accounts for locations, which is redundant and unnecessary.  It caused the accounts tree to freeze when trying to view the warehouses. 
•	When attempting to complete a stock entry, you have to know what location the stock is in before selecting it, since the system doesn’t show quantities in all warehouses, just the warehouse you have selected.  It also doesn’t filter the warehouse list to only warehouses that have inventory of the selected item.
•	With the change to the stock balance report, we were temporarily unable to view balances in the warehouse, in order to print a stock balance report for workers to view locations and quantities of goods.
 
Since this did not work, my second attempt at a workaround was to create a new doctype called ‘location’ and add this to the stock entry. The problem with this is that I can’t add it to the Stock Ledger Entry or Bin doctypes to pull from the stock entry, and even if I could, I cannot add a column for location to the Balance Report.  So, I used a custom report based on the stock entry to attempt to create a balance report for everyone.  It didn’t work, because it shows transactional quantities, but not a true balance.
 
For a solution, two ideas were put forward:
 
•	Nested Warehousing:  Treats warehouses in the same way as accounts and item groups.  I no longer think this solves our problem, at least not without a lot of work.
•	Location Doctype:  What I created above.  What needs to be done:
o	Location Doctype Made.
	Location Name Field
	Warehouse Field
	Disabled Button
o	Location link added to Stock Entry Detail
	Actually two links, one under source warehouse, and one under target warehouse.  The user should be able to enable locations in the Stock Settings (As to not interfere with existing implementations)
	When the warehouse is selected, the locations would show that belong to that warehouse.  Also, the quantity of available items would show in the list (like batches do)
o	Location added to BIN and Stock Entry Ledger Doctypes
o	Reports updated
	Stock Ledger, Stock Balance, and Batch-Wise Balance History all should have a column added for Location.
 
The previous quoted price was $500, but I just wanted to be clear about the changes that need made.  Please review this letter, and let’s iron out the details, and get this going!  This is a vital enhancement that will be of great benefit for all companies with extensive inventory.  For Metalcraft, this is a very necessary change, and our implementation is on-hold due to the current deficiency.

**Comment by rmehta** [comment]
> For M______, this is a very necessary change, and our implementation is on-hold due to the current deficiency.

What matters is intent. There is always the *one last feature* you need to start. You should check again with your management.

**Comment by vrms** [comment]
seems this issue is stuck a little at present because the funding ($500 where quoted) by the core team
is not organized. I thought it might help to put it on bountysource, so that's what I did

https://www.bountysource.com/issues/1319544-feature-request-sub-warehouses

@cgpurbaugh @jayants1-code could you post the funds you are willing to put on this there?
@alikhoja if the solution you mention is production ready ... could you publish your development, or just wait for the bounties and be the one to get paid for the development

with 0 experience in bountysource I think the code provided has to be accepted by the funding parties before the funds are actually being transferred to a developer.

**Comment by Kulv3r** [comment]
Hi!
I'd like to build this feature. Will start today and hope to finish in a week maybe.
Free of charge.
https://discuss.erpnext.com/t/funding-campaign-feature-request-sub-warehouses-1008/11237/3

**Comment by rmehta** [comment]
@Kulv3r Awesome. Happy to help you along if you need. Just ping us.

**Comment by rmehta** [comment]
@Kulv3r Awesome. Happy to help you along if you need. Just ping us.

**Comment by ramielian** [comment]
@cpurbaugh are you ready to contribute your 200$ ? there is a bounty of 115$ already in place additional 200$ would make it faster
