### ISSUE TITLE
Doing Payments Receipt Entry for customer group

### ISSUE THREAD

**Issue by SaurabhGupta329** [frappe/erpnext#10206]
Currently in Payment Entry option, we can select only one customer/Supplier at a time for payments, Instead option should be provided to select a customer group or the debtors a/c? to make or receive a consolidated payment from more than one entities.
This is more helpful when an ecommerce scenario is there, where we have portal reseller who pays us on the behalf of all the customers together.

**Comment by umairsy** [comment]
In this use-case, you should create a Sales Invoice for the portal reseller only, because that's the income you should be booking. You can track details of the end customer in the other custom field of the sales order and invoice, just for your reference.

Payment Entry should be created for one party at a time only, hence you can also get the print format and acknowledgment for that party.

As mentioned above, we will suggest you to create a Sales Invoice for the portal, so that only required amount is booked as income and not the whole/MRP amount.
