### ISSUE TITLE
Expense Claim is rejected if claim amount is less than sanctioned amount

### ISSUE THREAD

**Issue by sebinmichael** [frappe/erpnext#10294]
Version: ERPNext: v8.7.1 (master)
Bug: Expense Claim is rejected if claim amount is less than sanctioned amount
Description:  When I use expense claims, for some reason, the claim amount cannot be lower than the sanctioned amount. I think someone reversed the code there by mistake. If I am sanctioned 10k but I only use 3k, it should ideally accept the entry, but the entry is rejected instead, stating that the sanctioned amount must be lesser than the claim. Thus does not make any logical sense. When reported via email, I got a reply which didn't make sense either, and I couldn't respond to the email. 
The response is quoted below:
"As per the maximum use-case, the sanctioned amount is less than the claimed amount, hence this validation. Can you please create a Github Issue so that we can covering this use-case as well." 

This has to be incorrect, but if true, it could mean that all the companies running ERPNext have employees who are used to claiming more than they are sanctioned by their employers. 

However, I think the maximum use case is for claiming less than the sanctioned amount. For example, if your boss allowed you ₹10,000 dinner with a client, and you spent only ₹5,000, the sanctioned amount is ₹10,000 and claim is ₹5,000. Then how is it that the sanctioned amount is always lesser than the claim amount?

**Comment by tundebabzy** [comment]
Hi @sebinmichael 
Sanctioned amount represents the amount sanctioned from the claim amount only. The reason for that validation is because it is the sanctioned amount (approved amount) that will be posted as into the general ledger. 

I think the way ERPNext behaves at present is correct. If the pre-determined sanctioned amount is more/less than the actual expense, the pre-determined amount has failed the test of recognition of liability (there must probable outflow of money *AND* costs can be reliably measured) and doesn't have accounting effect.
