### ISSUE TITLE
Rounded Total - Automate posting in the WriteOff account

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10377]
For now, the Rounded Total doesn't have any impact on the accounting.

As requested by the user, can we also enable the posting for the Rounded Total. The different amount between Grand Total and Rounded Total should be posted to Write Off account specified in the Company master.

Also, can we duplicate the Rounded Total functionality to the purchase cycle as well?

**Comment by agwldeepak** [comment]
For Purchase Invoices we are simply trying to feed into the system what is present in the Purchase Invoice.  If the user has rounded off the value we round off. If he has not rounded off the value we do not round off. The system should be flexible so that a user can make use of round of on a need basis. 
Also when we round off that is the same value that should be posted to the Customer/Supplier Ledger since we cannot have a different value on the invoice and a different one in our books. 
Either this or we can simply enable precision 0 for Currency so that we can round off on a need basis. Currently we are able to use Precision 1 to precision 9 for Currency datatype.
