### ISSUE TITLE
Signature custom field issue

### ISSUE THREAD

**Issue by OneiricIT** [frappe/erpnext#10516]
ERPNext: v8.8.4
Frappe: v8.7.10

Browsers: Chrome / MS Edge

When using the signature custom field, if you keep clicking in the same spot the image appears to shift upwards causing a paint roll effect as below.

![2017-08-23_20-08-06](https://user-images.githubusercontent.com/22227933/29611022-65d6c8ea-883f-11e7-89d2-6bbeef0deb6d.gif)

**Comment by rmehta** [comment]
@OneiricIT confirm the issue. its related to the JS library jsSignature. Maybe raise the issue there?

**Comment by partzsch** [comment]
@OneiricIT 
I´m not shure it has to do with the jSignature lib alone as the [example](https://willowsystems.github.io/jSignature/#/demo/) from there does not display this behavior. I think
It is because the canvas.js is not fully implementet in Frappe. Which brings us to [this threat](https://github.com/frappe/frappe/issues/5363) in the frappe section as the signature field is actually a frappe feature. let us please continue there to find a solution
