### ISSUE TITLE
Overwriting very large number of items (90,000) in upload

### ISSUE THREAD

**Issue by ianpkano** [frappe/erpnext#10582]
I am uploading data, it won't overwrite the data that I uploaded before. How do I overwrite all databases with my new files?

**Comment by ianpkano** [comment]
How can I erase data? I mean over 4,000 records? Can I delete and upload new or can I overwrite including mandatory fields. The system seems too rigid for retail, it doesn't take into account 90,000 stock items that might need to be re-arranged (item group), and updating 1 at a time is not a solution. I need to be able to overwrite a database file or be allowed to erase one and re-upload.

**Comment by rmehta** [comment]
@ianpkano yes the UI is not designed to upload 90,000 items together, you are better off writing a script for this.

**Comment by ianpkano** [comment]
I have a major issue updating new columns of information in a databse file.
I have items, I added suppliers (column of data) and uploaded to update the
file, the bulk system ignored my update Since I have over 95,000 records it
is imperative to update information in bulk!!!

**Comment by netchampfaris** [comment]
I think we can chunk operations, rather than doing it in a single query.
@achillesrasquinha Want to take this up?

**Comment by rmehta** [comment]
No push it to background (enqueue).

**Comment by felixvarghese** [comment]
Once issue I've seen in this area is with the user permissions manager. The user permissions manager has  Download and Upload functions, which are quite handy.

However, if you're uploading large numbers of permissions, the upload says it's successful and permissions are applied. But if you check the permissions, will see that permissions are not applied. If, for example, you have 5000 lines, when uploading, maybe only 3000 or so of the permissions will be applied. That's not much of a problem if permissions are simply added. But when uploading, all existing permissions are erased.

We've stopped using the download/upload function of the user permission manager because we don't know if it has reliably completed or not.

**Comment by nabinhait** [comment]
The new Data Import utility in version 10 run in the background and can handle large data. Closing this issue.
