### ISSUE TITLE
[Feature Request] Create new DocType/Tool for Label Printing

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#10581]
Discussion:
https://discuss.erpnext.com/t/print-label-according-to-quantity/27589

Case Scenario:
I want to print item labels from packing list. Issue here is that I am unable to print based on Quantity.

Suggested Implementation:

1. From Packing List DT, able to Make >> Item Labels
2. New Item Label DT is created, Fields from Packing List are duplicated and Item Table is populated based on Quantity. Duplication of Items and Batch Number are allowed.
3. From here, user is able to create necessary print format by using "for row" Jinja template.
4. No ledger entry is required. You can call this a tool.

**Comment by vrms** [comment]
that would be a very useful tool I believe. It's important thought that more labels are printed then needed because in practice it can always happen labels get damaged or spoiled.

From my experience you need to add +2 (per variant) plus 105% of the quantity (per variant)

So if you have 

- **20 Tshirts** in black, size L:   you get 20 + 2 + 20 x 105% = **23 labels**
- **5 Tshirts** in white, size M:   you get 5 + 2 + 5 x 105% = 7.25 ~ **7 labels** printed

**Comment by addymuliady** [comment]
This can be set in the "Label Printing" DT I think.

Please back a bounty. I will add mine when I have the funds.

https://www.bountysource.com/issues/48746501-feature-request-create-new-doctype-tool-for-label-printing

**Comment by rmehta** [comment]
@addymuliady please create a new bounty at https://erpnext.org/bounties. Also please add detailed specs and expected output.

**Comment by umairsy** [comment]
@addymuliady as suggested, please create a Bounty for this feature, and sponsor to get it developed on priority.

**Comment by fthobe** [comment]
@rmehta Hey, we partially solved this issue constructing a webtool for Dymo label printers. May this can find it's way into ERPnext
