### ISSUE TITLE
Delivery warehouse

### ISSUE THREAD

**Issue by ianpkano** [frappe/erpnext#10662]
I have set up items, warehouses for companies, suppliers, taxes, etc...

I created a sales quotation, all good.
I created a sales order - it asks that the item have a delivery warehouse????

What where why and how?

**Comment by ianpkano** [comment]
OK< found it...OMG why put it in such a convoluted place? Open a field for delivery warehouse under the shipping area.

**Comment by umairsy** [comment]
@ianpkano please post your queries on the ERPNext community forum.

https://discuss.erpnext.com

If your query is validated as a bug or a generic feature suggestion, then only Github Issue should be created for it.

Since ERPNext is an open source project, you can also contribute the enhancements. That's how most of the open source projects grow.
