### ISSUE TITLE
Cannot change "series" on POS Profile

### ISSUE THREAD

**Issue by mist-01** [frappe/erpnext#10674]
I have an issue with POS Profiles.  My existing global POS Profile has no series.  It is just listed as "select".  This also means that sales invoices created through the POS have "select" in their name - which is far from ideal.

![profile list](https://user-images.githubusercontent.com/2146048/30047519-bc937696-9222-11e7-9af8-ce0a38d7b46c.png)

To try and correct this, I want to change the "series" field, but I cannot since  the field is read only.  I then tried to delete the profile, but I cannot since it is connected with sales orders.  

![no delete](https://user-images.githubusercontent.com/2146048/30047533-ceaa9ac6-9222-11e7-9398-33d6af89b2ed.png)

Finally, I tried to create a second POS Profile, but then I get an error about there already being a global profile.

![global profile](https://user-images.githubusercontent.com/2146048/30047575-0177d270-9223-11e7-9683-9e27cf1fcc40.png)

As far as I can tell, there doesn't seem to be a way to correct the issue.  Could we make the "series" field writable?  Or create a way to deactivate a profile?

**Comment by umairsy** [comment]
Hello,

For a User, only one POS Profile can be created. The error message suggests that you have defined Username instead of user ID/Emai ID? Please select the user ID.

Please post such queries on the ERPNext community forum first.

https://discuss.erpnext.com

Only if it is validated as a bug or a generic feature suggestion, you should create a Github Issue for it.
