### ISSUE TITLE
Serial No has already been received error

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#10721]
Hi,

While trying to submit a Purchase Receipt for a serial number, we got the error `Serial No xxxxxxxx has already been received`

The movement for the serial is as follows:

- Purchase Receipt (into ABC warehouse)
- Purchase Return (to Supplier)
- New Purchase Receipt (from Supplier into ABC warehouse) - The error pops up when trying to submit this

I’ve checked the posting time to be sure it isn’t before the Return

Please help fix this

Thanks

**Comment by DevenK** [comment]
Hi all,

I can confirm that I'm receiving the same error. Please see the topic started here for more information: [Serial No has already been received error](https://discuss.erpnext.com/t/serial-no-has-already-been-received-error/27981)

I can replicate the issue in:
erpnext 8.11.1
frappe 8.10.4
These are the latest versions as of now.

Some help on this would be greatly appreciated, we're unable to receive shipments because of this bug.

Thank you!

**Comment by sergyv** [comment]
Can we reopen this issue since it's a still a problem in the latest version?

**Comment by Olawale1** [comment]
Hi @sergyv 

Could you pls mention the specific version on which you tested ?

Thanks

**Comment by sergyv** [comment]
yes of course:
ERPNext: v12.10.0 (version-12)
Frappe Framework: v12.7.3 (version-12)

**Comment by sergyv** [comment]
@Olawale1 did you have chance to reproduce? could we reopen the issue?

**Comment by sergyv** [comment]
@rohitwaghchaure is it possible to reopen this issue?

**Comment by sergyv** [comment]
@Olawale1 @rohitwaghchaure?
