### ISSUE TITLE
Permission - Unable to view reports based on company

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#10786]
ERPNext: v8.11.2 (master)
Frappe Framework: v8.10.5 (master)

Unable to view reports due to permission issue

**Setup**
![image](https://user-images.githubusercontent.com/21187126/30423680-384ea094-9976-11e7-8992-791a23facd5c.png)

**Error**
![image](https://user-images.githubusercontent.com/21187126/30423739-66b863c0-9976-11e7-9d12-5d4773a1e936.png)

**Finding**
![image](https://user-images.githubusercontent.com/21187126/30423609-f4f7d432-9975-11e7-8371-1026abad05ea.png)

**Report Role**
![image](https://user-images.githubusercontent.com/21187126/30423881-d1d06072-9976-11e7-9af1-583f7ba6c47f.png)

**User Role**
![image](https://user-images.githubusercontent.com/21187126/30423970-109bbffe-9977-11e7-8022-e4a13605bd44.png)

**Comment by umairsy** [comment]
Is this issue occurring in your hosted ERPNext account? If yes, please report this issue on support@erpnext.com. Also, share the login credentials of the user facing this issue. Since this issue is related to specific configuration in your account, we will need to access your account remotely locate the cause of the issue.

If it is self-hosted (with no support subscription), request you to post it on ERPNext community forum.

**Comment by umairsy** [comment]
Please also ensure that in the Company master, you have checked Apply User Permission, with the condition on the Company field. After this, your permissions should work fine.

![screen shot 2017-09-21 at 12 46 51 pm](https://user-images.githubusercontent.com/910238/30683425-0d0f212e-9ecb-11e7-9c8c-1f567e0b42e1.png)

**Comment by addymuliady** [comment]
Hi @umairsy 

Have posted this on forum 10 days ago. And with no respond, I posted this into GitHub.
https://discuss.erpnext.com/t/permission-issue-unable-to-view-company-in-report-filter/28309

I did as required.

Added a Company field in the Company Master too.

![image](https://user-images.githubusercontent.com/21187126/30796847-5a1742ec-a206-11e7-9188-86bda633c0ee.png)
