### ISSUE TITLE
Reverse charge feature required.

### ISSUE THREAD

**Issue by Nehamirpuri** [frappe/erpnext#10894]
Following is the way on how reverse charge should work in ERPnext.

1. First at the supplier master we need to define whether the supplier is registered or an unregistered under GST.

2. Once invoice is created and if the selected supplier is unregistered and invoice amount is more than Rs.5000/-  for a day then it needs to apply GST i.e. either IGST-18 % or SGST & CGST-9% each depending on value updated in category in supplier master (i.e. local-purchases[cgst+sgst] or inter-state purchases[igst])

3.We shall also require a report showing all invoices under reverse charge so as to determine the total taxes to be paid under reverse charge,similar to GST purchase register or in the same report another filter can be added on supplier category,which shall filter invoices based on purchases from registered or unregistered supplier.

Also attaching link of Tally video of Reverse charge fetaure for your reference.
https://www.youtube.com/watch?v=eppzCZmZr6k

**Comment by giuseppelamatrice** [comment]
+1

**Comment by snvora** [comment]
We are planning to implement in following manner.

> First at the supplier master we need to define whether the supplier is registered or an unregistered under GST.

U can update supplier type in supplier as per your requirements.

> is more than Rs.5000/- for a day

Currently we have not worked on this. we plan to bifurcate spendings as expenses and purchases. where expenses are booked from Journal Voucher ( very small expenses generally amount may never exceed 5000/-). and Purchases are booked from Purchase Invoice ( we plan to pay tax on reverse charge under this category even if total spending is less than 5000 - Better to do this to ensure uniformity - No extra hassle and no extra cost incurred for this as we get credit in following month)

Implementation steps in Purchase Register

- Currently Following accounts would be already there.
   - Input CGST under Asset
   - Input SGST under Asset
   - Input IGST under Asset
   - Output CGST under Liability
   - Output SGST under Liability
   - Output IGST under Liability
- Create Additional Following accounts.
   - CGST Payable under reverse charge under Liability
   - SGST Payable under reverse charge under Liability
   - IGST Payable under reverse charge under Liability

- Currently 2 templates there in Purchase taxes and charges
   - In State GST
   - Out State GST
- Create 2 Other templates
   - In State GST under Reverse Charge
   - Out State GST under Reverse Charge

In these two new templates following additions to be made.
![capture](https://user-images.githubusercontent.com/10496564/30905011-3c125408-a391-11e7-8681-448675d3f57d.PNG)

I have added Row 6 (i.e. IGST Payable under reverse charge)  in addition to Out State GST template. It needs to be configured as follows. Kindly note I have deducted instead of adding this component.

![capture1](https://user-images.githubusercontent.com/10496564/30905144-9899104a-a391-11e7-9aa8-5c699587d4a6.PNG)

Similarly Following in In state GST under Reverse Charge Template

![capture2](https://user-images.githubusercontent.com/10496564/30905195-b2e7b280-a391-11e7-868f-96b843717d91.PNG)

- Updating tax rules to automatically choose purchase tax and charges template based on billing state and supplier type. Choose Priority Logically.

- Add Custom Script to make reverse charge field = Y based on tax and charges template.

Hope this helps.... :-)

**Comment by djpalshikar** [comment]
![](https://user-images.githubusercontent.com/10496564/30905144-9899104a-a391-11e7-9aa8-5c699587d4a6.PNG)
@snvora 
I see that you have labelled the expense as "Deduct", should this not be "Add" , as reverse charge is being added to the liability.

**Comment by snvora** [comment]
@djpalshikar 
Deduct here means it will reduce my total taxes and charges.
In effect it will add to my liability.
Try and check accounting. It works perfectly fine with us.
