### ISSUE TITLE
Updates to Chat

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#10910]
- [x] All messages in Chat table
- [x] Update with socketio
- [x] Realtime Notification
- [x] Active chat on top
- [ ] colour for chat
- [x] Input box at bottom
- [x] Groups
  - [x] Create Group
  - [x] Add member
- [ ] Images
- [ ] Emojis
- [ ] GIFs

[Frappe-2131](https://github.com/frappe/frappe/issues/2131)

**Comment by joolsr** [comment]
Really pleased to see this ;-) We need this and I was looking at using a separate application with better functionality and notifications. Can i ask that there is an option to send notifications with chat link or just means to reply via email as we have a few staff who prefer to uise email instead of being logged in all the time to the main ERPNext instance.

As an aside, do you have any thoughts on whether this could also be incorporated on an external website chat view similar to which Odoo use? This would enhance the website functionality and be great for businesses and would not be difficult to do once the chat code has been built into Frappe.

**Comment by rmehta** [comment]
Lets get the internal chat working first. But yes, porting it to the external website should not be too hard!

**Comment by applepipe** [comment]
channels would be a great addition too as someone pointed in the forum https://www.odoo.com/page/discuss

**Comment by elvise** [comment]
@achillesrasquinha I have seen your repo https://github.com/achillesrasquinha/chat it is very cool 👍are you working from this base...?

**Comment by achillesrasquinha** [comment]
@elvise ;) progress. Should be out soon.

**Comment by elvise** [comment]
@achillesrasquinha this is great!!!
Can i hope for December ?

**Comment by achillesrasquinha** [comment]
@elvise Now that I've promised you, yes.

**Comment by elvise** [comment]
@achillesrasquinha great sound bro 🤙🏻
I have one query, why user can upload only images on the chat...? 
Maybe user need upload also pdf excel word or others type 
What do you think...?

**Comment by joolsr** [comment]
Any chance we can have an option per user to send an email of the chat or a link to it at least if they're not logged in? We have one member in our company that much prefers email so this would be useful I'm sure to others too ..

**Comment by joolsr** [comment]
Also how I can test this out ?

**Comment by fatheyabdelslam** [comment]
i badly need this update ASAP

**Comment by achillesrasquinha** [comment]
We're almost there! I'd love contributions for the same. :smile: Please raise issues [here](https://github.com/frappe/frappe/issues/4725). You can test the same on your `develop` branch.
