### ISSUE TITLE
Item selection via Barcode - After scanning, Enter key needed to auto-selection of Qty

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10949]
Reported by Bryan via Issue WN-SUP28006

In the Stock Entry, Item Code is selected by scanning a Barcode value. And then the user enters tab to move to Qty field. However, in the Qty field, the value 0.00 is not auto-selected. Hence user has to first remove 0.00 and then entry actual qty. This is not very efficient for speedy data entry.

Currently, if Enter is pressed after scanning the Item Code, and then Tab towards Qty field, then value 0.00 is auto-selected. It means user can directly enter Qty value and then tab forward to new row.

Solution: After scanning, additional Enter key press should not be required for auto-selection of value in the Qty field.

**Comment by netchampfaris** [comment]
If we program the behaviour to suite faster data entry for barcode scanners, it may interfere with normal data entry through the keyboard, since ERPNext cannot know if barcode is connected or not.
I think there should be a dedicated modal specifically made for barcode scanners and not in the child table. Maybe we can do it if enough people want it. In that case, let's create a new issue for the same.
Closing this one.
