### ISSUE TITLE
Auto fetch batches based on quantity on POS

### ISSUE THREAD

**Issue by mdwala** [frappe/erpnext#11004]
In reference to
https://github.com/frappe/erpnext/issues/11003
and
https://discuss.erpnext.com/t/pos-change-selected-batch/28884
Batch selection should be automatic(optional may be) on “First Expiry First Out” based on required selling qty, I believe this is standard procedure for dealing in Batches for all businesses. Attached example snapshot shows require field to auto fetch batches. 
Thanks…
![4](https://user-images.githubusercontent.com/24455908/31053811-8717b84e-a6b6-11e7-9334-a5496d5a5251.png)

**Comment by tundebabzy** [comment]
- [ ] Add new setting in POS Settings so that user can choose for ERPNext to automatically choose batch
- [ ] In Batch Selector Dialog, expired batches should not be included
- [ ] Automatically batch number which will be the oldest in stock as quantity is not known before hand

- Automatically selected batch number means user will only need to enter "Qty" in Batch Selector Dialog
- If the automatically selected batch is not sufficient, user will have to either change the batch manually or add another batch to satisfy the order. 
- The Batch Selector Dialog will always appear.

**Comment by mdwala** [comment]
Hi. @tundebabzy 
If quantity is higher than single batch will auto batch selection be multiple batches?

**Comment by tundebabzy** [comment]
@mdwala
No. User will have to adjust for the remaining manually. I chose this design because of programming simplicity as I think the latter situation will not be frequent enough to be a headache. However, take my thoughts with a pinch of salt. That's the reason why I put the design requirements here for others to see and critique before I start coding. If it is important that ERPNext should fetch remaining batches, then I can add that....

**Comment by tundebabzy** [comment]
Just discovered that the POS cannot accept from multi batches at the moment. So present design will stand while my colleagues work on redesigning the POS.

**Comment by tundebabzy** [comment]
POS will now automatically fetch batch number into the Batch Selector Dialog in POS. #11004
