### ISSUE TITLE
Easy scrap/excess management system for sub-assemblies

### ISSUE THREAD

**Issue by rvxfahim** [frappe/erpnext#11178]
Hi,

This is Nafis. I need an easy scrap/excess material management system along with sub-assembly items during the production process.
The process is for a garments factory where there are 4-8 phases of production process:

1) make production order for 2000 pcs of item A 
2) transfer all raw material for item A to WIP warehouse.
3) start production from the first phase where each phase will make a sub-assembly item for the next phase.
4) after each phase the sub-assembly item will be checked for carrying it out to next phase. In case there is a damaged sub-assembly item after a production phase it will be marked as rejected. Also at each phase there can be damaged or excess raw material which also needs to be sent back to damaged/raw material warehouse. 
5) If there is a shortage of raw material due to damaged raw material for making a given quantity of finished goods then there should be some sort of notification or visible notice from which PO can be made.
6) Finally finished goods needs to be scanned into finished goods warehouse. Any rejected finished goods will be sent to rejected warehouse.
7) A automated timesheet that will track the production process based on the output of each phase.

Please let me know how long is it going to take for implementing this system.

**Comment by agritheory** [comment]
Hello Nafis,
A few suggestions:
"Please let me know how long is it going to take for implementing this system." 
This is a pretty hard-to-answer question without some more context, like "how big is a dog?" 
If you are planning on implementing this yourself, the user forum is a good way to do it. This is an open source community, so advice is given in kind (discuss.erpnext.com). If you are looking to hire somebody to do it, than I recommend you look for a service provider local to you at erpnext.org

Download the virtual image of the latest ERPNext installation and see if the manfacturing module works for you. Asking questions on the forum based on your experience will get you better answers than asking them in the abstract here. 
Scrap/selvage/short yards can all be "items" in your system since they are not truly scrap, they are a byproduct. Scrap as an accounting definition means it can only be thrown away.
