### ISSUE TITLE
Provision to save invoice in draft mode for Online POS

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#11298]

**Comment by cphoa28** [comment]
Is there any further details here?  Would be interested here to see if can solve the ff issue:

1.  Retail Pharma Store has 4 Pharma Assistance on the counter and 1 cashier in the back.
2.  Each Pharma Assistant takes medicine order from a customer and prepares what should be an equivalent of Sales Invoice in Draft mode
3.  Pharma Assistance will give the Sales Invoice # to Customer
4.  Customer goes to Cashier and gives the Sales Invoice #11316 
5.  Cashier Pulls up the Sales Invoice and process the payment 

So, would like a POS view of the Sales Invoice (cash invoice) for the Pharma Assistants and have ability to SAVE BUT NOT PAY

Cashier will have a POS view to see the unprocess Sales Invoices and pull it up and then complete the Sales Invoice

I suppose instead of a Sales Invoice in Draft, a Sales Order will also suffice.  We would just need a POS view of Sales Orders (just like in previous version) where it will create the appropriate Sales Invoice (cash invoice, of course).

Help and comment appreciated.  Much thanks!!

**Comment by tundebabzy** [comment]
I believe this is addressed by #12620
