### ISSUE TITLE
Changing a BOM in Production Order

### ISSUE THREAD

**Issue by JustinMuthusamy** [frappe/erpnext#11388]
Hi, 
Please note that we produce wooden pallets. To keep it simple a 2 metre plank can be cut into 1m to process an order. 
In the BOM if it is 1m and i dont have stock i can easily use a 2m (at half the quantity) - i.e cut it in production into half. 

The system is not flexible to allow me this meaning i have to actually enter everything manually with these sizes (2m). 

A further issue comes in when part of a sales order is fulfilled with the correct stock (1m for example) then delivered, and the remaining items I CAN SUPPLY with 2m by cutting it in half but cant now bring in the BOM and edit. 

Please fix this really critical issue, as i am sure that a lot of customers are experiencing this.

**Comment by djpalshikar** [comment]
Facing a similar issue. We manufacture instruments, where we need to cut pipes and use them. I understand your issue. But can you propose a solution ?

Since in each BOM we only have 2-3 items which have this issue, we have a workaround:
1. BOM has a generic Item like PIPE-SS, when we make a stock entry, we change it to PIPE-SS-1M 

2.Also we changed this setting: In Manufacturing Settings -> Change to Backflush based on = Material Transferred for Manufacture

**Comment by lowercase00** [comment]
I have a similar issue, and my solution was to have the stock registered for the "minimal unit" of that item (something like the lowest common denominator)

We produce soaps, and we buy raw material in different packages (1kg, 5kg, 10kg etc). For me to be able to work with the challenge, I have to have stock entries based on grams (in my case, the "lowest common denominator"), so all my entries are 1.000kg, 5.000kg etc. - Instead of having Raw Material 1 (10kg packaging) and Raw Material 2 (1kg packaging) and can only have Raw Material 1 (1 gram) - which is not optimal since I cannot analyze the cost/benefit of buying a 10kg (way cheaper on a per gram basis) vs a 5kg.

The solution could be to have a checkbox "is divisible" in items, if you click yes it would ask for the minimal common denominator and all control would be made on that front.

For the wood example: you entry a 10M piece of wood, and say that the lowest common denominator is 1M.

That might work

**Comment by creamdory** [comment]
UOM Conversion can be used for this one if you want the setup to have the "Generic" item. If in the event that you need to separate it to easily trace inventory, you need to "process" it first before putting into production. Example is converting a 2m plank to 1m plank to increase inventory of 1m.

**Comment by sharmanakul** [comment]
^ apart from that, 
stock entry of type 'repack' can be used here.
also, 'alternative item'.
