### ISSUE TITLE
Need a Cost center column in the following reports like Accounts Payable, Accounts Payable Summary, Accounts Receivable, Accounts Receivable Summary and also Cost center field to filter it.

### ISSUE THREAD

**Issue by AravindPranera** [frappe/erpnext#11433]

**Comment by umairsy** [comment]
Hi,

Please also elaborate the use-case and how will it benefit? Did you check existing reports based on Cost Center?

**Comment by umairsy** [comment]
duplicate issues https://github.com/frappe/erpnext/issues/11434

**Comment by sagar30051991** [comment]
Is It Done?

**Comment by AravindPranera** [comment]
Umair,

Same customer and supplier can do the transaction in different cost center,
that's why.

For example, customer A can do fabric purchase at Cost center A, and
customer A can do print at cost center B.

Thanks,
Aravind.


*1A, Sastri Nagar,Angeripalayam Road,*
*Near SP Office,**Tiruppur - 641602.*
*Mob : 9786473999.*
*ba@praneraservices.com <ba@praneraservices.com> | www.praneraservices.com
<http://www.praneraservices.com>*

*( ERP Implementation | Web Sites | CCTV | Bio Metrics )*

**Comment by umairsy** [comment]
Cost Center primarily links with the Income and Expense Account, and not with the Accounts in the Balance Sheet accounts. Since Customer and Supplier are the separate masters, you might have to do off-setting to get the overall profitability from the party who happens to be the Customer as well as the Supplier.
