### ISSUE TITLE
FedEx Integration

### ISSUE THREAD

**Issue by gupteshwar** [frappe/erpnext#11468]
- [x] Add new module Logistics
- [x] Add "FedEx" settings page. settings/master entry per service (Example FedEx, UPS etc.. in this case FedEx)
     - Disabled (Whether this configuration is Active/Inactive)
     - User ID ( : FedEx Key)
     - Password ( : FedEx Password)
     - FedEx Meter No ( : Unique identification from service)
     - Is Sandbox (Default if unchecked then Production)
     - Company -- Select out of enabled Companies (Leave blank if global)
- [x] Company master updates
    - Added TIN number
- [x] Address updates
    - Added Open/Close Time.
- [x] Delivery Note
    - Link to Shipping Plan
- [x] Shipper (New DocType)
    - Shipper Name
- [x] Shipping Plan ~~(To be initiated from Packing Slip)~~
     - Delivery Note (in draft only). Select one to be planned to ship. (Can be extended further for Sales Order, Stock Transfer, Packing Slip etc..)
     -  This page is specific to Shipper and currently only takes care of FedEx. (Can be extended further to accommodate additional Shippers).
     - Shipper (Selection from Defined Shippers and respective settings will take effect)
     - Shipping Date -- Proposed date of pick up.
     - Is Pickup Scheduled. -- Once submitted FedEx confirms date and this gets ticked as scheduled.
     - Drop Off Type -- 
     - Service Type
     - Shipment Type
     - Shipping Payment By (Self or Customer)
     - Duties Payment By
     - Octroi Payment By (With GST this need to be validated from updated FedEx API if any)
     - Shipment Purpose
     - Packing Type
     - Package Details
        - Weight in LB/KG (UOM of shipment:either KG or LB)
        - Total Handling Unit (Number of units/packages in a shipment)
        - Table (Package Master with dimension)
           - Package Code
           - Qty (Total item quantity)
           - Physical Packing (Whether this item with mentioned quantity packed in a Box or Pallet)
           - Package Unit (Inches or Centi meter)
           - Length ( : Package)
           - Width ( : Package)
           - Height ( : Package)
           - Package Weight (Total weight including Item, Qty )
           - Weight UOM (Should be same selected above)
           - Tracking ID (Updated from FedEx)
           - Shipment Purpose
     - Item Details (Item Master)
     - Item-Package Details
        - Package ID (Reference to Package Details)
        - Item Code (Reference to Item Details)
        - Qty (Allotted quantity to this package)
     - Shipment Charges
        - Shipment Amount (Updated from FedEx)
        - Shipment Currency (Updated from FedEx)
- [ ] Validations
- [ ] API Integration
  - [ ] Retrieving pickup updates and updating shipment details.
  - [ ] Retrieving Commercial Invoice and Label
- [ ] Handling event logs

**Comment by addymuliady** [comment]
Would integration with sites such as https://docs.aftership.com/api/4/overview
be better?

**Comment by gupteshwar** [comment]
@addymuliady We will add it to the wish list and evaluate.

**Comment by mosiolekdamian** [comment]
Are there any plans to extend this integration to UPS as well??

**Comment by gupteshwar** [comment]
Yes, we can. If Community demands and interested parties supports (in terms of account and API)

**Comment by adityaduggal** [comment]
Hi @gupteshwar 
Don't you think that initialisation of Shipping Plan from Packing Slip is FLAWED.
Give you are use case. Suppose we want to send a Letter via Fedex then this integration would be useful then as well but in that case we won't have a SO, SI or DN or Packing Slip and hence initiation via Packing Slip is flawed.

Please let me know where can I access the ongoing development since I am unable to find the required docs in any branch of erpnext

Also @addymuliady I have already made a similar setting in my custom app for something like aftership, we are currently using https://www.shipway.in for tracking the couriers after ship in India since it has support for more shippers.

See the development at below links:
https://github.com/adityaduggal/rigpl-erpnext/tree/master/rigpl_erpnext/rigpl_erpnext/doctype/carrier_tracking

https://github.com/adityaduggal/rigpl-erpnext/tree/master/rigpl_erpnext/rigpl_erpnext/doctype/courier_tracking_scans

https://github.com/adityaduggal/rigpl-erpnext/tree/master/rigpl_erpnext/rigpl_erpnext/doctype/shipway_settings

Also enclosing a copy of the pdf for the scans it basically pulls the scans automatically every hour and if the item is delivered it would automatically submit the transaction.

[CTRACK02094.pdf](https://github.com/frappe/erpnext/files/1642020/CTRACK02094.pdf)

**Comment by gupteshwar** [comment]
Hi @adityaduggal 
We have dropped plan of initialising Shipping Plan from Packing Slip. Shipping Plan will be currently dependent on Delivery Note but eventually come up it as independent page and can link to other DocTypes like Sales Order or Stock Transfer Note etc..

**Comment by adityaduggal** [comment]
Hi @gupteshwar 
Another suggestion as I have seen the code for old Fedex Integration and not privy to the current developments, based on the old code it seems that the fedex account no, key, meter no etc is fetched from settings page. I would suggest a better model for this as to include these fields in the Shipment Forwarder Field.
So it would cover all the scenarios like, if a user has only 1 account with fedex but want to ship through multiple services of Fedex then he would create multiple shipment forwarders and link them with sames key and account.

But this would come in handy for those cases who have multiple accounts with fedex and can link -
- Service X to Account A
- Serive Y to Account B
- Service Z to Account C and so on and so forth.

This would give the admins the ability to control which SERVICE is BILLED to which account of FEDEX as per their special pricing.

Just a suggestion though.
