### ISSUE TITLE
Print issue

### ISSUE THREAD

**Issue by FlexsoftsTech** [frappe/erpnext#11488]
dear Gents
how i can solve this issue, item description do not show up Probably, how i can costomize the invoice to show all required fields in the same page

![print issue](https://user-images.githubusercontent.com/33314211/32538008-94dc2fa0-c475-11e7-9767-1937cb906d44.png)

**Comment by FlexsoftsTech** [comment]
@umairsy your advice please

**Comment by umairsy** [comment]
Please check HTML for the Item Description. Perhaps there are additional HTML elements which were copied along the content. If so, clean your Item Description value (with minimal HTML).

Also, this issue has been fixed in the latest version. Ensure your ERPNext account is upgraded to the latest version.

Please do no tag individuals to get priority support. Rather you can consider subscribing for

https://erpnext.com/pricing/support

Avoid if you already have subscription.

**Comment by FlexsoftsTech** [comment]
Dear Umair
i am using my instance in the cloud so updates and upgrades comes to me automatically, 
more explanation please i did not get you
