### ISSUE TITLE
Project completed not visible on Portal

### ISSUE THREAD

**Issue by giuseppelamatrice** [frappe/erpnext#11563]
I completed a project but it is not visible on website.

![image](https://user-images.githubusercontent.com/4445879/32773807-a84319d2-c92a-11e7-8cf5-cca598a968db.png)

![image](https://user-images.githubusercontent.com/4445879/32773793-9d496874-c92a-11e7-9e80-24d20f2d1eb4.png)

**Comment by umairsy** [comment]
Replicating that Closed Projects are not shown to Website User. Someone please review if it is by design and if it could be considered as a feature suggestion.

**Comment by giuseppelamatrice** [comment]
It is a feature suggestion to show completed project to customer website. In this way customer can access to old project and monitoring progress project.

**Comment by chdecultot** [comment]
Hi @umairsy, I confirm that it is by design.
Only "Open" projects are displayed in the list on the portal:

`doc.status=="Open"`

Maybe we could make it an option in projects settings or portal settings ?

Personally I don't have an opinion on this and I think displaying all projects on the portal can be useful, but on the other hand if you have a lot of projects with one customer then the list may be too big...

If no one is opposed to the request I will gladly make a PR in the next days. Let's just wait until this week-end for feedback.
