### ISSUE TITLE
Unable to access Erpnext through the production vm

### ISSUE THREAD

**Issue by edwil13x** [frappe/erpnext#11581]
Hello, 
i have a internal server error when i try to access ErpNext. In addition it's not possible to login with the Administrator account only the frappe account works. It seems to be related with the database. Can you help me ?

Error 500
<img width="437" alt="capture d ecran 2017-11-15 a 07 09 40" src="https://user-images.githubusercontent.com/10283167/32821602-865f7400-c9d4-11e7-9d7a-c93640176324.png">
 
MySql Error
<img width="940" alt="mysql-err" src="https://user-images.githubusercontent.com/10283167/32821709-1b89ce0e-c9d5-11e7-91aa-c1168cbafb13.png">

Nginx Error
<img width="1004" alt="capture d ecran 2017-11-15 a 07 21 16" src="https://user-images.githubusercontent.com/10283167/32821811-afefc83c-c9d5-11e7-9451-fce1dde2a3b2.png">

My VM
<img width="710" alt="erpnext-login" src="https://user-images.githubusercontent.com/10283167/32821738-4d444e9c-c9d5-11e7-8ad7-afc5e0966b6f.png">

**Comment by umairsy** [comment]
Hello,

For the future reference, request you to post such technical queries on the ERPNext community forum.

https://discuss.erpnext.com

The Github Issues is primarily used for tracking bugs and feature suggestions so that other community members can collaborate on it.

You can shortly expect an update on it from one of the community member.

**Comment by edwil13x** [comment]
ok, i'll forward that on discuss.erpnext.

Thanks.
