### ISSUE TITLE
ERPnext won`t let me submit an invoice when I check `update stock`

### ISSUE THREAD

**Issue by otbopko** [frappe/erpnext#11711]
Hi, can I get help with the following - I was posting an invoice but did something stupid - changed the name of the client while I was writing the invoice. Then I tried to post the invoice but ERPnext tells me there is a problem, service error, blah-blah-blah.... 
If I do not check the `update stock` box - it`s fine. But I need to keep track of my inventory...
Help would be really appreciated. 
Thanks

**Comment by otbopko** [comment]
Seems like a problem with Shopify settings - I had installed Shopify but did not finish the integration setup. So I deleted all Shopify settings from ERPnext and vice versa - seems to be working now.

**Comment by kennethsequeira** [comment]
Hey, @otbopko thanks for the update. This seemed more like a technical usability query. If you have any such queries in future, I request you to post it on **https://discuss.erpnext.com/** where you can expect a quick reply from the community members.

Github is used to track bugs and report feature requests for the system. In case you have any such kind of requests, you can open a new issue.

Since you've said that your system is working now, I will close the issue for now. However, if you face more issues on the same topic, comment and let us know! 😄
