### ISSUE TITLE
Regarding Filter in Stock Ledger

### ISSUE THREAD

**Issue by lifestylesofas** [frappe/erpnext#11738]
Hi, 

I want the additional feature in stock ledger in which i can filter, what i have received, issue material. Example i purchased threads from market Red colour how much i have purchased in last three months and how much i have consumed separately.  At present i can see combine which i don't want. 

Please do he needful as its very important feature for manufacturing Unit as well retailers. 

Regards

Amit

Lifestyle Sofas

**Comment by umairsy** [comment]
If you are creating receipt entries only via one transactions, say Purchase Receipt, then creating Custom Report based on Purchase Receipt will give you required data. 

https://www.youtube.com/watch?v=TxJGUNarcQs

If you made receipt entries via multiple transactions like Stock Entry, Stock reco., the Stock Ledger report is the only report. But it will need additional filter for separate receipt/delivery entries.

**Comment by lifestylesofas** [comment]
i want filter because when we are receiving we are doing material receipt entry and when we are issue we are transferring to manufacturer.

**Comment by lifestylesofas** [comment]
If i want to check one item how many times i have purchased in 3 months i cannot check. Stock ledger is showing receive and issue both. which is not upto the mark.

**Comment by lifestylesofas** [comment]
Any updates on the above matter.

**Comment by umairsy** [comment]
No. As suggested, for now you should adapt to a workaround to get required data. For this feature to be incorporated in ERPNext, we will need to see if other members in the community also needs it, so that it becomes generated. Also, availability of resources at our end matter.

If you want to get it done on priority, please consider sponsoring for it's development. Perhaps one of our existing service provider can develop it for one time fee and contribute into ERPNext. Let me know if you would be open to it.

**Comment by lifestylesofas** [comment]
i will wait but not interested to pay. keep this point in priority

**Comment by lifestylesofas** [comment]
any updates

**Comment by lifestylesofas** [comment]
hello no response. any updates
