### ISSUE TITLE
{bug} Report Bank Reconciliation Statement > Drill down  click . document not found error

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/erpnext#11821]
**Step 1 :  Go to Report Bank Reconciliation Statement, click on any of the statement as shown below**

![image](https://user-images.githubusercontent.com/4900815/33473478-9acffb38-d69c-11e7-9e55-bb5a567d7a46.png)

**Will get the error as below**

![image](https://user-images.githubusercontent.com/4900815/33473606-22daf528-d69d-11e7-8876-46e7a421e552.png)

ERPNext: v9.2.18 (master)

Frappe Framework: v9.2.19 (master)

**Comment by tundebabzy** [comment]
Those should not be links.

**Comment by tundebabzy** [comment]
#11850

**Comment by deepeshgarg007** [comment]
These statements are shown as links because they are placed in payment entry column which is a link.

Currently we don't have provision to show different data types in a single column in datatable. To fix this we will have to change a lot of things which is not possible right now.

As this not causing any logical error I am closing this issue and will try to fix this in future versions.
