### ISSUE TITLE
HealthCare Module - Add Icons 

### ISSUE THREAD

**Issue by kennethsequeira** [frappe/erpnext#11838]
![screen shot 2017-12-04 at 11 51 59 am](https://user-images.githubusercontent.com/33246109/33539915-902b523c-d8ee-11e7-8921-8557de58ec66.png)

Minor issue, but nevertheless an important one since it has been three months since merging 😅

**Comment by achillesrasquinha** [comment]
This is important. @raghukamath, any quick fix?

**Comment by raghukamath** [comment]
@achillesrasquinha ideally this should have been done before merging :), I'll try to provide some icons , meanwhile we can also look if we can get temporary icons from octicon set.

**Comment by kennethsequeira** [comment]
@raghukamath that's a good idea. @rkurungadam you have any suggestions on this?

**Comment by achillesrasquinha** [comment]
octicons.com

**Comment by rkurungadam** [comment]
How about octicon-heart? https://octicons.github.com/icon/heart/

**Comment by achillesrasquinha** [comment]
Sweet! I'm not sure. But emoji's work too. But the drawback being it isn't consistent. :smile:

Would anyone like to work on this?

**Comment by system19** [comment]
I have some open source svg medical icons somewhere. I will try and locate and paste link to original source files.

**Comment by kennethsequeira** [comment]
@system19 thanks!

**Comment by system19** [comment]
Frappe currently has Font Awesome 4.7.0 installed which has:
12 Dedicated Medical Icons
12 Thermometer Icons
15 Accessibility Icons
Ambulance, Gender Icons, Cross, Hearts, Eye, Flask, Science Icons.
I will try and compile a single medical related cheat sheet. Otherwise view here:
Font Awesome 4.7.0
http://fontawesome.io/icons/

Font Awesome 5.0.0
Not immediately better than 4.7.0 on my quick look. Requires a .js upgrade shim to translate:
`<i class="fa fa-wheelchair"></i>` to `<i class="fas fa-wheelchair"></i>`
WTF? Didn't FA promise not to break the class names last time? Anyway an excellent collection.

https://fontawesome.com/icons?d=gallery&c=health&m=free

Other options might include installing fonts below:
25 Health related icon set - Healthies Icon Set - AI Only
https://ui8.net/product/healthies-icons-free

72 ICONS (X2) specialized in the Clinical & Medical world
http://samcome.github.io/webfont-medical-icons/

I have some Nurses, Doctors etc icons that are being hard to locate.

**Comment by system19** [comment]
<img width="1020" alt="fa med gallery 1" src="https://user-images.githubusercontent.com/7428077/34437758-2aa077c4-ecf5-11e7-97a7-88477d9bda76.png">
<img width="1055" alt="fa med gallery 3" src="https://user-images.githubusercontent.com/7428077/34437764-32261468-ecf5-11e7-969d-db3cbb829453.png">
<img width="381" alt="fa med gallery" src="https://user-images.githubusercontent.com/7428077/34437775-44c5913e-ecf5-11e7-9381-a4456bc4fa5a.png">

**Comment by system19** [comment]
I like either:
fa fa-user-md
or
fa fa-heartbeat
or
fa fa-medkit

For Module Logo?

**Comment by system19** [comment]
I tried to change the current desktop Icons for Healthcare. They are created in a domain and as such I can't work out where to change the code. Any advice would be good. 

If there are no objections I would like to propose these desktop icons:

Healthcare Module - fa fa-heartbeat
Consultation - fa fa-stethoscope
Lab Test - fa fa-flask
Patient - fa fa-user
Patient Appointment - fa fa-calendar-plus-o

Physician - fa-user-md
Physician Schedule - fa fa-calendar

Thanks

**Comment by raghukamath** [comment]
@system19 thanks for your suggestions.

I have added the icons, you can review the code here #12518
