### ISSUE TITLE
Barcode in Trial

### ISSUE THREAD

**Issue by bhatti4says** [frappe/erpnext#11831]
I can't see barcode field / feature and customize in setup. I want try this feature in trial mode, I couldn't find anywhere how to setup barcodes for products incoming & outgoing. There's also not a single video on youtube to setup barcode. This is so common feature yet no tutorial.

**Comment by kennethsequeira** [comment]
Hello, the Barcode feature should be enabled by default, setup is deprecated. Just go to Item and under the item name, you should find the barcode field.

**Comment by bhatti4says** [comment]
No i can't find the barcode field even in under item. has serial no and bathc no etc but not barcode. I can
![screenshot 9](https://user-images.githubusercontent.com/34199272/33568190-a9cf4084-d936-11e7-9c8c-9852db02f281.png)
here is the screenshot

**Comment by kennethsequeira** [comment]
@bhatti4says normally it should have appeared like this
![screen shot 2017-12-07 at 8 25 33 am](https://user-images.githubusercontent.com/33246109/33696440-48a53ff4-db28-11e7-8507-84bc825e89b2.png)

Are you the system manager on the account?

**Comment by kennethsequeira** [comment]
Since you're a cloud user drop a mail to support@erpnext.com

**Comment by kennethsequeira** [comment]
@bhatti4says check if this is enabled.


![screen shot 2017-12-07 at 8 38 45 am](https://user-images.githubusercontent.com/33246109/33696845-24b09434-db2a-11e7-898b-71bb0debdfc1.png)

**Comment by umairsy** [comment]
Barcode field was set as Hidden. Have been made available now.

https://imgur.com/a/75HE2

**Comment by bhatti4says** [comment]
Thank you Umair, I can see barcode field now. How to generate barcode?? I made an entry and now when I hit print, it should show me generated barcode right?? but its not showing.

**Comment by kennethsequeira** [comment]
@bhatti4says request you to move this kind of functional query to https://discuss.erpnext.com where community members can help you quickly.

For now, the barcode field is mainly there to input the barcode from a Scanner.
https://discuss.erpnext.com/t/how-to-use-barcode-in-erpnext/13548/6

If you want to generate the barcode, follow this discussion:
https://discuss.erpnext.com/t/new-barcode-type-info/29498

We will be updating the documentation on barcode generation soon. Till then, you can put such question to the community on Discuss. GitHub is primarily used to track/report bugs and feature requests.

Since you're a cloud user, you can drop a mail to support@erpnext.com if you face any problems in your account.
