### ISSUE TITLE
Gross profit report [Paid Development]

### ISSUE THREAD

**Issue by imansoltani** [frappe/erpnext#11845]
Please consider the following case:

I buy an item for CHF 27.00 (including VAT) and I sell it for CHF 28.50 (including VAT).

And when I get my Gross Profit Report, it shows a lost of CHF 0.61 which is not correct! This is because the system calculates the selling price excluding VAT (CHF 26.39) and deducts it from the buying price (CHF 27.00).

But in this case, the buying price must also be calculated without the VAT (CHF 25.00). If so, I will have a gross profit of CHF 1.39

Please notice when I buy the item for CHF 27.00, I pay also CHF 2.00 for the VAT which is included in the price.

**Comment by tundebabzy** [comment]
VAT should not be included in the Item valuation

**Comment by tundebabzy** [comment]
@imansoltani 
Actually, this is not a bug. You need to change the "Consider Tax or Charge For" field to "Total". The other options are "Total and Valuation" and "Valuation" and both will add the tax amount to the Item's valuation.

![peek 2017-12-05 13-24](https://user-images.githubusercontent.com/818803/33607291-ea3f2e74-d9c0-11e7-9e03-4f04577eb837.gif)

**Comment by imansoltani** [comment]
My field "Consider Tax or Charge For" was already set to "Total"!

The only difference with your example is that my buying prices are VAT lncluded.

**Comment by imansoltani** [comment]
The rates in the column of "The average buying rates" of the gross profit report are given by **including the VAT**. And this is precisely where the error comes.

For me the issue is not yet resolved.

**Comment by tundebabzy** [comment]
Did you check the "Is this Tax Included in Basic rate" check box?

**Comment by umairsy** [comment]
If you select "Total" as a category for the tax, the value of tax will not be included in the item's valuation. Only in the category for the tax or charges is selected as "Valuation" or "Valuation and Total", then an only value of that tax/charge is added to the item's valuation.

Generally, the tax amount is not included in the value of the item purchases, because after taking input credit on the tax, the tax amount payable is less. But if you still want tax amount to be added to the item's valuation, then ensure that you select "Valuation" or "Valuation and Total" as a category for the tax account.

Hope this helps.

**Comment by imansoltani** [comment]
@tundebabzy 
Yes, the box is checked but the the VAT is not deducted from the buying rate in the report.

**Comment by imansoltani** [comment]
@umairsy 
Here is the TAX setup for a purchase invoice:

![printscreen](https://user-images.githubusercontent.com/2845368/33652729-bef7cc44-da6a-11e7-8093-3dbd61a2756d.png)

In the invoice, all of the item rates are VAT included. I went through the tax breakup  and checked one by one the rows. The tax calculation is correct.  So, it doesn't seem the issue in the report comes from here.

**Comment by umairsy** [comment]
Because "Consider Tax or Charge for" is selected as "Total", and not as "Valuation" or "Valuation and Total".

If you want the tax amount to be added to the valuation of item's purchase, then it should be one of "Valuation" or "Valuation and Total".

**Comment by imansoltani** [comment]
When I change "Consider Tax or Charge for" to "Valuation" I get the following error:

![error](https://user-images.githubusercontent.com/2845368/33666699-207128be-da9b-11e7-8f44-46b5d8d53f9c.png)

And when I change "Consider Tax or Charge for" to "Valuation and Total" I get the following message:

![message](https://user-images.githubusercontent.com/2845368/33666749-3a834e6c-da9b-11e7-8185-5aabbfc1103e.png)

**Comment by imansoltani** [comment]
@tundebabzy
Can you please repon the issue?

**Comment by Ponyooooo** [comment]
Hi, do you have a solution for this issue? I am still looking for a solution for this one on the v12 and v13 since ERPNEXT still hasn't considered the valuation and total for non-stock items. And I need to add up the tax and charges on the gross profit for the Project module since the Gross Profit report still does not include the non-stock items too. :(
