### ISSUE TITLE
New Item - Create Variant Should not be First field

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11892]
![screen shot 2017-12-08 at 4 19 23 pm](https://user-images.githubusercontent.com/910238/33762727-a0a1e2be-dc33-11e7-858c-5e08d8fb29d0.png)

**Comment by vishdha** [comment]
https://github.com/frappe/erpnext/pull/11924

**Comment by pratu16x7** [comment]
I believe it is the first field as the entire dialog changes based on it, so that user first selects and then proceeds to fill in data. If he sets it after filling data, he will lose filled data anyway, at least for that setting.

![variant_check](https://user-images.githubusercontent.com/5196925/33820568-0cc9e7d6-de76-11e7-8e1b-696d27f462e4.gif)

I do agree that the dialog is meant to be simple for first time users. However, simply displacing the check without considering its functionality is probably not the way to approach it. If we want to keep it simple, we'll have to decide what we want to do with the dynamic settings for variant creation.
