### ISSUE TITLE
After Update  : the date filter is not working properly for doc type

### ISSUE THREAD

**Issue by nivedita05** [frappe/erpnext#12120]
In doctype suppose I want to filter the document by the date . Go to the doctype and apply filter by date .
Let us consider date between 1/12/2017 to 5/12/2017 
Before updation it was working fine but now if i put the before said date range 
it is considering 2/12/2017 to 6/12/2017 .

**Comment by Zlash65** [comment]
![between-date](https://user-images.githubusercontent.com/11695402/34215452-602792aa-e5cb-11e7-9977-da0efee8010e.gif)
Going by your plus 1 day logic, in my gif the item created 8 days ago shouldn't have been visible because selecting 12th dec should have taken 13th dec as its start right ? But seems to be working for me.
Can you provide a gif or a means to replicate it ?

**Comment by nivedita05** [comment]
![example](https://user-images.githubusercontent.com/21117856/34221745-2b3ca01c-e5df-11e7-844d-de7b97ec0cfb.gif)
I am attaching a gif . Go through it . 
I am explaining the cycle 
suppose 
purchase invoice --> in filter date ---> between 8/12 to 13/12 ----> apply ---> open one file randomly ---> date is 14/12 .

**Comment by netchampfaris** [comment]
https://github.com/frappe/frappe/pull/4810
