### ISSUE TITLE
Items won't load in Online POS but works in Offline POS

### ISSUE THREAD

**Issue by gbard** [frappe/erpnext#12289]
The Items from the Item Groups that I selected in POS Profile are not loading in the Online POS. If I manually enter a Item Group in the "Item Group" field it will load the Items but only for one Item Group at a time... There is no error in the console and it is working well in the Offline POS.

**Comment by rohitwaghchaure** [comment]
@gbard 

I have tested on local account and it's working properly. We have added this feature for online POS in version 10. Can you please share version details?

Set item groups in the POS Profile
![screen shot 2018-01-02 at 12 16 30 pm](https://user-images.githubusercontent.com/8780500/34476450-d5f2ebf2-efb6-11e7-996f-35810b6a1107.png)


Same item groups showing in the POS
![screen shot 2018-01-02 at 12 16 36 pm](https://user-images.githubusercontent.com/8780500/34476461-e310deca-efb6-11e7-8611-7396ab16998f.png)

Here system not showing result for an item STRIKE JAMB LANDING LH because this item has item group Sub Assemblies which is not selected in the pos profile.

**Comment by gbard** [comment]
Here is a screen capture:
![erpnext_pos_fetch_items](https://user-images.githubusercontent.com/11325063/34503045-74fdede6-efe4-11e7-886c-94839dde345f.gif)

I'm using latest version: ERPNext: v10.0.5 (master)

**Comment by rohitwaghchaure** [comment]
@gbard 

Seems like items are loading, can you wait for few seconds and don't type anything in the search box.

**Comment by gbard** [comment]
I waited but it still won't load. I changed the POS Profile to load nothing but a Item Group with less than 20 items and it's still the same.

![erpnext_pos_items_wont_fetch](https://user-images.githubusercontent.com/11325063/34532363-e681d71c-f083-11e7-8905-ff6bfdd2ccfd.gif)

**Comment by rohitwaghchaure** [comment]
@gbard 

I have checked on local account with different use cases and it's working properly. As this is specific related to your account, can you give me access of your account? Please PM(@rohit_w on discuss) the account details like application URL, System User's login credentials, POS Profile User's login credentials

**Comment by rohitwaghchaure** [comment]
@gbard 
Thanks for the details, I have checked into your account and found that the lft and rgt of your item groups which has been set wrong and therefore items not loading properly in the POS for online mode. Please run below commands from frappe-bench folder and check
```
bench console
from frappe.utils.nestedset import rebuild_tree
rebuild_tree("Item Group", "parent_item_group")
frappe.db.commit()
```

**Comment by rohitwaghchaure** [comment]
Closing this issue, feel free to reopen if issue still persists

**Comment by gbard** [comment]
Problem solved by running these commands in bench console:

bench console
from frappe.utils.nestedset import rebuild_tree
rebuild_tree("Item Group", "parent_item_group")
frappe.db.commit()

THANK YOU @rohitwaghchaure !
