### ISSUE TITLE
Gantt view in Projects, can't change "Week" view

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#12316]
Can't be changed from "Week" view to "Month" or any other.

![image](https://user-images.githubusercontent.com/25084259/34537605-b17688e6-f08e-11e7-8a26-cabe7ecda77b.png)

Installed Apps
ERPNext: v10.0.5 (master)
Frappe Framework: v10.0.6 (master)

**Comment by joolsr** [comment]
This is related to the changes in Develop branch for this where the period changer will be positioned right at the bottom of the page. I had this same exact problem as you report, but found that if I do a switch to Develop and back again to Master, then bench update twice that the problem is fixed.
This is obviously NOT the best way to clear this fault, but indicates some caching issue perhaps . or a set up issue

**Comment by pompeiisneaks** [comment]
I'm having the exact same issue on a fresh install, it can't be changed from 'day' view at all.  I've done it in dev mode in docker compose and now in a fresh production install as well.

**Comment by netchampfaris** [comment]
@franciscobuendiao Is this still replicating in the latest develop?

**Comment by joolsr** [comment]
In Develop, it was fine when i tested it. But this issue as described happens in Master

**Comment by joolsr** [comment]
![peek 2018-02-06 18-17](https://user-images.githubusercontent.com/934876/35876418-1f54276a-0b6a-11e8-8a20-e1d79349d23a.gif)

**Comment by umairsy** [comment]
For me, is doesn't show any option at all.

**Comment by joolsr** [comment]
Could this be fixed any sooner? I only ask as if you can't change the view for tasks it is a significant bug and obviously this used to work before . Though I appreciate you probably have another long list of other things that too are 'urgent' ..

**Comment by Zlash65** [comment]
https://github.com/frappe/frappe/pull/5100
