### ISSUE TITLE
[erpnext.org] delete chapter member does not change Member List entries as expected

### ISSUE THREAD

**Issue by clarkejj** [frappe/erpnext#12408]
The attached 2 images show and annotate the problem - (this issue added to erpnext.com issue list since no erpnext.org issue list found)
![image001](https://user-images.githubusercontent.com/11706903/34745073-900c75c2-f54c-11e7-9961-c9f33d8539bc.png)

![image002](https://user-images.githubusercontent.com/11706903/34745249-17e00d60-f54d-11e7-8d4c-99cdeaba96cd.png)

**Comment by vishdha** [comment]
![des](https://user-images.githubusercontent.com/6947417/34762679-9b2963b2-f60e-11e7-8e0d-d275db7b95c2.png)

**Comment by vishdha** [comment]
https://github.com/erpnext/foundation/pull/98

**Comment by dalers** [comment]
Hi @vishdha can you explain what happens next, I'm interested in understanding release process you follow. Do I understand correctly that the fix for this issue was merged into the foundation repo master branch _two_ weeks ago? What will happen next, before the fix goes live on erpnext.org? Also, what has to happen for this issue to be marked closed? Does this issue have to be closed before the production site can be updated? 

Cheers,
Dale

**Comment by vishdha** [comment]
Hi Dales,
We Migrated Some of the Doctype like chapter and membership to Non-Profit Domain. The fixed was for foundation app which is not present in non-profit in this movement. Don't worry we will solve and send fix to hotfix branch for production.

Thanks, 
Vishal

**Comment by vishdha** [comment]
https://github.com/erpnext/foundation/pull/111
