### ISSUE TITLE
Search results list has too much gap between results 

### ISSUE THREAD

**Issue by raghukamath** [frappe/erpnext#12401]
When a user searches from the search bar, the result that gets generated has big gaps in between, making it appear as if there is only one result.

this may be due to the following css rule

.result {
    min-height: calc(100vh - 284px);
}

version - 10

I can reproduce in both chrome and firefox

adding a gif demonstrating the bug

![peek 2018-01-09 19-07](https://user-images.githubusercontent.com/9101092/34723610-45ca29ee-f571-11e7-8833-99e97995b0b6.gif)

**Comment by Kronik-Lilus** [comment]
Hey I just read a lot of the rules and regs you sent me, explaining my
situation  and all that. So yeah sorry, i just dont know what im doing when
it comes to coding still so I was just trialing everything and learning
from any errors.
However, the full breach like hack attack sorta freaked me out at the time.

On 10/01/2018 12:44 am, "Raghavendra Kamath" <notifications@github.com>
wrote:

When a user searches from the search bar, the result that gets generated
has big gaps in between, making it appear as if there is only one result.

this may be due to the following css rule

.result {
min-height: calc(100vh - 284px);
}

adding a gif demonstrating the bug

[image: peek 2018-01-09 19-07]
<https://user-images.githubusercontent.com/9101092/34723610-45ca29ee-f571-11e7-8833-99e97995b0b6.gif>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/frappe/erpnext/issues/12401>, or mute the thread

**Comment by Kronik-Lilus** [comment]
So yer ill just keep my head down and update any needed code as you send me
it. Didnt know I was a risk sp to speak

**Comment by joolsr** [comment]
Can you replicate in demo.erpnext.com ?

**Comment by raghukamath** [comment]
@joolsr yes I can replicate this.

To reproduce

* Go to demo.erpnext.com
* Type anything in the search bar example "login"
* A search result popup will open, check the spacing between the result items

**Comment by joolsr** [comment]
Thanks for this. I only ask as I know the ERPNext team would have asked anyway ;-)

**Comment by vishdha** [comment]
https://github.com/frappe/frappe/pull/4903

**Comment by raghukamath** [comment]
thanks @vishdha
