### ISSUE TITLE
Error on sales order calendar view

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12410]
This can be reproduced on beta.erpnext.com just opening sales order in calendar view

Error message:
<img width="695" alt="screen shot 2018-01-09 at 8 33 22 pm" src="https://user-images.githubusercontent.com/18335894/34746760-6d0a58fc-f57c-11e7-89ba-41c18b0c5edc.png">

Full page:
![screencapture-beta-erpnext-desk-1515537061354](https://user-images.githubusercontent.com/18335894/34746726-4517242e-f57c-11e7-9c5e-e45a2320b4f9.png)

**Comment by umairsy** [comment]
Works fine in my test account.

![screen shot 2018-02-12 at 6 29 35 pm](https://user-images.githubusercontent.com/910238/36097862-b78e7d84-1022-11e8-8437-9610e7d71bf4.png)

After clicking on Calendar, what are the steps to be taken to replicate this issue? Feel free to reopen this issue is it is still recurring.
