### ISSUE TITLE
Side-Menu "edited this" or "created this" text displays incorrect information on Delivery Notes.

### ISSUE THREAD

**Issue by mobentec** [frappe/erpnext#12436]
Since V10 update, we noticed that the side-menu / side bar timing information on Delivery Notes is not accurate.

![2018-01-10 at 17-07-38](https://user-images.githubusercontent.com/6663120/34798581-a53a89a0-f62a-11e7-9634-db3e38ba6103.png)

Upon looking into the source, it looks like the time stamp is accurate, however, the conversion of the timestamp into human text, such as "in 5 hours" or "8 minutes ago", are not being calculated correctly.

![2018-01-10 at 17-07-35](https://user-images.githubusercontent.com/6663120/34798586-a9433ace-f62a-11e7-9f95-cc7d13fd1ab9.png)

How can we fix this?

**Comment by mobentec** [comment]
Hi @pratu16x7, is there any update to this?

**Comment by jaichavan** [comment]
Hello, this issue has been addressed and improvised in the latest version. Can you check and let us know if issue persists? @mobentec

**Comment by jaichavan** [comment]
Hello, @mobentec just replicated the issue, turns out it is a **bug**. Thanks for reporting this! We will address it earnestly :)

![GI-DN-version-track](https://user-images.githubusercontent.com/40264279/56471143-a17bc700-646c-11e9-855a-f1e5b5a37001.gif)

Version details:

![image](https://user-images.githubusercontent.com/40264279/56471145-a93b6b80-646c-11e9-9771-c5cf73e68b17.png)

**Comment by ankush** [comment]
This is old issue with timezones https://github.com/frappe/frappe/pull/13504
