### ISSUE TITLE
Double horizontal scrollbar on report builder

### ISSUE THREAD

**Issue by ioweb-gr** [frappe/erpnext#12520]
I'm experiencing an issue with report views. I can see two horizontal scrollbars and I lose proper alignment when scrolling. 

![image](https://user-images.githubusercontent.com/20220341/35037431-2f99a57c-fb80-11e7-8593-82b69124b4a9.png)

PS: I'm using a 1920x1080 resolution and also I can see that in HTML there are two tables for header and content. Is there a need for separate tables for header and body in the HTML?

**Comment by umairsy** [comment]
Issue not replicating in my local build, running on latest develop branch. Please upgrade your instance and check again. Also, indicate the browser in which this issue is occurring.

Will be great if we can shift this discussion in the community forum. If it is validated as the bug, we can reopen this issue.

https://discuss.erpnext.com
