### ISSUE TITLE
Can't add new primary contact before having saved the Customer

### ISSUE THREAD

**Issue by binary64** [frappe/erpnext#12588]
Am on latest erpnext develop..

Click Customer > New > Customer Primary Contact > Create a new contact.. > try and save it

`Could not find Row #1: Link Name: New Customer 2`

**Comment by saurabh-bhosale** [comment]
@binary64 Have fixed this bug, will be available on master soon. This Customer Primary Contact > Create a new contact was giving you an error because the Customer was not saved and it couldn't find the customer name in the database(child table's row). Hence this, 'Could not find Row #1: Link Name: New Customer 2'.

Also, that sections main purpose is to just select a primary contact out of many other contacts for that same customer. You will understand the correct flow after this fix is merged. Thanks!
