### ISSUE TITLE
Heatmap and Activity  does not work in develop

### ISSUE THREAD

**Issue by maxfu9** [frappe/erpnext#12722]
Heatmap and Activity  does not work in develop
![screen shot 2018-01-31 at 6 48 59 pm](https://user-images.githubusercontent.com/29174889/35626431-8c89e174-06b7-11e8-8f19-86e3d9ae763a.png)

**Comment by fproldan** [comment]
Same in master!

**Comment by Zlash65** [comment]
What timezone are you from ? This is most probably an issue of timezone I think. The unix_timestamp with data count from the server doesn't match with the timestamp generated for each block of heatmap on js side.

**Comment by maxfu9** [comment]
So how can be fixed ?

**Comment by Zlash65** [comment]
If you can test this out then it'd be really helpful https://pastebin.com/6yKZxAT0
Replace the code in frappe-charts.min.iife.js with the one on pastebin - the whole code. Do a hard refresh/reload and see if it did the trick. Also if anyone else from a different timezone, can test it and let me know..

**Comment by fproldan** [comment]
@Zlash65 Hi, I tested without no success. I've replaced the file and do a bench clear-cache and bench restart. Am I missing something? Thanks!

**Comment by Zlash65** [comment]
Hi @fproldan , thanks for trying it out. I was able to replicate it on my end too by changing timezone. Have update the code https://pastebin.com/6yKZxAT0 and tested it on India's and America/Dawson's timezone. Can you give it a try again ? Thanks!!

**Comment by fproldan** [comment]
@Zlash65 I tried again with no success. I only do a bench clear-cache and restart after change the file, a bench build is also needed?

**Comment by bghayad** [comment]
@Zlash65 
I am in Lebanon and I test what you mentioned (and I did very good refresh, even I restarted the server).
I tried the following timezones:
Asia/Beirut, Indian/Cocos and America/Dawson's.
And all of them gave me the same result, the heatmap did not work.
By the way, I tried this on the following versions:
ERPNext: v10.0.19 (master)
Frappe Framework: v10.0.20 (master)
But I have also another version which is erpext 9.2.2 and I did not find the file "frappe-charts.min.iife.js" but I find a gantt directory and gantt file. Why? 
Because this file: frappe-charts.min.iife.js is not existed in erpnext 9.2.2 so I feel it is not the file that is causing this trouble.
I am surprised how it worked at your system and did not work at our systems?
What is the erpnext version that you running and you did the test on it?
Regards
Bilal

**Comment by bghayad** [comment]
Hello @Zlash65 
By the way: you need me to replace the of the file frappe-charts.min.iife.js by which code (The below code or the above code?) in this link:
https://pastebin.com/6yKZxAT0  ?

Regards
Bilal

**Comment by bghayad** [comment]
Hello @Zlash65 
I tried both of them and it did not work. As frappe-charts was introduced in v10, so why the problem is existed since v9? In other words, if we considered that the problem from frappe-charts.min.iife.js and this file is not existed in v9, so why the heatmap problems is existed in v9?
Regards
Bilal

**Comment by bghayad** [comment]
Hello;
This issue was scheduled to be in February road map but until now not resolved.
Anyone has any idea about fixing it? Specially that I have recently upgrade for erpnext v10.1.4 and until now the heatmap has the same problem.

**Comment by fproldan** [comment]
@bghayad I also upgrade to v10.1.4 it seems the heatmap of Customer works, but Projects or Products doesn't.

**Comment by bghayad** [comment]
Hello @fproldan 
I am not able to see the heatmap is working in customer or student or any thing else. I am surprised how it worked with u in customer?! 
What is your Country and Time Zone?
Regards
Bilal
