### ISSUE TITLE
[Bug] Unable save Customer while unlink or remove Customer Primary Contact

### ISSUE THREAD

**Issue by jay-parikh** [frappe/erpnext#12872]
Steps to reproduce:
1) Open an existing Customer record
2) Under ADDRESS AND CONTACT section, create New Contact
 ![image](https://user-images.githubusercontent.com/3703266/36086530-039539d2-0ff3-11e8-9f0b-5b44f1862399.png)
3) Save new Contact details with Is Primary Contact checkbox checked.
 ![image](https://user-images.githubusercontent.com/3703266/36086533-064ae80c-0ff3-11e8-919d-c5777cc1976c.png)
4) Not all contacts mapped to ADDRESS AND CONTACT are showing in “Customer Primary Contact” selection. Only Contact with Is Primary Contact checkbox checked are showing.
6) Create new Contact from Customer Primary Contact
7) Go Back to customer again and try to remove “Customer Primary Contact” and save customer record.
8) But somehow new Customer Primary Contact is being created and not able to leave “Customer Primary Contact” field blank and unable to save Customer.

Gif for this issue:
![bug unable to delete or remove customer primary contact](https://user-images.githubusercontent.com/3703266/36086565-352393cc-0ff3-11e8-801f-c96a230e7ad0.gif)

**Comment by umairsy** [comment]
Thanks for reporting. We will soon check and get back to you.

**Comment by saurabh-bhosale** [comment]
@jay-parikh  Fixed this. Also, in your 4th point, you are correct. The section _" Primary Address and Contact Detail "_ shows only primary contacts linked to that specific customer, it is designed that way because a Customer can be identified using his/her primary number and can be searched using the selected mobile_no wherever a Customer link field exists.

**Comment by jay-parikh** [comment]
Thanks @saurabh-bhosale it make sense!
