### ISSUE TITLE
Linking Member with the Customer and Supplier

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12892]
In a cooperation structure, a Member can also be treated as a Customer and Supplier. Add a link of Customer and Supplier in the Member master. May be add a new section from these fields.

- [x] Add Link field of Customer
- [x] Add Link field of Supplier

In future, these values can also be used for analysis like how much sales by made by a member as a customer and vice-versa.

**Comment by kothagunda** [comment]
Should Member have links to Customer and Supplier. Or should Supplier/Customer have link to a Member ?
Or should there be a read only field in Customer/Supplier, which gets auto filled when the link is set in Customer.
So that when we do report pulling on customer/supplier table, we can also query based on the member id.
