### ISSUE TITLE
Missing barcode field on sales order item

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#13006]
Hello,

After the barcode update I got a strange issue, the field for barcode on sales order item is missing, and barcode information is not being filled with the barcode information anymore, apparently this is not related to the new barcode table as discussed here: https://github.com/frappe/erpnext/issues/12954

I have no apps installed or any modification made with developer mode on

ERPNext: v9.x.x-develop (7c744ac) (develop)
Frappe Framework: v9.x.x-develop (aa5f951) (develop)

**Comment by adityaduggal** [comment]
@applepipe Don't you think you are on an old develop branch since the current develop branch is way ahead of the version pointed out by you. See my develop branch settings below:

![image](https://user-images.githubusercontent.com/1057509/37239852-273ca580-2468-11e8-98c0-7e1d41ebafff.png)

I think you need to update your develop branch and then only confirm if you still have the issue, honestly I haven't checked for the issue but seeing the version only gives me a feeling that this issue must be closed since its on an old develop branch if it exists.

**Comment by applepipe** [comment]
@adityaduggal yes, considering that I've posted 20 days ago the version back then was way back than today, the updated version is dealing with barcodes the way it did before, for now closing.
