### ISSUE TITLE
Variable weight

### ISSUE THREAD

**Issue by delinatie** [frappe/erpnext#13172]
I'm setting up erpnext for a food trading company.

I'm having difficulties with the UOM and variable weights.

The products are always billed in kgs, because the pieces vary in weight. For example, 1 piece of pastrami has a target weight of 2kg, but can differ up to 10-15%.
There are 10 pieces of pastrami to 1 box, 8 boxes per layer on a pallet, and 9 layers of boxes on a pallet.
The customer orders in boxes or in kgs, get's billed in kgs. Delivery shine states kgs and pieces.
The supplier delivers in pieces and kgs (e.g. 20 pieces for 41.45 kg).

I've set up the items like this:
default UOM: kg
Inventory: Weight UOM: kg
                 Weight per unit: 1
UOM: kg, conversion factor: 1
          pieces, conversion factor: 2
          box, conversion factor: 20

I've tried to set the inventory weight UOM to piece and weight per unit to 2, but this always results in incorrect sales order quantities (it always multiplies the kgs with weight per unit (2 in this case), while it should divide).

When I make a sales order in boxes, I can enter the amount in kgs and set the UOM to kgs, but the system doesn't accept because the order was made in boxes. It will only accept number of boxes. However, I need to input the actual kgs to have a correct invoice and stock transaction.

What I basically need is a way to always translate number of boxes, palets, ... to pieces and kgs; both for the purchase and sales work flows. I should be able to make a receipt for x pieces with x weights, allowing for a tolerance in weight per item.

How should I go about it?

Thank you.

**Comment by umairsy** [comment]
I've tried to set the inventory weight UOM to piece and weight per unit to 2, but this always results in incorrect sales order quantities (it always multiplies the kgs with weight per unit (2 in this case), while it should divide).

**Try 0.5. You can also enter conversion rate in the sales order item itself.**

What I basically need is a way to always translate number of boxes, palets, ... to pieces and kgs; both for the purchase and sales work flows. I should be able to make a receipt for x pieces with x weights, allowing for a tolerance in weight per item.

**Since conversion rate is a editable field in the transaction, you can enter any conversion rate on the fly to get the correct no. in default UoM in the item.**
