### ISSUE TITLE
Sales POS Invoice shows unused Tax rows 

### ISSUE THREAD

**Issue by kothagunda** [frappe/erpnext#13208]
We use multiple tax rates for various items in a single invoice.  Since to get multiple taxes in a single invoice, we have to create a generic tax template, with tax set to 0, so that item tax is fetched we created a generic tax template.

![image](https://user-images.githubusercontent.com/30433779/37077574-8e8ac096-2201-11e8-821e-b90a51443519.png)

Now when we create a sales invoice, assume the invoice has only one item with tax 5%. Still the invoice shows a table of all the other tax rows also, with tax amount 0, as there were no items for those tax rate. This table itself occupies lot of space in the invoice. Once we add SGST, and CGST the table size will double. If we have 5 rates, total rows will be 10 (5 SGST, 5 CGST). 

![image](https://user-images.githubusercontent.com/30433779/37077741-45f8acf2-2202-11e8-88b5-347aa05c23e2.png)

![image](https://user-images.githubusercontent.com/30433779/37077760-5cb8c88c-2202-11e8-9054-9b3db5181238.png)

Can this be fixed to show only the tax amounts, for which items were present.

I guess Purchase invoice will have same issue. Did not try it.

**Comment by saurabh-bhosale** [comment]
@kothagunda This same thing can be achieved using the _'Item Tax'_ section in Item Doctype, this allows you to set taxes at item-level so that these get fetched in both Sales Invoice as well as Purchase Invoice and for taxes section you will just have to add entries like CGST, SGST only once and use this same template in your Invoices. 

Have added images to explain the flow:

**Item 1:**
![item1](https://user-images.githubusercontent.com/25682214/37211361-b6814800-23d1-11e8-8839-064ca8891b54.png)

**Item 2:**
![item2](https://user-images.githubusercontent.com/25682214/37211395-ce48279c-23d1-11e8-8616-6fcb12c30f8b.png)

**Sales Invoice with the above items:**

_Invoice' item's table:_
![si_item](https://user-images.githubusercontent.com/25682214/37211407-d71f61f0-23d1-11e8-8673-a586867a49f4.png)

_Same Invoice' tax table:_ 
![si_tax](https://user-images.githubusercontent.com/25682214/37211466-056bb522-23d2-11e8-8805-ccc4b1af7b63.png)

**Purchase Invoice with the above items:**

_Invoice' item's table:_
![pi_item](https://user-images.githubusercontent.com/25682214/37211528-3ba5008a-23d2-11e8-9d59-54bfc2c1be36.png)

_Same Invoice' tax table:_
![pi_tax](https://user-images.githubusercontent.com/25682214/37211534-41cfe97a-23d2-11e8-8bba-7eef374d2412.png)

**Sales charges and Tax template:**

![tax_template](https://user-images.githubusercontent.com/25682214/37211630-9627de7e-23d2-11e8-9c81-531c343d83bd.png)

Hope this helps in resolving your concern.

**Comment by kothagunda** [comment]
Thanks @saurabh-bhosale for the detailed work around with snapshots.. I think this solution is definitely better then the way i used the tax heads. Couple of things

1. In your case, the tax table in the invoice shows that the rate is 0. But the tax amount is non zero. In my case also, it shows up as zero, but since account head name is GST8% we atleast know what %tax rate was applied. Is there a way to show the tax rate applied in the invoice. It would be a good user experience
![image](https://user-images.githubusercontent.com/30433779/37217165-cd25da42-23e2-11e8-8fec-343329fe2ac9.png)

2. What %rate did you set while creating the SGSC, IGST, CGST account heads in the chart of accounts. In mine for SGST8% i set 8% and so on. 

3. Also this would still be a problem, for those who want to have a separate tax account heads for each tax rate. [But i will check with my accounts person here and go with the way you suggested.]

Thank you again.

**Comment by saurabh-bhosale** [comment]
@kothagunda Glad to help!
1. You can see what rate/taxes are applied to each by checking the _Tax Breakup_ Section which is below the tax table in Invoice. It shows item-wise tax breakup and you can see it in GST POS Invoice(refer above POS image in earlier comment) as well.
![taxbreakup](https://user-images.githubusercontent.com/25682214/37220408-907669f4-23ec-11e8-9737-fc92e39a664f.png)

2. Since the tax rates are defined at Item level, the rate in each of these used Account Head is set to zero. 
![account head](https://user-images.githubusercontent.com/25682214/37220916-1be2c0ea-23ee-11e8-9c56-fd1c3c4c949f.png)

**Note:** In cases, where a rate exists in both Account Head as well as at item-level, the rate set in item level is given more priority and the same is picked up in Invoices.

**Comment by kothagunda** [comment]
Thank you for the responses @saurabh-bhosale . Sure will use the GST POS print. Thanks for sharing the HSN based tax rate.

I got response from my Account team, he said "yes, we have to open separate tax head for each tax rate. ". So i think we will have original issue. As we cant just use SGST, CGST, IGST, instead we will have multi SGST each with the tax rate ex SGST-8% etc. Similary CGST, and IGST

so can something be done for this please ?

**Comment by umairsy** [comment]
It is configurable from Print Settings.

![screen shot 2018-03-19 at 11 14 49 am](https://user-images.githubusercontent.com/910238/37579924-0579182e-2b67-11e8-9c02-ce9e1dd47846.png)

**Comment by kothagunda** [comment]
Thanks @umairsy  and @saurabh-bhosale .
Appreciate your responses.
