### ISSUE TITLE
Enable and Disable option for Standard Print format

### ISSUE THREAD

**Issue by AravindPranera** [frappe/erpnext#13292]
We need a option for Enable and Disable the Standard Print format because we have a custom print format. And also there is a chance for user to take the print in standard format by mistake.
Kindly do needful.

Thanks.

**Comment by saurabh-bhosale** [comment]
@AravindPranera You can either set your custom print format as default by opening it from the print format list
![ans1](https://user-images.githubusercontent.com/25682214/37345752-9e1d65b2-26f3-11e8-875d-8448906338e4.png)


Or by using Customize Form and entering the Doctype for which the custom print format is to be applied and set the default print format there.
![ans](https://user-images.githubusercontent.com/25682214/37345829-c3049fb2-26f3-11e8-8d3a-e3c568b8c239.png)

**Comment by AravindPranera** [comment]
If Purposely user is taking in Standard print format mean?

Thanks.

*Pranera Services & Solutions Private Limited*
*1A, Sastri Nagar,Angeripalayam Road,*
*Near SP Office,**Tiruppur - 641602.*
*Mob : 9786473999.*
*ba@praneraservices.com <ba@praneraservices.com> | www.praneraservices.com
<http://www.praneraservices.com>*

**Comment by pipech** [comment]
This feature is needed because there might be some information on standard print format that company want to hide.

ie. Purchase Receipt,
I've set user permission to hide all price field and report but **I can't disable standard print format which contain price field which I want to hide.**

![capture](https://user-images.githubusercontent.com/24489363/51654318-e73e0600-1fc9-11e9-8493-a4fa55939b81.JPG)
