### ISSUE TITLE
PO No. not getting fetched from Sales Orders to Sales invoice

### ISSUE THREAD

**Issue by maheshengg** [frappe/erpnext#13294]
I describe my problem as per below.

Case I
In my print format, if I put customer purchase order no  : po_no , it fetches purchase order reference from sales order while making sales invoice from SO
but same po_no when entered while making a stand-alone / seperate invoice, it does not work.

Case II
In my print format, if I put customer purchase order no. : po_no_custom, it fetches purchase order refernce when making stand-alone invoice, i.e no ref of any doc (so/dn), however, when trying to make invoice from DN or SO, it doesnt show po.

Support suggested that I should create two duplicate print formats? NO WAY

Another option would be to add both the PO No. and Date field in the field format. It will only show the PO Field which has value. The PO field which doesn't have value should be hidden by default. But this didnt worked either, as I am using custom-html inside Print Format Builder. In the custom print format, i have embedded custom html, and it prints "none" if the field value is blank,
can you help me with some script that can hide this "none" appearing in the print format, a simple if else then kind of script ? can anyone help me with some script that can hide this "none" appearing in the print format, a simple if else then kind of script ?

```
<div style="height: 1.5in"></div>
<div align="center">
  <center>
<table class = "table table-condensed table-bordered" style="border-collapse: collapse" bordercolor="#111111" cellpadding="0" cellspacing="0">
<tr>
<td style="width: 35%;">
<b>{{ _("Invoice To") }}:</b> <b><font size="3">{{doc.customer_name}}</font></b><br>
{{ doc.address_display }}
</td>
<td style="width: 35%;">
{{ _("Ship To") }}: <b><font size="3">{{doc.customer_name}}</font></b><br>
{{ doc.shipping_address }}</td>
<td style="width: 30%;">
<b>{{ _("Invoice No") }} : </b>&nbsp;<b><font size="3">{{ doc.name }}</font></b><br>
<b> {{ _("Invoice Date") }} :  {{ frappe.utils.formatdate(doc.posting_date, "dd-MM-yyyy") }}<br>
<b>{{ _("PO #") }} :</b> {{ doc.po_no_custom }}<br>
<b>{{ _("PO Date") }} :</b> {{ frappe.utils.formatdate(doc.po_date, "dd-MM-yyyy") }}</td>
</tr>
</table></center>
</div>
```

Currently I am using both the fields, , heres the output looking like

![image](https://user-images.githubusercontent.com/1590079/37338532-b9faeb1c-26dd-11e8-9092-1ea138b0108f.png)

Dear All, it was working perfectly earlier, now suddenly you thought there should be another field as std field, making my PO field as custom.

Need to resolve this asap

**Comment by saurabh-bhosale** [comment]
@maheshengg 

1. If purchase order&date are fields that WILL exist in both the case(standalone invoice/invoice with some reference) and you have a custom field for po as well as po date, try doing this:

```
<b>{{ _("PO #") }} :</b> {{ doc.po_no or doc.custom_field_name }}<br>
same for po date
```

or if you dont have a custom field to enter po no and date in standalone invoices and wish to add/write it on the go on the print then consider adding a blank quote like this:
```
<b>{{ _("PO #") }} :</b> {{ doc.po_no or " " }}<br>

```


2. and if all you want is to skip printing po no and po date in your print format when you don't have it(for standalone invoices) since you have custom HTML in your case, can you try doing this?

```
{%  if(doc.po_no) %}
<b>{{ _("PO #") }} :</b> {{ doc.po_no }}<br>
<b>{{ _("PO Date") }} :</b> {{ frappe.utils.formatdate(doc.po_date, "dd-MM-yyyy") }}</td>
{% endif %}
```  

Please try the suggested approaches and if things still don't work out let us know on [ERPNext Forum](https://discuss.erpnext.com/) since that is the correct place to clear these customization doubts/questions.

Closing this issue for now.

**Comment by maheshengg** [comment]
Thanks but this issue has been re-addressed by changing the behaviour the
field.
Now it can pull the value from one doc as well as get from user

Regards,
Mahesh
