### ISSUE TITLE
Bench update command getting stuck on new Production VM

### ISSUE THREAD

**Issue by sahilburman** [frappe/erpnext#13313]
Testing the new Production VM with Ubuntu 16 x64

Running bench update or bench update --reset command getting stuck at 
`INFO:bench.utils: sudo supervisorctl restart frappe-bench-workers: frappe-bench-web:`

![image](https://user-images.githubusercontent.com/1945140/37506381-96ddfe92-290f-11e8-99ce-1c9210af746d.png)

**Comment by codingCoffee** [comment]
Have identified the issue, and working on a fix. In the meantime, use
```
sudo systemctl restart supervisor
```
before running

```
bench update
```

**Comment by krnkris** [comment]
@codingCoffee 

Your commands solve the problem.
Will be a new Production VM upload?

In case then please change the "Administrator" password back to "admin".

**Comment by codingCoffee** [comment]
> Will be a new Production VM upload?

Yes, there will be a new Production Image released every week. 

> In case then please change the "Administrator" password back to "admin".

Any specific reason for the same ?

**Comment by krnkris** [comment]
@codingCoffee 

"Any specific reason for the same ?"

Confuses people if they see on the download page password "admin" 
instead of the pasword "frappe":

https://erpnext.com/download


"Once the Virtual Machine boots, use your HOST operating system's browser and go to:

    http://localhost:8080

and login using:

    user: Administrator
    password: admin
"

**Comment by codingCoffee** [comment]
Thanks for pointing it out. Will make amends on this page ( https://erpnext.com/download ) too

**Comment by krnkris** [comment]
@codingCoffee 

THX.

BTW:
The virtual appliance uses Ubuntu 16.04.
instead of
Ubuntu 14.04

**Comment by codingCoffee** [comment]
Yup, I know that @krnkris :P 
I am the one working on it :P

**Comment by krnkris** [comment]
@codingCoffee 

Just download a new VM Production 
the issue is the same, with first 
bench update.
It stuck on: 
INFO: bench.utils:sudo supervisorctl restart frappe-bench-workers: frappe-bench-web:

After rebooting the VM instance 
bench update 
goes well.

Thank you!

**Comment by codingCoffee** [comment]
I don't think this is fixable. The problem lies in Ubuntu or rather Debian I presume. Supervisor does not start properly on reboot. I had bypassed this by using a cron job which executes 20 seconds post reboot. And hence as you mentioned after the 1st reboot it works properly. 

https://github.com/frappe/bench/blob/63047730c5cb8a39a4015efc4bb6ade4c555fb1f/vm/scripts/restart_supervisor.sh#L8 

I think when you load the virtual machine the 1st time it does not execute the cronjob. And hence the issue. After the 1st boot, you can execute `systemctl restart supervisor`, and get the `bench update` working

**Comment by krnkris** [comment]
@codingCoffee 

THX.

BTW:
The virtual appliance uses Ubuntu 16.04.
instead of
Ubuntu 14.04
