### ISSUE TITLE
Leader-board not being translated 

### ISSUE THREAD

**Issue by dufani1** [frappe/erpnext#13337]
I noted that the leaderboard contents not translated when change the user language.
Regards,

**Comment by jaichavan** [comment]
Hello, @dufani1 thanks for reporting this issue and pointing out something that skipped our attention. Just replicated the issue on my test account and I stand corrected. We will investigate and ensure this issue is addressed in the upcoming versions, as soon as possible. Attaching screenshots for reference:

1. LeaderBoard in "en" :

![screenshot 2019-01-19 00 49 17](https://user-images.githubusercontent.com/40264279/51408386-860ad280-1b84-11e9-8e8f-bcff12a0c450.png)

2. LeaderBoard in "ar" :

![screenshot 2019-01-19 00 50 43](https://user-images.githubusercontent.com/40264279/51408413-9d49c000-1b84-11e9-86ba-2da7c80569e5.png)

**Comment by Anurag810** [comment]
Fixed
