### ISSUE TITLE
Option to skip Employee monthly Loan deduction

### ISSUE THREAD

**Issue by ushashmi** [frappe/erpnext#13501]
Can we add a provision in the system not to deduct the loan installment in any particular month? Actually if employee is on Leave without pay for the whole month then there is no salary from which the loan can be deducted.  Currently the system is making negative salary 

Additionally there should be option to recalculate the repayment schedule once a loan deduction is skipped.

**Comment by mamtakb** [comment]
I also need this. Please let me know is there any work around to skip load deductions for given month

**Comment by seehive** [comment]
i am also looking for a solution to skip loan repayment for any specific month. is there any update on the same ?

**Comment by aakvatech** [comment]
I am looking for this too

**Comment by aakvatech** [comment]
1. As an employee, I should be able to raise a "Loan Deduction Amount Change Request" to change loan deduction amount or skip it during the next payroll, so that my net pay is calculated accordingly.
2. As an approver, I should be able to approve the loan deduction amount change, so that the "Loan Deduction Amount Change Request" is duly approved and affected in the payroll calculation.
3. As an employee, the system should ensure that there is no negative pay due to larger loan amount deductions or overlapping loans, so that I get a certain amount of net pay to keep up my livelyhood.
4. As a system administration, I should be able to setup % of normal net pay as minimum amount or fixed minimum amount of net pay, so that the payroll calculations can alert the hr/payrol manager accordingly as a prompt when creating/saving payslip.
5. As a hr/payroll manager, I want the loan to be rescheduled when a  "Loan Deduction Amount Change Request" is approved so that the next months deductions can be done accordingly. This should consider the pending amount and monthly deductions specified in the loan. The number of months for the loan, if set, should be updated accordingly.

**Comment by manan-ft** [comment]
One thing that we might have to take care of is the revised Repayment Schedule. If we change the repayment amount, the repayment schedule changes if there is interest applicable. We need to think through how to handle this.
This is what the logic should be according to me,
1. The interest amount due after a period is calculated based on the period elapsed , the applicable interest rate and Remaining Principal Amount
Interest Amount = Remaining Principal Amount * Rate of Interest/100
2. Based on the Request for Change in Repayment Amount (Approved Repayment Amount), Remaining Principal Amount (after this payment) is calculated and stored
New Remaining Principal Amount = Approved Repayment Amount - Interest Amount
3. Next the values below the above line (Current Repayment) is recalculated

Would like to know everyone's comments/suggestions
