### ISSUE TITLE
Leave and Expense Claim Approval

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#13520]
- [x] Add child table for expense approvers in Department
- [x] Add child table for leave approvers in Department
- [x] Implement existing (master) approval process

**Comment by nabinhait** [comment]
@Olawale1 You are right that the approval process needs more level from outside department. We are implementing approvers table in department for first level approval. At the same time, we are also implementing conditional workflow. By using conditional workflow (using amount or any other field's value from the form), you will be able to implement more complex approval process as per your need.

**Comment by Olawale1** [comment]
@nabinhait thanks for your response. I'm really glad to hear about conditional workflow and I hope it's ready like yesterday :)

I'm however still wondering what would be the use of this table and hoping it won't interfere with workflow. In the current implementation where we have a single expense approver defined, it is causing problems in workflow because it is hardcoded and therefore still required even when the workflow says otherwise! If you add a table for 1st level approval, how does a user extend it if they need more than that (and most people do)? The only way is to bypass it and use workflow

Since you are already working on conditional workflow, why not just set a default (workflow) for Expense Claim and Leave Application? If however you are still convinced about the table, please ensure that it doesn't interfere with workflow like the issues we are facing currently

Thanks
