### ISSUE TITLE
Batch Update of BOM Costs #feature request

### ISSUE THREAD

**Issue by nmikaty** [frappe/erpnext#1357]
Hello,

It would be nice to have a tool in the Manufacturing module that would allow us to update all the BOM costs at once.
After an Item price change, we need to update manually every single BOM the item is in. This can take forever if you have hundreds of BOM and Items.

Best regards,

Nicolas

**Comment by tkhamdan** [comment]
+1

**Comment by graphskill** [comment]
I am flabbergasted that this is not implemented. This is an essential part of any ERP system. The cost of the raw material goes up, the BOM HAS to be automatically updated. I cannot think of any situation where this would not be necessary.

Sales staff ask for 1000 ubolts. Production staff create production order and manufacture them. BUT the details are wrong because the raw costs have not been updated 

There should be a tick box setting in manufacturing that asks the question "Do you want stock price changes to automatically update BOM cost"

If that is ticked then whenever the BOM is viewed it should automatically fetch new prices, and whenever a production order is created, again new costs automatically fetched

Is this such a difficult task that it cannot be implemented very quickly?

Surely any though of using ERPNEXt for profit and loss goes out the window without this feature

**Comment by shreyasp** [comment]
@graphskill We will be happy to have merge PR.. 🙂

**Comment by shreyasp** [comment]
@graphskill We welcome all contributions from the community and will be happy to merge PR's from the community, as not every feature can be submitted by Frappé team.

Hope you understand this fact.

**Comment by graphskill** [comment]
@shreyasp Thank you for the clarification. Your first response made it sounds as though the team had it ready. But you are really saying the team has no plans to implement this. I cannot program, so I need to find someone else to program it, then to submit it for the team to review. If all is OK they will add it to the core so that I can use it on cloud? If the team do not approve the sumission then I have wasted my money on the programmer

I understand all that and the reasons why

My main concern though is why this is not already part of core. Surely this is essential, no, an intrinsic part of ERP? Having to MANUALLY update thousands of BOM's is bizarre and I cannot understand why the core team think that is the best method

**Comment by corbincavolt** [comment]
@rmehta Would Frappe be interested in developing this if it's sponsored?  If so, the company I work for would be interested in sponsoring it.  I think ideally, rather than a button, a change to the cost of an item would automatically trigger a price update to any BOMs that contain that item, so there's no user intervention required.

**Comment by rmehta** [comment]
@corbincavolt I would rather change on an event, because if your rates are volatile, you don't want to change it very frequently.

Maybe have a setting in Manufacturing Settings:

- Update BOM Rates Automatically - options (Never, Daily, Weekly, Monthly)

Does that work?

**Comment by corbincavolt** [comment]
So I may have gotten ahead of myself here, unless I don't understand how this works.  Is the manual update only relevant if your rate of materials is based on the last purchase rate or a price list, or does it also pertain to using the valuation rate (which is what we'll be using, specifically FIFO).

**Comment by rmehta** [comment]
@corbincavolt last purchase rate may also be volatile, maybe that could also be a trigger?

**Comment by graphskill** [comment]
Last purchase rate would be essential for us

**Comment by epochc** [comment]
@corbincavolt, @rmehta: Help me on this one. The effect of the rate of the raw materials on the finished product will be reflected in the valuation rate of the finished product, right?

I mean, just taking a look at the stock balance report and looking at the valuation rate should give you the rate of the BoM, right?

Or am I missing something?

**Comment by corbincavolt** [comment]
@epochc I've been trying to figure out how this works, and I think I've got it, but I could be missing something.  If you use FIFO costing like we do, it seems like the valuation rate doesn't actually affect how costs are recorded.  If you look at the stock ledger for a given raw material, the valuation rate seems to be the average cost of your current stock for that item.  For instance, if you purchase 10 of an item at $20 each, and then later purchase 10 of the same item at $30 each, your valuation rate will show as $25.  If you then sell 10 of that item, and view the journal entries on the general ledger, it'll show Cost of Goods Sold to be $200 ($10 x 20), which is exactly what you'd expect if you're using FIFO costing, so it doesn't seem like the valuation rate factors into how items are actually costed.  I did the same test with a BOM and got the same result; the journal entries used FIFO costing, not the valuation rate. 

So with that in mind, @rmehta, does the "Rate of Materials Based On" field have any effect on how the costs of the BOM are actually recorded for a production order, or is it just for the purpose of having an up-to-date approximate cost for the BOM so you know what to set your sales price at to achieve x amount of profit?  If it's just to approximate BOM cost, would it be possible to just trigger a BOM cost update automatically when opening a BOM, instead of worrying about a global periodic update?

**Comment by epochc** [comment]
How about a custom report that lists the trends of last purchase rates? You filter by BoM and you get a sense of what the trend of raw material pricing looks like. You can ignore extraordinary prices and manually assign costs for each raw material in your BoM and that should be very close to reality, while giving you a sense of control over the process. I'd be uncomfortable about ceding control over the whole process to a system, even a system as awesome as ERPNext.:)

**Comment by epochc** [comment]
But @corbincavolt thanks for figuring out the numbers. So you are saying the FIFO/Moving Average part that you choose at the item master only has an effect on the Cost of Goods Sold and not on stock valuation. But I think that once you make that product consuming the raw material at $20, your stock valuation should now be $30.

But interesting point you bring up on the selection at the BoM level - Valuation Rate and Price List Rate. I can understand valuation rate and last purchase rate and depending upon whether you choose Moving Average or FIFO, the cost of goods sold will be charged appropriately. But I wonder, where the delta between the actual COGS and the price list rate gets charged to. Which account? And how does that impact an organization's books? Any thoughts @rushabhm?

**Comment by corbincavolt** [comment]
@epochc Actually, I'm pretty sure FIFO and moving average _would_ have different stock valuations.  In the example I gave they would be the same, but if you say purchased an additional 10 units at $30, the FIFO stock valuation would stay at $30 (you're right in saying at the end of my example above it would be $30) whereas the moving average stock valuation would be $27.50.  My point was just that the FIFO stock valuation will not be the same as the item rate in the CoGS unless you've purchased all your stock for that item at the same price or you use your entire item inventory fulfilling an order.

I need to do more testing to be sure, but my current impression is that it doesn't seem to me like _any_ of the rate of materials options (last purchase rate, price list, or valuation rate) have an effect on CoGS, they're just different approximations of what your BOM cost could be.

**Comment by rmehta** [comment]
Stock valuation is at the transaction level on basis of FIFO. The only reason it would take the price list rate is when the first entry is a negative one.

**Comment by corbincavolt** [comment]
@epochc Just tested last purchase rate for the rate of materials option, and it still used FIFO costing to calculate CoGS, not the last purchase rate.  That being the case, it doesn't seem like a global BoM update is all that important since BoM prices don't affect CoGS.

Regarding the custom report, I don't know personally how much I'd want to rely on last purchase rate since we end up adding shipping-in cost later which increases the price of the items.  I think for us, valuation rate would probably be the most accurate measure, but I like what you're saying about looking at trends in pricing; I think that could be useful.

I may be getting off topic here and may need to create a separate issue for this if I want to explore it further, but regarding pricing, I think it would be nice to be able to have a "BoM Configurator" of sorts where you could test out different product configurations without having to save it as an actual BoM (unless you wanted to).  You'd also be able to add things like overhead and profit margin (potentially in the form of percentages), so you could get a selling price out of it.

**Comment by corbincavolt** [comment]
@rmehta Instead of doing a global update whenever an item price changes, since the pricing on the BOM page doesn't affect GL entries, would it be possible to have the "Update Cost" button functionality just trigger on page load and remove the button?

@epochc Regarding manually setting prices for items in the BOM, couldn't you just create a price list that's just for BOM pricing, change your "rate of materials based on" to price list, and then set it to said price list?  It wouldn't have an effect on your GL entries (none of the pricing options do as far as I can tell), but maybe it would help you if you're trying to figure out how to price a BOM.

**Comment by Terencepcurtis** [comment]
@rmehta , re BOM , Hello, did you resolve the Cost and roll up. I see you talking here about, I am looking at the same problem , can you give me an update ? thanks,, Terence

**Comment by Terencepcurtis** [comment]
@rmehta  we are also trying to look at the BOM cost issues, like you were I am very surprised by this not being very workable, either that or I am missing something in the set up config, or how are using the BOM, as it appears quite primitive . I was expecting the updat versions to resolve this , no, did not. ,

**Comment by nabinhait** [comment]
Added in my todo list

**Comment by Terencepcurtis** [comment]
@nabinhait  hello,, thank you for looking into the BOM cost, I am ok for now about the need to manual (IE Click update) update the cost of BOM but I need to see or get some understanding of what the ERP does with the cost or BOM value, does that update the item price as reference? or what is done with the cost when I "click" Update cost? we make a number of PCBA , some have 50 some have 250 Item parts, so I gather as we add stock and PO update this updates the Item price, so then if I open the BOM it reflects the new Item Price? (correct??) , and then if I click UPDATE BOM, there is new Cost, , so what is that doing, ? clearly I am missing something?  where is the new price located ? thanks .. Terence .

**Comment by LifeP** [comment]
@nabinhait I hope this will address multi-level BOMs. Also is it possible to do this automatically before submission of any transaction?

**Comment by Terencepcurtis** [comment]
@nabinhait hello, was there some activity on this, we are trying to implement ,

**Comment by Terencepcurtis** [comment]
@nabinhait Hello, is the issues of the MULTI Level BOM resolved? 
thanks, Terence

**Comment by nabinhait** [comment]
@Terencepcurtis The feature request is in my immediate todo list. Hoping to finish it in a week or so.

**Comment by Terencepcurtis** [comment]
@nabinhait hi, the BOM Update (manual type) does the BOM update, but also should / needs to update the Parent Item Price ..  
the current update Button in BOM appears to be inconsistent, it, updates the current BOM cost, but not always update the Parent Item in the BOM ? but does not update the Parent Item Price . 

if the update Button was to update the Item Price, I would have thought that would refresh then when you open the Parent BOM and Update Button.  tks, thought ?

**Comment by nabinhait** [comment]
@Terencepcurtis No, currently manual cost update also does not update rate in parent BOM. It only updates rate of current BOM. I will work on it in the next week.

**Comment by Terencepcurtis** [comment]
@nabinhait hi, Ok what I appear to have found is that the Parent Item Price , IE the Parent BOM needs to have a "Item Price " = 0 , the Update does not update the Item Price, as you say, but it allows the Parent BOM to Update correctly, so the BOM price can reflect the new changes, , which does explain what I was thinking was inconsistent, as some Item Price actually had a Value (1.50) etc example, and some had no Item price. This appears to be consistent, it would be "nice" if the Parent Item Price BOM was recorded in that Item Price. 
also.

there is another thread 
BOM - Currency symbol issue #10099
talking about the Currency bug, be aware. 

thanks,

**Comment by Terencepcurtis** [comment]
Nabin,

hello,

the BOM update I now have is "working" reasonable enough, the remaining 
issues are the USD when should be CNY, as I noted in the GitHub issue 
#10099 .. as you can see, this is a more "common" problem, i think it 
would be far better if the Field for Company was at the TOP and inserted 
FIRST so this currency can be clear and set. it appears to be the same 
in number of other screens,

what you can see is in the Exploded BOM view the CNY currency is CORRECT 
,

I would like to see more improvement to the use of the BOM, as it does 
need work , but it shows some promise, if we can get the few bugs 
sorted.







  Regards TGL - Hong Kong www.TGL-manufacturing.com Terence Curtis -
Director LinkedIN: http://au.linkedin.com/pub/terence-curtis/39/b58/61a
Australia: +61 412262646 China: +86 186 8226 8058 Skype: TerencePCurtis

**Comment by nabinhait** [comment]
Fixed via #10195, pending to merge.

**Comment by Terencepcurtis** [comment]
hi, when do you expect these changes to be released?

any timing, ? date
'tks


  Regards TGL - Hong Kong www.TGL-manufacturing.com Terence Curtis -
Director LinkedIN: http://au.linkedin.com/pub/terence-curtis/39/b58/61a
Australia: +61 412262646 China: +86 186 8226 8058 Skype: TerencePCurtis

**Comment by nabinhait** [comment]
It will go into staging branch tomorrow and in the next week will be merged into master.

**Comment by Terencepcurtis** [comment]
@nabinhait hello, did this BOM and cost update happen, not seen any changes, or is there deeper multi currency problems,

**Comment by nabinhait** [comment]
Yes, the changes has been released in master. What is the problem you facing?
