### ISSUE TITLE
Employee Promotion

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#13646]
### Employee Promotion

- [x] Promotion Date
- [x] Employee
- [x] Child Table (Property, Current, New)
     - [x] Modal to add items to child table
     - [x] Populate all the field's label of Employee in Modal
     - [x] On selection of Property, Current value will be fetched

---

- [x] On submit, update new properties to the Employee record via scheduler

**Comment by felixvarghese** [comment]
@nabinhait The downside of calling the doctype "Promotion" is there are also instances where employees are depromoted (moved to a lower designation) and also horzontal moves which aren't necessarily promotions. So, those would also be entered in the "Promotion" doctype. For semantic reasons, you may want to consider using "Transition" rather than "Promotion".
