### ISSUE TITLE
Attribute Customization not working properly

### ISSUE THREAD

**Issue by fusepw** [frappe/erpnext#13660]
Could somebody please help me, i am new on this community and i am trying to setup a items template. One of my attributes requires just generic text, so i customized the interface to give me that option, but not when i go to create the PO it will not let me create the item variant on the pop-up it keeps telling me the field is blank it it is not. 

Want could i do to fix this?

**Comment by umairsy** [comment]
This feature is not available for now. Perhaps you can add a custom field for it in the Item master, or use Item Description, so that value in this field can be updated on the fly.

Please post such queries on the erpnext community forum. If it is validated as a bug or feature request, we can create/open/reopen a Github Issue for it.

https://discuss.erpnext.com
