### ISSUE TITLE
E-way Bill for Indian Customer

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#14292]
- Sales Invoice 

I think, at the time of submission, there should be a script that will check invoice amount is greater than 49,999.99. If yes, then there should be a dialogue box that will pop-up and force the user to key-in the eWay-Bill number. ( that will make the user generate e-way bill from the GSTN portal) and then submission of the invoice should happen.

- Purchase Invoice

Similarly, at the time of submission, there should be a script that will check the invoice amount as per above and force the user to key-in the e-way bill. In this case, he may also be required to upload the Form for his reference and records.

**Comment by PawanMeh** [comment]
I assume this should be only for users who transport goods or receive goods from a transporter.

**Comment by kennethsequeira** [comment]
#13948

**Comment by maheshengg** [comment]
@PawanMeh validation can be taken from the chart of accounts. If the item has default income account as "sales" .. else if "service" bypass the condition.

**Comment by amitsaxena01** [comment]
It will be a good addition. Can we also have an ability to download a JSON file that can be uploaded to eway bill server?

**Comment by test2a** [comment]
Forcing e way bill generation is a bit strong because you have to consider 2 limits. First the bill value exceeding 50,000 of only "taxable " items in a bill. So if there is a mixed bill of taxable and non taxable goods, only taxable goods would be counted for e way bill.

Second, the local sale distance limits which is 50 kilometres in the state/ut of the seller. There is no need. There are further exceptions to e way bill generation so I would suggest:

Once a sale invoice is generated and saved, it should ask for e way bill. If selected yes, then ask for transporter details and other missing details. Then it should generate a json file which would be manually uploaded to e way bill login. 
Bulk e way bill json should be made available and a validation engine of sorts which would tell of any mistakes before generating the json.

I would strongly suggest avoiding going the api route because that needs a lot of development time and costs money per api call. Json is free.

Im up for any technical help related to gst india, so please ask up.


https://taxguru.in/goods-and-service-tax/cbec-amends-eway-bill-rules-cgst-amendment-rules-2018.html?amp

**Comment by maheshengg** [comment]
heres the flow chart of decision making whether a Eway-Bill is required or not. 
To start with we can work out with a JSON download option. 

![image](https://user-images.githubusercontent.com/1590079/40976633-51064fc4-68ec-11e8-93b7-9e1a7d9d995e.png)

**Comment by maheshengg** [comment]
any updates on this ?

**Comment by jk2081** [comment]
Why was this closed? Is it already added?

**Comment by nabinhait** [comment]
Yes, it has been added in develop branch
