### ISSUE TITLE
Error when migrating to latest ERPNext 10.1.36 

### ISSUE THREAD

**Issue by fabyc** [frappe/erpnext#14321]
When trying to migrate from ERPNext 10.1.27 to latest 10.1.36 I get this error:

`pymysql.err.InternalError: (1050, u"Table 'tabEmployee Health Insurance' already exists")
`

The command I’m using to update is:

`bench --site thesite.com migrate`

This is reported on:
https://discuss.erpnext.com/t/error-when-migrating-to-latest-erpnext-10-1-36/37226

Thanks

**Comment by Zlash65** [comment]
It appears that you switched your branch from develop to master or vice-versa thats causing the issue. Maybe try maintaining different sites for master and develop branch to avoid conflicts.

Develop and Master branches are different from one another in the sense that develop has a lot of data that haven't been refined yet and master consist of those selectively refined data. Switching between them causes issues because a lot of stuff might have been deleted, renamed, etc which will cause issue when you run a patch or migrate.
