### ISSUE TITLE
Cannot Receive from Supplier without any negative outstanding invoice

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#14575]
Can't allocate a payment to more than one purchase invoice.
_**Cannot Receive from Supplier without any negative outstanding invoice**_

1. Create New Payment Entry
2. Select Mode of Payment
3. Select Party Type and Party
4. Enter Paid Amount
5. Receive message "Cannot Receive from Supplier without any negative outstanding invoice"
6. Allocate Payment amount in table
7. On save, receive again "Cannot Receive from Supplier without any negative outstanding invoice"

![new_payment_entry_1_-_new_payment_entry_1](https://user-images.githubusercontent.com/25084259/41552275-f0f75846-72f3-11e8-903f-084aa5bf5ffa.jpg)

**Desktop (please complete the following information):** :cyclone:
 - OS:
    - [ X ] macOS
    - [ X ] Windows
 - Browser:
    - [ X ] Safari
    - [ X ] Chrome
    - [ X ] Firefox

**Version Information**
ERPNext: v10.1.37 (master)
Frappe Framework: v10.1.36 (master)

**Comment by navtertechnologies** [comment]
What did you say about this windows?

Desktop (please complete the following information): cyclone
    OS:     
   [ X ] macOS
        [ X ] Windows
    Browser:
        [ X ] Safari
        [ X ] Chrome
        [ X ] Firefox

Version Information
ERPNext: v10.1.37 (master)
Frappe Framework: v10.1.36 (master)

**Comment by jaichavan** [comment]
Actually, @franciscobuendiao I was trying to replicate this, you can't add payment entry to one purchase invoice, also, if there is no negative outstanding invoice. Whether this should be viewed as a bug or just validation of the person who developed this, can't comment. Let me review this with my team at Frappe, and get back to you! Thanks for reaching out.

**Comment by elan-k** [comment]
@jaichavan, @franciscobuendiao 
Looks like this message popup when your not selecting the "Payment Type" as "Pay" on the Top of the Screen. 

"Receive" is selected as default at the "Payment Type" field. Plz change that to "Pay" since you are trying to pay your suppliers, then your problem will disappear (becaz i was having this issue too). 

![Pay at Payment_Entry](https://user-images.githubusercontent.com/78781781/116706060-d4a5a900-a9ea-11eb-8194-52d2090fc237.PNG)


Version Information
ERPNext: v12.19.0 (HEAD)
Frappe Framework: v12.16.3 (HEAD)

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.
