### ISSUE TITLE
Incorporate Incoterms in PO and SO along with scope of delivery

### ISSUE THREAD

**Issue by vorasmit** [frappe/erpnext#14712]
Issue: Feature Request

It is related to goods industry.
Incoterms are internationally accepted standard terms of delivery. Mentioning them in sales order/purchase order would clarify what additional charges (like packing, loading, freight, insurance charges) may be required to charge in invoice while preparing the same.

Scope of delivery is an important factor for business with custom added features for their customers, which may change from order to order (eg: free delivery).

However, It may be similar for particular customer class.

Considering all this, I propose following solution.

Solution:
- New Doctype for Incoterms (with all incoterms, with their description).
- New Doctype for the scope of delivery (which will cover additional features promised for order, like packing/loading/testing/freight etc.)
- Map Incoterms with Scope of Delivery. Like Incoterm FCA (Free Carrier) would cover Packing and Loading charges, but will not cover freight and insurance.
- Add Incoterms field and scope of delivery in Sales and Purchase order.
- Standardized Incoterms for particular customer/supplier configurable from supplier/customer doctypes, fetched in SO and PO.

Application:
- Similar to Taxes and Charges template.
- We choose incoterms and relevant scope of delivery table pops up (which covers charges borne by the seller).
- Where required users can add custom scope of delivery conditions to the table.

The objective of adding Scope of Delivery as separate doctype:
- Users can customize it to add various benefits provided in order and could reduce chances of invoice with errors.
- Also, Check can be put to all purchases.

Link to understanding incoterms:
https://www.tradefinanceglobal.com/freight-forwarding/incoterms

**Comment by abhioncode** [comment]
This is definitely a needed feature for ERP that claims to be for larger customers. I have found one thing that could work for this, which would be Shipping Rule. The issue with Shipping Rule is that its too focused on being a fixed shipping module, if we could make changes and make it more flexible, say assign a shipping rule and allow user to introduce the cost on an per invoice basis (since Impex the prices always fluctuate). The other option would to ignore shipping rule as it doesn't make much sense and be to just add and incoterm field onto the Invoice, SO, PO, etc. At least we will be able to show suppliers and customers under what conditions we purchased or sold the goods. Someone in another thread even suggested to use T&C as this which I feel might be a decent workaround.
