### ISSUE TITLE
[V11] Shift Assignment - Attendance - No link or validation

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#14764]
Steps:

1. Created Shift Assignment for the user. It was created it bulk on submission of Shift Request.
2. In Shift Assignment, there was no value to check/uncheck "Present" field.
2. Created Attendance, hoping that it will check Present field in the Shift Assignment.

Seems there is no link between Attendance and Shift Assignment. Should there be?

**Comment by karthikeyan5** [comment]
The 'present' field in 'Shift Assignment' has been removed in V12 (as there was no visible use case for it). Yes, there is no link between Attendance and Shift Assignment... is such a link required? what purpose would it serve?
But, there is a link between Attendance and Shift Type, A 'Shift Type' can be linked to attendance if that attendance was marked for that shift.

Closing as this seems outdated, please reopen if it is otherwise.
