### ISSUE TITLE
[Feature Request] Allow to change the Depreciation Amount in the Asset for Manual depreciation method

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#14809]
Allow to edit the depreciation amount while making depreciation journal entry for Manual depreciation method

**Comment by FinForceConsulting** [comment]
@rohitwaghchaure - what is  Manual depreciation method?
I have only know SLM or WDW method of depreciation in accounting. As per accounting standards, the methods cannot be self-defined.

**Comment by ma-lalonde** [comment]
I request this as well. The current depreciation options are not flexible enough to account for all country regulations. A truly manual mode where you can create the dates and amounts without having them overwritten is necessary.

For example, in Canada, depreciation is calculated on a year-to-year basis, not per real duration. So if I bought something in December, I can't even have a manual entry for December 31st because the manual mode also creates an entry in January - which is undesirable.
