### ISSUE TITLE
Sales Invoice Timed out 

### ISSUE THREAD

**Issue by deepak727** [frappe/erpnext#14800]
Hi,

I am trying to create the sales invoice from delivery notes, where there is more than 300 Delivery notes and more than 600 items. i.e. some of the delivery notes contains 5 items and some contains 10, so this is how the total number of items may be 600 plus or even more.

Now when I am creating invoice from that delivery note it gives me request timed out error, and it seems this is happening due to fetch the data from SQL and gunicorn process is responsible for that.

Please the below post in forums and please try to resolve this in high priority.

https://discuss.erpnext.com/t/sales-invoice-timed-out-error/37898/3

Regards,

Deepak Singh

**Comment by deepak727** [comment]
Hi @rohitwaghchaure ,

Any News on the same ?

Regards,

**Comment by deepak727** [comment]
Hi 

Team any good new ? :)


Thanks.

**Comment by deepak727** [comment]
Hi Guys,

First of all happy new year.

Any good news on this issue? Since it is pending from long time.

Thanks

**Comment by rmehta** [comment]
@deepak727 this could be due to multiple reasons. At scale inserting via ORM may not be the best option and it would be wiser to do a custom insert.

At the product level, at this point there is nothing we can do to fix your specific issue.

I would recommend buying professional support from Frappe (https://erpnext.com/support) or a freelancer would be the best option
