### ISSUE TITLE
Properties 'width' and 'columns' have no effect

### ISSUE THREAD

**Issue by Simiil** [frappe/erpnext#14916]
I have a DocType, containing a table of another DocType that is configured as a child table. The second doctype has 8 properties (of type float) with `in list view` set.

**Expected behavior:**
The Table that is shown for the child-doctype contains 8 columns, or the number of columns specified in the entry of the parent doctype. The columns should also have the sizes given in the 'width' property.

**Actual behaviour:**
The table shows only 5 columns, and all columns have the same size, regardless of what is set in 'width' and 'columns'

However, the sizes are reflected in the print view.

**Comment by aure1is** [comment]
I can set the columns for fields of a child table, and they work in grid view of another doctype table field. However, when I set columns for a field that is not a child table but a normal table the list view does not represent the columns setting for the fields. The list view is not modifiable via columns or width field.

**Comment by ollyboy** [comment]
Confirm this issue still exists in the latest dev. This is a highly visible annoyance to users

**Comment by Nihantra-Patel** [comment]
**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.
If the issue occurs then please create a new issue according to the latest version (14 or 15) with a video document if possible.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
