### ISSUE TITLE
ERPNext Tally Migrator

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#15099]
Make a connector between ERPNext - Tally to sync following masters from Tally in ERPNext.

- [x] Chart of Accounts
- [x] Parties
- [x] Invoices
- [ ] Warehouses
- [x] General Ledgers
- [ ] Stock closing (if available)

**Comment by vijaywm** [comment]
I have done some work in pushing Invoices into Tally. How are you planning to do this? Do you have any design for this. I may be able contribute.

**Comment by karthikeyan5** [comment]
I too have done some work in converting tally XML to ERPNext Data Import Format... and it happens to be in Python... hoping I can pitch in here... 

The things I have imported from tally:

- Customers details
- Chart of Accounts
- Sales Vouchers
- Supplier details
- Payment Receipt
- Closing Entries for all parties and accounts


Also, is the plan to have two-way sync or just tally to ERPNext?
Or is it planned to be just one time migration?

**Comment by Muzzy73** [comment]
Hi,  I fail to understand that while ERPNext has complete in-depth account module why spend time in creating Tally connector. I have moved client from Tally to ERPNext and over time shut down Tally completely.

**Comment by parsimonyERP** [comment]
I can't speak to Tally, but we have supported the development of a QuickBooks Online connector because we:
a) have existing companies that want to bring their financial history with them as you have indicated.  We call this "one-time" or,

b) want to utilize some portions of ERPNext but still want to originate some financial transactions in QBO and then transmit them to ERPNext on a regular basis.  We call this "one-way".

There is also a third use case ("two-way") where their accounting team or advisor is reluctant to move away from the comfort of QBO and doesn't want to learn a new system, but the rest of the organization DOES want the benefits of ERPNext.  Note: the QBO connector will NOT support "two-way" as far as I know, and we will not support the building of it because we want to strongly encourage our customers to step up the benefits of ERPNext.

I hope that helps.

**Comment by Muzzy73** [comment]
Hi. Fortunately for us we do not have to worry about taxation as there is only VAT in place of residency (Arabian Gulf).  Overall yes Tally has more in the accounting side then ERPNext as of now. But ERPNext as whole package is much more to offer.  The ERPNext standalone accounting software is work in progress. This I feel can be compared to Tally. Give it a try. I works on any OS, Windows is a breeze. After your test drive you can raise issues that you encountered for the team to fix. And also list of features that should be there for it tp be far ahead of Tally. 

Here's the link. https://github.com/frappe/accounting

**Comment by test2a** [comment]
@Muzzy73 ah. that was exactly my point. for a small business owner interested in only "accounting and inventory" tally is a simpler version depending who says that. i have a 9 year working experience on tally so my word i skewed a bit. i have attempted as i said to move my clients from tally over to erpnext but it just is not letting me. there are numerous issues open here on github but they seem to have been put on backburner instead the work is being done on emailing and agriculture and stuff. Look, i am not blaming the team. its not a paid product and all are volunteers. my point is unless erpnext reaches to the level of tally in terms of at least accounting as for me in particular and lots of clients out there, tally would still be preferred

**Comment by Ravn10** [comment]
We are ready to sponsor this add-on

**Comment by test2a** [comment]
has anybody started talking to @Ravn10 about this addon?

**Comment by Ravn10** [comment]
no one yet 
this is my mail id :- anikets@criscoconsulting.in
phone no: 9833471636

**Comment by netchampfaris** [comment]
https://github.com/frappe/erpnext/pull/17405
