### ISSUE TITLE
Auto-email for the General Ledger report to Customers

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#15211]
In the Auto-email report, there is an open to apply filter. This works but requires create Auto-email report for each Customer. Also, there is no clear option to apply filter on date which will ensure all outstanding Sales Invoices are available.

**Comment by turner-james** [comment]
We would like to suggest that not ONLY the auto-email report is developed for better functionality. We strongly suggest that an "email" function be added to the General Ledger Report. So, along with the ability to print / pdf the report (Statement of Account print format), we can also choose to email the report, as a pdf attachment, with the primary customer contact as the default email address. This functionality is already available for documents. We want the functionality to be extended to reports - or specifically the General Ledger report.

**Comment by turner-james** [comment]
We would be willing to sponsor this development or offer a bounty.

**Comment by turner-james** [comment]
Hello. I understand that this issue was started with the subject "Auto-email for the General Ledger report". However, I suggested that much of our frustration can be solved by simply adding an "Email" function to the General Ledger report MENU - which will enable us to email customers directly from that report. At the moment, every time we want to send a customer a Statement of Account, we have to PDF the report first, then attach it to an email. This is very time-consuming, especially when we have many customers who require a statement at the end of each month.

**Please could you add an "EMAIL" function to the General Ledger report menu. When an email box is opened, it must automatically choose the primary contact email for the customer, and must default to attaching the report in the standard (Statement of Account) print format.**

_This is becoming very urgent for us to get this simple feature. Our debtor accounts department is spending days each month trying to email separate statement of accounts to each customer - and really needs resolution._

![screenshot](https://user-images.githubusercontent.com/17749712/50907068-26e3ea00-142f-11e9-9c79-7f772e247aa6.png)

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
