### ISSUE TITLE
India GST Improvisations

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#15276]
- [x] Create GST tax account for each tax slab. 5%, 12%, 18% and 18%. For now, it is created only for 18%

- [x] In the Sales tax and purchase tax master, update CGST, SGST and IGST account for each tax slab.

- [ ] Check if itemised tax can be fetched on selection of HSN/SAC code in the item master.

- [x] In the Print Settings, disable "Print taxes with zero amount". May be we can remove the tax rows for which no amount is calculated.

- [x] In the invoices, itemised taxes table, ensure that only columns with some value is made visible in the print format. Or if we remove the tax rows if zero amount, that shall resolve this issue.

**Comment by test2a** [comment]
- there is still no way at least not that i know of, to make inward freight entry. even if its a b2B one, you still have to do a reverse charge on that unless the transporter has charged you tax already. 

- item master currently does NOT have a way to set a "tax history" wherein the govt may decide from 01,11,2018  to change the tax rate, currently if we change the tax rate and we get a pre change invoice, we would have to change the rate back to old, make the entry and then change it back to new one. a " change by" date would solve this issue.

- there is a kerala govt sponsored project called "gnu khata" that aims to be an open accounting package. maybe the team can look it up and see how they do things around there. they already have a lot of functionality built into their system.

- i have tried and failed to bulk import entries because it seems there is a lot of options built into the tool and there isnt a cohesive way to import new entries. for example, see how GSTR-1 is built, how you can have one entry with multiple tax rates. i tried to make an entry and then download the template with that entry but i was unable to import any more entries.  can you look into that? all you have to do is assume the gstr-1 report that we export from the system could be re imported into the system as fresh entries. 

- new return formats have been introduced and the govt is expected to roll them out on 1 january next year. has anyone looked them up?

- gst has rules regarding purchases and payments and one of them is if we do not pay our suppliers within 180 of the invoice date, we have to reverse the input and that input is allowed only when we pay the supplier. agreed its all self assessed and all but right now we have no way of knowing if there is any entry that needs to be reversed. maybe a report that shows overdue entries?

- reports beyond the gstr-1,2,3,3b

**Comment by snvora** [comment]
Hi,

I don't see core reason/value addition for creating tax accounts for each tax rate. Nither its required by law.

As far as I know, even tally has one tax account, and tax rates are fetched from item master.

**Comment by test2a** [comment]
@snvora right. but currently how erpnext is built, it goes through that and fetching tax rate from ittem master has its own issues here because as per the documentation, you have to select 0 tax account and system does correctly calculate tax from item but it shows it under 0 tax rate in print which is wrong. i have mentioned that multiple times but that doesnt seem to be prioritized as of now. plus, it does not have item tax history

**Comment by test2a** [comment]
any updates on this front?

**Comment by karannshah** [comment]
@umairsy is this discussion focussed on how do I add multiple tax slabs to a single item. Nobody wants to create 4 transportation charges like "Transport 12%" "Transport 18%" and so on - they want a single Transport Charge with selectable tax slab at line item level in invoice.

**Comment by test2a** [comment]
@karannshah a bit late to reply but this is one of the things i am having issues with. Even quickbooks online india is having this problem. The logic should be, tax item aka 18% GST should be say added to item tax and then, depending on the place of supply and address of customer, either IGST or CGST/SGST should be auto selected. Same for as you said transportation charge and other charges that may be incurred. Asking this selection at data entry time is bound to cause issues when an incorrect tax head is selected. Second of all, slab based taxation is non existent in the current erpnext implementation. I have already written multiple times about the practical issues with GST implementation of erpnext on github and also discuss forum but the devs are kinda taking it slowly. Doing a fine job nonetheless

**Comment by karannshah** [comment]
@test2a can we connect sometime? We are making significant changes to bring in handling of Non GST, exempted, nil rated...and also are making changes in GST reports to make them practically usable. I believe we can benefit from your inputs and, hopefully we might be solving some issues you are facing as well. I can be reached on karan@shipmnts.com. Thanks.

**Comment by test2a** [comment]
@karannshah sure. i'll drop you an email  right away. I would love to help

**Comment by test2a** [comment]
as much terrible as it sounds, there are three new gst returns applicable from april, normal, sahaj and sugam....... someone probably should start working on that
