### ISSUE TITLE
Add Timesheet to Track Labour Cost in Job Card

### ISSUE THREAD

**Issue by andiyan1** [frappe/erpnext#15805]
Hi

By adding Timesheet creation in Job Card, we are able to track labour costs against each Job order incurred in the workstation's operations. The Timesheet will enable us to:

- Able to define any labour activity and define/relate incurred labour costs into Operations.
- Assign User/Employee responsible for each timesheet and or Activity
- Add an option to expense or bill each activity created in manufacturing projects. 
- Able to create salary slip for any incurred labour costs (track labour daily costs with accounting0
- Able to create Invoice for any labour costs ( if subcontracting activity are done on behalf of customer)

<img width="988" alt="screen shot 2018-10-25 at 09 54 03" src="https://user-images.githubusercontent.com/7466361/47476038-00ed7700-d83c-11e8-8937-a76d69a975e5.png">

**Comment by mallesree** [comment]
Feature will be very helpful. Linking the operations with the relevant work order will help in tracking the labor cost.

**Comment by Ponyooooo** [comment]
@andiyan1 and @mallesree do you know how can the manufacturing module or the job card can automatically create a timesheet? I am trying to find out how can the labor cost be integrated on the payroll module. Only way is trhough  the timesheet however I dont know where can I automatically create or link the job card on the timesheet. Do you have any idea if this issue was already solved?

**Comment by mallesree** [comment]
@Ponyooooo , I like the feature and appreciate its utility. However I am not sure how to get there. May be some one with little coding knowledge in ERPNEXT should be able to guide you.
