### ISSUE TITLE
Auto Email Report - option to select a Print Format

### ISSUE THREAD

**Issue by crescent28** [frappe/erpnext#16056]
Account Receivable report has multiple print formats, but Auto-Email Report doesn't give option to just specific print format. Please add this selection in the Auto-Email Report

**Comment by Zlash65** [comment]
Can you elaborate on "Account Receivable report has multiple print formats..." ??
As far as I know there is only 1 print format for Account Receivable too right ?

**Comment by RAurelian** [comment]
Hello,

Thank you for reaching out!

I`m currently out of the office with limited access to email, so in very urgent matters please call or text me. Otherwise, for HW Test / Age Rating projects, please contact pccolceriu@quanticlab.com, tfpacurariu@quanticlab.com and dcpacurariu@quanticlab.com. For inquiries regarding other type of projects, please contact sales@quanticlab.com.

In case of issues with QL IT services, please submit a ticket or contact lszabo@quanticlab.com.

Best regards,
Ionel Aurelian Rău
QUANTIC LAB – Quality Assurance
