### ISSUE TITLE
If we uncheck Quick Entry checkbox on the ToDo List the Default value on the description does not appear in the screen.

### ISSUE THREAD

**Issue by rushikesherp** [frappe/erpnext#16086]
Steps to Reproduce

1. Customise the Todo List form to add a default value to the "Description" Text box field and turn on Quick entry if not turned on by default.
2. When you click on "New ToDo" the default value appears in the "Description" Box.
3. Now customise the form again to uncheck Quick Entry for the Todo Form.
4. Now click on the new button.
5. The default value does not appear in the New Todo Form's Description field

Default Value added to the Description field.

![image](https://user-images.githubusercontent.com/40016931/48997695-ce0a0c00-f176-11e8-913b-d80b1e3fc375.png)

Value appears on Quick Entry

![image](https://user-images.githubusercontent.com/40016931/48997730-eaa64400-f176-11e8-9721-60f3455dabfb.png)

Value Does not appear if you uncheck Quick Entry.

![image](https://user-images.githubusercontent.com/40016931/48997803-26410e00-f177-11e8-9640-6d0fc4deae09.png)

Tested on 
ERPNext: v11.0.3-beta.24 () (staging)
Frappe Framework: v11.0.3-beta.30 () (staging)

**Comment by surajshetty3416** [comment]
@rushikesherp This does not seem to be a bug.

Because:
We do not allow "title field" to have default value (to avoid duplicate documents) and since for ToDo doctype description is a title field, no default value for description gets applied.

Quick entry does not check for this condition and hence default value is set for description while doing quick entry.

I you want to set default value for description anyway, you can change the tiltle field to subject if that works for you.
