### ISSUE TITLE
Job Card - Actual start date must be less than actual end date

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#16151]
receiving the error "Actual start date must be less than actual end date" when attempting to start a job card.  End date field is blank.

ERPNext: v10.1.73 (upstream/develop)
Frappe Framework: v12.x.x-develop () (develop)

![image](https://user-images.githubusercontent.com/13136405/49399498-6c661680-f70f-11e8-980e-a928b1bede5d.png)

**Comment by tristanvigar** [comment]
Has there been any movement on this issue? It is also present in **ERPNext: v11.1.3** (master). 

The only way I've seen to resolve this issue is to set an Actual End Date but this negates the purpose of having a built in timer and removes the option to 'Start Job'

The other potential workaround I've seen is to save the job card with an Actual Start and End date and simply remove the End date and save the Job Card again. This introduces the timer again and presents a 'Complete Job' button but it's a hacky solution.

**Comment by happy-cat-coder** [comment]
I have the same problem on 

**ERPNext**: v12.10.1 (version-12)
**Frappe Framework**: v12.8.4 (version-12)

**Comment by sharmanakul** [comment]
@cgpurbaugh @ousvat @tristanvigar does this still persist? I checked it on v13.14 and did not face it. Can you please check?
