### ISSUE TITLE
how to install the ERPNext app 

### ISSUE THREAD

**Issue by rkhyd** [frappe/erpnext#16347]
How to get the ERPNext app installed in the frappe framework?
![image](https://user-images.githubusercontent.com/15903310/50735008-ca35c480-11cd-11e9-9462-5252b6b31032.png)
Is it just an app name or is it a module?

**Comment by aakvatech** [comment]
bench --site <<name of site>> install-app erpnext06.01.2019, 13:42, "Ravi Kumar Ch" <notifications@github.com>:How to get the ERPNext app installed in the frappe framework?

Is it just an app name or is it a module?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

Best Regards,Aakvatech

**Comment by adityaduggal** [comment]
This is not an issue and hence closed should be posted in https://discuss.erpnext.com
