### ISSUE TITLE
India Tax Report Enhancements

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#16380]
- [x] Add Supplier Name column in the TDS Computation Summary and TDS Payable report.
- [x] Add filter of Finance Book in the Trial Balance report
- [x] Report: Supplier-wise bank account details (ref. Pawan)
- [x] "On Account" amount as a separate column in the report in the Account Receivable Summary, Payable Summary reports
- [x] Payment Reconciliation - performance optimization

- [x] Purchase invoice without GST code of supplier, will it come in GSTR2? 
      Use GST Settings

**Comment by umairsy** [comment]
@PawanMeh could you please share specs for the supplier-wise Bank account report?

@nabinhait does all the Purchase Invoices reflect in the GSTR2 report, or are there filter based on which we only set of invoices are fetched? If yes, what's the criteria?

**Comment by test2a** [comment]
@umairsy GSTR 2 shows ALL purchases made during the month and that includes purchases from unregistered person both which attract reverse charge (purchase tax) and on whom there is no need to do reverse charge.
any purchase without GSTIN of the supplier automatically should be classified as unregistered purchase and that would then ask for reverse charge application or not. That said, all purchases, registered or not should have option to add reverse charge which if i remember correctly  is already present in the software.

This is because in order to compute the "purchases" that comes in our annual financials, we need to show the same monthly and GSTR 2 return is necessary for that. Otherwise, we wont be able to claim any more purchases than what exists in the returns. Hit me up if you need more assistance

**Comment by PawanMeh** [comment]
@umairsy, For Supplier wise bank account report, we can plan to add the bank account related fields to Payment Entry doc type. 

Fields can default from Bank Account master if there is only one Supplier bank account linked. Fields to be defaulted 

- [ ] Account
- [ ] Bank
- [ ] Bank Account No
- [ ] Branch Code
- [ ] Swift Number
- [ ] IBAN

If more than one Bank Account exists, then user can select the fields as needed. They should be filtered based on Supplier linked to Bank Account.

Once these fields are available users can use Report Builder to pull in the details appropriately for Payments.

**Comment by dj12djdjs** [comment]
If this is still relevant please re-open at
https://github.com/resilient-tech/india-compliance
