### ISSUE TITLE
Import Data from CSV is very slow - how can I improve this?

### ISSUE THREAD

**Issue by jazzyjackson** [frappe/erpnext#16396]
Hello, 

I am running ERPNext on a fresh Ubuntu 18.04 install, installed everything via the easy installer script.

I am importing CSVs from my old (version 5) ERPnext system -- it has taken nearly 20 minutes to import 150 items to the master item list before giving me the errors that some key was not found (have not imported the default warehouse, default income account, etc)

I have experience using python to interact with SQL, reading 150 lines from a csv and committing them to a database should take no time at all -- I am a developer, can you please tell me where to look in your source code for where this parse csv + commit to database is taking place? Maybe I can improve the system.

The PC is a quadcore i5 with 8gb RAM and a fast SSD, it should not be an issue.

**Comment by Don-Leopardo** [comment]
I think that the CSV import is from Frappe and not from the ERP. Maybe you should put this issue in the Frappe repository.

**Comment by crckmc** [comment]
I'm currently trying to import directly into the database via the cli like it is described here:
https://discuss.erpnext.com/t/bulk-update-tool/14171/9
maybe this helps you

**Comment by chdecultot** [comment]
Hi @jazzyjackson,

It may have to be related to your installation I'm afraid. I recently imported files with several hundred item lines on several instances running ERPNext v11 (latest staging) and it took only a few seconds. I can confirm that the import tool works fine in v11.

Can you please try to check if there is any error log related to your import in the database, nginx and erpnext logs ?
Maybe try also via the CLI to see if the problem comes from the database installation.

**Comment by joolsr** [comment]
I can concur with @chdecultot I imported about 2000 items on V10 and although a little slow it took only about two minutes. 20 mins for 150 items is not correct at all.

**Comment by jazzyjackson** [comment]
Thanks for all the feedback everyone - I'll start googling "mariadb ubuntu slow" instead of blaming frappe development :) Sorry for my short tone, I was frustrated after a long day of minor inconveniences.
