### ISSUE TITLE
Credit Note adjustment, without any Payment 

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#16697]
For now, Payment Entry doesn't handle the Sales Invoice - Credit Note reconciliation, where payment is not involved at all. it has to be done via Journal Entry. The reconciliation of Invoice and Credit Note without any payment involved should be simplified.

Here is the example of reconciliation via Journal Entry:

Journal Entry Type = Journal Entry

Cr. Debtor .... XYZ Infotech... 200 ... Ref Doc: Sales Invoice ... Ref Name: SINV-01234 (outstanding invoice)
Dr. Debtor .... XYZ Infotech... 200 ... Ref Doc: Sales Invoice ... Ref Name: SINV-09876 (credit note invoice)

**Comment by federicocalvo** [comment]
Hi  umair. I use stand alone credit notes in this way to cancel them against an invoice (because it is credit that the customer has).

In theory I thought it was correct, because the document disappears in accounts receivable, but then I saw another issue where it is not showing any credit note stand alone.

Wouldn't it be feasible to raise the fact that credit notes can be used in the invoice reconciliation tool or as advance payments?
There are several issues dealing with the subject, and it is something really useful for retailers for example.

Anything you need with this topic at your disposal.

**Comment by federicocalvo** [comment]
Hi @umairsy, any news for this?

**Comment by SaiFi0102** [comment]
@federicocalvo I think it's a good idea to allow credit notes in Payment Reconciliation Tool. I was thinking of generalizing the code to allow all vouchers with a (negative) balance to be reconcilable.

**Comment by anasanzari** [comment]
+1

**Comment by Anuja-pawar** [comment]
works
