### ISSUE TITLE
Serious problems with Issues handling for Hosted Plans

### ISSUE THREAD

**Issue by cosimot** [frappe/erpnext#16874]
Per our experience the way Issues are managed for Hosted Plan's Customers should change.

**Actual scenario:**
- We notify a BUG
- Sometimes the BUG is identified by Support team, sometimes it takes some days of email exchange.
- Bug is fixed within a couple of days and we receive the message "we identified and fixed the bug, the fix will be released with the new release". 
- We are not informed when the fix is updated into our account.
So basically we have a bug which does not allow us to work or gives us serious problems and we have to wait long time until it is fixed.
This happens with a daily frequency as ERPnext in the last 6 months is very very unstable.
Sometimes bugs are not identified and you have to live with that.
One concrete example is that after a software update all of the reports were canceled. We had to rebuild all of them as customer service did not identify the bug and did not help us to recover reports.

**Desired scenario:**
if there is a bug and we are stuck (meaning we can't use modules of ERPnext) the BUG must be fixed shortly in order to let us work again.

**Comment by rmehta** [comment]
@cosimot Thanks for your feedback.

Yes I accept we have a large backlog of bug fixing that takes time to fix. What are we doing to fix it? Based on our observations, bugs are generally around new releases and customizations, so we have decided to slow down pushing new updates.

On the other hand we also genuinely want to support small businesses with great ERP software hence we are also short of resources. Not to mention overflowing community requests on various platforms. This is clearly our own doing, and we are trying our best to maintain our service levels while we keep making the product better.

ERPNext is also 100% Free and Open Source, so you are free to move to your own hosting whenever you want to make that call. Thank you for being a customer and your patience. We accept your feedback and will use it in our further decision making.

Closing this issue here, since it is not relevant to the product.
