### ISSUE TITLE
Bug: Paid amount does not update in Sales Invoice

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#17173]
![image](https://user-images.githubusercontent.com/13136405/55738336-ec212c00-59f4-11e9-9f8b-eb719d8f1080.png)

**Comment by crescent28** [comment]
@cgpurbaugh could you elaborate the issue with a use case so that we can replicate.

**Comment by kennethsequeira** [comment]
@cgpurbaugh version?

Checked a scenario on ERPNext: v11.1.28, Frappe: v11.1.35 it worked well:

![image](https://user-images.githubusercontent.com/33246109/59441295-fa852d00-8e15-11e9-9725-85a6d83b6298.png)

![image](https://user-images.githubusercontent.com/33246109/59441417-2ef8e900-8e16-11e9-9835-fc25f14da86a.png)


1. Created sales invoice
2. Created payment entry
3. Went back to the sales invoice and reloaded

Can you check if the problem is still persisting?

**Comment by cgpurbaugh** [comment]
I think this was fixed at some point, I can't replicate.  Thanks!
