### ISSUE TITLE
Fetching exact timestamp on DocTypes

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#17829]
Instead of "Kenneth created this 10 days ago", if we could get the exact timestamp, there would be more crisp and accurate data points available for time-wise document tracking. 

![image](https://user-images.githubusercontent.com/40264279/58758544-58726480-853a-11e9-9236-70a5abd9aebc.png)

**Comment by barredterra** [comment]
The "10 days ago" is a feature that many companies need. Exact timestamp would be easy as that's how the data is stored.

So we need a checkbox in System Settings (or user settings) "Display Relative Dates". When the checkbox is checked, display "10 days ago". When it's not checked, display "on 02/28/2019, 02:15 PM".

**Comment by ankush** [comment]
Not required. 

ProTip: you can hover over them and it will show the exact timestamp.

**Comment by barredterra** [comment]
@ankush don't you think this is still a valid feature request? The fact that I can hover doesn't help me a lot if I don't like relative dates.

**Comment by ankush** [comment]
If people cared enough about this it would've happened in 3 years, it's not such a big change to implement. (Somewhere in boot add the flag from system config and swap pretty date with timestamp)


This is also only required occassionally (?) and if you need it on many docs you're better off using report builder to fetch these timestamps. 

If we add this the next obvious request would be to customize it on per user basis because not everyone wants will be happy with system config too. 😄
