### ISSUE TITLE
Error when importing Chart of Accounts

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#18214]
Error when importing Chart of Accounts. The error message doesn't indicate what to correct. Values in the template (attached) seems to be fine.

<img width="1370" alt="Screenshot 2019-07-10 at 11 51 41 AM" src="https://user-images.githubusercontent.com/910238/60945730-06c3b380-a30a-11e9-8364-8b545a57ceff.png">

[CoA Imported Testing.xlsx](https://github.com/frappe/erpnext/files/3375998/CoA.Imported.Testing.xlsx)

**Comment by umairsy** [comment]
Another try in the ERPNext account hosted on erpnext.xyz. Following is the error message which says:

<img width="1287" alt="Screenshot 2019-07-10 at 2 45 23 PM" src="https://user-images.githubusercontent.com/910238/60957023-8ad56580-a321-11e9-8392-1dca27764465.png">

The file I am uploading (attached) has Accounts of each of this type.

**Comment by deepeshgarg007** [comment]
@umairsy Is this the same template you uploaded in the earlier message?

Currently chart of accounts only supports csv file. In the previous msg xlsx file was uploaded thats why previous error was occuring.

These are some issue I could identify from looking at the template

s is small in "sold" for "Cost Of Goods Sold"
![image](https://user-images.githubusercontent.com/42651287/60958118-772afe80-a323-11e9-9ae4-a72f3893426e.png)

There are only group accounts for Payable and Depreciation 
![image](https://user-images.githubusercontent.com/42651287/60958547-2b2c8980-a324-11e9-852c-9fd7e2c11126.png)

I'll try to provide better error messages for these issues. Please share if you are trying to upload any other template or file that you were unable to import so that I can replicate the issues faster.

**Comment by umairsy** [comment]
Importing another template where said corrections where already made. Cannot attach file here as it doesn't allow CSVs. Will PM the attachment.
