### ISSUE TITLE
Bank Account for Party

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#18227]
If am creating Bank Account for Party, why should we have "GL Account" as a mandatory field there? We won't create Supplier's Bank Account in our books of Account. Right?

<img width="1208" alt="Screenshot 2019-07-10 at 3 44 29 PM" src="https://user-images.githubusercontent.com/910238/60961457-d5f37680-a329-11e9-96eb-e76cddcb9e83.png">

**Comment by frehu01** [comment]
Are there any news on this bug?
This makes it impossible to create a bank account for any party other than the own company.

The following seem to be related to this bug:
- The dropdown field "Default Bank Account" in supplier doctype filters for "Is company account = 1" which also doesn't make sense.
- If you set the default bank account in supplier and create a payment entry it fills that into "Company Bank Account" instead of "Party Bank Account".
