### ISSUE TITLE
Payment Order - When Add Row, field doesn't show up

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#18229]
<img width="1251" alt="Screenshot 2019-07-10 at 3 52 37 PM" src="https://user-images.githubusercontent.com/910238/60962016-f839c400-a32a-11e9-9d2f-e73665631029.png">

**Comment by Mangesh-Khairnar** [comment]
A payment order can either be from payment entry or payment request. Each child table row represents a child table "references" row from either payment entry or payment reference. Since there is no direct linking available for the same. On adding information manually the user can be allowed to link a particular payment order. However, we have to automatically import multiple rows from that given payment entry. This will be really confusing for the user.

**Comment by liyakatalilal** [comment]
@Mangesh-Khairnar, What I understand about the 'Payment Order' use case is that it is a single DocType created for facilitating combined payment from bank, so what one wants is to bring all the Payable or Payment entries at single place and keep the reference.

Referring to your comment, to make user less confused, add 'Message' if there is a restriction on how it is to be used and stating that user is allowed only to import 'Payable or Payment entries' and it can not be added - Also, if the 'Add Row' button gets disabled, it would be even better.
