### ISSUE TITLE
Workflow Bulk Approval [UX]

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18504]
In v12, for the case of bulk approvals, all workflow states are available for approval/rejection in ListView, which is just sad UX and confusing for users, as below:

![image](https://user-images.githubusercontent.com/40264279/61991133-6d1a3700-b069-11e9-8890-5f0a50ce788e.png)

The workflow has 3 states, which are shown for approval as well as "Submit"/ "Cancel"....this is causing confusion for users.

![image](https://user-images.githubusercontent.com/40264279/61991140-7f947080-b069-11e9-8b3d-d264dd2480be.png)

In the case of v11, it **just** offered, "Submit" or "Cancel":

![image](https://user-images.githubusercontent.com/40264279/61991081-f41adf80-b068-11e9-9948-03d4633d9843.png)

**Maybe, we can**
1) just display submit/cancel which performs the next workflow action in case of several other actions. (Revert to v11 working)
2) Only display _next_ consecutive workflow state, not all states like it is doing now.

PLEASE HELP!

**Comment by surajshetty3416** [comment]
@jaichavan This issue has been fixed here https://github.com/frappe/frappe/pull/8323. You will not get Submit / Cancel options in the list view if workflow has been enabled for the doctype.

And about the Workflow Action buttons... we are only showing the next possible actions based on the checked document's status. And since you have selected "pending" documents, all actions i.e "Approve", "Review" and "Reject" are valid (according to your transition rules). Try selecting documents with another status to verify this.

**Comment by rjbharath1003** [comment]
client side script before_workflow_action not working in list view.
