### ISSUE TITLE
Wrong Amount in item table if tax not included

### ISSUE THREAD

**Issue by joni1993** [frappe/erpnext#19246]
I setup my taxes as described in [here](https://discuss.erpnext.com/t/wrong-item-tax-calculation-on-sales-invoice/28039/3) and [here](https://discuss.erpnext.com/t/wrong-or-difficult-tax-selection/9241/4).
The overall taxes for the items are calculated correctly as seen in the tax calculation table but in the item table the amount is showing the same as the net amount. Clearly if taxes are applied (as seen in the tax calc table) the amount column should show the net_amount+taxes.

**Invoice:**
![Bildschirmfoto von 2019-10-04 11-33-00](https://user-images.githubusercontent.com/29347/66197593-ffa70a00-e69a-11e9-9a3b-8bdb7215334b.png)
**Invoice Tax:**
![Bildschirmfoto von 2019-10-04 11-38-40](https://user-images.githubusercontent.com/29347/66197719-4bf24a00-e69b-11e9-8c9a-f12b74e06bee.png)
**Item Tax:**
![Bildschirmfoto von 2019-10-04 11-39-09](https://user-images.githubusercontent.com/29347/66197741-544a8500-e69b-11e9-97e8-95603f0cd207.png)
**Applied Item Tax Template**
![Bildschirmfoto von 2019-10-04 11-39-16](https://user-images.githubusercontent.com/29347/66197757-5ad8fc80-e69b-11e9-8d80-e2de13f53d01.png)

Versions:
ERPNext: v12.1.6 (version-12)
Frappe Framework: v12.0.16 (version-12)

**Comment by clarkejj** [comment]
See https://discuss.erpnext.com/t/item-tax-only-visible-if-included-in-base-rate/53069

**Comment by deepeshgarg007** [comment]
If you want to show tax included amount in item table then it has to be configured in ERPNext.
For the items enter the item rates inclusive of taxes and check "Is this Tax included in Basic Rate?" in the taxes table. Closing this issue since there is nothing actionable for now.

<img width="1193" alt="Screenshot 2020-02-08 at 9 16 15 PM" src="https://user-images.githubusercontent.com/42651287/74088077-59d83180-4ab8-11ea-91eb-7f75426a8713.png">
