### ISSUE TITLE
Depends on Payment Days is not working in formula calculation

### ISSUE THREAD

**Issue by cospin** [frappe/erpnext#19413]
_Discuss link: https://discuss.erpnext.com/t/depends-on-payment-days-is-not-working-in-formula-calculation/54270_

## Description of the issue
When using a variable whose value is affected by "Depends on Payment Days" in the formula of any other component, it takes the total value and not the value with the "Depends on Payment Days".

## Context information

**Output of `bench version`**
```
erpnext 12.1.7
frappe 12.0.17
```

## Steps to reproduce the issue

1. Create a new _Salary Structure_
2. Add a new _Salary Component_ for example Basic Salary (`BS`) with a formula value as: `base`, and set _Depends on Payment Days (DPD)_ as **enabled**.
3. Add a new _Salary Component_ for example Basic Salary Two (`BS2`) with a formula value as: `BS`, and with _Depends on Payment Days (DPD)_ **disabled**.
4. Test the _Salary Structure_ with an employee that has less _Payment Days_ than _Working Days_

#### Example configuration

Working Days: 30
Payment Days: 15
`base`: 1.000

Basic Salary (`BS`) = `base`
Basic Salary Two (`BS2`) = `BS`

### Observed result
`BS` = 500 _(Correct as it's affected by DPD)_
`BS2` = 1.000 _(Incorrect as `BS` has a value of 500, it should be also 500)_

### Expected result
`BS` = 500
`BS2` = 500

**My scenario is as follows:**

I need to calculate other components, taking into account the `BS` (affected by _DPD_), but adding another variable that should not be affected by _DPD_, example:

`BS` = `base` = 1.000 = 500 (with _DPD_)
`X` = 5.000 _(Fixed value that should not be affected by DPD)_
`BS2`= `BS` + `X` = 5.500 (But right know it displays 6.000 incorrectly)

**Comment by clarkejj** [comment]
Thanks for reporting this issue - two requests

Please also post this to discuss.erpnext.com,. That way all the community is informed and benefits, and can expedite responses and possible fixes, thanks

Add a link to this post here, and on discuss to link to here

**Comment by cospin** [comment]
Thanks! Done!

**Comment by clarkejj** [comment]
Thanks https://discuss.erpnext.com/t/depends-on-payment-days-is-not-working-in-formula-calculation/54270

**Comment by onlinebizsoft** [comment]
I have a few questions too
1. What counted in "Payment days" ?
2. Does ERPNext count days since the Join date if an employee join in middle of month? (right now it is not when I set base salary component as Depends on Payment days)
3. Will date marked as Absent (in Attendance tool) be excluded from "Payment days" or still be included ?

**Comment by onlinebizsoft** [comment]
@rajibbasu11 @nabinhait this is not working on latest code
https://github.com/frappe/erpnext/issues/17757
https://github.com/frappe/erpnext/issues/16134

**Comment by onlinebizsoft** [comment]
ERPNext is great open source but look like recently the workload seems to be out of control of the team and many important bugs stay in the backlog even no team member communicate or confirm.

**Comment by clarkejj** [comment]
"the workload seems to be out of control of the team" 

Assuming you refer to the Frappe folks they have much to juggle...see this 'burning ourselves by supporting the community' read https://medium.com/@rushabh_mehta/a-week-in-germany-988128a69668

**Comment by onlinebizsoft** [comment]
@clarkejj yes I really understand and of course, every one is thankful to the ERPNext team. But it is up to them to decide their strategy. So they can 
- Develop it as a closed software and sell license only
- Continue to maintain it as an open source and implement many major updates (in this case they need to find funding source or somehow to grow their team faster, refine the process because right now I can see many important bugs are not picked up)
- Continue to maintain it as an open source but they should slow down major update and keep the software bugs fixed faster, more stable.

**Comment by clarkejj** [comment]
Certainly Frappe's paying customers face the same bugs. And of course 'serious' users are free and encouraged to develop their own strategy - to scratch their own itch. Nothing prevents them from doing so.  Bug fix contributions are always welcome.

Quality is a matter of testing, and of course automated test suites are the way to go. But users must  support this.

**Comment by onlinebizsoft** [comment]
You are going on right way now :)
https://discuss.erpnext.com/t/erpnext-release-cycle/56790

**Comment by ruchamahabal** [comment]
Fixed in https://github.com/frappe/erpnext/pull/27349
