### ISSUE TITLE
Disable Energy Point Emails

### ISSUE THREAD

**Issue by raymondliew1992** [frappe/erpnext#19474]
**Energy Point is an excellent feature but the notification email can be very annoying**

This issue was raised a  month ago: https://discuss.erpnext.com/t/how-to-disable-energy-point-emails/53393/4

We badly need a way to disable this notification.

**Comment by muchai** [comment]
See this thread: https://discuss.erpnext.com/t/integrated-notifications-center/54220/4

**Comment by lasalesi** [comment]
+1.

Propose to have an option 
[ ] disable email digest
on the Energy Point Settings.

**Comment by aakvatech** [comment]
Does it go to all users? Customers and Suppliers user accounts? That's a big issue if it's the case.

From my understanding, it only goes to System users and that too can be disabled by the user on their own.

This issue should be closed.

**Comment by Tropicalrambler** [comment]
It goes to all users, I just had a customer ask me today, thinking that it had come from their server. It turned out to be mine. The problem was not the digest itself, but a new name that showed up in the summary, which seemed to our customer like an apparent breach of security on their server, which doesn't even have email configured anyway.  This is crucial to have the ability to turn on and off.

**Comment by aakvatech** [comment]
Why is this closed?

**Comment by aakvatech** [comment]
Problem is most probably due to the line
https://github.com/frappe/frappe/blob/b51f13c2914b08e82f4d9bc77f165eb5696474f7/frappe/social/doctype/energy_point_log/energy_point_log.py#L309

It is looking at frappe.session.user and not identifying the user who doesn't want to receive the logs, but just session user.
https://github.com/frappe/frappe/blob/b51f13c2914b08e82f4d9bc77f165eb5696474f7/frappe/social/doctype/energy_point_log/energy_point_log.py#L325

**Comment by aakvatech** [comment]
https://github.com/frappe/frappe/issues/13114
