### ISSUE TITLE
Shopify Integration

### ISSUE THREAD

**Issue by raymondliew1992** [frappe/erpnext#19543]
**ERPNext App No Longer Exists in Shopify App Store**
In order to integrate ERPNext with Shopify, ERPNext app is required in the Shopify App Store.

**Comment by EconCode** [comment]
Hi @raymondliew1992,
I had to setup the shopify connector on ERPNEXT v12 recently, maybe I can help you. 
Are you following the latest instructions to set it up? It used to be that you installed an app but now you create a private app and copy your access keys and settings to the shopify connector settings in erpnext. I think [this is the latest tutorial on how to set it up](https://erpnext.com/docs/user/manual/en/erpnext_integration/shopify_integration).

**Comment by clarkejj** [comment]
https://discuss.erpnext.com/t/v12-integration-with-shopify-erpnext-app-is-no-longer-available-in-shopify/54820/2

**Comment by chengdada123** [comment]
422 Client Error: Unprocessable Entity for url: https://4b10*******37065eb003693e******9@******.myshopify.com/admin/api/2019-04/webhooks.json
Traceback
Traceback (most recent call last):
  File "/home/cheng/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/shopify_settings/shopify_settings.py", line 43, in register_webhooks
    d.raise_for_status()
  File "/home/cheng/frappe-bench/env/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://4b10*******37065eb003693e******9@******.myshopify.com/admin/api/2019-04/webhooks.json

**Comment by EconCode** [comment]
Hi @chengdada123!
It's difficult to helo you without more context. I assume you are running ERPNEXT locally in a VM?
When you setup the shopify connector it tries to register webhooks. They need a valid https url to report back to.  Otherwise, they will return Error 422:
[https://help.shopify.com/en/api/reference/events/webhook#create-2019-04](https://help.shopify.com/en/api/reference/events/webhook#create-2019-04)

This is done here: https://github.com/frappe/erpnext/blob/444156184cb70f5e7a4ba32b109c5b16fd82c5fa/erpnext/erpnext_integrations/doctype/shopify_settings/shopify_settings.py#L39

However, if you are running locally or frappe.request.url function fails for any other reason the url endpoint provided will start with "http://localhost:8000". This stems from this function on Line 38/39:
https://github.com/frappe/erpnext/blob/444156184cb70f5e7a4ba32b109c5b16fd82c5fa/erpnext/erpnext_integrations/utils.py#L30 

To fix your problem you would have to expose whatever server/pc you are running ERPNEXT on publicly. Maybe you are running a private VM? Or you haven't setup DNS/Domain correctly? All I can tell you that frappe.request.url is most likely failing. You can test that out in the bench console to verify.

**Comment by chengdada123** [comment]
How do I change it? I now support domain name access. Still giving an error.

**Comment by chengdada123** [comment]
<img width="632" alt="微信截图_20200118221520" src="https://user-images.githubusercontent.com/59160585/72665089-40574300-3a40-11ea-8427-3d2bac049481.png">

**Comment by EconCode** [comment]
@chengdada123 I wouldn't hardcode it like that. It would give you the right url but I doubt that it is reachable as erpnext needs to provide the correct endpoint somehow.  
I think it has to do with correctly setting up the domain name mostly.  
Maybe this thread will be helpful to you: https://discuss.erpnext.com/t/setting-up-a-domain-name/33329/4

Generally speaking I don't know of an easy way to get this connector working WITHOUT having a valid domain registered and setting it up in erpnext. Maybe somebody who has more knowledge on running a setup from start to finish can chime in.

**Comment by rpineda** [comment]
> How do I change it? I now support domain name access. Still giving an error.

Hi, you can try use: ngrok - https://ngrok.com/ - this generarte a valid https for your localhost.
