### ISSUE TITLE
Feature request: Make field values translatable

### ISSUE THREAD

**Issue by chlarsen** [frappe/erpnext#1981]
Dear Crowd,
While ERPNext already sports a good number of translations for the application user interface, there remains an important issue for all those institutions that work in multi-lingual environments, but where not everybody speaks or writes all the languages used across the organisation.
Therefore, it would be terribly useful to have a facility included into each and every page of ERPNext that allows an appropriately authenticated user to translate field values into other preferred languages.
Then, as other users choose their preferred language, any such field entries would appear in the "right" language... terribly useful, if not essential for mission-critical operations in multi-lingual environments.
I know that the feature request list is long, but this may become rather important to those users operating in diverse environments. Thanks a lot!
Chris

**Comment by anandpdoshi** [comment]
Another feedback from a lead: Allow invoices to be sent in customer's language. This will require item names, descriptions and other such values in customer's language.

**Comment by gabtzi** [comment]
+1 for multilingual support in document field values. No current ERP here in Greece provides a good way to solve this issue so it would really be an asset in Marketing ERPNext here.

**Comment by alikhoja** [comment]
+1 for multilingual support. For expanding business it's a must have.

**Comment by rmehta** [comment]
Fixed. In Frappe 6.25, Setup > Custom Translation

**Comment by Idat-Consulting** [comment]
Hello @rmehta ,

I have a nice proposal for a good generic solution of the problem with translatable field-values.
Please study my proposal in the following thread in your discuss.

https://discuss.erpnext.com/t/mutlilingual-article-names/11820

In my opinion handling this in the common Custom Translation is ok, but if the value of e.g. article_name is changed, then the translations would be lost and hard to find. 
My idea would cover this usecase, because the translation of field-values could be in a table with the fields:
- DocType
- FieldName
- Language
- Value

So when changing the default value of the field, all the translation would stay in place.

**Comment by rmehta** [comment]
@Idat-Consulting looks like a good idea. If you implement this, will be happy to accept your contribution.

**Comment by mhbu50** [comment]
+1

**Comment by villiger** [comment]
+1

**Comment by giancarlo64** [comment]
+1
