### ISSUE TITLE
[Healthcare] Calculation of number of free Patient Visits for Appointment with the same Practitioner is faulty

### ISSUE THREAD

**Issue by palashjhabak** [frappe/erpnext#19964]
## Description of the issue
There is a setting in Healthcare Settings which allow any hospital to let patients have a few free consultation after their chargeable consultation. This works fine for one set of visits but the calculation gets wrong for multiple sets of visit. 

Let me explain this with an example. Lets say there are 2 total visits allowed after first visit which will not be charged so in Healthcare Settings "Patient Encounters in valid days" will be set to 3. Now below are 2 scenarios one of which will work fine and one will not. 

Scenario 1: Patients visits for 3 times so in Sales Invoice only 1 Item will come in Get Items from healthcare
Scenario 2: Patient visits for 6 times so in Sales Invoice only 2 chargeable Appointments should come but with current logic, 3 items are charged

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. Set  "Patient Encounters in valid days" to 3 in Healthcare Settings
2. Create 6 Appointments for a Patient with the same practitioner
3. Create a new Sales Invoice and do Get Items from Healthcare Practitioner 

### Observed result
total 3 appointments appear to be charged
### Expected result
only 2 appointments should appear to be charged
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by ruchamahabal** [comment]
A number of issues with Fee Validity have been fixed in https://github.com/frappe/erpnext/pull/20811/ including this one.
1. The fee validity was getting updated twice, once during the appointment creation and once when the sales invoice was getting submitted.
2. The payment related fields shouldn't be mandatory if fee validity has been set up.
3. Fee Validity is now created only for new patients. Earlier it was creating the fee validity again after the earlier one gets completed.
4. It also has a status as Completed or Pending now and user is not allowed to create it since the creation and update process is handled during appointment creation / cancellation.
4. The Fee Validity should not be linked to invoices since appointments within valid free period  should not be invoiced. Hence it now shows up a series of reference appointments which have not been billed due to the fee validity doc:

![fee_validity](https://user-images.githubusercontent.com/24353136/76870869-55115500-6890-11ea-97f8-d218054118eb.png)

**Comment by palashjhabak** [comment]
Wow. Awesome. Would test this as soon as I get time. Thanks a lot. :)
