### ISSUE TITLE
TTFB Very Slow

### ISSUE THREAD

**Issue by mariotruss** [frappe/erpnext#20296]
## Problem
- `desk` is causing huge performance issues
- Will occur once you reload the page or open in a new tab
- Loading time to first byte(TTFB) this sometimes takes 35s (that's 35000ms)
--> 100-500ms would be okay
- Content Download = 2ms
- Request send = 0.29ms
- Queuing = 3.38ms
- Only the creation of the document for desk takes a long time. Everything else is performant
- **Security Issue/GDRP:** `Desk` contains a HMTL will all user data. Every person with a login could easily get all employee information.
- We tried some of the improvements on your blog, but it did not change a lot for us
![image](https://user-images.githubusercontent.com/24277433/72418263-cc384900-377a-11ea-8899-5a8e3fbcab4d.png)

## Potential Source of Error
We found a pattern, why we think this issue might occur:
- Desk is downloading a huge html file containing a json with 10800+ lines of code
- The lines of code increases, the more users and the more DocTypes are in the system
- This document contains all users and their rights, a lot of information about ERP & the DocTypes
- The cache works sometimes, mostly until new entries like a new user or doctype have been created
- We have 180 User, therefore our files are larger, it takes longer to gather all data and therefore it takes longer to download
- We tried decreasing the user size and the performance increased
- This leads to the hypothesis that the current process is not scalable as the loading time increases linear to the increase of user and doctype size

## Expected Result / Ideas
- Loading times is fast and rapid, independent from data size
- Only changes will be downloaded as the rest is saved in cache

**Comment by scmmishra** [comment]
Hi @MarioMeetsWorld 

About your observations
> Desk is downloading a huge html file containing a json with 10800+ lines of code

It's less than 500kb, it's not much of a problem really.

The actual problem is pre-processing when serving desk.

We recently made a few changes for better caching and less number of queries. It's going to be released soon. (PR: https://github.com/frappe/frappe/pull/9079)

It has been in develop branch for about a month, we're releasing it in version 12 as well. For my test instance with 400 system users with all roles set including system manager, the TTFB reduced from 49 seconds to just over 2 seconds. 

It should solve your problem. I'm closing the Issue, update your instance with the next release and it should be fine.

**Comment by mariotruss** [comment]
@scmmishra Okay, we will do that.
Still, what do you think about this?
`Security Issue/GDRP: Desk contains a HMTL will all user data. Every person with a login could easily get all employee information.`
