### ISSUE TITLE
Supplier Quotation ID field in Supplier Quotation

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#20316]
Supplier Quotation DocType does not have a field to enter the Supplier Quotation # or ID with its corresponding date.

I am proposing the following fields be added to core:

Label | Type | Name | Options

- [ ] Supplier Quotation Details | Section Break | supplier_quotation_details | None

- [ ] Supplier Quotation ID | Data | supplier_quotation_id | None

- [ ] None | Column Break | column_break_xx | None

- [ ] Supplier Quotation Date | Date | supplier_quotation_date | None

Despite internal tracking series and number (ID) configured within ERPNext, suppliers have their own supplier quotation numbers or identification serials.  Adding it to the title of the quotation is not practical, as this is internal to ERPNext usage.  This addition is an id and date separate from posting date, and the id is separate and different from erpnext supplier quotation number.

Occasionally, suppliers offer quotations for similar or equal products in quick succession, with different price, terms, etc. and it is crucial to have the ability to quickly differentiate and eliminate ambiguity by having the ID and date readily available when referring to quotations with suppliers.

**Comment by federicocalvo** [comment]
Hi @Tropicalrambler 
I was looking all over for this, and there was no one asking for it in discussion.

The importance of the date is also that the quotes have states, because like the sales quotes, they expire.

Another thing is that it makes more sense for reports like Quoted Item Comparison or whatever you can do from the report generator.

Regards
