### ISSUE TITLE
UX: Link to Customer from Contact

### ISSUE THREAD

**Issue by mariotruss** [frappe/erpnext#20409]
## Role of Customer in Contact
In CRM of the key information about a Contact is the Customer it is connected to. Therefore, adding this relationship should be able to execute this operation should be intuitive and fast. Secondly, it should be visible directly.

## Problem
Currently, Customers can be linked in the Reference Section, which you can see, when you scroll down 1 or 2 times. 
![image](https://user-images.githubusercontent.com/24277433/73055478-2b8a0d80-3e8d-11ea-8f7a-29b89eb3e7a3.png)

To things to consider here:
- A new user may not know that it is so far down in the UI and will be frustrated.
- Customer to Contact relationship is more than just a reference.

In the context of the reference section, I would imagine things like:
- E-Mails
- Banks Accounts
- Contract

**But Contact to Customer relationship is a major information**

A functional problem, that also occurs with this implementation:
- You can add the same customer multiple times as a reference though the api, which should be an invalid action. This only clutter up the the Customer, as it will render the contact x amount of time in Customer View.
- The Dynamic Link requires for 2 extra step every time: First you have to add a new row, then you have to choose which DocType you want to link to. In 99% of all time I have seen with our user, they wanted to add a customer.
![2020-01-24 09 38 08](https://user-images.githubusercontent.com/24277433/73055609-799f1100-3e8d-11ea-86b3-d57eb3575b93.gif)

**So how to present this information more visually and easily accessible?**

## Solution
You have implemented the wonderful multi-select, which helps declutter the screen and I love it. 
One way, I would see this feature be equally-powerful but more visual is to implement it like that:
![2020-01-24 09 41 42](https://user-images.githubusercontent.com/24277433/73055757-c8e54180-3e8d-11ea-9372-660d4074f26f.gif)

What would happen then?
- If you click "Add Contact" in Customer, this Multi-Select would be automatically filled instead of the reference Dynamic Link.
- This reference will be replace the old implemention, meaning: relation between Contact and Customer will be retraced though the Multi-Select now.

**Comment by Huehnerbrust** [comment]
Great suggestion! This was really confusing for me as new user of ERPNext.

**Comment by wojosc** [comment]
@itsmatru I had the exact same question from a client today!

Is there a possibility of getting more info into the selection? We now use customer numbers instead of names which can then only be used in a limited fashion. I guess this accounts for all serialized DocTypes?

**Comment by mariotruss** [comment]
@wojosc I don't fully understand you question. Could give me a image or something to grasp the idea? What confuses me is:
- Get more info where?
- What problem solves using customer numbers instead of name?

To me it sounds like you mix up this issue with Display of Link Field Name. 

U think that's true?

**Comment by wojosc** [comment]
@itsmatru Get more Info in the shown element. So If I chose "Company" from your example I would like to see more than just the name of the company. Similar to this:
![grafik](https://user-images.githubusercontent.com/22279621/77654805-d1cbbf80-6f71-11ea-9404-3d5688db77b7.png)

Using Numbers instead of Names has the benefit that I have a customer number in the first place. For example I can use this for identification with my customers. Also, as we manage loads of assets of our customers we can attach the customer number every where (in Folders on network shares, DocTypes, Invoices etc.). Basically a unique identifier for the customer. Typing the whole name can lead more mistakes and can sometimes be confusing.

I don't think it's a mix up, but somewhat related.


I tested the funktion of Multi Select in "User Account" beeing part of "User Group" (custom DocTypes on our system). Multi Select would be great because if does save a lot of screen space. It where nice though if it would show more that just the DocTitle.

Regards

**Comment by mariotruss** [comment]
@wojosc 
I am not sure whether I get you fully, but @hrwX has built this app for us: https://github.com/hrwX/title_links/tree/v12/title_links
Maybe that's helpful for you as well.

It fixed the issue of seeing the name/id in link field. Now it will display what ever I have configured as title and will only show the name/id, as a fallback option.

Plus you can configure search field to display designation, email and telefone number for contacts for example.

Maybe we can talk on hangouts and we can talk about this.

**Comment by wojosc** [comment]
@itsmatru I'd be happy to. Send me some details via e-mail or whatever...
