### ISSUE TITLE
Clinical Procedure Template | Auto fetching of item code from template name gives item not found error.

### ISSUE THREAD

**Issue by abhijitkumbharInd** [frappe/erpnext#20526]
## Introduction
While creating a clinical procedure template if the user enters the template name item code automatically fetched into item code and once the user saves the form it always throwing error.
"Could not find Item Code". It is not understandable to the user that this item needs to create first hence we have to keep this as a blank.

**## Steps to reproduce the issue**

1. Create Clinical Procedure Template
2. Enter Template Name
3. Select Item group
4. Save the doc
5. Trowing error: Could not find Item Code: ***

### Expected result
To avoid confusion to a user no need to fetch item code from template name. User has to select item code manually

**Comment by akurungadam** [comment]
Clinical Procedure Template by default creates the Item (with the template name) on saving. The user is not expected to create the Item first and then supply it but I agree this not not quite obvious to the user. Ideally, we should default the Item code field (to template name, as it's now) and then allow user to change the item name if required. If the item is not present, saving the template should create a new item (or use the existing one if exists) with the name provided, instead of throwing the error.

**Comment by ruchamahabal** [comment]
> Clinical Procedure Template by default creates the Item (with the template name) on saving. The user is not expected to create the Item first and then supply it but I agree this not not quite obvious to the user. Ideally, we should default the Item code field (to template name, as it's now) and then allow user to change the item name if required. If the item is not present, saving the template should create a new item (or use the existing one if exists) with the name provided, instead of throwing the error.

Automatic creation of Items for Clinical Procedure Template is great but since Link fields are validated on save, copying the "Item Code" for an item in a Link field which is not created is anti-pattern and affects user-experience. If we want to copy the template name in the item code field it should be 'Data' field. Then on save the Item is created and a read_only Link field "Item" gets set in the Clinical Procedure Template. That is what is done in https://github.com/frappe/erpnext/pull/20811
