### ISSUE TITLE
Create RFQ from Opportunity

### ISSUE THREAD

**Issue by dufani1** [frappe/erpnext#20916]
Hello,
Please why we can not create RFQ from Opportunity?
We need to link RFQ with opportunity, this help a lot of customers.
RFQ shall possible to be created from Opportunity.
This from user experience.
Regards,

**Comment by zuron7** [comment]
Are you looking for RFQ at the Opportunity Stage in order to do a Price Evaluation for the product being offered to the end customer?

Okay, so I just saw #20918 and realized that your process is more for companies that are dealers/traders while ERPNext way of doing things is better for manufacturing companies.

Have you tried making the link by modifying the DocType in your implementation. Some feedback on how your implementation works for you might help make a better decision as to the better system.
