### ISSUE TITLE
Error Log:erpnext.assets.doctype.asset.asset.make_post_gl_entry

### ISSUE THREAD

**Issue by zhangminghao1989** [frappe/erpnext#21018]
## Description of the issue
Error logs appear every day.
## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.6.0
frappe 12.4.1
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```

{'site': 'erpnext.site', 'method': <function make_post_gl_entry at 0x7f79afa9e598>, 'event': 'daily', 'job_name': 'erpnext.assets.doctype.asset.asset.make_post_gl_entry', 'kwargs': {}, 'user': 'Administrator', 'is_async': True, 'retry': 0, 'log': <function log at 0x7f79afc5ea60>, 'method_name': 'erpnext.assets.doctype.asset.asset.make_post_gl_entry'}
Traceback (most recent call last):
  File "/home/zhang/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 99, in execute_job
    method(**kwargs)
  File "/home/zhang/frappe-bench/apps/erpnext/erpnext/assets/doctype/asset/asset.py", line 520, in make_post_gl_entry
    if not is_cwip_accounting_enabled(self.asset_category):
NameError: name 'self' is not defined
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
Debian 10

**Comment by Thunderbottom** [comment]
hi, there's no bug as such that exists here, you probably need to pull and update your current instance.

reference: [asset.py#L525](https://github.com/frappe/erpnext/blob/version-12/erpnext/assets/doctype/asset/asset.py#L525)

which seems to be fixed with: https://github.com/frappe/erpnext/commit/da5e227ad6da284498dcd3c901faa8cf482ce58d
