### ISSUE TITLE
[Feature] Report Print Templates in Landscape [Bounty]

### ISSUE THREAD

**Issue by bohlian** [frappe/erpnext#2132]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=4151489)](https://www.bountysource.com/issues/4151489-feature-request-report-print-templates-in-landscape?utm_source=4151489&utm_medium=shield&utm_campaign=ISSUE_BADGE)
The print templates for reports should be configurable such that the output is in landscape orientation. Currently this is not available.

**Comment by devdesco-ceo** [comment]
:+1:

And I requesting adding the landscape format selection option individually for financial reports such as ledger report, etc., though Invoices, PO's etc to be in Portrait format :)

**Comment by vermettej** [comment]
+1 to this request

**Comment by geekroot** [comment]
:+1:  to this request.  I am trying to do this now.

**Comment by mainul94** [comment]
I also need same feature.

**Comment by jsalcie** [comment]
+1 to this request

**Comment by kodybaker** [comment]
+1 please!

**Comment by neeraj022** [comment]
This feature would help us a lot, Please implement it

**Comment by jsalcie** [comment]
+1

----------------------------------------------------------------------------------------------------------------
Ing. Jesús Salcié Negrín
Soldeva SRL / Mediaplan
soldeva.com.do / mediaplan.com.do
Telf: 829-341-0730 Telf: 809-534-3984

**Comment by gladwynlewis83** [comment]
Any update on this? This would be an awesome feature to have for the outputted PDF files!

**Comment by Tropicalrambler** [comment]
I agree. This is a very important feature. I think that reports should also have a configurable print format similar to what the individual DocTypes have. This is a screenshot of the format selector for individual DocType Sales Order. My expectation is to have the same ability for reports. Since Custom Print format enables ANY page size configurable by the user, then this solves the "landscape" print problem originally stated above.

![screen shot 2017-02-04 at 11 48 31 am](https://cloud.githubusercontent.com/assets/16600935/22620413/0d0e9ff0-ead1-11e6-9b61-3a072a53fbd6.png)

I have also posted this on [discuss.erpnext.com: 20093](https://discuss.erpnext.com/t/report-print-format-add-feature-existing-elsewhere/20093)

**Comment by mhbu50** [comment]
+1

**Comment by rmehta** [comment]
@Tropicalrambler having a customisable report is a very different issue than having landscape mode. I think landscape mode is already implemented.

**Comment by Tropicalrambler** [comment]
You are right!  I decided to piggyback on this issue, which is similar, and addresses only one functionality request, and help refocus it onto something that includes not only landscape, but helps in configuring a format for reporting.

**Comment by Tropicalrambler** [comment]
Now.. I do not know how to enable landscape mode for printing a report in ERPNext...  care to enlighten me?

**Comment by rmehta** [comment]
> You are right! I decided to piggyback on this issue

Bad idea! This becomes very hard to manage

I am closing this issue, please withdraw your bounty and place it on a new issue. The clearer a specific issue the better!

> Now.. I do not know how to enable landscape mode for printing a report in ERPNext... care to enlighten me?

Do you want to post this on the forum.
