### ISSUE TITLE
Due Date calculation

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2135]
As received from Lumi.

In the Sales Invoice, Payment Due Date is correctly updated based on Credit Days mentioned in the Customer. But if user amends Posting Date of Sales Invoice, Payment Due Date is not updated.

Same way, on the purchase side, user expects item's "Required By Date" to be updated, after changing Posting Date of Material Request/Purchase Order.

**Comment by sbkolate** [comment]
Hi,
In the Sales Invoice, Payment Due Date is correctly updated based on Credit Days mentioned in the Customer. But if user amends Posting Date of Sales Invoice, Payment Due Date is not updated.

This can be solved using custom script
```
cur_frm.add_fetch('customer','credit_days','credit_days');
cur_frm.cscript.posting_date = function(doc){
        cur_frm.set_value("due_date", frappe.datetime.add_days(doc.posting_date,doc.credit_days));
}
```
I this this should be added in ERPNext. Can I send pull request for this feature?

Thanks,

Sambhaji
Systematrix Solutions

**Comment by nabinhait** [comment]
@sbkolate 
Actually the code is already there ( https://github.com/frappe/erpnext/blob/develop/erpnext/accounts/party.py#L127 )
It sets due_date based credit_days, on selection of customer or posting_date. But the problem is, if there is already a value selected in due_date field, it does not reset it. It is because system could not identify the due_date is entered by the user or calculated based on credit days. If it was set by user, system should not reset it.

**Comment by nabinhait** [comment]
Same as #3451 
WIP
