### ISSUE TITLE
empty desk

### ISSUE THREAD

**Issue by PCzerw** [frappe/erpnext#21415]
After moving to new server I have empty desk.
First I had error - no workspace folder
/frappe-bench/apps/frappe/frappe/core/page/workspace
I created it, now I do not have an error but empty desk.

When I put direct link for example:
/desk#List/Project/List
works perfect, but
/desk
is empty.

New server:
ERPNext: v12.7.1 (version-12)
Frappe Framework: v12.5.1 (version-12)

Old server:
erpnext 12.x.x-develop
foundation 0.0.1
frappe 12.x.x-develop

**Comment by xyzeem** [comment]
I am also having the same issue right now, Is there a way to specify that I want version 12.5.1

**Comment by PCzerw** [comment]
There is something between 
page-workspace (bad)


<div class="content page-container" id="page-workspace" data-page-route="workspace" style="display: block;"></div>


and 
page-desktop (OK)

<div class="content page-container" id="page-desktop" data-page-route="desktop" style=""><div class="container"><div data-v-5afcca30="" class="modules-page-container"><a data-v-5afcca30="" class="btn-show-hide text-muted text-medium">
		Show / Hide Cards


But everything is on the same server with the same frappe.
it has to be in database I think.

**Comment by xyzeem** [comment]
I am new to frappe and I have literally uninstalled and reinstalled over 20 times already

Easy install guide throws up error too

**Comment by xyzeem** [comment]
I just reinstalled again, I guess it is an issue with erpnext 
![image](https://user-images.githubusercontent.com/38592473/80345626-4f306b80-8861-11ea-8e52-aaa363f575b1.png)

**Comment by kennethsequeira** [comment]
@PCzerw workspace is the layout for desk on develop branch. The issue is arising since you've switched from develop to version-12 branch on Frappe. There is no page workspace on the version 12 branch at all.

I would suggest reinstalling the db on the develop branch and checking again (perhaps a different setup).

PS: never migrate from develop to a stable/release branch if they've been split a long time ago. Version 12 was split 9 months back.

**Comment by kennethsequeira** [comment]
@PCzerw have you restored the original backup on develop branch and checked?

**Comment by PCzerw** [comment]
I installed new develop 12 version on new server.
Restore and working fine.
After 
sudo bench setup production erp
bench update
bench version
erpnext 12.x.x-develop
frappe 12.x.x-develop
still OK

bench switch-to-branch version-12 --upgrade
bench migrate
bench update --patch
bench version
erpnext 12.7.1
frappe 12.5.1
white desktop and error The resource you are looking for is not available.

Its a possibility to switch to latest production?
On other server I have dns_multitenant on and few databases with 12.7.1 and everything working fine.

**Comment by kennethsequeira** [comment]
@PCzerw no point in switching from develop to v12 since the desk has been rewritten. Hence the error like I mentioned earlier, since the system is still looking for workspace page which is not present on v12 at all.  
  
Also, you might want to try to v13 beta branch since that is closer to develop at the moment.

**Comment by half4den** [comment]
I know this is closed, but we're having the exact same issue...Adding to odd behavior, is the fact that we start with a clean V12 install, everything is fine. We restore our backup, no Desk-with error. The page states the missing file(s) are the workspace folder). If I create the folder "workspace" where the system is looking, ERPNext works, with a blank Desk. By works, I mean that we can access our various areas via the global search.

**Comment by kennethsequeira** [comment]
@half4den what version's backup are you restoring ,ie, the backup was taken on which version?

**Comment by half4den** [comment]
Our has been a long and painful road...We were in 10, then did the upgrade/migrate/develop on 11 path to a version of 12 that worked, but would crash. So, I rebuilt from scratch, and pulled the backup from that V12 system. 
I'm positive your assessment about being on an older version/develop split is accurate. The question is, how do we import the backups, and remove whatever keeps looking for "workspace"? 
Thank you for your help by the way! This has been driving us nuts!

**Comment by half4den** [comment]
If it helps, we went through all the different ways of installing, and this last method, we finally just grabbed the VM, and are running the following versions:
12.6.0 - erpnext
12.4.1-frappe
Also, we had to switch into development to be able to modify certain forms. My next quest will be figuring out how saving those changes across upgrades/updates works. I have been testing stashing, and whatnot, but just don't quite get it yet...

**Comment by kennethsequeira** [comment]
Let me dive a little deeper in to the problem.

 If you're on develop/v13 where the desk is redesigned, you access it via workspace, which is a page added to the core:

https://github.com/frappe/frappe/blob/develop/frappe/core/page/workspace/workspace.json

When you are accessing any module via the desk, it will do so through the workspace page (check the url):

![](https://user-images.githubusercontent.com/33246109/81806719-82018180-953a-11ea-8d2a-3e89d2470ff3.png)

Again, since this is a core page, it is available in your site's database as well:

![](https://user-images.githubusercontent.com/33246109/81806905-c2f99600-953a-11ea-8332-709b80ddb3c3.png)

So if you're taking a backup of develop/v13, workspace is available in the backup.

Now, when you install the backup with with workspace inside it back on v12, it will cause the no workspace error. version 12 has no page called workspace:

![](https://user-images.githubusercontent.com/33246109/81807498-cd685f80-953b-11ea-936b-73808f9c788c.png)

Even if you create it manually, it wouldn't work as the intended behaviours on both versions are very different.

Migration in frappe only works on way, ie, upward. This means that you cannot possibly downgrade easily since there are lot of schema changes downwards which are not handled. Upwards, there are migrations and patches written to do this.

That is why if the data from v12 has been restore to develop, will work but the reverse will cause massive problems also since the branches have split close to a year ago.

If you have to make changes, you need to enable developer mode in your config, not switch the branch to develop. If branches were switched then there has been an upgrade and then attempt to downgrade again which has gone wrong.

**Comment by half4den** [comment]
Kenneth, one thing. We're not using the development branch (V13). We're in "developer mode" of version 12. Sorry for unclear info. We've upgraded upward. I believe we've followed the steps to upgrade/migrate properly. However, the net result has not been a system where the previous need for workspace is dropped.

**Comment by PITPL-Akshay-Prajapati** [comment]
I've installed frappe version 13 on digital ocean server. on server IP, I am getting skeleton on card but same thing is working fine on "localhost:8000".  I've tried to fix it by version, branch and also installed erpnext from my private repo but not got any proper solution yet. not getting any console or sever error.

![Screenshot from 2022-02-14 13-56-14](https://user-images.githubusercontent.com/95674015/153827614-82435d4a-d54d-419f-b5b6-285d2aef5eb3.png)

**Comment by kennethsequeira** [comment]
@akshay-pseudocode can you check the browser console for any traceback?

**Comment by PITPL-Akshay-Prajapati** [comment]
> 
no one error in console.

**Comment by bhaveshmahavar** [comment]
In Frappe Version 14 ,
How to remove Create Workspace button from Homepage of frappe
