### ISSUE TITLE
Backlink from Maintenance Visit to Maintanence Schedule missing

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#21485]
Hi,

we have started using the Maintenance Schedule and Maintenance Visit. I feel there is a link missing between the two. Though I can create a Maintenance Visit from M Schedule there is no field maintenance_schedule in M Visit.
I have added this in this PR: https://github.com/frappe/erpnext/pull/21484

**Comment by wojosc** [comment]
Hi @rohitwaghchaure thank you for clarification.

Is there a known reason why this is in the table and not the DocType Level?

**Comment by Nihantra-Patel** [comment]
Hi @wojosc,

There's a section in the "Maintenance Visit" where you can find a table called "Purpose." This field is located in a table called "Maintenance Visit Purpose." The reason it's in the table instead of the main section is because it makes it easier to handle multiple maintenance schedules for the same customer. By having it in the table, you can manage everything in one document, making it more organized and convenient.

Thank You!
