### ISSUE TITLE
Report Builder shows wrong currency symbol in Totals

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#21890]
Hi ,

I just observed that if you have a column showing foreign currency values in your report, the Totals row (which is appended by using the 'Show Totals' option) displays the local currency symbol!

![Report Builder Currency Issue 01](https://user-images.githubusercontent.com/9269337/82740770-cca5a980-9d43-11ea-80c0-60cf81171e9f.png)

Please help fix asap

Thanks

**Comment by clarkejj** [comment]
Refer to https://discuss.erpnext.com/t/report-builder-shows-wrong-currency-in-totals/61916/2

**Comment by Muzzy73** [comment]
This was never resolved. It happens when Print or PDF is clicked. Symbol is incorrect in every line not just total. Headers in Export to Excel/CSV are correct. The values in the screenshot are correct as per USD. Symbol should be USD.
![image](https://user-images.githubusercontent.com/16674535/92971251-cd944f80-f488-11ea-8d1b-bd79993e0fa8.png)

From

ERPNext: v12.11.2 (version-12)

Frappe Framework: v12.9.1 (version-12)

**Comment by deepeshgarg007** [comment]
@Muzzy73 The issue that you are mentioning is different, @Olawale1 please reopen a new issue if it still persists in latest releases
