### ISSUE TITLE
Tender bid management module for ERPNEXT

### ISSUE THREAD

**Issue by nikunj1222** [frappe/erpnext#22080]
**Is your feature request related to a problem? Please describe.**
**Module to manage tender bid and process. This is to target companies managing the turnkey project and contracts.**

**Describe the solution you'd like**
**Module / Domain called tender to be included having following sub-modules or features.
Tender Followup**

>    --Tender open date
>    --Tender Close date
>    --Tender Submission date deadline
>    --Tender Description
>    --Tender win probability
>    -- Attachment of the tender related documents.
>    --Tender bid request amount
>    --Tender security deposit amount

**Tender followup should follow the workflow from Draft-->Approved**

**Once approved the Tender Bid request amount/ Tender security deposit amount shall be connected to Accounts for further payment processing and creating relevant accounts entries.**

**If the Tender is in WIN status having possibility to create a project from this tender.**

**Describe alternatives you've considered**
Currently i have created a doctype called Tender followup. But the problem I am facing is to connecting this to account doctype so that all the relevant payment done for tender bidding is mapped/entered into corresponding COA via accounts module.

**Additional context**
This is must require domain since there are lots of contracting company who can use this module/doctype. This will make ERPNEXT much more strong contender then our competitors. (provided if we have tender management out of box solution available.)

If you need more info on tender management please let me know. I can work on the flow chart to explain the full process.

**Comment by mikladious** [comment]
This feature should be developed considering both parties,
the buyer: it is the entity which publish the tender in order to get best offer 
the seller who submit offer to get awarded for tender scope of work.

from the buyer sides there are multiple functions could be developed such as;
- Attachment of the tender related documents could be segregated into 2 different categories (Technical Offer) and (Financial Offer)
- Correspondences between the two parties (buyer/seller) during bids evaluation stage which dramatically affect the project scope of work and contract between the parties. thus should be considered 
- Encryption and decryption functionality of sensetive details such as submitted prices by sellers
- Involve sub-contractors
...etc.

**Comment by nikunj1222** [comment]
Hi Erp team,

Any updates on this feature request ?

**Comment by zahra-erp** [comment]
Hi all, 
confirm this is really very much needed feature to add in erpnext .. thanks

**Comment by sakhr1980** [comment]
Yes , it is important .

**Comment by ankush** [comment]
This is too niche for ERPNext. Maybe a separate app can be created for this if there's demand.

**Comment by thangapandianne** [comment]
> This is too niche for ERPNext. Maybe a separate app can be created for this if there's demand.

How to get the Tender management module ?
