### ISSUE TITLE
Monthly Repayment Amount from Loan Application is not picked on creation of Loan- v13.0.0-beta.2

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#22100]
Monthly Repayment Amount field in yellow below is not picked on creation of Loan from Loan Application.

![image](https://user-images.githubusercontent.com/1822868/83723725-c8cd2d80-a647-11ea-8096-3241a9981af5.png)

**Comment by deepeshgarg007** [comment]
@muchai The monthly repayment will appear correctly on saving the Loan since other required info to calculate are properly picked from loan application.

Please refer below GIF
![Loan Application](https://user-images.githubusercontent.com/42651287/83970011-cf320280-a8f0-11ea-88c1-4929cb3d2f1d.gif)

Closing this issue

**Comment by muchai** [comment]
Ok. Thank you.
