### ISSUE TITLE
API does not accept names containing a '#'

### ISSUE THREAD

**Issue by grolode** [frappe/erpnext#22144]
![grafik](https://user-images.githubusercontent.com/7470674/83974988-639c6500-a8f1-11ea-8a6a-b6ac3213abbd.png)

It's fine for UI:
![grafik](https://user-images.githubusercontent.com/7470674/83975002-8169ca00-a8f1-11ea-83f8-67f40136f4c8.png)

Remedy:
1. Don't accept this kind of special characters in the first place
2. If character is accepted, query via API should work when containing it.

This is 3 hrs worth of extra work for me (on a sunday) to workaround this S**T ... 
Sorry, I'm loosing my patience.
Thank you very very much.

**Comment by grolode** [comment]
It's annoying stumbling over the same silly bugs since the late 90's.

Again and Again, as if predecessor generations hadn't made the same mistakes .... and learned from it.

Young developers know everything better - do everything better ... judging by their over exagerated self esteem. And then you see the same stupid mistakes you know for more than 20 years now.

I'm really P***ED.

Gotta do the same process all over again, simply to get rid of a silly little character.

**Comment by clarkejj** [comment]
Note this InvalidNameError added to v13 in April https://github.com/frappe/frappe/pull/10030

**Comment by Thunderbottom** [comment]
@clarkejj that name validation is for user name fields including first and last name. I don't think that's the cause in here.

@grolode, have you tried encoding the URL before passing it through the API? You do not need to get rid of anything.

**Comment by Thunderbottom** [comment]
This is not an issue with ERPNext. Please read up on [URL fragments](https://en.wikipedia.org/wiki/URI_fragment), as that part of the URL is not sent to the server by the browser at all. The only way to fix your "issue" would be to follow the industry standard and [encode the URL](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote) before making a request.

> judging by their over exagerated self esteem. And then you see the same stupid mistakes you know for more than 20 years now.

This industry standard for URL Fragments has existed since 2005, as defined in [RFC3986](https://tools.ietf.org/html/rfc3986#section-3.5). The URL needs to be percent-encoded before the request is made. There is nothing anybody can do about it, other than sending a url-encoded request.

**Comment by clarkejj** [comment]
Thanks very much for your especially patient informative notes Chinmay...
