### ISSUE TITLE
Item TAx template captures all companies tax inspite of user given specific company user rights

### ISSUE THREAD

**Issue by kfcspl** [frappe/erpnext#22221]
## Description of the issue
Item Tax Template for specific company not working user has to update
 
## Context information (for bug reports)
Item Tax template 

**Output of `bench version`**
```
(paste here)
```
It should show only one code as per company as well as user restrictions.

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

ERP Nxt Version 12.9.04
![Screen Shot 2020-06-12 at 5 50 17 PM](https://user-images.githubusercontent.com/52742315/84502064-4989ca80-acd5-11ea-9e70-e350bcdb4328.png)

**Comment by nasirrr** [comment]
I validated this. The restricted user is able to see the item tax templates of all the different companies. 
But in sales taxes and charges, it is displaying the values of only the restricted company. 

USER PERMISSION (RESTRICTED to DAB COMPUTER SERVICES - WEB DIVISION)
![image](https://user-images.githubusercontent.com/93313345/145825473-386498cf-130a-4bdf-9b6b-f6cd45b7d7ea.png)

SALES TAXES AND CHARGES (SHOWING RESTRICTED ACCOUNTS)
![image](https://user-images.githubusercontent.com/93313345/145825774-9590d55e-a6e5-4593-ae97-70e88fc4fe57.png)

ITEM TAX TEMPLATE (SHOWING ALL COMPANIES ACCOUNTS)
![image](https://user-images.githubusercontent.com/93313345/145826015-00477381-7fae-42bb-9c2f-0bb4d1ae9677.png)


ERPNext Version 13.16.1
Frappe Version 13.16.0
![image](https://user-images.githubusercontent.com/93313345/145826329-5f2068cd-1711-4345-9aa4-5848838a3588.png)

**Comment by hamzahali** [comment]
Same issue here

**Comment by hamzahali** [comment]
@ankush I am facing the same issue, its a bug.

**Comment by deepeshgarg007** [comment]
This seems to be fixed in the latest released versions. Checked on my local site.

Item Tax template filtering based on Company
<img width="1121" alt="Screenshot 2022-11-14 at 1 07 20 PM" src="https://user-images.githubusercontent.com/42651287/201602198-24856598-9a16-4dea-96be-5070ed673ddc.png">


Sales Taxes and Charges filtering based on company
<img width="1186" alt="Screenshot 2022-11-14 at 1 07 01 PM" src="https://user-images.githubusercontent.com/42651287/201602176-2a2e467c-f233-494e-af2e-8c53a5b2d88c.png">

For permission issue, item tax template is visible only when company is selected in the invoice, and users are able to select companies only as per assigned permissions.

<img width="1125" alt="Screenshot 2022-11-14 at 1 09 29 PM" src="https://user-images.githubusercontent.com/42651287/201602407-f9fdbdc1-a87c-4e25-ab78-f8960b8278ee.png">
