### ISSUE TITLE
Integration with Nextcloud

### ISSUE THREAD

**Issue by asbasawaraj** [frappe/erpnext#22919]
NextCloud is an open-source file hosting software.
https://nextcloud.com/

The requirement is as follows.

A. Backup files 
Just like DropBox/Google Drive/Amazon S3 need a feature to push backup files to Nextcloud.
Refer https://docs.erpnext.com/docs/user/manual/en/erpnext_integration/dropbox-backup

Note: While the SQL file must be pushed as per frequency, pushing files must be optional via a checkbox.

B. When files are attached to any DocType, they should be directly uploaded to Nextcloud instead of the server on which ERPNext is installed.

The main project: https://github.com/nextcloud
The Server: https://github.com/nextcloud/server
API Docs: https://docs.nextcloud.com/server/15/developer_manual/core/externalapi.html

**Comment by vecoreda** [comment]
On PibiCo we have made a Frappe App to do such integration and more over Nextcloud. You are invited to look at https://github.com/doloresjuliana/pibiapp.

**Comment by asbasawaraj** [comment]
@vecoreda Can you send a PR so that this functionality can be merged into Frappe framework? cc: @wojosc

**Comment by vecoreda** [comment]
> @vecoreda Can you send a PR so that this functionality can be merged into Frappe framework? cc: @wojosc

App is already available with documentation on the github repository and licenced to be used if interested in so, even by the Frappe Framework itself.

**Comment by wojosc** [comment]
Hello @vecoreda thanks for the info on the matter.

It has been a while back, that I tested the pibiapp but I can not remember getting it to run (back then we had v11). Are you aware if it runs on v11, v12 or maybe even v13?

Best
Wolfram

**Comment by vecoreda** [comment]
Hello,

Actually, we have pibiapp running on v11, with the following requirements

ERPNext: v11.1.31 (master)
Frappe Framework: v11.1.29 (master)
Full Size View: v2.0.0 (master)
Meeting: v0.0.1 (master)
App Pibi: v0.2.0 (master)

I have recenty tried to install pibiapp on v12, but there is an error 
due to location of a frappe file. We will update as soon as possible to 
get it installed on v12. Also we have installed pibiapp in a new v11 
instance, but while we can install pibiapp and enable nextcloud 
settings, there are errors in uploading files and making backups. These 
are the parameters on V11 where pibiapp cannot run.

ERPNext: v11.1.77 (version-11)
Frappe Framework: v11.1.69 (version-11)
App Pibi: v0.2.0 (master)

**Comment by robinrosenstock** [comment]
Just linking the discussion from the forums: [Nexcloud integration](https://discuss.erpnext.com/t/nextcloud-integration/65047/1)

**Comment by umairsy** [comment]
Completed.
