### ISSUE TITLE
Problem with tables as custom field

### ISSUE THREAD

**Issue by JensBohlin** [frappe/erpnext#2310]
Hi, 

When I try to add a custom field of type Table to a document, the browser window crashes when I try to add a row in that table.

I have tried to add a table linked to contacts in a Note-document and a table linked to group items in Price list-document. In both cases the browser window terminates when trying add a row in the tables.

**Comment by rohitwaghchaure** [comment]
Hi @JensBohlin 

It seems that you're adding the parent table in the options instead of child table. Check with the child table, the way sales order item has added into the sales order. I am closing this issue, feel free to reopen it, if issue still exists and also share the screenshots to identify the issue easily
