### ISSUE TITLE
Change amount included in "Pos Closing Entry" on hand Cash balance - V13 beta 4

### ISSUE THREAD

**Issue by olamide2** [frappe/erpnext#23125]
Version 13 beta 4

At end of day when the cashier is closing out for the day, the amount of change giving to customers is still added to the expected Cash closing figure

Let me give an example

If a cashier makes sales of $400 and is giving $500 cash. She will give out $100 change to the customer. 

At closing the cash on hand should be $400.

But the Pos closing is showing $500.

We need to add a column for total change and deduct this from the on hand expected cash.

For now the end of day figure is wrong

**Comment by michaeleino** [comment]
this issue is still exist for versions 12.19 and 13-dev

it was working perfectly couple of months ago, but now it is really doing confusion for the GL
as we found the Closing vouchers is more than or less than the cash account on daily basis

for ex:
sale for 60
customer pays 100
change amount 40

expected amount should be **60**, unfortunately it appears **100**

are there a quick fix for this ?

**Comment by deepeshgarg007** [comment]
@olamide2 Please reopen a new issue if this still persists in latest version-13 or higher releases
