### ISSUE TITLE
Latency

### ISSUE THREAD

**Issue by Suryaprakash2sla** [frappe/erpnext#23305]
Hello Team,

I have started a new ERPNext account and I am seeing a lot of latency in the system.

I tried to clear the cashe and all the system cleanup but still the latency is there.

https://alsabahelectric.erpnext.com/

Please help me.

Thank you.

Regards,
Surya Chinta

**Comment by barry86m** [comment]
Has this resolved now? When ERPNext is running a lot of background jobs (e.g. after setting up a new installation) it can sometimes be a bit slower than usual. This usually resolves when the background load reduces.

If this hasn't resolved please try contacting ERPNext directly: https://erpnext.com/contact-form
GitHub is for development issues e.g. software bugs. If the problem is on a server you need the server administrator to look into it.

**Comment by kennethsequeira** [comment]
@Suryaprakash2sla contact the support team for this issue as indicated.
