### ISSUE TITLE
Link Loop

### ISSUE THREAD

**Issue by Raxreedoroid** [frappe/erpnext#23456]
## Description of the issue
I wanted to cancel a project and delete it but it said I can't because it is linked with a sales order so I went to delete that sales order and it said it is linked with the project I tried to set status of the project to cancelled but still no change
I want to delete them because the order is also linked to an item group that need to be deleted

## Context information (for bug reports)
The components keep pointing to each other which make it impossible to delete them

**Output of `bench version`**
```
ERPNext: v12.6.0 (version-12)

Frappe Framework: v12.4.1 (version-12)
```

## Steps to reproduce the issue

1.Delete the specified item group
2.I can't it's linked to a sales order A
3.Delete the sales order A
4.I can't it's linked to project B
5.Delete the project B
6. I can't it's linked to sales order A
7.goto step 3 (loop)

### Observed result

Can't delete a sales order it's linked to a project which is the superior compenet

### Expected result

I must be able to delete that sales order

### Stacktrace / full error message

```
Cannot delete or cancel because Sales Order SAL-ORD-2020-00003 is linked with Project Al-Nasban Group
```

## Additional information
I can add multiple sales order to a project while I can't add multiple projects to a sales order

OS version / distribution, `ERPNext` install method, etc.

**Comment by gdbaldw** [comment]
I have the exact same problem. In my case:

LinkExistsError: Cannot delete or cancel because Sales Order <a href="#Form/Sales Order/SAL-ORD-2020-00001">SAL-ORD-2020-00001</a> is linked with Project <a href="#Form/Project/SAL-ORD-2020-00001">SAL-ORD-2020-00001</a> 

and

LinkExistsError: Cannot delete or cancel because Project <a href="#Form/Project/SAL-ORD-2020-00001">SAL-ORD-2020-00001</a> is linked with Sales Order <a href="#Form/Sales Order/SAL-ORD-2020-00001">SAL-ORD-2020-00001</a>

As workaround, used...

$ bench --site <sitename> mariadb
MariaDB> delete from `tabSales Order`; (need to specify the Sales Order)
