### ISSUE TITLE
Can't create asset without CWIP

### ISSUE THREAD

**Issue by carstenblt** [frappe/erpnext#23462]
## Description of the issue
Creation of an asset always fails with an error telling me to set an CWIP account in the asset category or company. 

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.11.2
frappe 12.9.1
```

## Steps to reproduce the issue

1. Create an item as fixed asset
2. Create an invoice with the item
3. Create an asset

### Observed result
Creation fails with an error

### Expected result
Asset is created without CWIP

**Comment by kennethsequeira** [comment]
@carstenblt make sure CWIP is disabled in the Asset Category:

![image](https://user-images.githubusercontent.com/33246109/94645972-ca171a00-030a-11eb-9d09-79063ccc58df.png)

**Comment by carstenblt** [comment]
@kennethsequeira I did, it is disabled. About a year ago it worked flawlessly with the same procedure...

**Comment by gwhitney** [comment]
I am having the same problem. This is on the latest version of develop as of today, for both frappe and erpnext. The problem occurs adding my first asset, with "Is existing asset" checked. Capital work in progress accounting is definitely disabled in the only asset category I have created, which is the category for this asset item. I have no capital work in progress account, and this is an existing item in our inventory of equipment assets. But I cannot enter it into this system, the draft Asset will not submit, because of this issue, which is definitely a bug (I don't see a way for me to put the label back on, but it definitely should be).

The problem may be in the vicinity of line 470 of erpnext/assets/doctype/asset/asset.py, in validate_make_gl_entry(), where self.get_asset_accounts() is called. That method tries to obtain both the fixed asset account and the cwip account, even though it's not yet been checked whether cwip is enabled.

I will try to create a pull request to resolve this, but the difficulty is I am not 100% sure what the desired General Ledger entries are for the various cases here -- is that documented anywhere? I.e., what the GL entries should be when an asset is created, with cwip either turned off or turned on? If there's anything you can point me to (or if someone more internal to the ERPNext project is going to address this bug and wants to call me off to avoid duplicated effort) just let me know. But right now this bug is a blocker for generating our financial statements as we can't get our existing assets into the system, so it's a serious, high-priority bug for us.  Thanks for your attention and understanding!

**Comment by gwhitney** [comment]
Actually, there seems to be a more serious issue in the code. In that same file, erpnext/assets/doctype/asset/asset.py, consider the method make_gl_entries(). If it does generate any entries, it currently only ever creates a ledger entry which credits the CWIP account and debits the fixed asset account. Therefore, it seems clear to me that if CWIP is not enabled for an asset category, make_gl_entries() should never be called (since we don't want any entries involving a Capital Work In Progress account if we are not doing Capital Work In Progress accounting). So it would therefore stand to reason that the validate_make_gl_entry() method, which determines whether to call make_gl_entries(), should always return False if CWIP is not enabled for the relevant asset category. On the other hand, there are explicit cases in the current code for validate_make_gl_entry(), such as lines 486-488 quoted below, which return True when cwip_enabled is false. This seems very confused.

Hence, I am going to make a hot fix in our installation which adds as the first line of the validate_make_gl_entry() method the following check:
`if not is_cwip_accounting_enabled(self.asset_category): return False`
However, unless you would like me to, I am not going to presume to file a PR for this change as it appears to be so far from what is going on in the code as it currently stands (even though I cannot really understand what the intentions are of the current code, as they don't seem to be self-consistent).

So **please** investigate this issue and this code and resolve the situation to something that is reasonably working -- it is critical to using ERPNext, especially for an institution with existing assets prior to ERPNext adoption. Thank you very much!

For reference, current lines 486-488 of erpnext/assets/doctype/asset/asset.py:
```
                elif not cwip_enabled and (not expense_booked or cwip_booked):
                        # if cwip is disabled but expense hasn't been booked yet       
                        return True
 ```

**Comment by carstenblt** [comment]
Just adding a CWIP account for the company as a workaround worked for me today. No error message and it doesn't create any entries on the CWIP account.

But yeah, requiring you to add an account that will never be used is definitely something that should be fixed.

**Comment by gwhitney** [comment]
But as the quoted code in my last comment shows, there definitely are circumstances in which GL entries will be created even though CWIP is disabled. Not understanding what those circumstances precisely are, our Finance Director is unwilling to create a "fictitious" CWIP account until this is resolved. So it is very urgent for us; we are going to proceed with the workaround line of code I mentioned above, which I am willing to submit as a PR if the ERPNext maintainers feel it is appropriate, but otherwise I will not be able to submit a PR to fix this as the intentions of the current code are not at all clear to me, nor do they seem to be fully documented. Hence, we are relying on ERPNext maintainers to address this bug at their soonest ability. Thank you!

**Comment by kennethsequeira** [comment]
@gwhitney encourage you to raise a PR. If anything is missing in that, the maintainer can pick it up from there to resolve it.
