### ISSUE TITLE
Setup Wizard Domain Service not found

### ISSUE THREAD

**Issue by ryuliantoro** [frappe/erpnext#23693]
## Description of the issue
When selecting domain Service, the setup wizard can not complete the process (after that Complete Setup button).

## Context information (for bug reports)

**Output of `bench version`**
```
bench_manager 0.0.1
erpnext 12.11.2
frappe 12.9.1
```

## Steps to reproduce the issue

1. Fill in all fields on every stage of setup wizard
2. Choose Service at domain selection stage
3. Proceed until the last stage
4. Click the Complete Setup button
5. Wait for the process

### Observed result
The setup wizard stops and pop up error
![Screen Shot 2020-10-21 at 05 35 37](https://user-images.githubusercontent.com/13296444/96652302-d36f3180-1360-11eb-99b5-716b95acb51f.png)

## Additional information

CentOS 8
Manual install

**Comment by zahlenhexe** [comment]
I can confirm this. I am new to ErpNext and not able to finish the setup. Is there any workaround to fill the json manually? 
When I try to click on the button of desk#setup-wizard/3 (Domains) 
In the debug console the error is:
```
Uncaught TypeError: txt.replace is not a function
    strip_html common.js:111
    get_values field_group.js:89
    set_values slides.js:109
    next_btn slides.js:353
    jQuery 2
common.js:111:12
```
I think the values in json are not set so the wizard cannot finish

**Comment by ryuliantoro** [comment]
Have this issue solved?
This not-found issue is also happen to Hospitality and some other domains.

**Comment by zahlenhexe** [comment]
Not really.

Finally I have managed to install erpNext, but it was a long, rocky road. 

I think there are many dependencies in the setup wizard that prevent it from completing. Some Country/Domain/Account combination can be selected but will result in an error. It is then really difficult to find out where the problem is, especially if someone is new to erpNext. In addition, it is not possible to complete the installation without the wizard.

It would be helpful if there were a possibility to make settings via a conf file, so that the installation is possible without the wizard. An alternative would be to complete the installation via bench. 

There is something similar at nextcloud with the occ command for installation of apps and check code.

**Comment by ryuliantoro** [comment]
If I'm not mistaken it is possible to bypass setup wizard. I think there is a hooks parameter to do it. But I really don't remember what and I currently don't have my computer with me to look for it.

**Comment by sharmanakul** [comment]
this problem doesn't exist anymore.

**Comment by ryuliantoro** [comment]
Is it solved in version 12 ? or version 13 only?
