### ISSUE TITLE
I cannot make save for delivery note

### ISSUE THREAD

**Issue by mohammed-spec** [frappe/erpnext#24420]
AFTER SUBMIT I FIND MESSAGE DID NOT SAVE.

**Comment by sharmanakul** [comment]
hey @mohammed-spec we generally need more details in order to work on an issue. So it would help if you provide us with the steps you took before you found the error/bug.

i'm closing it for now. feel free to reopen if the issue still persists for you.

by the way, if you provide all the information correctly, you should be able to create delivery note.

**Comment by mohammed-spec** [comment]
I want to add barcode to sales invoices in Saudi arabia.
https://tazia.erpnext.com/desk#
