### ISSUE TITLE
customer rename   merge

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#2549]
I have one customer with two slightly different names entered. Tried to merge.
1) copied the correct name 2) went to incorrecly named customer. 3) ticked Merge 4)
pasted the correct name>>> Error message that the customer does not exist.

Tried to find if there is an option to make a customer "inactive"  Could not find such.

Then renamed the customer in removed(Hemmer) Hemmer is the wrong customer name.

Than went to invoice but the wrong customer is still droplisted under customer.

As different people use the system I want to prevent that the wrong name can be selected because than we invoices for one and the same customers under two different accounts.

please advise

rgds robert

**Comment by umairsy** [comment]
Hello Robert,

Thanks for the detailed explanation.

Firstly I tried replicating Customer merging issue in my test account. I merged two customers, later one with spelling mistake. I could correclty merge wrong Customer into correct Customer. Same was also updated in the already existing invoice of wrong customer.

Please provide more information about this on support@erpnext.com so that we can check into it from here.
