### ISSUE TITLE
Not able to fetch data from shopify. 

### ISSUE THREAD

**Issue by rakshithrddy** [frappe/erpnext#25510]
As mentioned, I am not able to fetch data from Shopify to the erpnext. 
![Screenshot from 2021-04-29 10-49-28](https://user-images.githubusercontent.com/36509967/116505772-61f8d880-a8d9-11eb-9d41-b11119d6ef74.png)

Erpnext version: v13.1.1 (HEAD)
Frappe Version: v13.1.2 (HEAD)

**Comment by ankush** [comment]
Shopify doesn't support http webhooks. 

**Assuming your ERPNext site has a valid SSL certificate and can accept HTTPS connections**, here's the solution: 

1. Access your erpnext site using `https://`
2. Go to Shopify settings and disable it, if not already.
3. Reenable it, this will cause it to register new webhooks with HTTPS urls.

**Comment by ankush** [comment]
@rakshithrddy added PR to force HTTPS while registering webhooks.

**Comment by taj-meltedmoon** [comment]
Hi @ankush , I am using v13.6.0 of ERPNext. I am still having same issue as shown by @rakshithrddy .
And my site is working under https.

**Comment by taj-meltedmoon** [comment]
This is what i am getting in shopify logs
![shopify log](https://user-images.githubusercontent.com/49357910/125936934-c0799fff-ee6b-427f-a790-3fab92f56ed5.jpg)

**Comment by ankush** [comment]
This is not because of HTTP / HTTPs, there are stale webhooks on your site which is preventing it from registering new ones.

Maybe try disabling and enabling it again. 

I was thinking of adding a utility function to clean up stale webhooks, because this issue pops up at random. 


Aside: Shopify integration is now moved to a separate app:  https://github.com/frappe/ecommerce_integrations old integration won't receive any features or minor bugfixes and it will be removed in v14.
