### ISSUE TITLE
[v13][POS] Can't pick POS Profile while opening

### ISSUE THREAD

**Issue by glibersat** [frappe/erpnext#25709]
## Description of the issue

After a fresh installation of v13, when you start the POS, you can't pick a POS Profile since the Company filter is set to "Empty" instead of the selected company. The result is that you can't start the POS.

## Context information (for bug reports)

**Output of `bench version`**
v13.2.1

## Steps to reproduce the issue

1. Create a POS Profile
2. Open the POS
3. Pick your company
4. Try to pick the POS profile (you can't)

### Observed result

The filter is set to "Empty" instead of the company name.

### Expected result

The filter is set to the company previously picked and you can select a POS Profile.

### Stacktrace / full error message

![image](https://user-images.githubusercontent.com/262663/118244041-66a7ba00-b49f-11eb-9791-35705f47fb58.png)

## Additional information

Frappe Docker official image.

**Comment by glibersat** [comment]
Looks like it can be solved by setting the Session Defaults:

![image](https://user-images.githubusercontent.com/262663/118250856-2d734800-b4a7-11eb-9685-1efd80e41ca6.png)

![image](https://user-images.githubusercontent.com/262663/118250889-37954680-b4a7-11eb-8427-347d0035d1d8.png)

Once that is done, the POS profile are shown:

![image](https://user-images.githubusercontent.com/262663/118250953-4bd94380-b4a7-11eb-9aa0-9da68be538d0.png)

**Comment by abhioncode** [comment]
@glibersat ,

Thats because now under V13 you need to add each user into all specific POS Profiles. 
Go to POS Profile, click on one and scroll down to Users. Each user that can access this POS Profile needs to be added. You can add one user to multiple POS Profiles, but only one POS Profile can be set to default.

Once you do this, the user will start seeing the POS Profile available to him/her.
