### ISSUE TITLE
POS Required flat amount Discount

### ISSUE THREAD

**Issue by amet123** [frappe/erpnext#26035]
Hi

Under POS we required Discount flat amount , Currently show in % discount in individual item

![image](https://user-images.githubusercontent.com/326649/121808767-b54f9c00-cc77-11eb-9f42-857861bb1c9e.png)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yesmathew** [comment]
If I understood correctly, it is similar to my customer's requirement!
The way we change individual items rate, the system automatically applies the discount. Similarly, before checkout at the counter instead of discount percentage, the customer wants to give discounted grand total and the percentage can be calculated from the final amount.

![discounted-amount-feature](https://user-images.githubusercontent.com/8710780/125191856-36438880-e262-11eb-99a4-1a375943830a.png)

**Comment by yesmathew** [comment]
Similar to in **Sales invoice** is also good - Apply Additional Discount On "**Net Total**"
Additional Discount Amount: **50**

If the Grand Total was **₹ 350.00**

Then - 
Net Total       **₹ 283.02**
CGST @ 2.5%  ₹ 16.99
SGST @ 2.5%  ₹ 16.99
KFC @1%        ₹ 16.99
Grand Total   **₹ 300.00**

Additional discount becomes: 14.29

**Comment by amet123** [comment]
Yes i thing awesome pos can fullfill features

**Comment by tawhk** [comment]
Please keep open this request. I really need it. Discount flat amount in POS.

**Comment by tawhk** [comment]
We still don't have flat amount discount in ERPNext?
