### ISSUE TITLE
MariaDB Syntax Error in Credit Note (Sales Invoice)

### ISSUE THREAD

**Issue by abhioncode** [frappe/erpnext#26258]
When creating a credit note through sales invoice. I ha

pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Productos Terminados' - DB' and item_code in ('7840032924034'))\n\t\t\tand timest...' at line 4")

Also same problem in Purchase Invoice.
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Producción' - DB' and item_code in ('Frac.Ciruelas'))\n\t\t\tand timestamp(posti...' at line 4")

This seems to happen near ItemCode. I believe there in a space missing from "/t and"

ERPNExt Version 12.5.2

**Comment by ankush** [comment]
Sounds like an unescaped parameter.

Can you tell me the full name of what is "Productos Terminados" and does it have any quotes in the name?? If you could share a traceback, it will be likely very trivial to fix. Just need to find the query where this is happening. 

> ERPNExt Version 12.5.2

This version is ~1.5 years old now. Similar issues were fixed in later versions. I'd suggest upgrading.
