### ISSUE TITLE
bug: Stock Entry from Work Order failing if Work Order and Stock Entry are cancelled and recreated

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#26443]
## Description of the issue
The result of this bug is that a new Work Order cannot be recreated and finished because the finish button does not appear because `material_transferred_for_manufacturing` is not increased from zero.

The responsible code I believe is in:
erpnext.manufacturing.doctype.work_order.work_order.make_stock_entry

## Context information (for bug reports)

**Output of `bench version`**
```
13.6
```

## Steps to reproduce the issue

1. Work order has been created from production plan and Started, stock entry for materials created and submitted
2. Stock Entry cancelled and Job Cards deleted
3. Work Order Cancelled
4. Validate `material_transferred_for_manufacturing`=0
5. New Work Order created from Production Plan
6. Press Start on the Work Order

### Observed result
Message: "All items have already been transferred for this Work Order."
Stock entry is not populated

### Expected result
Continues as a fresh Work Order

**Comment by nameduser0** [comment]
@yadavyk what was the value of `material_transferred_for_manufacturing` on the Work Order at step 5 ?

**Comment by yadavyk** [comment]
@casesolved-co-uk the value of material_transferred_for_manufacturing on Work Order at step 5 was set to 5.

**Comment by nameduser0** [comment]
@yadavyk If you can reproduce this so that `material_transferred_for_manufacturing` returns to zero, you'll see the bug

**Comment by Nihantra-Patel** [comment]
We no longer provide support for version 13 or older.

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.
If the issue occurs then please create a new issue according to the latest version (14 or 15) with a video document if possible.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
