### ISSUE TITLE
UX: Refreshing stock for production plan

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#26450]
## Description of the issue
There is a button `Get Raw Materials For Production` which first opens a dialog with a multi-select field named `Source Warehouses` to gather source material warehouses, then allows you to `Get Items`, then updates the `Material Request Plan Items` with those that are out-of-stock with either a Purchase or a Material Transfer.

The `Material Request Warehouse` on-page field is used as the Production source warehouse, and therefore also the target warehouse for any planned material transfers.
The  field `Create` -> `Material Request` menu option can then be used to create Material Requests from the plan.

Wouldn't it be better to:

- rename the existing Warehouse field `Production Source Warehouse`
- remove the dialog
- move the multi-select field on-page and name it `Additional Source Warehouses (optional)`
- rename the existing button to `Refresh Materials Request Plan` or even just trigger the refresh from Warehouse field changes
- rename the download button to `Download Materials Request Plan`

Edit: Updated due to comment by @guilmori

## Context information (for bug reports)

**Output of `bench version`**
```
13.6
```

## Steps to reproduce the issue

1. Create a Production Plan
2. Put some required items into stock
3. Click `Get Raw Materials For Production`

### Observed result
Dialog pops open

### Expected result
Just refreshes the list

**Comment by guilmori** [comment]
Field `Material Request Warehouse` is where the system will look for available stock quantities. It is also the target warehouse for the material requests.

The dialog with the multi-select field `Source Warehouses` is used to pick other warehouses in which the system will check for available quantity and generate Material Request of type `Material Transfer`.
This is not so well explained in the help text: _System will pickup the materials from the selected warehouses. If not specified, system will create material request for purchase_

So for example if there is not enough stock in `Store` warehouse, and there is stock in `External Stock` warehouse, instead of creating a `Purchase` material request, it will be a `Material Transfer` from `External Store` to `Store`.

I too was confused about the second selection of warehouse, and had to look in the source code to understand.

**Comment by nameduser0** [comment]
@guilmori Thanks for the explanation, that now makes more sense but think it could still be improved. Description updated.
