### ISSUE TITLE
Payment Entry: Allocated and Outstanding amount are different but Writeoff is not reflecting the amount

### ISSUE THREAD

**Issue by eleben** [frappe/erpnext#26542]
## Description of the issue
When creating a payment entry 

## Context information (for bug reports)

**Output of `bench version`**
```
13.6.0 - Frappe Cloud
```

## Steps to reproduce the issue

1. Create Payment Entry
2. Add Paid Amount to Amount section (different amount than Invoice)
3. Add Received Amount After Taxes (different amount than Invoice)
4. Add outstanding Invoice under Reference section

### Observed result
Writeoff amount is not showing a difference and therefore not showing a button to create a writeoff amount

### Expected result
Button to create a writeoff amount due to a difference between Paid Amount/Outstanding Amount from invoice

## Additional information

![Outstanding-AllocatedDifference](https://user-images.githubusercontent.com/272594/126075415-ad8a2166-d2a6-4cc8-b722-3b87e84d08be.jpg)

**Comment by eleben** [comment]
Write off amount button only appears when the Allocated amount is more than the Outstanding amount

**Comment by deepeshgarg007** [comment]
How can the write-off amount be shown if the allocated amount is less than the outstanding amount? You can receive partial payments against invoices too. The system cannot guess if it's a partial payment or has to written off if the amount is less. It has to be as shown in the image below. Also, the Received amount after-tax amount is only for internal purposes and is a hidden field now so that should not be an issue.

![image](https://user-images.githubusercontent.com/42651287/148094698-c83dfcdb-4a45-4de5-8e5d-d047557dced0.png)
