### ISSUE TITLE
Employee check in 

### ISSUE THREAD

**Issue by ahmadRagheb** [frappe/erpnext#26561]
in version 13 log type isn't mandatory 
also in version 12 it wasn't mandatory to tell the last push on the code ??
??

**Comment by ahmadRagheb** [comment]
even in the docs and in the function and API description for the biometric push on this doctype it said it's optional field not mandatory

**Comment by ruchamahabal** [comment]
Log Type isn't mandatory because in Auto Attendance settings for Shift Type we have an option to Determine Check-In and Check-out:

https://docs.erpnext.com/docs/v13/user/manual/en/human-resources/shift-management#determine-check-in-and-check-out

If the option is set to **First Check-in and Last Check-out** then the user does not need to provide log type through biometric. While marking attendance, the system automatically detects whether the entry was IN/OUT

Closing this issue.
