### ISSUE TITLE
Navbar shows every single domain even though one domain 'services' is selected and all items are being merged togather without labels

### ISSUE THREAD

**Issue by itskanny** [frappe/erpnext#27172]
## Description of the issue
I just installed erpnext using latest version and i selected only services domain while setting up the site but in my dashboard it displays every single domain available in erpnext. 

![](https://cdn.discordapp.com/attachments/818880540060418125/880413109217542194/unknown.png)

while my selected domain are only 'services'

![](https://cdn.discordapp.com/attachments/818880540060418125/880413341376466964/unknown.png)

this happens even if i create a new site and install erpnext on it. I used "bench get-app erpnext" to install latest erpnext version

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.x.x-develop
frappe 13.x.x-develop
```

## Steps to reproduce the issue

1. installed bench on fresh ubuntui machine
2. initialized bench
3. installed erpnext using "bench get-app erpnext" and then installed it on a site using "bench --site site.local install-app erpnext"

### Expected result

While results should have been like something like this
![](https://cdn.discordapp.com/attachments/769588491893735435/880418654980804640/unknown.png)

### Stacktrace / full error message

Bench does not show any errors

## Additional information

Ubuntu 20.04, Manual installation using frappe.

**Comment by Mostafa-Rawash** [comment]
Hi  @Umair9736, 

i faced the same issue, and trying to change in setting and other ways then trying to install the previous worked  version of erpnext, and will i'm trying to change the version i found the other error like 
`ImportError: Module import failed for Delivery Trip (erpnext.stock.doctype.delivery_trip.delivery_trip Error: No module named <module-name>)` 
, and after some researches i found the error in the versions of erpnext and frappe so i thing 
**The **problem****
the problem happen because the version of erpnext and frappe not the same as you see in the version here in [frappe ](https://github.com/frappe/frappe/blob/develop/frappe/__init__.py) is '14.0.0-dev' and in [erpnext ](https://github.com/frappe/erpnext/blob/develop/erpnext/__init__.py) is '13.9.0' and both in develop branch so you will to install the last version of found in both and it's '13.9.1' or wait to new version '14.0.0' 
**What you will do** 
` bench get-app frappe --branch v13.9.1 `
` bench get-app erpnext --branch v13.9.1`
,then need to reinstall the website using: 
` bench --site {site} reinstall`.

wallah congratulation you fix the issue

**Comment by Mostafa-Rawash** [comment]
Hi  @Umair9736, 

i faced the same issue, and tried to changed in setting and codding but there's not any thing happen , then i decided to install the previous worked version of erpnext, while I trying to change the version of erpnext i found the other errors like:

`ImportError: Module import failed for Delivery Trip (erpnext.stock.doctype.delivery_trip.delivery_trip Error: No module named <module-name>)`

, and after some searches i found the error in the versions of erpnext and frappe, should to be same so i think


**What you will do** 

` bench get-app frappe --branch <tag name / branch name > `
` bench get-app erpnext --branch <tag name / branch name >`

,then need to reinstall the website using: 

` bench --site {site} reinstall`.


, and  wallah ✨✨ congratulation you fixed the issue 



,as you see in [frappe](https://github.com/frappe/frappe/blob/develop/frappe/__init__.py) the version here is '14.0.0-dev' and in [erpnext ](https://github.com/frappe/erpnext/blob/develop/erpnext/__init__.py) the version here  is '13.9.0' and both in develop branch so you want to install the last version found in both and it's '13.9.1' or wait to new version '14.0.0' like it's in  frappe

**Comment by itskanny** [comment]
Hi @Mostafa-Rawash,

My frappe and erpnext both version are 13.x.x none of them are 14 so it may not be that issue but i will check it again

**Comment by MagedMRawash** [comment]
Hi @itskanny  
try reinstall frappe & erpnext of the same version or branch -> 13.9.1 works fine .
`bench get-app frappe --branch  13.9.1
bench get-app erpnext --branch  13.9.1
`
then normal setup

**Comment by Mostafa-Rawash** [comment]
> Hi @Mostafa-Rawash,
> 
> My frappe and erpnext both version are 13.x.x none of them are 14 so it may not be that issue but i will check it again

if you see the list of tags for each app you will found the last tag in erp is "v13.9.2" and last one in frappe is "v13.9.1" , so you  will install for both apps tag "v13.9.1"
