### ISSUE TITLE
Currency wrong in Asset module

### ISSUE THREAD

**Issue by blewsky** [frappe/erpnext#27511]
## Description of the issue
Currently the Asset module does not support multicurrency. The value of the Assets is always displayed in "$" despite a different company currency.
This affects several doctypes, reports etc. in the Asset module.

## Expected behavior
The doctypes/reports in the Asset module should include a currency field (similar to the invoices) or at minimum the company currency should be displayed.

## Additional information
ERPNext: v13.10.2 (HEAD)
Frappe Framework: v13.10.0 (HEAD)

**Comment by blewsky** [comment]
It is annoying that the issues are closed because the maintainer team does not care enough about a specific bug. The bug is still in the system. It's fine if there is nobody working on resolving this but I think it's not the right approach just to close issues because nobody wants to work on it currently. What is the reason in submitting issues then? Please leave issues open until they are resolved or validated to be incorrect. Thanks!
(This has happened recently to several issues I submitted. It is really discouraging if issues are closes just because nobody likes working on them...)

**Comment by kvikster** [comment]
it's an issue for me too. please consider to fix or provide workaround.

**Comment by deepeshgarg007** [comment]
@blewsky Can you please also share why an Asset has to be in multicurrency? ERPNext only has provision to maintain company assets so values just in Company's current should be enough. What's the use case here? If there is any other currency account allowed anywhere maybe that needs to be fixed

Coming to closing the old issues. If the issues are just kept open and no one looks at them then there is no point in keeping them open. Issues will just keep on piling up making it difficult for the maintainers to prioritize. Since there are frequent refactors many issues become irrelevant and need to be cleaned up, it's completely the maintainers' call.

We are currently working on an Asset Module refactor as well and this seems like a feature request without much description rather than a bug, In case there are any valid use cases please explain and reopen the issue and we will consider.

**Comment by blewsky** [comment]
Thanks @deepeshgarg007  for your detailed reply and for explaining the rationale why issues are closed after some time. 
If I am not mistaken, I didn't explain myself well. The problem is not only confined to the assets module but to several modules in ERPnext. I guess it is not apparent to most users since I guess the majority does not use a multicurrency setup.

The issue is: If you have two companies in different currencies (e.g. Company A in USD and Company B in ¥), the asset module shows only $ signs in all reports for company B etc. although the company currency is ¥. This is not a feature request or something similar but a clear bug. I agree it is more aesthetic. We managed to tell our employees that it's just a bug they shouldn't care about ("Everything is in your company currency, not $") but it is confusing and IMHO wrong. Please let me know if this helped to clarify, if not I am happy to provide more detailed context.
