### ISSUE TITLE
 One Day Leave Marked as Half Day (0.5) in Attendance DocType - HR Module

### ISSUE THREAD

**Issue by elan-k** [frappe/erpnext#28223]
## Description of the issue
Applied for a leave (1 Day) but the system marked it as Half Day (0.5) in the Attendance DocType on the approval. 

**Output**
![image](https://user-images.githubusercontent.com/78781781/140035247-5471ebd4-25df-417d-83d2-ef46e7daf19e.png)

## Steps to reproduce the issue
Note: This issue is not happening for everyone (Out of 64 Leaves Applications - 10 Entries have this issue) 
1. Apply Leave for full Day (Half Day Checkbox - Unchecked) 
          Desk > HR Module > Leave Application 
2. Approved by the Reporting Manager  
          Desk > HR Module > Leave Application > Select the Same Leave Record > Approve (Leave Approval Permission Required) 
3. Check the Attendance Record for Half Or Full Day Marked
          Desk > HR Module > Attendance > Select the Same Employee & Same Date 

### Observed result
Applied for 1 Day Leave but Attendance marked as Half Day Only

### Expected result
Any Leave Period should be marked as a leave in the Attendance Doctype without any change. Because this leads to lots of manual verification on payroll processing. 

## Additional information

OS version / distribution, `ERPNext` install method, etc. 
ERPNext: v12.25.0 (HEAD)
Frappe Framework: v12.22.2 (HEAD)
Hosted with frappecloud.com

**Comment by elan-k** [comment]
This issue has been reported and discussed on the ERPNext Forum but no solution was offered even after a long time.
[
https://discuss.erpnext.com/t/error-in-attendance-entry-for-approved-leave/37340](https://discuss.erpnext.com/t/error-in-attendance-entry-for-approved-leave/37340)

Look like this issue was there from Jun 2018.

**Comment by BMTTeam** [comment]
I would like to add one more scenario for the reported bug.
For example, if employee submit his leave request couple of days during his vacation and you want to reflect his/her vacation in the app (let's say the vacation is starting in Monday and you submit the request in Wednesday), the day you submit the vacation period is also counted as half day. There is no difference if the employee is submitting the request or user behalf with enough access level. The app always count the day on which the submission is made as half day.
Expected behavior - all working days should be full day vacation from day one to the end, no matter when the request was made/approved.

Cheers,
-Tiho

**Comment by sharmanakul** [comment]
hi @elan-k , i'm on v13.14.0 (HEAD) and tried to validate the issue. 

Applied and approved leave application for today.
Checked the attendance.

It is working fine for me. I'll suggest updating to the latest version.

**Comment by elan-k** [comment]
Hi @sharmanakul 

As mentioned in the "Steps to reproduce the issue", 

This issue is not happening for everyone (Out of 64 Leaves Applications - 10 Entries have this issue)
