### ISSUE TITLE
Earned Leave Not Calculating

### ISSUE THREAD

**Issue by spacezmonkey** [frappe/erpnext#28245]
Hello , I am using ERPNext v13.13 ( self hosted ) and i am testing out with a dummy entry and unable to calculate earned leave when leave assignment is based on "joining date".

if i assign leave based on “Leave Period” , it will calculate.

![image](https://user-images.githubusercontent.com/73033222/140303550-3f7cec40-3b4a-4014-b1f8-baf031e669d3.png)

![image](https://user-images.githubusercontent.com/73033222/140303573-03693a30-3fbc-4760-a238-1a4689d58fe3.png)

However, if i choose “joining date” in leave policy assignment, it do not calculate.

![image](https://user-images.githubusercontent.com/73033222/140303620-4d252b19-6e03-4f06-8ffd-c96e8e71e574.png)

![image](https://user-images.githubusercontent.com/73033222/140303637-282e8928-8529-4382-911e-35202de3eada.png)

**Comment by pushkarjsh88** [comment]
@spacezmonkey It worked fine for me. Do let me know if anything is missed at my end

Assignment based on leave period:-
![Screenshot 2021-11-18 at 10 01 09 AM](https://user-images.githubusercontent.com/89507981/142352452-0df236e3-432b-4987-8281-4409f73d247a.png)

![Screenshot 2021-11-18 at 10 01 25 AM](https://user-images.githubusercontent.com/89507981/142352499-187b6821-ffbb-4e16-8f09-25c610430ecc.png)


Assignment based on joining date:-

![Screenshot 2021-11-18 at 10 01 50 AM](https://user-images.githubusercontent.com/89507981/142352552-6d778389-c0a5-4ee4-a008-1636d4c8424a.png)

![Screenshot 2021-11-18 at 10 02 04 AM](https://user-images.githubusercontent.com/89507981/142352568-f89ab97c-9714-4044-be6e-9a7f9cd68b32.png)

**Comment by ruchamahabal** [comment]
@spacezmonkey Earned Leaves allocation is always 0 first and they are allocated automatically based on the frequency set in the Leave Type. For eg: If your leave type is Earned Leave and the leave policy is for 12 earned leaves for Monthly frequency, then the employee should get 0 leaves at first and 1 leave allocated at the end of every month. You can get more details here:

https://docs.erpnext.com/docs/v13/user/manual/en/human-resources/leave-type#22-earned-leave

In the screenshots you have shared, the assignment based on Joining Date allocates 0 leaves at first which is actually correct. There was an issue with the Leave Policy assignment based on Leave Period that would assign all leaves at once, which was incorrect because earned leaves should be allocated periodically based on the frequency. This second issue is now fixed in https://github.com/frappe/erpnext/pull/29163
