### ISSUE TITLE
'Get material request' in production plan is not fetching the items

### ISSUE THREAD

**Issue by sharmanakul** [frappe/erpnext#28517]
## Description of the issue
'Get material request' button in the production plan is not fetching any items despite having the BOM items in the material requests
![image](https://user-images.githubusercontent.com/88872881/142989133-7709cc26-79ac-4f5d-8d1e-30488a1ae29c.png)

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. NEw production plan
2. set 'Get items from' value as Material Requests
3. click on Get material request button

### Observed result
the child table remains blank

### Expected result
appropriate items should be fetched else some validation is to be provided.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
ERPNext v13.14

**Comment by ankush** [comment]
seems to work. Is the purpose set to "Manufacture" in material request? 

This code hasn't changed since 2018

https://github.com/frappe/erpnext/blob/8b33358660fac5ee66c2b56e966faca1f6ba0522/erpnext/manufacturing/doctype/production_plan/production_plan.py#L66-L97 


<img width="1105" alt="Screenshot 2021-11-26 at 2 46 20 PM" src="https://user-images.githubusercontent.com/9079960/143556733-1ae6d1ee-b04c-4f06-8cac-681bfb1a7925.png">

**Comment by sharmanakul** [comment]
did not set the purpose as 'manufacture' in the material requests.

HOwever, a validation may be helpful to the end user here.
