### ISSUE TITLE
"Asset" > "Manage" button, actions labels not translatable v.13.15.0

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#28532]
## Description of the issue
"Asset" > "Manage" button, actions labels not translatable
## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.15.0 (version-13)
Frappe Framework: v13.15.0 (version-13)
```

### Observed result
![Captura de Pantalla 2021-11-23 a la(s) 10 41 11](https://user-images.githubusercontent.com/25084259/143066725-2f855363-40cd-4b41-b676-7457e125c403.png)

### Expected result

![Captura de Pantalla 2021-11-23 a la(s) 10 43 56](https://user-images.githubusercontent.com/25084259/143067183-e5931007-3f21-4f8e-9e1b-fb75ab426b06.png)

**Comment by ankush** [comment]
Since you're already prepared a fix, send a PR?

**Comment by franciscobuendiao** [comment]
> Since you're already prepared a fix, send a PR?

I'd like to, but I don't know how, I've never posted a PR. Sorry. Your help would be much appreciated.

**Comment by ankush** [comment]
You can follow any "first PR" tutorial.

https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/


If you already have frappe/erpnext set-up locally on bench you can skip lots of parts and just add your fork as a remote repository: https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories 

Alternatively, since this is such a tiny fix you can probably just edit from frontend and raise a PR.

**Comment by ankush** [comment]
@GangaManoj might as well add a semgrep rule for this, all button text should be translatable by default. 

Example: https://github.com/frappe/semgrep-rules/blob/develop/rules/report.yml#L2

**Comment by GangaManoj** [comment]
@ankush good idea, will do.

**Comment by ankush** [comment]
@GangaManoj did it already :P. https://github.com/frappe/semgrep-rules/pull/2

**Comment by GangaManoj** [comment]
@ankush damn, you act fast.
