### ISSUE TITLE
Raw Materials Consumption

### ISSUE THREAD

**Issue by peterebCMG** [frappe/erpnext#29006]
### Information about bug

In Manufacturing Settings Raw Materials Consumption is ticked and enabled. 

According to the documentation, [https://docs.erpnext.com/docs/v13/user/manual/en/manufacturing/articles/material_consumption](url), "Once enabled, a Material Consumption button will be available in Work Order once started."

Once **Start** is selected a "Select Quantity" pop up is shown with no option of "Material Consumption"

If the “Skip Material Transfer to WIP Warehouse” in Works order, is not checked then the “Material Consumption” button does show up. If it is checked then it does not show up.

This has been discussed in the forum [https://discuss.erpnext.com/t/manufacturing-issues-in-version-11/47349/3](url)

### Module

manufacturing

### Version

ERPNext: v13.16.1 (version-13)

Frappe Framework: v13.16.0 (version-13)

### Installation method

manual install

**Comment by peterebCMG** [comment]
Just to clarify what happens:

- _Skip Material Transfer to WIP Warehouse_ **NOT** enabled  then once submitted  **Start** and **Material Consumption** can be selected as per the documentation.

- _Skip Material Transfer to WIP Warehouse_ **IS** enabled  then once submitted  **Start** and **Material Consumption** are not available and the only available option is **Finish**

**Comment by peterebCMG** [comment]
Any progress/time frame on this issue?
Thank you

**Comment by s-aga-r** [comment]
@peterebCMG I think this is the expected behaviour. Check https://github.com/frappe/erpnext/pull/8515

In the case where "Skip Material Transfer to WIP Warehouse" is checked/enabled the Transferred Qty will be "0" which means we can't do "Material Consumption" based on the transferred qty. It might be possible with Available Qty but it will only work if the Backflush Raw Materials Based On is set to BOM
