### ISSUE TITLE
Error in making delivery note and reporting error to support. 

### ISSUE THREAD

**Issue by kapscool** [frappe/erpnext#29089]
### Information about bug

i have recently migrated my date from ERPNext to Frappe.cloud

i only use, Quotation, and delivery note module in erp. 

quotation is working file after migration. 

but wile making new delivery note or duplicating old one it show GST_Category error. 

Please help. 
![Screenshot 2022-01-01 at 12 29 04 PM](https://user-images.githubusercontent.com/19993925/147845851-fb9ccc7c-be85-4580-97ab-407893da1b3e.png)

![Screenshot 2022-01-01 at 11 38 59 AM](https://user-images.githubusercontent.com/19993925/147845852-25c356bb-0302-4924-82d6-60dd346667b4.png)
![Screenshot 2022-01-01 at 12 28 41 PM](https://user-images.githubusercontent.com/19993925/147845853-f21b7609-9022-48de-8d4a-5cf23c29b452.png)
![Screenshot 2022-01-01 at 12 29 04 PM](https://user-images.githubusercontent.com/19993925/147845858-c7d4a493-4c2a-4907-98ed-9fe0d1d32c46.png)

### Module

stock

### Version

ERPNext: v13.16.1 (HEAD)

ERPNext Support: v0.2.1 (master)

Frappe Framework: v13.16.0 (HEAD)

### Relevant log output / Stack trace / Full Error Message.

```shell
i am getting following message wile making delivery note in stocks module. 

"Field not permitted in query: gst_category"
```

**Comment by ankush** [comment]
This is due to the failed setup of the regional module; nothing much can be done about it other than re-running it. 

In the company doctype find the company and change country to some other country which doesn't have any specific regional code (e.g. Afganistan) save and then set it back to Indian.

Don't ignore any failures during setup, they could be problematic later!
