### ISSUE TITLE
After Import employee with Emp No, we can change Emp No with new number but its show old number on the list.

### ISSUE THREAD

**Issue by tsothun** [frappe/erpnext#29247]
### Information about bug

![photo_2022-01-11_22-33-00](https://user-images.githubusercontent.com/56767875/148972112-2359bc8b-ea26-432f-bf00-1760f041e890.jpg)
![photo_2022-01-11_22-33-05](https://user-images.githubusercontent.com/56767875/148972123-8b185e39-0f88-4c02-9418-bd2395b7f2e9.jpg)

### Module

HR

### Version

Frappe Version 14
ERPNext Version 13.18

**Comment by ruchamahabal** [comment]
Changing the "Employee Number" does not rename the document because changing the primary key is not a good practice since it can be linked with so many other documents and all these documents like salary slips, claims, etc would have been generated with the old employee number and are already given out to the employee. Renaming this after the payroll is processed or operations already carried out, will change the employee id on all related transactions which is again not very correct.

If you do not have problems with the things mentioned above, after changing the Employee Number, you can rename the document with new the new Employee Number

https://docs.erpnext.com/docs/v13/user/manual/en/using-erpnext/articles/renaming-documents
