### ISSUE TITLE
Routing Time Operation in Work orders miscalculation

### ISSUE THREAD

**Issue by Somberface** [frappe/erpnext#29764]
### Information about bug

Three bugs actually but all related:

1 - You put in an operation time of let's say 45 minutes for a batch of 10 Kgs in the Routing form.  When you make a work order for an item and you ask to make 10 Kgs and add the Routing, it puts the time at 4.5 minutes.  If you put 1 Kg to make, you got 0.45 minutes.  So the time has to be setup manually which is a pain.

2 - When you add a Sub-operation to an Operation, the cost of that sub-operation does not get calculated either in the BOM or the Work Order Costing section.  Only way around is to add that cost as an additional cost in the Work Order, which defeats the purpose of COGS calculation, operational costs and planning for the worker and Workstation.

3 - Trying to find a solution to the above point, I put in the sub-operation as a 2nd Operation in the Routing, all with defined batches of 10 kilos.  If I make a Work Order for an item for 30 Kilos it will produce 6 Job Cards.  Once the first Operation for the first batch of 10 Kgs is finished and submitted, I cannot start Operation 2 until all 3 batches of the first Operation are done.  That cannot be so as it should be batch per batch for both operation, i.e. Batch 1 Operation 1 then 2, batch 2 Operation 1 then 2, etc.

Thank You for your help.

### Module

manufacturing

### Version

Frappe version 13.19.0
ErpNext version 13.19.0

### Installation method

manual install

**Comment by Somberface** [comment]
Anyone ? Anyone ?

**Comment by Nihantra-Patel** [comment]
**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
