### ISSUE TITLE
Timesheets: Row with the same end time as another row with the same start time is seen as overlapping

### ISSUE THREAD

**Issue by vermeulendivan** [frappe/erpnext#29781]
### Information about bug

When a row in a timesheet has the same end time as the start time of another row, it is seen as overlapping and the timesheet cannot be saved. For instance, row 1 ends at 14:00 and row 2 starts at 14:00 - this results in an overlapping error, which is not the case (should not be an error) and this has not been an issue before. The only way to resolve this is to have the start time to be a second/minute later than the previous row's end time.
This were ONLY an issue in the same timesheet, whereas rows from other timesheets does not cause these overlapping issues. Also, this problem has ONLY been found with one timesheet, and other timesheets has no issues such as these with itself.

### Module

projects

### Version

Frappe version - v13.20.1
ERPnext version - v13.20.1

### Installation method

FrappeCloud

**Comment by gbm001** [comment]
Did this get fixed?

**Comment by gbm001** [comment]
I've found this is because get_time_overlap was comparing strings, and (for example) '2022-02-18 16:10:00.000000' is not equal to '2022-02-18 16:10:00'. I've patched around it by turning off the overlap detection in Project Settings and then adding a fixed version (that casts things to datetimes) in a validation hook for Timesheet.
