### ISSUE TITLE
bug: Production of Item with BOM batch operation doesn't produce a batch

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#30281]
### Information about bug

Create a BOM with an operation with batch size set to 5
Create Sales Order, Production Plan and Work Order for quantity 3

Result:
Job card is created for qty 3 along with 3/5 of the operation time.

Expected:
Job for batch of 5 with only costs set to 3/5

### Module

manufacturing

### Version

v13.19.0

**Comment by Nihantra-Patel** [comment]
Hi @nameduser0,

For example, if the quantity to manufacture is 100 in the work order and the work order has an operation cutting with batch size as 30 then the system will create four Job Cards for the operation ‘Cutting’ with sizes 30, 30, 30, and 10.

**BOM:**

![image](https://github.com/frappe/erpnext/assets/141945075/bd9ba37a-dfe2-4ad0-a537-3b9dbde2b24c)

**Sales Order:**

![image](https://github.com/frappe/erpnext/assets/141945075/cf5f3faf-6eaf-4d41-96e7-4071d10655c4)

**Production Plan:**

![image](https://github.com/frappe/erpnext/assets/141945075/c40be051-4dcc-4254-876b-961f15070efa)


**Work Order:**

![image](https://github.com/frappe/erpnext/assets/141945075/7bbd82b8-e8b0-42ab-a7eb-8bc34e8f36b8)

It will calculate the time based on the qty and according to the batch size. and it's worked properly according to the scenario in version 14.
 

If you have a solution for that then please contribute it and raise the Pull Request for the latest version of ERPNext because **We no longer provide support for version 13 or older.**


Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
