### ISSUE TITLE
Filters on web form list view are not working for customer's login. 

### ISSUE THREAD

**Issue by sujayjahagirdar256** [frappe/erpnext#30352]
### Information about bug

Filters on web form list view are not working for customer's login. 
Lets take there is a webform called “Order Processing” of Project Doctype ,  in which I want to filter the project based on the status . Even after selecting the status also the filters are not working . Same with other attributes. Apart from  project doctype , if filters are going to work for all other doctype also then it will awesome . 

![Web Form](https://user-images.githubusercontent.com/62817745/159445563-0e4dc0e0-448e-4515-925e-6e78a9e0e90e.png)

### Module

projects

### Version

ERPNext:v13.22.0 (version-13)
Frappe Framework:v13.22.0 (version-13)

### Installation method

manual install

**Comment by joshuarestivo** [comment]
I've run into this in v14, as well: 
get_webform_transaction_list
    filters.append((d.fieldname, "in", allowed_docs))
TypeError: 'NoneType' object is not callable

**Comment by Nihantra-Patel** [comment]
**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.

https://github.com/frappe/erpnext/assets/141945075/cd32304b-4f98-4df9-a7af-8cec429baf19


Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
