### ISSUE TITLE
Issue Updating Valuation Rate via Stock Reconciliation using Moving Average cost

### ISSUE THREAD

**Issue by guilmori** [frappe/erpnext#30424]
### Information about bug

Please have a look here:
https://discuss.erpnext.com/t/update-valuation-rate/87661

This seems a bug to me, I set ALL batches of item to 0.34, but the resulting valuation rate is 1.13.

I think the Stock Reconciliation should proceed all Outgoing transactions first (so they all use the actual valuation rate), then proceed with Incoming transactions.

### Module

stock

### Version

v13.23.0

### Installation method

manual install

**Comment by guilmori** [comment]
Can I have some answer ?

**Comment by guilmori** [comment]
Is there anyone who can help on how to update actual valuation rate ?

**Comment by guilmori** [comment]
More info:
https://discuss.erpnext.com/t/how-to-update-actual-valuation-rate/91106

Please tell me what is missing to get an answer here.

**Comment by guilmori** [comment]
Bump

**Comment by Nihantra-Patel** [comment]
**We no longer provide support for version 13 or older.**

Kindly upgrade to version 15, then refresh and check again because lots of bugs fixed in the new version.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
