### ISSUE TITLE
Company None not Found

### ISSUE THREAD

**Issue by jondayfoods** [frappe/erpnext#30481]
### Information about bug

When we click off of the home screen on the Desk View, the error "Company None not found" and "Company is Mandatory". We have several companies listed on ERPNext, and have been using it for years
<img width="1025" alt="Screen Shot 2022-03-29 at 8 09 59 AM" src="https://user-images.githubusercontent.com/33882770/160645121-d19439a6-90c9-435e-9a10-054099c4e802.png">
.

### Module

accounts, stock, buying, selling

### Version

ERPNext: v13.24.0 (version-13)

ERPNext Support: v0.2.1 (master)

Frappe Framework: v13.24.0 (version-13)

Journeys: v0.0.1 (version-12)

### Installation method

FrappeCloud

**Comment by nisarg5900** [comment]
Set default company in "Global Defaults". 
This may happen if u have deleted the default company created during startup. 
![image](https://user-images.githubusercontent.com/89855003/160929086-9f535d96-0027-41a3-9e8d-1b3b152d6181.png)

**Comment by jondayfoods** [comment]
> Set default company in "Global Defaults". This may happen if u have deleted the default company created during startup. ![image](https://user-images.githubusercontent.com/89855003/160929086-9f535d96-0027-41a3-9e8d-1b3b152d6181.png)

Thanks for the input. We have the Global Default settings correctly pointing to a current company. Unfortunately we are still experiencing that issue.

**Comment by nasirrr** [comment]
The issue is caused by the charts. Either you can remove the charts, or you would have to manually set it for each company everytime. 

On all the workspaces which contain chart like shown below, this error happens. 
![image](https://user-images.githubusercontent.com/93313345/160988456-8610c28b-2e7c-4d11-a444-d46da0a17f72.png)


Alternatively you can click here and set the company for the chart. (click on the filter icon, to set the company) Do note that you would have to do it manually for each chart!
![image](https://user-images.githubusercontent.com/93313345/160988728-a8518f75-e97b-48c5-980d-5fdb2e755524.png)

**Comment by jondayfoods** [comment]
> The issue is caused by the charts. Either you can remove the charts, or you would have to manually set it for each company everytime.
> 
> On all the workspaces which contain chart like shown below, this error happens. ![image](https://user-images.githubusercontent.com/93313345/160988456-8610c28b-2e7c-4d11-a444-d46da0a17f72.png)
> 
> Alternatively you can click here and set the company for the chart. (click on the filter icon, to set the company) Do note that you would have to do it manually for each chart! ![image](https://user-images.githubusercontent.com/93313345/160988728-a8518f75-e97b-48c5-980d-5fdb2e755524.png)

This solved our issue! Thank you very much, you have saved the sanity of our admin team.
