### ISSUE TITLE
bug: Work Order references should be Links not Data

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#30506]
### Information about bug

Several pieces of information are available at the bottom of the Work Order. However they are defined as `Data` field types and not `Link`.

NOTE However you get an error once the `Production Plan Item` is changed to link when creating the Work Order:
"Could not find Production Plan Item:  'new-production-plan-2' "

![Screen Shot 2022-03-30 at 22 47 15](https://user-images.githubusercontent.com/64409021/160936566-badec813-421f-4c19-a0e4-915917be052e.png)

![Screen Shot 2022-03-30 at 22 43 55](https://user-images.githubusercontent.com/64409021/160936391-32cdea6f-e8ff-4568-bbd8-c2c0f2384a4b.png)

### Module

manufacturing

### Version

v13.19.0

**Comment by marination** [comment]
As far as the value "new-production-plan-item.." goes, it's incorrect data via a bug that was fixed in https://github.com/frappe/erpnext/pull/30399 and https://github.com/frappe/erpnext/pull/30223

Frappe does not support (UI) child table links in documents afaik. So even making it a Link does nothing essentially, which is why it is kept as it is.

**Comment by nameduser0** [comment]
You're talking nonsense.
Why os the production_plan field a Link that works then?
Look up the bom_no field on Sales Order Item.
You should know your product better than me!

**Comment by ankush** [comment]
`bom_no` is not a child table link, it's a link to non-child doctype. 

If you can't discuss respectfully, please don't come here. We have warned you before also.
