### ISSUE TITLE
bug: Allow Zero Valuation Rate in Stock Entry Detail cannot be set with Source Warehouse

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#30533]
### Information about bug

Why does `Allow Zero Valuation Rate` read-only depend on *not* having a source warehouse?

https://github.com/frappe/erpnext/blob/8d16c7f44bde1fcdb6d09063d79d5f8a8439da1c/erpnext/stock/doctype/stock_entry_detail/stock_entry_detail.json#L349

### Module

manufacturing

### Version

v13.24.0

**Comment by ankush** [comment]
If you have a source warehouse that means item already exists and FIFO/LIFO/moving average rate has to apply. You can't force zero valuation in that case. If you do the inventory that's valued at some **X** amount will get consumed/transferred at 0 value and that will be adjusted for against stock adjustment account.

Is there any use case that breaks from this?

**Comment by casesolved-co-uk** [comment]
I disagree.

Having a source warehouse just means you have a source warehouse.

If you remove the warehouse, tick the box, then put the warehouse back, this breaks.

I would prefer to see this tick box moved to the Stock Settings for example. It would be useful if all of the costs in Stock and Manufacturing could be zero/omitted instead of enforcing items to have a value.

Sometimes customers just want to keep track of stock movements (use ERPNext as an MRP) and they do all their money accounting separately.

**Comment by ankush** [comment]
> If you remove the warehouse, tick the box, then put the warehouse back, this breaks.


https://github.com/frappe/erpnext/pull/29681/files#diff-9e1debdfe31c6b17eb5d333b8357db36224dd0d256416fb3be288ba404fdeca8R636

It works, but the checkbox isn't refreshed so it feels like it didn't work.

Even if you look at server code, this isn't really respected for the source warehouse. 

https://github.com/frappe/erpnext/blob/692c978cd97f3254d5e59c0873fe2ea970da1c92/erpnext/stock/doctype/stock_entry/stock_entry.py#L648-L650 


> Sometimes customers just want to keep track of stock movements (use ERPNext as an MRP) and they do all their money accounting separately.

We have this: if you disable perpetual inventory then accounting entries aren't made. 

Moving internally with non-zero value does NOT affect accounting entry anyway if both warehouses use same inventory account.
