### ISSUE TITLE
Price List Rate & Price Field with Discount Field Issue in submitted PO While updating Price.

### ISSUE THREAD

**Issue by pra17shant** [frappe/erpnext#30672]
**In my snapshot Created one PO and it's Submitted and the status will be "To Receive and Bill"**
hear as my issue is am raise PO with discounted PO but some are case i needs to be change discount after submitting (Please Note don't amend) on that time we need to be update PO.
But while Clicking on that button Price List Rate Not Available on that dialog Box.

![1](https://user-images.githubusercontent.com/99401472/162667040-5369a9f3-5202-4323-91ff-4e017a368da6.jpg)

**Update Button Click**
While Update Button Click there is no available item Price List Rate field for updating...
 it's too important while we working with discounted items.
![image](https://user-images.githubusercontent.com/99401472/162666455-ba0a9f31-0a77-4776-b9cc-d429b06a7b4e.png)

**Comment by marination** [comment]
@pra17shant Hi Prashant can you give us a real world scenario where discounts frequently change after submission?

**Comment by pra17shant** [comment]
Thanks for replaying @marination

- When you work with Price and discount it will manipulate the Price field according to the discount Field "which is not correct",

- Must you check out after submitting when I update the **"Rate"** using the **"Update Button"** it could be different to get an answer!

- (I suggest just including the "Price List Rate" field in the Item Update Button otherwise don't manipulate the value in the "Rate field" after applying the Discount)

Thank's in advance.

**Comment by pra17shant** [comment]
@marination any update

**Comment by marination** [comment]
@pra17shant 
> When you work with Price and discount it will manipulate the Price field according to the discount Field "which is not correct"

Before submission it manipulates the "Rate" field according to the discount which makes sense. It is applying a Pricing Rule configured by you. (the first time the item is fetched)
After submission, via **Update Items** popup, **it respects whatever rate you add** and adjusts discount accordingly (the opposite, because the discounts must make sense relative to the Price List Rate)

The **Price List Rate** is fetched from **Item Price** (where the rate is set against a buying/selling price list).

I do not see a reason to alter the Price List Rate (thats not done before submission either usually). Also we're avoiding adding more unnecessary fields to this pop-up. At this point it's already too many values that can be changed after submission.

> Must you check out after submitting when I update the "Rate" using the "Update Button" it could be different to get an answer!

Can you submit a GIF of this. Except discount i don't see anything major changing on updating **Rate** after submission

**Comment by marination** [comment]
inactive/inconclusive/invalid
