### ISSUE TITLE
"Rejected inventory" warehouse type

### ISSUE THREAD

**Issue by Alchez** [frappe/erpnext#30705]
### Information about bug

**Steps to Reproduce:**

1. Create a Purchase Receipt
2. Add a batched item
3. Set the received and rejected quantities to any value greater than zero, and the accepted quantity to zero
4. Submit the Purchase Receipt

**Expected Behaviour:**
- Either no batch is created, or an empty batch is created, or a stocked batch is created but a record of rejection is visible

**Actual Behaviour:**
- A stocked batch is created for the item with no record of rejection

### Module

stock, buying

### Version

Frappe version - v12.26.1
ERPNext version - v12.29.0

I couldn't find a fix for any of the later versions, so I'm guessing this exists for all versions.

### Installation method

manual install

**Comment by ankush** [comment]
This is expected behavior. The rationale is you asked for X items, of which Y was accepted and Z was rejected. You still received all of them (in two different warehouses). Hence batch gets created with rejected qty, you can return it or discard it (as per your process)



Currently, the stock ledger implementation has no way to differentiate between rejected stock and accepted stock, that's typically implemented by creating a warehouse for all rejected stock.

**Comment by Alchez** [comment]
That makes sense to me, but maybe we add checks or validations in the system that can help avoid accidental entries in other operations?

I see two possible options:
- Disable all rejected batches, which will prevent it from being used for any flow that doesn't end up flushing the stock out.
- Add a rejected warehouse type, and filter out stock from those warehouses in any documents.

**Comment by ankush** [comment]
> Add a rejected warehouse type, and filter out stock from those warehouses in any documents.

This seems like a good option. 

We already have warehouse-type field.  (only used for transit) We will probably have to keep this optional because someone out there is probably not using separate warehouses and will have to change their process 😄 

Something like this
Stock Setting -> stock validations tab -> allow receiving rejected stock in regular warehouses? 


By default, we should block the receipt of rejected stock in non-reject type warehouse.. 

cc @marination

**Comment by Alchez** [comment]
@ankush 

> Something like this?
> Stock Setting -> stock variations tab -> allow received rejected stock in regular warehouses?
>
> By default, we should block the receipt of rejected stock in non-reject type warehouse..

This sounds good to me. The setting can be patched and be checked for existing sites, but new sites would have it unchecked by default.
