### ISSUE TITLE
Mobile Safari on iOS: Cannot undo what is typed more than once

### ISSUE THREAD

**Issue by sahil48** [frappe/erpnext#30851]
### Information about bug

In Mobile Safari for iOS, if I am editing a text field, I cannot press the undo button more than once. The field I tested was the Subject Field in the Task Module

### Module

other

### Version

Frappe 13.27.0
ERPNext 13.27.1

### Installation method

FrappeCloud

**Comment by ankush** [comment]
This is browser-specific, we don't support Safari on iOS. 


Also, iOS safari can burn in hell: https://infrequently.org/2021/04/progress-delayed/

**Comment by sahil48** [comment]
What browsers does ERPNext support. Which ones would Frappe address browser-specific issues for?

**Comment by ankush** [comment]
We support Chrome and Firefox and derivatives (like Edge, Brave) on all platforms

Safari on MacOS also works fine. 

On iOS mobile all browsers are using same Safari engine because Apple doesn't allow other engines (check the link above.)

It's like supporting internet explorer now. You can express the concern to Apple, they should allow other properly functioning web engines to compete. 😄 


We don't officialy support != It doesn't work. It works but it will rough around the edges because of outdated browser engine.

**Comment by sahil48** [comment]
Okay, that makes sense. Thank you for the clarification. This bug seemed to fix itself in a recent update.

If there is one thing I do hope for, it is that in the upload attachments section, you allow built-in scanning functionalities of the Mobile OS to be accessible for easily add documents just processed into ERPNext Document. That would be a tremendous timesaver and great improvement over just allowing camera to be used for a single pic at a time. Aside from that, I am mostly happy with the Mobile Experience, even with the rough edges.
