### ISSUE TITLE
Payment overallocation against invoice

### ISSUE THREAD

**Issue by rtdany10** [frappe/erpnext#31138]
### Information about bug

Invoices can get over allocated and outstanding amount goes to negative. Attaching video for reference.

https://user-images.githubusercontent.com/52111700/170423673-cf6bf64f-5fd6-4cc7-8b80-4eddc3ff1bff.mp4

### Module

accounts

### Version

ERPNext: v13.30.0 (HEAD)
Frappe Framework: v13.29.1 (HEAD)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@rtdany10 @dj12djdjs Looks like this is desirable hence just a warning was added for this to notify the user rather than completely stopping them from making the payment entry

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/42651287/201659362-a6e8307c-eab6-4ffa-b1fb-02303116ef13.png">

PR link https://github.com/frappe/erpnext/pull/21501
