### ISSUE TITLE
Allow adding custom fields in POS

### ISSUE THREAD

**Issue by b3rew** [frappe/erpnext#3132]
UnLike any other forms pos view can not be customized like adding new fields
Thanks

**Comment by robertbecht** [comment]
yepp, should be more customizable

**Comment by robertbecht** [comment]
Believe that for the very large retail market the easy of use of the POS is a critical decision factor to use a system, or not.
Also shops are different. Specialized items properly coded or a supermarket with a scanner.
So the will be a need for customisation.

Some suggestions:
That could be added through customisation.

The reversed order of display: the last entered order is at the top, easy a quick check whther data is correctly entered. Now, with a long list of entries one works in the dark, since the entries are not visisble.
Customisation of the "selected item are and properties: number of columns (say 2,3,4,5 ) size of pictures, treatment of text (wrapped or truncated), fields displayed, numer of text lines under picture.
I have not yet properly tested but merging the item search and barcode fields as in 5.0 seems a very useful improvement!!
Check out field: which fields, default value, mandatory. Here eg I would prefer that the paid amount would automatically copy amount to be paid, but others may prefer the current setting. 
Some users may like a small numerical keypad
///
The treatment of discounts is, and always has been, one of the weaker properties of Erpnext, or I am running behind the facts and do something wrong.
I still do not see a recalculation of the VAT after discount. Strange, since this is a key issue in all markets where prices are always tax included, thus the whole EU.

I would like to see here a combination of the two ways to discount.
a) A tick next to discount field to enter either an absolute amount or a percentage.
b) under POS settings an account head where the discounts are recorded (like with the tax and charges)
c) an immediate recalculation of the taxes (VAT)
d) probably some users may like an second tick next the the discount field (apply on net (without tax price/rate)

Most likely other users have other suggestions. Ideally, different POS 's can be defined, where the suggestions can be set and enable, disabled.

Again, given the very large size of the POS market, a first rated POS may help ERPNEXT to become a success.

A similar discussion could be useful for the CART (webshop). Also here some minor improvements would increase the usage. At this moment, sorry to say so, our clients suffer wehen using the CART.

rgds robert

**Comment by system19** [comment]
I agree with @robertbecht . I think the market for ERPNext in small retail bricks and mortar shops is massive. As @robertbecht mentioned above I would also love to see:
a: The ability to have different views of the items/services. One view which is exactly the same as the current view. One view of rows with a small indicator icon (say 20x20px) on the left with the item info text on the right. Maybe a third view which allows for a tabbed view of sale/service item groups. For example a corner store might create a Food Tab, Phone/Internet Tab, Magazine Tab. This subgrouping would aid in the quick processing of POS sales. Restaurants use this layout a lot.

b: Sales Tax is vital for users in Australia and NZ as we well as we have GST which is exactly like VAT. 

c:  The ability to input sales via a cash register style keypad. This should be optional due to screen real estate space. It should by default be mapped to the numeric part of an external keyboard. It should come in two display sizes. One larger version for touch device's and a smaller one which is just for user visual reference when using an external keyboard. It would be good if when a number is typed in via the external keyboard that the matching numeric key on the Virtual POS highlights at the same time to show that data is being entered. I personally think you could could even charge for an advanced POS solution as an add-on. 

d: The most important new addition would be that a POS user can be created. The POS user can only see the POS View, Current Stock Levels-Location, Customer Name and Contact Details. They don't need to see anything else at all. Cash up at the end of the day can be done by a Sales Manager.

**Comment by rmehta** [comment]
Good ideas @system19 Let me see if I can implement some of them next week before I go on vacation :)

**Comment by system19** [comment]
@rmehta Thanks for the positive feedback. Enjoy your vacation, Getting v5 out the door must have been full on.

**Comment by robertbecht** [comment]
hi 

@System19  thanks for support. Maybe the crew in Mumbai should inventorize te views of the active POS users. Believe there are even supermarkets in West Africa using Erpnext. Also a look at a "leading POS" system could generate more ideas.

So many users so many whishes. This could be an acid test for customisation options and have a set of different configured POS's with differnt properties.

Customisation could be done by an extensive POS customisation screen, but alternatively a set of custom scripts could be developed that can be loaded by the user. Well leave this IT/.design considerations to our friends in Mumbai.

Finally, if one looks at dedicated POS systems, they do support a cash drawer. dedicated receipt printers and the like.

Just read in todays newspaper an article  about Ethiopia where even the smallest shops, bars, hairdresser etc are obliged to have an electronic cahs register to allow the governement to get there taxes. None compliance means a few years in jail. The market is enormous,

For such developing country  markets a POS module, that also works when Internet is down (off line), and allows the transfer of data once connectivity is back, would be an advantage!!


rgds robert

**Comment by system19** [comment]
@robertbecht following on our chat about POS. Agreed so many users so many wishes. So if at all possible they and keep features simple.
1: **Automated cash drawer's** and quality receipt printers like the EpsomTM series can be easily controlled via USB and can be called via web bowsers. One setup is to go computer USB OUT to Cash drawer USB IN. Then loop through Cash Drawer USB OUT to Printer USB IN. When printing a receipt the drawer automatically opens. So thats not a major problem. Other more complex configs are available.
2: **POS Tabs/Sub Groups** could be created automatically when adding a new item:
On the "add new item" page we could add a:
"Is a POS Product / Service" check box Yes / No. (Default =Yes)
If Yes is selected then a 
"Select POS Sub Group" field would become visible.
This would link to a newly added "POS Product Sub Group" feild in the POS Profile page.
The default Product Sub Group would be "Main".
In a ERPNext update the tabItems schema would get updated to hold the new POS tag and all existing items would get tagged as a POS Item listed under the Main sub category.

**Comment by peijiehu** [comment]
Good thoughts @system19 
I'm really interested in the POS setup in retail shop. Is `1: Automated cash drawer's` a standard scenario that people use a lot when using an ERP with POS software like ERPNext? If not, can you please share other popular approach that you are aware of, especially for setup that takes credit card payments? Thanks much!

**Comment by adam-je** [comment]
@peijiehu We sell POS as an entry point to ERP. Yes, over 95% of our clients need a cash drawer.

**Comment by deepeshgarg007** [comment]
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/42651287/198889895-1b50f74a-c718-40c3-a318-f6ffed7e8888.png">

@b3rew This is possible to do now in the latest POS using the POS settings. Just add the field you want and it will be shown in the POS UI

**Comment by dArc-K** [comment]
@deepeshgarg007 I set 2 custom field in the POS form remarks and terms, but it didn't show, is there any additional setup to make it show?

Btw am using Erpnext v15 and Bench v15 on frappecloud

Thanks & Regards,
Anto
