### ISSUE TITLE
Point Of Sales Not Allowing Selection of POS Profile

### ISSUE THREAD

**Issue by azeemanwar** [frappe/erpnext#31332]
### Information about bug

On Opening the Point of Sales Screen, system is asking to select the following:

1. Company
2. Profile
3. Default Mode of Payment

However, the filter applied for Profile is "Company = empty" and POS profile can't be created without Company as it's a mandatory field. Looks like you can't use Point of Sales Screen.

### Module

selling

### Version

Frappe Version: 13.22.2
ERPNext Version: 13.26.0

### Installation method

manual install

**Comment by dj12djdjs** [comment]
This should be caused by
https://github.com/frappe/erpnext/blob/d87dcb756bb921db3ad795a6ab27ab31686f4ef8/erpnext/selling/page/point_of_sale/pos_controller.js#L104-L107

The filter is set when the page initializes, and doesn't get modified if the `company` field changes. 

https://user-images.githubusercontent.com/29856401/173264282-27e3f8dc-5730-483f-b5d6-102bf50b84b5.mp4
