### ISSUE TITLE
Customer Group in Quotation can not be displayed

### ISSUE THREAD

**Issue by yingjiegau** [frappe/erpnext#31357]
### Information about bug

i noticed recently Customer Group in Selling Quotation Form can not be displayed after i have selected the Customer
Label: Customer Group
Type:Link
Name:customer_group

permission
Depends on seems OK 
eval:doc.quotaion_to=='Customer' && doc.party_name;
<img width="1042" alt="Screen Shot 2022-06-14 at 19 16 10" src="https://user-images.githubusercontent.com/66231137/173609657-173ade4e-0c9e-4337-8024-cefd0f7ac411.png">

### Module

selling

### Version

ERPNext: v13.33.0 (HEAD)
Frappe Framework: v13.32.1 (HEAD)

### Installation method

FrappeCloud

**Comment by dj12djdjs** [comment]
This is caused because `Hidden` is checked. According to:

https://github.com/frappe/frappe/blob/562499609c27c1b42a50b4197eef0f789ab3ecb2/frappe/public/js/frappe/form/controls/base_control.js#L50-L58

Since, `Hidden` checkbox is evaluated first, the `Display Depends On` field is ignored. Should be an easy fix just uncheck the `Hidden` option.

**Comment by nihantra** [comment]
Spelling mistakes in depend on condition eval:doc.**quotaion_to**=='Customer' && doc.party_name;
Set it like : eval:doc.**`quotation_to`**=='Customer' && doc.party_name;

See the Reference: #31362 

Thank You!
