### ISSUE TITLE
Customer Item can't save with stock --> item 

### ISSUE THREAD

**Issue by JasonFu06** [frappe/erpnext#31450]
### Information about bug

In the stock - item, when adding a customer item, when it is added to the 11th, there is an error in saving. The reason is that the sum of all customer item strings exceeds the length of 140.
![6024145](https://user-images.githubusercontent.com/93484850/175786526-c26f4ce7-b107-40bb-9425-4df2de217d67.png)

### Module

stock

### Version

Frappe Framework: v113.33.1
ERPNext: v13.34.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Value too big
Item W25Q64JVSSIQ: 'Customer Code' (TYWL.401.CK02.013,1059750 ,0110014200,101011142,A.01.08.03.293-01,JA.01.08.03.293-01,10401017900,91503000046,01.I.2000100,3110570033,01.16.01.256401) will get truncated, as max characters allowed is 140
```

**Comment by szufisher** [comment]
it is a bug caused by this new function

![image](https://user-images.githubusercontent.com/12823863/175822999-f4dba5b8-d2a9-4053-8c1a-e16fa56d012a.png)


quick fix, create one line server script for Item doctype before save event.

`doc.customer_code = doc.customer_code[:140]`

![image](https://user-images.githubusercontent.com/12823863/175822914-1b7f1b79-c80d-4a32-ac81-e70da8f600a5.png)

**Comment by ankush** [comment]
You can convert customer code fieldtype to "Small text" from customize form. (better fix than stripping values, if you do indeed routinely need to store longer codes)
