### ISSUE TITLE
Pricing rules Threshold for Suggestion doesn't work as expected

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#31483]
### Information about bug

Say you set a **Threshold for Suggestion** of 9,000.00
The expectation is the system will notify you at this stage? Is it?
All in all, the system notifies you regardless of amount on the transaction.

![image](https://user-images.githubusercontent.com/1822868/176460437-4f8f6ff8-c1ef-4892-96cb-7104a6d08064.png)

### Module

selling

### Version

ERPNext: v13.34.1 (HEAD)
Frappe Framework: v13.33.1 (HEAD)

### Installation method

FrappeCloud

**Comment by rohitwaghchaure** [comment]
@muchai The label here is confusing, you have to put value in the percentage. It seems that you have not set the value in percentage which causing the issue. We can't put actual value and using percentage because obviously for each item the min and max quantity could be different even though they comes under same **Item Group** 

We have fixed the label by adding extra characters like (In Percentage) [here](https://github.com/frappe/erpnext/pull/32238)

With proper percentage the suggestion feature is working fine
