### ISSUE TITLE
Errors from regional separation

### ISSUE THREAD

**Issue by nidhipurohit11** [frappe/erpnext#31532]
### Information about bug

Many accounting and selling scripts are breaking due to taxes.js file missing error. Also, many flows are not working like the quotation page is not getting loaded and throwing error - 

![image](https://user-images.githubusercontent.com/82337328/177685538-bce22a8a-60c7-4e81-9235-3996a7107ae1.png)

Getting the following error -
FileNotFoundError: [Error 2] No such file or directory: apps/erpnext/erpnext/regional/india/taxes.js

![Screenshot 2022-07-05 at 9 35 27 PM](https://user-images.githubusercontent.com/82337328/177373195-140d7e36-88e0-4d7d-8639-655b8d480503.png)

Ref run - https://dashboard.cypress.io/projects/da59y9/runs/3690/specs

### Module

accounts, selling, other

### Version

ERPNext: v14.x.x-develop () (develop)

Frappe Framework: v14.x.x-develop () (develop)

**Comment by ankush** [comment]
@deepeshgarg007 @sagarvora Item doctype also doesn't open because of missing GST code doctype


<img width="1301" alt="Screenshot 2022-07-07 at 2 23 58 PM" src="https://user-images.githubusercontent.com/9079960/177733540-85a45ead-4b73-4e07-9804-15ab871bb103.png">
 


Edit: I think it's because I have other company with India as country.

Anyway... HS codes can be part of default setup, they are largely standardized across countries AFAIK 😅

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/pull/31546

**Comment by sagarvora** [comment]
Existing test sites will fail, unless GST HSN Code is re-created I guess.

> Anyway... HS codes can be part of default setup, they are largely standardized across countries AFAIK
- They weren't so far (?)
- "GST HSN Code" additionally encompasses SAC codes designed and used only in India.

**Comment by sagarvora** [comment]
We could update the patch to "unlink" existing HSN Code fields. What do you think @deepeshgarg007 @ankush?

Or just remove them (without removing related DB column).
