### ISSUE TITLE
Forecasting in Manufacturing module

### ISSUE THREAD

**Issue by TripathiSK1967** [frappe/erpnext#31640]
### Information about bug

I observed errors in the results  of monthly forecast qty, for forecasting based on the sales orders. Results are not matching with manual calculations based on the  formula in the ERP Next documentation .

### Module

manufacturing

### Version

ERPNext: v13.0.0-beta.4

Frappe Framework: v13.0.0-beta.5

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Item ID	50000007-500 ML		
Item Name	Cow Milk-500 ML		
UOM	Nos	Nos	
Month	Actual Sale	Forecast (SF-0.3) by ERPNext	Forecast (SF- .3) As Calculated   using exp 
                                                         smoothing formula
Apr 2021	94764	106795	                         94764
May 2021	103900	74757	                         97505
Jun 2021	167777	52330	                         118586
Jul 2021	291264	36631	                         170390
Aug 2021	318568	25641	                         214843
Sep 2021	239092	17949	                         222118
Oct 2021	220916	12564	                         221757
Nov 2021	216408	8795	                         220153
Dec 2021	197992	6157	                         213504
Jan 2022	177392	4310	                         202671
Feb 2022	166972	3017	                         191961
Mar 2022	178884	2112	                         188038
Apr-22	136664	1478	172626
May-22			120838
Jun-22			84587
```

**Comment by TripathiSK1967** [comment]
In correct calculation by ERP.

**Comment by Nihantra-Patel** [comment]
**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.


Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
