### ISSUE TITLE
On Sales Invoice, Project link on Item is not working

### ISSUE THREAD

**Issue by michalls01** [frappe/erpnext#31837]
### Information about bug

**Sales invoice item project has to be the same as in the sales order header**

Business case:
Customer requests us to send 1 invoice for all projects at the end of each month.

Scenario:
I got customer with projects A and B. I created Sales Order for project A and another Sales order for project B. When I fetch SOs in the sales invoice and fill Project on Item (header project is blank) as per the SO, the invoice cannot be saved with error message "Incorrect value: Project must be = A" (project from 1st item). The only way we could make this work is if the proceeding sales order does not have a project filled (which is not correct).

Assumptions:
This works in case of incoming invoice where I can take multiple Purchase Orders from one supplier and separate items on multiple projects. In the chart of accounts ledger, the project of the voucher is taken from the 1st item, but then in the NET income analysis, the items are distributed correctly on the projects. I assume the same should work for Sales invoice as well, including proper Accounts ledger distribution.

### Module

accounts, selling, projects

### Version

13 / 14

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @michalls01,

Instead of adding the project in the sales order, just add it to each item in the sales order. This way, if you have multiple projects with the same customer, you can keep track of them separately at the item level. When you create the sales invoice, all items with their respective projects will be automatically included, reducing the chances of errors.

However, it's currently difficult to implement your scenario in erpnext because it's not set up to handle determining which project to include in the invoice at a given time. It's not practical to do this at the moment.

Thank You!

**Comment by michal-bee** [comment]
Hello @Nihantra-Patel,

Thank you for your reply! Unfortunately afaik there is no project link for the Item in the Sales Order (on the contrary this link is available in the Sales Invoice Item). So it is not possible to do it on the Item level from Sales Order currently.

**Comment by michal-bee** [comment]
@Nihantra-Patel Solution might be to extend the Item in Sales Order for the Project Link? Shall we post PR?

**Comment by Nihantra-Patel** [comment]
Hi @michal-bee,

I know the project field is not available in the Sales Order Item but available in the Sales Invoice, but you can create a custom field project in the Sales Order Item. When you create a Sales Invoice and Get the Sales Order data then project will automatically fetch without any coding. Try it.

I hope this helps.

Thank You!

**Comment by michal-bee** [comment]
@Nihantra-Patel Will do, thank you.
