### ISSUE TITLE
expense claims not creating 

### ISSUE THREAD

**Issue by AMNdungu** [frappe/erpnext#32105]
### Information about bug

error message  "Expense Claim HR-EXP-2022-03313 already exists"
When users create a new expense claim that error message emerges, we tried cancelling the claim referred to but the problem persists

### Module

HR

### Version

ERPNext: v13.21.0 (version-13)

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@AMNdungu Looks like your naming series is messed up, the system is trying to create new expense claims from an existing counter. Please fix your naming series, this looks like a data issue rather than a bug. For help refer 

https://docs.erpnext.com/docs/v13/user/manual/en/setting-up/settings/naming-series#3-updating-the-current-value-for-existing-naming-series

**Comment by AMNdungu** [comment]
My appreciation

Andrew M. Ndungu
