### ISSUE TITLE
CRM (V14) Error/bug Customer Group and Default Price List (Opportunity) Trasfer to Quotation

### ISSUE THREAD

**Issue by aei-gt** [frappe/erpnext#32108]
### Information about bug

i have a problem when in a Opportunity when try to create a Quotation and the client have a Default Price List assigned because always assign the ‘Standard sales price list’. This is a bug/error? because the users never can change price list assigned to a client and erpnext use always standard price list.  how resolve this problem. If add items in opportunity again show the Standar price list and not the client price list asigned. 
Aditional not show prices in Opportunity if add items.

![image](https://user-images.githubusercontent.com/111803510/188715851-b0a17795-96f6-4038-be10-2a3c7880077d.png)

![image](https://user-images.githubusercontent.com/111803510/188716034-6a3ccdd9-f013-4af1-aac1-64603eaba87f.png)

![image](https://user-images.githubusercontent.com/111803510/188716198-d64627d2-1893-4c65-b1ef-853934b9fc55.png)

![image](https://user-images.githubusercontent.com/111803510/188716450-c065567f-288d-4817-9cdb-07f0076afd04.png)

### Module

CRM

### Version

Frappe v14.5.0
ERPNext v14.0.3 

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @aei-gt,

By default, ERPNext doesn't include price lists in opportunities, and the default rule for item price lists isn't applied and as of now feature is not developed yet. However, if you want to include price lists in opportunities, you need to create a custom field called "Selling Price List."

Fetching an Item Price from the Price List In Opportunity.

When you select/change the price list then automatically update all item prices in the table.
**client script**
```js
frappe.ui.form.on('Opportunity', {
    selling_price_list: function(frm) {
        frm.doc.items.forEach(function(item) {
            var childDoc = locals['Opportunity Item'][item.name];
            get_rate(frm, childDoc);
        });
    }
});

frappe.ui.form.on('Opportunity Item', {
    item_code: function(frm, cdt, cdn) {
        var item = frappe.get_doc(cdt, cdn);
        get_rate(frm, item);
    }
});

function get_rate(frm, item) {
    var price_list = frm.doc.selling_price_list; // Get the selected price list from the Opportunity DocType
    var item_code = item.item_code;

    frappe.call({
        method: 'frappe.client.get_value',
        args: {
            doctype: 'Item Price',
            filters: {
                item_code: item_code,
                price_list: price_list
            },
            fieldname: 'price_list_rate'
        },
        callback: function(response) {
            if (response && response.message) {
                frappe.model.set_value(item.doctype, item.name, 'rate', response.message.price_list_rate);
            }
        }
    });
}
```

Reference: https://discuss.frappe.io/t/fetching-item-prices-in-opportunity/105513/2?u=ncp

We initially utilized "price_list" in a custom field, but we recommend switching to "selling_price_list". This change is beneficial because when you generate a quotation from an opportunity, the item rate and price list are automatically fetched without requiring any additional code.

I hope this helps.

Thank You!
