### ISSUE TITLE
I can't rename Report

### ISSUE THREAD

**Issue by GoldenScrew** [frappe/erpnext#32116]
### Information about bug

In menu of Report doesn't exist possibility to rename Report.
But in List view of Reports you can edit Report Name.
But when you do it nothing changes.
![QIP Shot - Screen 252](https://user-images.githubusercontent.com/3992823/188857159-9192cd2f-b9d2-4807-be4d-5f39b33fcb07.png)

### Module

stock

### Version

ERPNext: v13.35.0 (version-13)
Frappe Framework: v13.35.0 (version-13)

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell
Updated successfully
```

**Comment by dj12djdjs** [comment]
Renaming from List View isn't supported. You must open the record and rename it there.

If you have multiple documents to rename use the https://docs.erpnext.com/docs/v13/user/manual/en/using-erpnext/articles/bulk-rename

**Comment by GoldenScrew** [comment]
> You must open the record and rename it there.
Like I said before I can't to do it. Not possible.
![QIP Shot - Screen 266](https://user-images.githubusercontent.com/3992823/192154131-f48d52d6-e200-48f4-8091-1eff3a33c500.png)

**Comment by dj12djdjs** [comment]
Some doctypes aren't allowed to be renamed by design, you can check this in the doctype definition.
Here you can see report doctype Allow Rename is un-checked.
![image](https://user-images.githubusercontent.com/29856401/192315922-a949c6ef-cd95-4f8a-9f8d-1bc82d489b4f.png)

This means the only way to "Rename" these reports is to create a new report with the desired name. Then ether disable or delete the old report.

I believe the reasoning report doctype is not allowed to be renamed is because it interacts with the file system and renaming the report could result in un-intended behavior.
