### ISSUE TITLE
Cost Center under Subcscription not changing if we select a new one. Always goes back to default one.

### ISSUE THREAD

**Issue by Vaybl** [frappe/erpnext#32125]
### Information about bug

Cost Center under Subcscription not changing if we select a new one. Always goes back to default one. We want to have different cost centers for each client, so that we can follow individually costs for each one of them.

### Module

accounts, selling

### Version

Frappe Framework: v13.33.1 (version-13)
ERPNext: v13.34.1 (version-13)

**Comment by sebastiano-riva** [comment]
Any news on this? Thanks

**Comment by Nihantra-Patel** [comment]
**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.


https://github.com/frappe/erpnext/assets/141945075/177ad66a-c9df-45e9-afb7-96e373930835


Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
