### ISSUE TITLE
Rename payment mode and other

### ISSUE THREAD

**Issue by latoile** [frappe/erpnext#32593]
### Information about bug

Hello, 

I am trying to rename a payment method, for example. 
As soon as I click for example on cash and I would like to rename it to cashs, I have this error message that appears.

![image](https://user-images.githubusercontent.com/24554787/195559947-f182a8a4-a985-4688-8439-d5b21f58f482.png)

### Module

accounts

### Version

ERPNext: v14.3.0 (version-14)
Frappe Framework: v14.11.1 (version-14)

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@latoile This is not an error but a notification message, since renames could take up sometime based on the no of records they are linked to and might time out after a certain time from v14 onwards we have started doing renaming by background jobs, this message is to notify you that your job has been queued
