### ISSUE TITLE
item quantity in sales invoice should be default 1 ( like it used to be)

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#3309]

**Comment by nabinhait** [comment]
Fixed, will be released on Monday.

**Comment by adityaduggal** [comment]
Well would have loved to see the default quantity at 1 only and there should have been a way to not allow ZERO qty in Sales invoice. This ways one can ensure that the user is not missing entering the quantity otherwise with default set at 1 there are chances that the user just might forget to enter the quantity and then submit the invoice.
