### ISSUE TITLE
Add charges based on net weight in Landed Cost Voucher

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#3321]
A way to calculate the total weight of shipment (By adding all the net weights of the items in a Purchase Receipt).  Then the charge in Landed Cost Voucher is proportianally shared among the weights of the shipment.  
For instance.  
Apples for 250 boxes (net weight is 20Kg) @ 10$
Oranges for 200 boxes (net weight is 15Kg) @ 8$
Grapes for 180 boxes (net weight is 5 Kg) @20$
Transport cost is let's say 1500$.  (so this is 1500$ to be shared for 8900 Kg, or 0.1685$ per Kg)
So the charges added are
20*0.1685$ per box of apple
15 * 0.1685$ per box of oranges
5 * 0.1685$ per box of grapes.  

Does this make sense?

Cheers

**Comment by nabinhait** [comment]
Here Default/Stock UOM for all the items is same i.e. Kg. But, there might be some items with different default/stock UOM, in that case it will not work. Any way, there is an option to distribute landed cost charges based on qty and amount.

**Comment by fderyckel** [comment]
Hi Nabin,
I understand the options about quantity and amount.  Unfortunately, for most full loads with mixed items in them, you don't share the transport costs by amount (some items might be very light and expensive) or quantity (in case you have 5 heavy things and 1000 light things in your load.), Instead, one will use weight!

I was not talking about the default UOM for item.  In item, you have a whole section on Inventory, there there is the field Nett Weight.  Why can't we use that field as long as all the UOM for Net Weight are the same.  

![screen shot 2015-05-26 at 10 46 08](https://cloud.githubusercontent.com/assets/7240992/7808592/b1cca4ae-0394-11e5-81f6-195f0213edb7.png)

**Comment by ai-erp** [comment]
@fderyckel i agree with you... I think it is better if there is an option for weight as the basis of allocating additional cost on LCV. It is because usually, shipping cost were calculated based on weight of the shipment and not on quantity or amount. The amount option will only be applicable in allocating customs duty but not for freight. Another suggestion is that we can add more column for Weight in the LCV which can be manually encoded upon making entry of LCV.
[LANDED COST.xlsx](https://github.com/frappe/erpnext/files/170476/LANDED.COST.xlsx)
[Doc1.pdf](https://github.com/frappe/erpnext/files/170477/Doc1.pdf)

**Comment by admin627863** [comment]
![image](https://github.com/frappe/erpnext/assets/22075543/ad992883-cca0-459a-adec-9d1c992b9101)


We will do that this way!!
