### ISSUE TITLE
In the report "Sales Order Analysis" Delivered Qty is not updated for the Non Maintain Stock Item after the Sales Invoice is created

### ISSUE THREAD

**Issue by AravindPranera** [frappe/erpnext#33425]
### Information about bug

In the report "Sales Order Analysis" Delivered Qty is to be updated for the Non Maintain Stock Item too after the Sales Invoice is created

### Module

selling

### Version

ERPNext Version 13

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @AravindPranera,

**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.
If the issue occurs then please create a new issue according to the latest version (14 or 15) with a video document if possible.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
