### ISSUE TITLE
No delete action for blog post

### ISSUE THREAD

**Issue by betabank** [frappe/erpnext#3347]
We are on v5.0.9 and there is no option to delete a post from the blog, only unpublish.

By the way, "Page Name" should be on top, somewhere near the title, maybe even with the label "Page Name (URL)".

**Comment by anandpdoshi** [comment]
You can add Delete rights via Permission Manager. Most people don't want to
delete posts, just unpublish them.

Page Name ideally should be derived from the title and hence it is moved at
the bottom so that only users who need it bother to access it. You can move
it to the top if you want via Customize Form.
