### ISSUE TITLE
Pricing Rule wrongly applied at Purchase

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#33520]
### Information about bug

Setup Pricing Rule for Selling
Per Transactions Amount > 100,000 will get 2% discount
![image](https://user-images.githubusercontent.com/62122640/210361770-5269016d-085c-415d-800a-85f64ebbd177.png)

Account Settings
![image](https://user-images.githubusercontent.com/62122640/210361860-b491bf52-12af-4e38-8d34-5e7bb0e4d0ed.png)

Purchase Invoice
even I had Clicked "Ignore Pricing", discount still applied
![image](https://user-images.githubusercontent.com/62122640/210362046-02b65d3c-06f2-4fb8-813e-2f1ec79edc82.png)
![image](https://user-images.githubusercontent.com/62122640/210362111-d037015c-69fe-4f92-91d0-48c7374354c9.png)

However, when I made purchase system applied 2% discount wrongly

### Module

buying

### Version

ERPNext : [v13.42.7]

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @thida-bcn,

We no longer provide support for version 13 or older.

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
