### ISSUE TITLE
Loyalty Point Calculation is not Correct

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#33550]
### Information about bug

Setup Loyalty Program with Mulit Tier
Min Spend 100,000 will get 1 point per 1000 spending
Min Spend 300,000 will get 1 point per 900 spending
![image](https://user-images.githubusercontent.com/62122640/210759600-b1c486f5-5a4a-4b19-a6fe-d220583d19c2.png)

Expected 
When voucher Amount is 196,000, point should be 196
Now system calculated as 217
![image](https://user-images.githubusercontent.com/62122640/210759966-03638976-5c55-4a1c-8aec-1ce9f6851d0b.png)
![image](https://user-images.githubusercontent.com/62122640/210760053-e32ba0c2-af90-4b42-a8fe-500152e95326.png)

When Voucher Amount is 20000, expected point should be 0
![image](https://user-images.githubusercontent.com/62122640/210760565-f46ae583-d8c2-4cc9-acd9-11d98eb8ecbe.png)

### Module

selling, other

### Version

ERPNext : [13.43.0]
Retail

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @thida-bcn,

Because the G2 tier applied in your case. calculation like

points_earned = cint(eligible_amount / collection_factor)
points_earned = 196000/900
points_earned = 217.77

If G1 is applied then the point will be 196.

Please check the method:

https://github.com/frappe/erpnext/blob/version-14/erpnext/accounts/doctype/sales_invoice/sales_invoice.py#L1548-L1586

Thank You!
