### ISSUE TITLE
ERPNext v13 subscription raising sales invoice every hour instead of monthly set parameter

### ISSUE THREAD

**Issue by showlinepos** [frappe/erpnext#33556]
### Information about bug

calculating subscription every hour instead of month .l have 900 subscription that have been running well on monthly basis they were supposed to expire on the 31st of December 2022 but l didn't not check on cancel subscription on end date so it means they will just continue , so they continued but soon after they get into January 2023 its raising invoice very hour however for others that are expiring in 2024 they are doing well

### Module

selling

### Version

ERPNext: v13.35.2 (version-13)

Frappe Framework: v13.35.1 (version-13)

### Installation method

manual install

**Comment by jeremy-ftl** [comment]
Same exact issue except docker installation.

**Comment by showlinepos** [comment]
but l have seen it in another post , it was said the issue was resolved in other latest versions so now l need to upgrade from 13 to 14

**Comment by Nihantra-Patel** [comment]
**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
