### ISSUE TITLE
Payment Entry base total allocated amount rounding issue

### ISSUE THREAD

**Issue by tritchot-sga** [frappe/erpnext#33681]
### Information about bug

When entering multiple payments on a payment entry where the currency of the payment is not the default currency, the total allocated amount (in the default currency) may not match the paid amount (in the default currency). This appears to be the result of calculating the rounded total of each payment reference and adding them together, rather than adding all the payment references together, then rounding the total. This results in a 1 cent remainder when calculating the difference amount.

In the example below:
ROUND(1357.13 * 1.35, 2) + ROUND(1357.13 * 1.35, 2) + ROUND(2714.25 * 1.35, 2) = 7328.50
ROUND((1357.13 * 1.35) + (1357.13 * 1.35) + (2714.25 * 1.35), 2) = 7328.49

![image](https://user-images.githubusercontent.com/119268744/212712607-1e2e9b30-7b94-48c8-8225-1f2621574ce0.png)

### Module

accounts

### Version

ERPNext: v13.34.1 (development)
Frappe Framework: v13.33.1 (development)

### Installation method

manual install

**Comment by felixlu07** [comment]
I'm having this issue in my client's sites as well. Purchase Invoice is 1226.82 for both credit AP and debit cost. But in the offsetting entry after payment entry was done, the debit entry to clear off the AP became 1226.81, leaving an unaccounted 0.01.

I may be wrong. When I took a look at the codes, I think there could be a bit of a discrepancy in the way FX loss is being calculated in the Payment Entry doctype. Assuming a scenario where we are dealing with a foreign currency purchase invoice, the eventual total base_amount of that invoice, may not be simply the invoice's conversion_rate multiplied by the invoice total, that is in a foreign currency.

E.g. Purchase invoice has an exchange rate of 4.811, and a total of 255 USD that is made up of multiple line items. On the UI of the purchase invoice, the base total is stated as 1226.82. Mathematically, if we take 255 USD * 4.811, we are not going to get 1226.82. We would get 1226.805 instead. What I'm trying to state here is that; the method of getting the total base_amount for the entire invoice is actually a culmination of item level calculations between the item rate (in the foreign currency) and multiplied with the document currency. Thereby if the document currency is 4.811, the effective exchange rate (aka conversion_rate), is in actuality something more like 4.811059 instead due to some rounding happening at the line level.

This leads us to the next point in how payment entry calculates FX loss. 

In the `calculate_base_allocated_amount_for_reference` function under payment_entry.py, under the lines `			allocated_amount_in_pe_exchange_rate = flt(
				flt(d.allocated_amount) * flt(d.exchange_rate), self.precision("base_paid_amount")
			)`, we see that 	`allocated_amount_in_pe_exchange_rate` is calculated using the exchange_rate of the document d.

`allocated_amount_in_pe_exchange_rate` 's objective is to get the value of the document in base currency, based on the conversion rate. And in reality, since the purchase invoice has an effective fx rate of 4.811059 instead of the 4.811 that is stored as the conversion_rate, with the above function, we end up having a slightly larger FX loss, which leads to this 0.01 difference.

**Comment by Nihantra-Patel** [comment]
**We no longer provide support for version 13 or older.**

Kindly upgrade to version 15.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
