### ISSUE TITLE
Point of Sale glitches when default customer is set on POS profile.

### ISSUE THREAD

**Issue by kcrtr** [frappe/erpnext#33727]
### Information about bug

After selecting items (at least one) and then selecting checkout, the item count is infinitely incremented (it only stops when the count exceeds the stock available. The best way I can explain this is with the video below:

https://user-images.githubusercontent.com/75222674/213315982-1bf8eb54-49b7-4807-b6f5-82c45c1c8835.mp4

### Module

other

### Version

ERPNext: v14.13.0 (version-14)
Frappe Framework: v14.23.0 (version-14)

### Installation method

manual install

**Comment by corestats** [comment]
Hey @kcrtr was there a fix for this?

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs have been fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.

https://github.com/frappe/erpnext/assets/141945075/f69b7214-d147-43ce-89a0-b0722d6ae05f
