### ISSUE TITLE
Item taxes from item tax template are not applied when updating items

### ISSUE THREAD

**Issue by uepselon** [frappe/erpnext#33737]
### Information about bug

PR for fix: https://github.com/frappe/erpnext/pull/33738

**Summary**
When taxes are applied via Item Tax Template on Item Group level, taxes are not applied when an item is added via Update Items functionality at Sales & Purchase Orders.

We have the following setup for taxes in our system:
1. Item Tax Template with a specified tax of 19 %
2. We reference this template in the item group Services

<img width="1252" alt="Bildschirm­foto 2023-01-19 um 17 05 01" src="https://user-images.githubusercontent.com/49870752/213493975-50f29f28-93d2-459d-b791-f9ffac0a20f0.png">
 
<img width="1250" alt="Bildschirm­foto 2023-01-19 um 17 05 59" src="https://user-images.githubusercontent.com/49870752/213494029-03ca3a22-16de-49ab-b539-fc2ddd6eda71.png">

Steps to reproduce the issue:
1. Setup the taxes as described above
2. Create a new Sales Order with an Item which is part of Item Group Services
4. Taxes will be shown, if you look at the item details (e.g. via console), you will see that an Item Tax Template is referenced
5. Submit the Sales Order
6. Add an additional item (can be the same as above) with the same Item Group (Services) in the Update Items dialog
7. The Item Tax Template is not applied for this item

<img width="1274" alt="Bildschirm­foto 2023-01-19 um 17 10 16" src="https://user-images.githubusercontent.com/49870752/213494103-22e717e6-2ce2-444a-bde0-e9ed70421234.png">

### Module

selling

### Version

Frappe 13.47.1
ERPNext 13.43.2

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @uepselon,

It's hard to manage the Item Tax Template when updating an item. Also, the design of the "Update Item" button needs improvement for quicker and smoother entry without canceling transactions. Sometimes it doesn't handle everything properly, but it does calculate when updating the quantity or rate of an existing item. I'm aware that you've submitted a pull request for version 13. **We no longer provide support for version 13 or older.**

If you understand the problem and the changes Deepesh mentioned in your pull request (PR), you can submit the PR again for the latest version (either Develop or 15). If everything is okay and it works well without any problems, they will accept it. However, please note that we have closed the issue because we no longer offer support for version 13 or older.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
