### ISSUE TITLE
Incorrect proposed total time in capacity planning

### ISSUE THREAD

**Issue by LukasBCG** [frappe/erpnext#33819]
### Information about bug

A production time is set in the BOM for each item and operation. 

**Example: Operation XY with 10 min per item.** 
If the number 10 is to be produced, the planned time should be 100 min.

The actual planned times are not correct. See screenshots. In this example, only 30 min are planned.

![Zeichenfläche 1](https://user-images.githubusercontent.com/103038727/214645910-276d1c80-312d-4ede-8c37-6a51b6b749e3.jpg)

### Module

manufacturing

### Version

ERPnext V14

### Installation method

None

**Comment by s-aga-r** [comment]
@LukasBCG unable to replicate, please provide the steps.

**Comment by s-aga-r** [comment]
@LukasBCG please provide steps to replicate.

**Comment by s-aga-r** [comment]
@LukasBCG The issue is not replicable. Please provide the steps to replicate it and reopen the issue.

BOM Items
![image](https://github.com/frappe/erpnext/assets/63660334/c242e0cf-15ba-4235-96b4-9dbb80a73efe)

BOM Operations
![image](https://github.com/frappe/erpnext/assets/63660334/ba2a5a78-c387-45cd-bb5b-8970e4532ce9)

WO Qty and Required Items
![image](https://github.com/frappe/erpnext/assets/63660334/4758959a-65c6-4add-a7da-580310d982b0)

WO Operations
![image](https://github.com/frappe/erpnext/assets/63660334/6dc3389d-b5d7-4beb-a8cb-864bf903381c)

Auto Created Job Card
![image](https://github.com/frappe/erpnext/assets/63660334/83c157b7-9a9a-4489-aaef-f61ce1934aaf)

**Comment by LukasBCG** [comment]
Hi @s-aga-r 
Thanks for your feedback. The error occurs when an item with batch production is used. In a batch 10 pieces are produced, but 20 pieces were ordered. Then the calculated time is not correct. Can you check this?
