### ISSUE TITLE
Delete Sales Order Item bug

### ISSUE THREAD

**Issue by badrbin** [frappe/erpnext#33973]
### Information about bug

We have been made sales order with our customer and need to delete some items but permission associated with sales order permission and that really dangerous. It means  should give him delete sales order permission for delation. Is there any way to give him permission to update items seprately
• sales order Item permission.png

### Module

selling

### Version

Frappe: 14.24
Erpnext: 14.14

### Installation method

FrappeCloud

**Comment by skygunner** [comment]
That's more like a feature request not bug. Also did you read what you've submitted after you wrote those? The image doesn't even posted

**Comment by badrbin** [comment]
I am sorry, I will attach the pictures. 
It not a feature, 
In V13 erpnext working perfectly and you can delete items. 
But in V14 erpnext you have delete sales order permission and can delete items and sales order. 
![image](https://user-images.githubusercontent.com/124630341/217146799-53a653ed-efed-4a44-9507-ffa1a760b3c7.jpeg)
I will delete the first item 
![image](https://user-images.githubusercontent.com/124630341/217146863-91bf186a-85c7-44a7-b196-018939ed97f5.jpeg)
I can't delete it because I don't have delete sales order permission, if give my employee that permission maybe delete sales order contract by fault.

**Comment by skygunner** [comment]
I see. V14 still has lots of bugs, better wait for longer time before trying to use it for production

**Comment by badrbin** [comment]
How can I contact with developer to solve my issue?

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

The system is designed to consider the client's perspective. If a user does not have deletion rights for a sales order, and they try to delete an item from the 'Update Items' section, they will not be able to do so. This is a useful functionality because if there were no validation, anyone could delete the item and cause issues. Please watch the video for further clarification.


https://github.com/frappe/erpnext/assets/141945075/49133489-5f03-402c-9268-e44e2e1903b3

Thank You!
