### ISSUE TITLE
skip_setup_wizard set to 1 not working

### ISSUE THREAD

**Issue by chrisdent** [frappe/erpnext#34365]
### Information about bug

adding skip_setup_wizard set to 1 in site_config.json for a new site is not working.

The wizard still appears.

### Module

other

### Version

ERPNext: v14.11.0 (version-14)
Frappe Framework: v14.20.0 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
n/a
```

**Comment by dj12djdjs** [comment]
@chrisdent This flag only has effect after the app is installed on the site. Because it's frappe, you cannot set this flag before the app get's installed because the site_config.json file doesn't exist yet.

To get around this do, you must run `bench reinstall` after setting `skip_setup_wizard` for it to take effect.
