### ISSUE TITLE
New Project - On Monitor Progress 

### ISSUE THREAD

**Issue by tjomtek** [frappe/erpnext#34386]
### Information about bug

Created a new project , populated fields as required , under "monitor progress" collect progress enabled. Select "hourly" from 09:00am to 15:00pm , the system notifies every hour irrespective of "from" - "to" times. After 12:01am there is flurry of emails from the system.
As seen in attached ...

![Screenshot 2023-03-10 at 00 25 48](https://user-images.githubusercontent.com/77873407/224174360-869e6510-44fb-436a-9bb3-07efe5762200.png)

### Module

projects

### Version

ERPNext: v13.47.0 (version-13)
Frappe Framework: v13.49.3 (version-13)

### Installation method

None

**Comment by dj12djdjs** [comment]
Hi @tjomtek 

Just want to make sure before I dig into this, is your server time set same as your local time?

**Comment by tjomtek** [comment]
sorry @dj12djdjs only reading this now , yes both server and app times are in sync.

**Comment by Nihantra-Patel** [comment]
**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
