### ISSUE TITLE
Functional Error in Production Planning

### ISSUE THREAD

**Issue by knaveenhyperbaric** [frappe/erpnext#34629]
### Information about bug

Hi
Please find the attached video showing the "ProductionPlanning report"
We have added Item [[TK]-SA-DC ACCESSORY BOARD ASSY- ECU PER SET in materail Request - Qty - 2 Nos.](https://teknamfg.frappe.cloud/app/item/%5BTK%5D-SA-DC%20ACCESSORY%20BOARD%20ASSY-%20ECU%20PER%20SET)
and generated production planning report for Material Request MAT-MR-2023-00002-4
Some of the items in [[TK]-SA-DC ACCESSORY BOARD ASSY- ECU PER SET is doubled in Production planning report and the required qty is showing wrongly,] 

https://user-images.githubusercontent.com/117721538/228462021-119cd028-5745-4525-baf5-025cd93785e3.mp4

(https://teknamfg.frappe.cloud/app/item/%5BTK%5D-SA-DC%20ACCESSORY%20BOARD%20ASSY-%20ECU%20PER%20SET)

### Module

manufacturing

### Version

Installed Apps
ERPNext: v14.17.0 (HEAD)

Frappe Framework: v14.26.0 (HEAD)

Frappe HR: v14.0.3 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
https://teknamfg.frappe.cloud/app/query-report/Production%20Planning%20Report?company=TEKNA%20MANUFACTURING%20PVT%20LTD-FY-2022-2023&based_on=Material%20Request&docnames=%5B%22MAT-MR-2023-00002-4%22%5D&raw_material_warehouse=TEK-MR-22-002%20-%20TM(P)L&order_by=Required%20Date
```

**Comment by knaveenhyperbaric** [comment]
Hi
Can anyone help us with the above issue?

**Comment by Nihantra-Patel** [comment]
We created this under various scenarios, so the issue wasn't identified. If multiple instances occur, please review the sales order item. This is because if a sales order includes multiple finished items, they may be displayed twice in relation to production.

![image](https://github.com/frappe/erpnext/assets/141945075/635b019d-4cd3-474c-a67b-05936dbf17ac)

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.
