### ISSUE TITLE
Stock summary report shows incorrect bar chart. It creates bar scale for each page and more button creates new scale of bar 

### ISSUE THREAD

**Issue by liyakatalilal** [frappe/erpnext#34721]
### Information about bug

The stock summary report shows inventory and its corresponding bar chart to represent it graphically. The scale of the bar is considered for a single page loaded and when the More button is pressed it does not readjust the bar with all the items shown on the screen, instead, the bar graphs for the new page loaded restart with its new list.

![Stock summary](https://user-images.githubusercontent.com/31281816/229499962-954c740e-299c-423d-953c-6b3e51525805.gif)

### Module

stock

### Version

ERPNext: v14.20.0 (version-14)
Frappe Framework: v14.30.0 (version-14)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @lalnco,

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.
If the issue occurs then please create a new issue according to the latest version (14 or 15) with a video document if possible.

Thank You!
