### ISSUE TITLE
Cannot rename company in erpnext

### ISSUE THREAD

**Issue by Rajinder122** [frappe/erpnext#34907]
### Information about bug

Cannot able to rename company 

It got stuck in between and the name does not get changed ?

Kindly please provide a solution to this problem asap ?

Is it due to lot of transactions against that company ?

![image](https://user-images.githubusercontent.com/127853260/232747168-5a1e40c1-4526-4b39-b160-91b8bec60b32.png)

### Module

accounts

### Version

ERPNext: v13.25.1 (version-13)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @Rajinder122,

Kindly upgrade to version 14 or 15, then refresh and check again. Sometimes it will take time because of lots of transaction.

https://github.com/frappe/erpnext/assets/141945075/ad25e2cc-93f4-49db-8260-0cee8021e76d

We no longer provide support for version 13 or older. 

Everything is working fine. No problems were encountered in versions 14 and 15.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
