### ISSUE TITLE
Period Closing Trial Balance Figures Do Not Tally With Period Opening Trial Balance Figures

### ISSUE THREAD

**Issue by THEOSKaris** [frappe/erpnext#34933]
### Information about bug

The Trial Balance report is having issues. Here are examples we cannot explain:

2020 Fiscal Year: Suspense Account has closing balance **N2,994,204.22 Debit**
![image](https://user-images.githubusercontent.com/67414153/233150191-126255f2-0b7d-4150-a460-91962d785f82.png)

2021 Fiscal Year: Instead of opening balance of **N2,994,204.22 Debit**, Suspense Account shows credit balance of **N38,820,692.68**
2021 Fiscal Year: Suspense Account has closing balance **N16,698,926.98 Debit**.
![image](https://user-images.githubusercontent.com/67414153/233150559-d8e815be-cc49-46f4-8b8c-1b7731750888.png)

2022 Fiscal Year: Instead of opening balance of **N16,698,926.98 Debit**, the account displays credit balance of **N45,350,259.68**
![image](https://user-images.githubusercontent.com/67414153/233151471-9086f874-0b88-4dd3-aa3b-98f51f16a248.png)

We do not understand how the closing debit account balance at the close of a fiscal year changes to a different figure and a different balance in the next fiscal year. Things like these can jeopardize people's jobs. Kindly help look into this..

Thank you.

### Module

accounts

### Version

Frappe version - v13.54.0 (HEAD)
ERPNext version - v13.49.13 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @THEOSKaris,

**We no longer provide support for version 13 or older.**
Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
