### ISSUE TITLE
Chart of Account Importer doesn't create child company account tree

### ISSUE THREAD

**Issue by asoral** [frappe/erpnext#34935]
### Information about bug

I used a chart of account importer to create a chart of accounts for the parent company and in general if I create an account in the Parent company, the corresponding account gets created in the child company. I was assuming the same should happen with this tool but it did not.

### Module

accounts

### Version

V14 Latest

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @asoral,

You're correct. When you import the chart of accounts, you use Excel or CSV files. While the parent accounts update successfully, the child company accounts don't update. This is because the structure is designed for fast importing without facing issues during import. Additionally, there's no option to create accounts in the child company during import. However, this functionality is available when you create accounts from the user interface.

I hope this explanation makes sense.

Thank You!
