### ISSUE TITLE
Not able to rename company

### ISSUE THREAD

**Issue by unidow** [frappe/erpnext#34971]
### Information about bug

Property management is not "Force Removed" by us. but it's removed by you. We are not able to find it for installation and that has create a chaos while changing name of the company. Make this forum relevant for frappe cloud subscriber and provide a practical fix to the problem. Do not jump into closing the issue without proper solution. you may bill us if require a min of yours to fix this issue.

### Module

accounts

### Version

ERPNext: v13.49.13 (HEAD)
Frappe Framework: v13.54.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "13.49.13",
	"frappe": "13.54.0"
}
```
### Route
```
Form/Company/UNIDOW Advisory Services LLP
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1473, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/load.py", line 78, in getdoctype
    docs = get_meta_bundle(doctype)
  File "apps/frappe/frappe/desk/form/load.py", line 89, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "apps/frappe/frappe/desk/form/meta.py", line 51, in get_meta
    meta = FormMeta(doctype)
  File "apps/frappe/frappe/desk/form/meta.py", line 65, in __init__
    self.load_assets()
  File "apps/frappe/frappe/desk/form/meta.py", line 81, in load_assets
    self.add_code()
  File "apps/frappe/frappe/desk/form/meta.py", line 109, in add_code
    path = os.path.join(get_module_path(self.module), "doctype", scrub(self.name))
  File "apps/frappe/frappe/modules/utils.py", line 193, in get_module_path
    return frappe.get_module_path(module)
  File "apps/frappe/frappe/__init__.py", line 1224, in get_module_path
    return get_pymodule_path(local.module_app[module] + "." + module, *joins)
KeyError: 'property_management_solution'

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"doctype": "Property Management Settings",
		"with_parent": 1,
		"cached_timestamp": null
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.load.getdoctype"
}
```
### Response Data
```
{
	"exception": "KeyError: 'property_management_solution'"
}
```
```

**Comment by Nihantra-Patel** [comment]
Hi @unidow,

Please check the post video.

https://github.com/frappe/erpnext/issues/34907#issuecomment-1987828165

Another point to note is that "property_management_solution" is not included in Frappe ERPNext because Frappe ERPNext does not have a property management application.

We no longer provide support for version 13 or older. 

Everything is working fine. No problems were encountered in versions 14 and 15.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
