### ISSUE TITLE
Customize Form Bug : Delete field from customize form but show in form

### ISSUE THREAD

**Issue by megha0071994** [frappe/erpnext#34985]
### Information about bug

I've created a customize form with 9 fields. and I deleted that field from that form. but it is appearing in form still.

### Module

other

### Version

Installed Apps
ERPNext: v13.28.0

Frappe Framework: v13.28.0

Twilio Integration: v0.0.1

### Installation method

manual install

**Comment by s-aga-r** [comment]
@megha0071994 

What I have tried:
- Added a field in Purchase Order via Customize Form, the field was visible in the Purchase Order Form View.
- Deleted the field from Customize Form, the field also disappear from Purchase Order Form View.

The issue is not replicable. Please provide the steps to replicate it and reopen the issue.
