### ISSUE TITLE
Footer Doesn't come properly on the PDF

### ISSUE THREAD

**Issue by asoral** [frappe/erpnext#35006]
### Information about bug

I have added an html footer with style width=100% and it shows properly on the report preview but when I print a PDF, the footer looks like it is ~170% wide. Which is not correct.

### Module

other

### Version

Version-14 latest

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @asoral,

Could you please provide the code, image, or video so we can investigate from our side? We need to determine whether the problem lies with wkhtmltopdf or if it's something else. Sometimes, what appears correctly in the print preview may not display properly in the PDF view due to differences in functionality. We can adjust the print preview according to our requirements, but it's not always possible to adjust everything at the PDF level. If the issue has been resolved, please close it. Otherwise, share the code and video for easier troubleshooting.

Thank you!
