### ISSUE TITLE
Last Purchase Rate in Company Currency & PO Currency

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#35176]
### Information about bug

Dear Team,

We have made a PO with USD and the last purchase rate showing as the value in INR and but Showing as $. It makes confusion for approval.

Can anyone rectify this issue? 

### Module

buying

### Version

Frappe Chat: v0.0.1 (main)

ERPNext: v14.23.0 (version-14)

Frappe Framework: v14.34.0 (version-14)

Gatepass: v0.0.1 (main)

Frappe HR: v14.2.2 (version-14)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @dineshpanchal93,

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.


https://github.com/frappe/erpnext/assets/141945075/9acae1b3-652a-48b1-9654-1a50fecd599e

Thank You!
