### ISSUE TITLE
Issue in Gross Profit Report of invoices with Include Payment (POS) option checked or Warehouse is different in Delivery note and Sales invoice

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#35240]
### Information about bug
Issue is related to Gross profit where user create  invoice first and then deliver the item from any other than default warehouse.

>>1 Created a POS Profile

With Default Warehouse "Stores-EI"
![image](https://github.com/frappe/erpnext/assets/112148467/a23d65f4-2a12-48d7-9c20-e502039ec22f)

>>2 Created a  Sales invoice with Include Payment (POS) cheked and unchecked Update stock.
>>3 Added few items
>>4 Save and Submit

![Screenshot 2023-05-10 at 09-45-42 Walk in Customer - ACC-SINV-2023-00045](https://github.com/frappe/erpnext/assets/112148467/af001e6a-f207-4cb3-adf1-884aa69a9183)

>>5 Create Delivery Note

>>6 Change the Warehouse to different one i.e., i selected Site Main-El

>>7 Save and Submit the delivery note
![Screenshot 2023-05-10 at 09-48-20 Walk in Customer - MAT-DN-2023-00027](https://github.com/frappe/erpnext/assets/112148467/88e87d74-4740-4b55-b88f-c13c80663073)

now the Gross Profit report generates following values:

the report is not showing Valuation and buying rates of item. also the report is showing default warehousew of POS profile instead of warehouse from which item is delivered.

![Screenshot 2023-05-10 at 09-50-04 Gross Profit](https://github.com/frappe/erpnext/assets/112148467/cb883d02-597f-4478-a44b-fcf034824861)

### Module

accounts, stock, buying, selling

### Version

Tested on both V13 and V14

ERPNext: v13.45.1 (HEAD)
Frappe Framework: v13.49.1 (HEAD)

ERPNext: v14.23.4 (HEAD)
Frappe Framework: v14.35.0 (HEAD)
Frappe HR: v14.3.0 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @maveezmh,

It's difficult to cover everything here, but I'll give a brief overview. Valuation Rate in the Gross Profit report shows how much it costs to sell each item. It's like the price tag for your inventory. When you sell stuff, ERPNext uses these price tags to figure out how much you spent (the cost of goods sold) and subtracts it from your sales to find your profit. So, the Valuation Rate field helps you see the cost side of your sales and profit.

but you should look at the file [gross_profit.js](https://github.com/frappe/erpnext/blob/develop/erpnext/accounts/report/gross_profit/gross_profit.py) and search for "buying_rate" because the valuation rate is the same as the buying rate [("buying_rate": "valuation_rate")](https://github.com/frappe/erpnext/blob/develop/erpnext/accounts/report/gross_profit/gross_profit.py#L388). 
If you buy the material before of sale then it will calculate the valuation rate. Take some time to debug, check, and explore it.

Reference: https://techfordai.com/index.php/2023/08/25/gross-profit-report-in-erpnext/

I hope this helps.

Thank You!
