### ISSUE TITLE
Update item pop up is not showing row number. 

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#35258]
### Information about bug

when you submit Purchase order or sales order there will be a button to update items in them. 
once we click update item the item table is not showing the row number. which is normally available in table.

![Screenshot 2023-05-11 at 16-35-23 Craft Trade - SAL-ORD-2023-00045](https://github.com/frappe/erpnext/assets/112148467/5a2d5da4-1305-414b-bd79-516dcc3ae81d)
 

### Module

buying, selling

### Version

Not available in both V13 and 14

### Installation method

FrappeCloud

**Comment by maveezmh** [comment]
any Update on this?

**Comment by Nihantra-Patel** [comment]
This design adheres to the structure of the child table field in the dialog because when numbers are added, other field columns become compact and difficult to view and organize rows in the child table. Moreover, even if a custom dialog is developed with the child table, it does not appear. I hope this clarifies.
