### ISSUE TITLE
POS Barcode scan error

### ISSUE THREAD

**Issue by arcadio-nseng** [frappe/erpnext#35310]
### Information about bug

I have an issue with the POS barcode scanning. I can add items manually but not with a barcode scanner, when I scan a product with a conventional barcode scanner I get random numbers appearing on the filter field and sometimes items keep adding indefinitely. I can use barcode scanning normally on other modules such as stock entries. I'm not sure if it is a bug or I'm missing any configuration option.

ERPNext: v13.18.0
Frappe Framework: v13.18.0

https://github.com/frappe/erpnext/assets/52861036/37663786-d85f-4103-b88d-b5fef812795c

https://github.com/frappe/erpnext/assets/52861036/99082412-b4db-4e6d-aad9-c9f583b6f028

### Module

selling

### Version

ERPNext: v13.18.0
Frappe Framework: v13.18.0

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @arcadio-nseng,

Might be issue has been fixed in the latest versions 14 and 15.
Reference: #32799

**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15, then refresh and check again.
Everything is working fine. No problems were encountered in the latest versions 14 and 15.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
