### ISSUE TITLE
Missing Resources/Pages in Modules

### ISSUE THREAD

**Issue by ashabmoaz** [frappe/erpnext#35334]
### Information about bug

Hi 

I am using (PWD) provided in the Git (https://github.com/frappe/erpnext).
I successfully setup it up with the provided guidelines and test credentials. I can see and navigate through the modules provided in the left menu. However, when I try to open any feature/page from the right pane, it throws some missing resource error in an alert. 

### Module

selling, projects, CRM

### Version

Frappe - Not sure 
ERPNext - V3

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
CRM -> Territory:

Not found
Page territory not found
The resource you are looking for is not available
-----------------------------------------------------------------
CRM -> Lead

Missing DocType
Field territory is referring to non-existing doctype Territory.
-----------------------------------------------------------------
Projects -> Project

Missing DocType
Field holiday_list is referring to non-existing doctype Holiday List.
```

**Comment by Nihantra-Patel** [comment]
**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
