### ISSUE TITLE
glitch in POS invoices

### ISSUE THREAD

**Issue by mohbake** [frappe/erpnext#35494]
### glitch in POS invoices

We noticed a glitch in POS invoices. When we choose a point of sale in the sales invoice and the currency of the invoice is different from the currency of the payment method, the amount paid is considered as a payment in the same currency as the invoice instead of being considered in the currency of the payment method

### Module

accounts, selling

### Version

ERPNext: v14.25.0 (HEAD)
Frappe Framework: v14.36.3 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
without Relevant log output
```

**Comment by Nihantra-Patel** [comment]
Hi @mohbake,

However, I've tested this scenario in both version 14 and 15, and it seems that the system still processes payments according to the currency of the invoice rather than the currency of the payment method selected at the point of sale. If you're experiencing this issue in the latest versions as well, I would recommend documenting the process with a video demonstrating the problem and any error messages encountered. This will help in pinpointing the exact issue and potentially resolving it more effectively.

Thank You!
