### ISSUE TITLE
Item rate could not be fetched from Blanket Order to Purchase Order when performing multi-currency operation

### ISSUE THREAD

**Issue by reinald-at** [frappe/erpnext#35624]
### Flow 1: Purchase Order Creation from Blanket Order

- Created Blanket Order document which has different default currencies in the Company document (IDR) and the Supplier document (SGD).

- A Purchase Order document was then created from the Blanket Order document.
![image](https://github.com/frappe/erpnext/assets/134350557/2347b68c-76f6-4f86-a983-601d0b6d0797)

- When the Purchase Order document was loaded, the  **item code, quantity, and rate were not fetched along to the new Purchase Order document**. 
![image](https://github.com/frappe/erpnext/assets/134350557/d6a9620a-4a0b-4c45-8544-e21dc3094a7c)

### Flow 2: Purchase Order Creation with Manual Linking to Blanket Order
- Created a new Purchase Order document with the same company, supplier, and item as in **Flow 1**.

- Then, the Edit button on the right side of the item row was clicked and the Blanket Order field in the References section was filled manually.
![image](https://github.com/frappe/erpnext/assets/134350557/f4504b1b-8748-4d25-b773-a219ff75d1cb)

- As seen in the previous image, the **Blanket Order Rate field did not follow the rate currency in the Purchase Order document which was SGD**.

### Module

buying, manufacturing

### Version

Frappe version v14.33.0
ERPNext version v14.22.0

### Installation method

docker

**Comment by Nihantra-Patel** [comment]
Hi @reinald-at,

Flow 2 has been fixed, so please update to version 14 or 15. After updating, refresh and check again because many bugs have been fixed in the new version.

Regarding Flow 1, it has been tested. When you create a Purchase Order from the blanket order, the document loads properly, and the item code, quantity, and rate are fetched correctly.

Regarding currency issues, the blanket order currently offers limited functionality. It provides faster entry for creating purchase orders or sales orders. If you need to configure the currency, please add a custom field like "currency" in the blanket order doctype. When you create a purchase order or sales order, the currency will be fetched and set automatically. You can ignore the currency symbol in the blanket order once you've added the custom currency field.

If the issue occurs then please create a new issue according to the latest version (14 or 15) with a video document if possible.

Thank You!
