### ISSUE TITLE
Request: To change/remove the word "DRAFT" on print

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3563]
![image](https://cloud.githubusercontent.com/assets/12539216/8478104/d809f31c-2101-11e5-982b-9c05a898f47a.png)

Can it be done through the system itself or does it have to be customization?

**Comment by justinlusg** [comment]
We want to print documents which are not submitted yet but do not want the word DRAFT to appear on the print out.

**Comment by rmehta** [comment]
@justinlusg you **don't** want to print drafts because they change. Hence submission.

**Comment by Priyanka-IAS** [comment]
Hi,

We too need the same thing. And the reason is that we know that  the document might change. Here is the use case:

USE CASE 1 -  When we make an Invoice and send for Customs clearance - we need to remove the draft a we can't send a draft copy to customs. Yet, VERY often, the customs guy will request a change in the invoice. We don't want to submit and then amend as it will then change the invoice number with a revision and the while set of Customs documents including the Bill of Entry will need to be changed.

USE CASE 2 - When we send a Purchase order to our supplier, we send it while it is still NOT submitted in the system as we are almost sure that a number of things will changed based on the Order acknowledgement we receive. Changes could include exact weight (quantity) or even packing charges.

We currently use the REDACTION facility in Adobe to remove the word DRAFT but its cumbersome and it would be nice to have the option to remove the DRAFT word from the system itself.

Possible to reconsider your decision ??

**Comment by rmehta** [comment]
@Priyanka-IAS maybe we can add it as an option in Print Settings

**Comment by Priyanka-IAS** [comment]
Hi Rushabh, 

That sounds perfect. As long as we can avoid the word “DRAFT” in our prints. Thanks.


Regards,

Priyanka Kaushal

Director Operations

Indo Aerospace Solutions  (P) Ltd

Visit us on-line at www.indo-aerospace.com <http://www.indo-aerospace.com/>

**Comment by Priyanka-IAS** [comment]
Hi,

I was trying to write a custom script to do some calculations in the delivery note. I managed to make it work but it is triggered on SAVE of the form.

I want to trigger the script when the qty(quantity) of each delivery note item is changed. How do I do that?

 Regards,

Priyanka Kaushal

Director Operations

Indo Aerospace Solutions  (P) Ltd

Visit us on-line at www.indo-aerospace.com <http://www.indo-aerospace.com/>

**Comment by rmehta** [comment]
@Priyanka-IAS you have to call it on 
```
frappe.ui.form.on('Delivery Note Item', {
  qty: function(frm, doctype, name) {
    // call your function
  }
);
```

best place to ask these queries is on https://discuss.erpnext.com :)
