### ISSUE TITLE
Opening Inventory Valuation Posting In GL Issue through Stock Reconciliation Tool 

### ISSUE THREAD

**Issue by RJMHASKE** [frappe/erpnext#35692]
### Information about bug

Opening Inventory Valuation Posting In GL Issue through Stock Reconciliation Tool

**we have updated opening stock through stock reconciliation tool , Total Valuation of Inventory- 4159853.08/- but Accounting Ledger posting only- 4085611.94/- Diff in Inventory Valuation- 74241.14/-**
<img width="697" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/3dd4a413-f7be-4708-a214-80c39972afc2">
<img width="792" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/12c8b2d8-29e0-4a0a-a0bc-c4347375e9f3">
<img width="805" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/4c5cc9bc-8769-471b-ad71-261f0fe16ef3">

How this happened??

### Module

accounts, stock

### Version

ERPNext: v14.22.2 
Frappe Framework: v14.33.1
India Compliance: v14.6.0

### Installation method

manual install

**Comment by s-aga-r** [comment]
There was an issue with Stock Reconciliation: The ledgers (Stock and Accounts) got updated after Reposting or back-dated Stock Transactions but not the Stock Reconciliation document. This is already fixed in ERPNext v14.27.0. You need to create a Repost Item Valuation to update the Stock Reconciliation Document.

ref: https://github.com/frappe/erpnext/pull/35481
