### ISSUE TITLE
Cannot Auto Fetch from Inter Transferred Items Warehouse

### ISSUE THREAD

**Issue by keymealll** [frappe/erpnext#35729]
### Information about bug

I performed an Inter Transfer Transaction between company A and B, and using an auto fetch function for 5 unit items.
After the inter-transfer transaction its seems that the Serial No still being kept inside.

![image](https://github.com/frappe/erpnext/assets/75361771/e8f05892-bbf6-47fe-a4d1-72aae36b2a87)

Im about to fetch 5 serial number and I've got this message:
![image](https://github.com/frappe/erpnext/assets/75361771/97c2fe88-3432-4f67-adc5-db3d4d221226)

It's Strange, cos in the serial no List, that warehouse contains these serial numbers, 
![image](https://github.com/frappe/erpnext/assets/75361771/34eaba7c-824e-4f3f-b8dd-3f5a981f6a4d)

I suspect it turns out that the serial No can be auto fetched if it was created from Stock Entry only. meanwhile, this doesn't apply to the serial numbers created from Purchase Receipt. 
![image](https://github.com/frappe/erpnext/assets/75361771/6c9c9a29-2836-4d57-abd8-e09ea2824e51)

The odd thing I found is that i can fetch those serial numbers from this field. but i need to auto fetch in case that i need to fetch around 10 items serial numbers which would be hassle if i use this field
![image](https://github.com/frappe/erpnext/assets/75361771/108e1ea8-fd2d-4e60-b2df-70735aff92e3)

Let me know how do you view this, and please solve asap

### Module

accounts, stock

### Version

"erpnext": "13.39.2",
"frappe": "13.41.3",

### Installation method

None

**Comment by Nihantra-Patel** [comment]
**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version. and lots of functionality has been changed.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
