### ISSUE TITLE
Reports created from Reference reports have issue in Column Labels

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#35976]
### Information about bug

Analytics Reports such as sales/purchase analytics or reports like Profit and loss or Balancesheet which can be seen monthly quarterly or yearly.

the labels on header of each column is flexible and changes based on selected filter for example lets take sales analytics :

![Screenshot 2023-07-03 at 15-16-21 Sales Analytics](https://github.com/frappe/erpnext/assets/112148467/8b7c9a92-5a26-42c1-9060-b56dc50d40ad)

now when i add few additional columns and save it as a custom report. the header gets fixed to state when we saved the report. 
because of this when i change the date range the system still shows the headers which were there while saving the custom report. 

![Screenshot 2023-07-03 at 15-18-54 Sales Analytics By Customer Salesperson](https://github.com/frappe/erpnext/assets/112148467/e7c19dbd-249b-4a9c-9a6c-d21d5ded9ecc)

as the saved report keeps client code for the header as default.

![image](https://github.com/frappe/erpnext/assets/112148467/7b00edae-dc94-4337-b689-266acfeac997)

### Module

accounts, stock, buying, selling

### Version

V13 and V14

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @maveezmh,

You're correct, but when you make a new report from the Reference Report or standard report and save it, all the columns with their titles are also saved statically. This means they're not handled dynamically because they're generated from the client code of the report. So, I suggest creating a new server script report similar to Sales Analytics. It's a limitation of the framework for duplication reports/ new reports from the reference report.

![image](https://github.com/frappe/erpnext/assets/141945075/4bb85de9-07f2-4477-b0c2-f558fa055d3d)


Thank You!
