### ISSUE TITLE
Not billed sales order in the customer portal, supposed to be not billed

### ISSUE THREAD

**Issue by maxfu9** [frappe/erpnext#36242]
### Information about bug

Not billed sales order in the customer portal, supposed to be not billed but it shows not paid.
<img width="239" alt="Screenshot 2023-07-23 at 3 34 34 PM" src="https://github.com/frappe/erpnext/assets/29174889/e1a7ccf9-5ab8-43db-a6ac-0f72792f675c">

### Module

selling

### Version

ERPNext: v14.31.2 (version-14)
Frappe Framework: v14.41.0 (version-14)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @maxfu9,

It's made to show things from the client or user's point of view. It tells you which sales orders, invoices, or payments still need to be completed. The "not billed" status isn't shown because if you use the portal view and make a payment, it automatically creates a sales invoice and payment at the same time, so it won't appear as "not billed."

Thank You!
