### ISSUE TITLE
Company GSTIN is a mandoatory field for GST Accounts

### ISSUE THREAD

**Issue by toykraft** [frappe/erpnext#36267]
### Information about bug

We have just upgraded to V14 and have setup India-Compliance APP as well for GST e-Invoicing. Now while submitting any stock entries, we are getting an error as mentioned above.

### Module

stock

### Version

Frappe Version - v14.41.0 (HEAD)
ERPNext Version - v14.31.3 (HEAD)
India Compliance: v14.12.0 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Please check it and set it.

![image](https://github.com/frappe/erpnext/assets/141945075/896cf111-9664-410a-91e3-3c7e8e8000e8)

Also set it in the company address and GST Settings.

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.
