### ISSUE TITLE
The 'Not Permitted' issue is shown when clicking on the Sales Invoice Item Dashboard

### ISSUE THREAD

**Issue by aditya3366** [frappe/erpnext#36296]
### Information about bug

"I want to create a sum of the total amount of each item name in the 'Sales Invoice Item' child table. To create this dashboard, I first added a chart where I selected 'Document Type: Sales Invoice Item', 'Parent Document Type: Sales Invoice', and applied a filter for the item name. After adding this chart to the dashboard and opening it, a 'Not Permitted' issue is shown. I have checked all role permissions, and they seem to work for the parent doctype but not for the child table."

![Screenshot_152](https://github.com/frappe/erpnext/assets/107920741/cb43a498-ad15-4c03-8378-f2e77497a3da)

### Module

selling

### Version

Frappe Framework: v14.30.0 (version-14)
ERPNext: v14.20.0 (version-14)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @aditya3366,

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.


https://github.com/frappe/erpnext/assets/141945075/ddaf335c-8602-44f2-8e32-08e5ddcc50f3
