### ISSUE TITLE
Failed to post depreciation entries

### ISSUE THREAD

**Issue by tdlworld** [frappe/erpnext#36472]
### Information about bug

Hi Anyone have encountered this error in Assets Module?

Failed to post depreciation entries

The Asset module is not posting automatic Depreciation Entries, No Error Log, No Issue log….
No Documentation found and nothing in forum also.

### Module

accounts, assets

### Version

Frappe Chat: v0.0.1 (HEAD)
ERPNext: v14.33.1 (HEAD)
Frappe Framework: v14.43.0 (HEAD)
Frappe HR: v14.8.0 (HEAD)
India Compliance: v14.14.3 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by nitin-anantpranali** [comment]
Finally, I figured out the issues. And the issue was very very strange.
The Message is not correct as in the message 2 solutions were suggested.

A. First part its asking to change the Cost Centre in JV which is not possible because its in memory and not saved as Draft.

B. The Second part is asking to change the “Default Cost Centre” in Company Master. Here in Company Master there are two places for Cost Center Setup.
- "Default Cost Center" which have nothing to do with this issue and 
- "Asset Depreciation Cost Center" which need to setup and then only the Depreciation entry is made.

The Message created whole messup otherwise it would have made life very easy

**Comment by anandbaburajan** [comment]
Added better validations here https://github.com/frappe/erpnext/pull/36477.
