### ISSUE TITLE
List View is not working for few doctypes when the Show Title in Link Field is set to true.

### ISSUE THREAD

**Issue by alaahariri** [frappe/erpnext#36526]
### Information about bug

We are experiencing a problem where the List View is not functioning correctly for a few specific doctypes when the 'Show Title in Link Field' setting is enabled. This issue closely parallels a previously resolved issue [35312](https://github.com/frappe/erpnext/pull/35312). 

The previous fix was successfully applied to the 'Item List' doctype. However, we have identified that the same problem persists in the following doctypes:

- Website Item
- Item Group
- Item Alternative

These doctypes are also impacted by this issue and require a similar fix to ensure consistent functionality across all doctypes. We request to expand the fix scope to include these doctypes as well.

**Item Group:** 
![image](https://github.com/frappe/erpnext/assets/17312481/c4e8be77-18ac-48b5-acbc-2a1a08779734)

**Item Alternative:**
![image](https://github.com/frappe/erpnext/assets/17312481/1d7a47b1-8958-4a8f-ad38-01f77ca152e8)

**Website Item:**
![image](https://github.com/frappe/erpnext/assets/17312481/3e168c0b-1340-4351-99e0-4483e6200446)

### Module

stock, ecommerce

### Version

- ERPNext: v14.30.6 (version-14)
- Frappe Framework: v14.40.3 (version-14)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Please upgrade to version 14 or 15, then refresh and check again because many bugs have been fixed in the new versions. Everything is working well, and no problems were encountered in the latest versions 14 and 15.

However, if you have enabled "Show Title in Link Fields" for any tree doctype, you may encounter another issue. This is because you haven't mentioned the Title Field name, which maps the parent node tree. But in another doctype, we haven't encountered this type of issue.
