### ISSUE TITLE
Multicurrency mix in Payment Entry impossible

### ISSUE THREAD

**Issue by nissekalle0** [frappe/erpnext#36548]
### Information about bug

Charges in a different currency due to local bank charges impossible... must be a bug in use case planning and design of the function.
Of course the local bank must be able to charge in its own local currency of a paid purchase invoice like...
- exchange fees
- admin fees

### Module

accounts

### Version

Latest

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
no errors
just not possible to do
```

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.
If there's a problem, make sure to create a new report for version 14 or 15. If you can, include a video showing the problem. Describe the error message, the transaction where you encountered the problem, and the app you were using.

Thank You!
