### ISSUE TITLE
Missing journal entries in FY 2022-23

### ISSUE THREAD

**Issue by mehulmehta** [frappe/erpnext#36566]
### Information about bug

My erpnext version is 13. Last year for the first few months of the FY (Apr-March) in the journal entry there was a field called Finance Book which was mandatory. During this time some vouchers were entered without the finance book field as well. Subsequently the finance books is created automatically and the same is chosen in the journal vouchers automatically. We do not have an option to change it. 

The issue now is when we go through the ledgers for the full year all journal entries appear except the ones with the finance book. The moment we choose the finance book the entries with the finance book chosen too appear with the ones where the finance book is not chosen but the opening balance changes which in turn changes all other balances. The result is we have two separate closing balances for the same account and period - one with the finance book entries and one without the finance book entries. The end result being we do not know what is our accurate profit and loss and balance sheet. I hope you guys look into it and sort it out as our books of accounts is in a mess. I also hope my account too is sorted out as it is hosted on Frappe Cloud. I look forward to your prompt debugging of this issue.

Thanks and regards,
Mehul Mehta.
   

### Module

accounts

### Version

Frappe Framework v13.58.4
ERPNext v13.52.8

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @mehulmehta,

We no longer provide support for version 13 or older. some issues might be fixed in the newer version.

Kindly upgrade to version 14 or 15, then refresh and check again.

Everything is working fine. No problems were encountered in versions 14 and 15.
If the issue occurs then please create a new issue according to version (14 or 15) with a video document if possible.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
