### ISSUE TITLE
Sales Invoice API giving wrong status

### ISSUE THREAD

**Issue by agrVidushi** [frappe/erpnext#36700]
### Information about bug

After creating sales invoice, the status from API is "Unpaid" but in dashboard it is "Draft".

### Module

accounts

### Version

ERPNext - version-12

### Installation method

None

**Comment by Nihantra-Patel** [comment]
**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.
If the issue occurs then please create a new issue according to the latest version (14 or 15) with a video document if possible.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
