### ISSUE TITLE
V14 in Quotation item name is not getting fetched automatically

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#36731]
### Information about bug

if you see the item code field only item code is visible but  not the name
![image](https://github.com/frappe/erpnext/assets/112148467/0bf966ca-6ab2-45d6-b68d-8200dae549d4)

where as if you do same in sales order the system is fetching item name

![image](https://github.com/frappe/erpnext/assets/112148467/b8c1f74c-56af-4326-b541-e17d2ac968e0)

### Module

selling

### Version

V14 latest

### Installation method

None

**Comment by maveezmh** [comment]
@deepeshgarg007

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.

v14:

![image](https://github.com/frappe/erpnext/assets/141945075/69c6a602-0b87-4f98-9436-00c652201b31)


v15:

![image](https://github.com/frappe/erpnext/assets/141945075/60529ac3-f145-4983-bac8-e895d5d21af0)
