### ISSUE TITLE
GST Tax Rates not visible in Purchase Invoice Print Outs

### ISSUE THREAD

**Issue by Rajatha26** [frappe/erpnext#36818]
Hi Team,

When we take the print outs of Purchase Invoices, then the tax rates(CGST,SGST and IGST) are not getting displayed of the respective doc types even if the taxes are added in the Purchase Invoices.
Attaching screenshots for reference:
![Screenshot (58)](https://github.com/frappe/erpnext/assets/130460172/468f4f27-518c-4952-aeaa-a152ce722289)
![Screenshot (57)](https://github.com/frappe/erpnext/assets/130460172/216c4fd5-d422-4396-9cad-b553ba810134)
![Screenshot (56)](https://github.com/frappe/erpnext/assets/130460172/cea5042a-0ed8-4513-93b6-87d2be38bcc2)
![Screenshot (55)](https://github.com/frappe/erpnext/assets/130460172/ae431369-9aec-44d4-b660-1a0bbd64c163)

Kindly check these issues and revert.

Thanks and Regards,
Rajatha B
Functional Consultant
Promantia Business Solutions Pvt. Ltd.
Bangalore

**Comment by Nihantra-Patel** [comment]
Hi @Rajatha26,

I think you should make a [customized print format](https://docs.erpnext.com/docs/user/manual/en/records-print-format).

Otherwise, I share the suggestion link you should add the [Tax Breakup](https://docs.erpnext.com/docs/user/manual/en/taxes-and-charges) in your print format.

**Output:**

![image](https://github.com/frappe/erpnext/assets/99652762/c39f7fae-857e-4189-873b-800c69b7fc11)

Thank You!
