### ISSUE TITLE
PAYMENT REQUEST - it gives a wrong amount

### ISSUE THREAD

**Issue by GerardoIPM** [frappe/erpnext#37139]
### Information about bug

Creating a payment request from an order
https://ilpezzomancante.erpnext.com/app/sales-order/SO23-00253

The client is asking to pay the full amount in advance, so I need to issue a payment request.
The Grand Total of the order is € 5.110,00
Client paid already € 1.533,00

I need to create a payment request for €3.573,00

But the system allows maximum €2.044,00 - kindly check the enclosed screenshot

If I change the amount and write €3.573,00, when I save I get the following message:
"Total Payment Request amount cannot be greater than Sales Order amount"

![Schermata 2023-09-18 alle 15 24 52](https://github.com/frappe/erpnext/assets/143416246/b83989aa-3634-451e-b5c9-42548c0520c3)

### Module

selling

### Version

ERPNext: v13.52.15 (HEAD)
ERPNext Shipping: v0.0.1 (HEAD)
ERPNext Support: v0.2.1 (HEAD)
Frappe Framework: v13.58.11 (HEAD)
Journeys: v0.0.1 (HEAD)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
"Total Payment Request amount cannot be greater than Sales Order amount"
```

**Comment by Nihantra-Patel** [comment]
**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
