### ISSUE TITLE
ERPnext with  flutter

### ISSUE THREAD

**Issue by adhamfaiz** [frappe/erpnext#37158]
hiii guys 
I have question 
your response will help me

can I use ERPNext as backend for flutter app
if yes 
tell me about the advantages and disadvantage

**Comment by DonnC** [comment]
@dhomea yes, since its built on top of the frappe framework and it comes with Rest API endpoints out of the box for any doctype and more for what you already have on ERPNext web desk, then YES you can use it as a backend for any other front end or client.
So its not a feature for ERPNext because its already there, you will consume the REST Apis with flutter packages like dio or http or any library and you will be able to communicate to your ERPNext backend from Flutter.
