### ISSUE TITLE
Landed cost Voucher improvement. 

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#3738]
Using landed cost voucher ...
Here is the situation.  
Let's say I have a 100,000USD load from Supplier A.  (no problem here, we can do purchase receipt)
Then transport on this load is 30,000 USD but from Supplier B
Clearing Charges is 2,000 USD from Supplier C
Duties at the border are 8,000USD (from Gov.) and this duty is only for item #1.

Now landed Voucher is good to put to right valuation on the stock, but then 30,000 + 2,000 + 8,000 is all in expenses included in valuation as one lump sum (offset by stock asset account). The issue is also that the lump sump is attributed to the Purchase Receipt # and not the LCV #.  So there is no traceability there. 
That is very problematic in this case.  Am I missing something?

Landed cost voucher should be able to offset these amount from expenses included in valuation by creating the appropriate liabilities amount to the relevant creditors.

**Comment by fderyckel** [comment]
How can I add the "Paid development label" on this issue?

**Comment by rmehta** [comment]
> Landed cost voucher should be able to offset these amount from expenses included in valuation by creating the appropriate liabilities amount to the relevant creditors. 

Can you explain this clearly? The liabilities will be booked via Purchase Invoice? What is the connection between this expense and liability?

**Comment by fderyckel** [comment]
Hi Rushabh, 
Can you then let me know what is the most effective way to do this with ERPNext? 
I receive 1 load (with 2 products, Item #1 and Item #2) and I am being billed by 4 different service providers on that load (each one increasing the value of the stocks received)
Bill # 1: Port Charges (for whole load)
Bill # 2: Transport Charges (for whole load)
Bill # 3: Clearing Fees at the Border (to our Clearing Agent)
Bill # 4: Import Duties and Taxes to the Government (let's say 2000$ for item #1 and 1600 for Item #2)

Doing 4 LCV on the same Purchase Receipt seems a bit tedious.  
We should have a way to them all in once so that each service providers account is being credited accordingly and the value of the goods received is increased accordingly as well. 

Maybe 1 LCV should create 1 Journal Entries (with all the different accounts credited / debited ) at once.

I hope this clarify things.

**Comment by nabinhait** [comment]
@fderyckel 
You do not need to create 4 LCV to update landed cost of those items, you should put all the charges in the same LCV. On submission of LCV, "Warehouse" account will be debited and "Expense Included In Valuation" will be credited.

Now to book specific expenses like "Port Charges", "Transport Charges" etc, you need to create different Purchase Invoice as they have different suppliers. That way you should be able to track outstanding and payments against those invoices.

And finally when you deliver those items, the amount booked in "Expense Included In Valuation" will be nullified.

There is only one problem in LCV, there is no option to modify the item-wise additional costs. That is on our to-do list #3717, which is tagged as paid development with estimated hours. May be you can contribute the amount, to increase the priority of that feature.

**Comment by ai-erp** [comment]
Hi Nabin, i understand what @fderyckel  is trying to say. it would be helpful if in the LCV, instead of directly crediting the account "expense included in valuation", we can choose the the account of the service providers to be credited accordingly so that there will be no need to make another entry to create to establish payables to the service providers. Thank you..

**Comment by nabinhait** [comment]
@ai-erp In that case you will not be able to reconcile/link payment entry of the service provider. And The amount will always be shown as outstanding in Accounts Payable report.

**Comment by me2ne** [comment]
We have this issue too . plus shipping Charges not for whole load same , for example whole load is 200kg and we paid transportation charge 3$ per kg , it should be calculate base on weight of items and add to cost , for example if in shipment 200 x goods1 each one 1kg and 10 x goods2 each one 100kg , erpnext calculate shipping charge divide by 210 , and it's not correct . 
should be divide by weight and add shipping charge of goods1 3$ each and shipping charge goods2 30$ each on goods cost . 
for custom fee also usually different by items or some percentage of items cost should be calculated . 
Regards

**Comment by ai-erp** [comment]
hi @nabinhait , i don't get the point why "expenses included in valuation" will be offset once the item with landed cost is delivered... the reason why we want creditors (fedex/aramex/tnt/dhl/etc) should be credited in this case is to show as if we are making accrual of expenses(debit to expense or in this case stocks and credit to payable to shipping company)... In this case, when we want to make the payment for the shipping company, then we can close payable account which belongs to shipping company...

**Comment by me2ne** [comment]
when received items in erpnext  this is 3 different cost added on items : 

1 ) shipping cost    ( it's should divided by items weight ) 
2 ) Custom fee ( should divided by items value and custom rate of items ) 
3 ) clearance and handling charge ( should decided by item weight to cost - optional )

for each of this expense we should select account , for example if items shipped by fedex and fedex have account with , they should debit or credit fedex account for shipping expense 

or for custom fee use clearance company account . 

Hope you understand

**Comment by addymuliady** [comment]
To add, can we do an LCV to take the amount from a Purchase Invoice?

For example, we paid an Invoice for a forwarder and would like that to be distributed to a PR/PI.

**Comment by ai-erp** [comment]
Hi @nabin,

Currently, the entry affected in making this entry to LCV is  as below:
<img src="/uploads/default/original/2X/5/54131f156e20f63ea225ddd935eec0bb6885d8de.png" width="690" height="310">

While entry created upon delivery of the goods is below:
<img src="/uploads/default/original/2X/a/a5b43c27f54c3213d5ddd80fa6280b633f059c1d.png" width="690" height="271">

I suggest that instead of Automatically creating an entry of Credit to Expense included in Valuation in making LCV, why not have the option to select Shipping company Account so that there is no need to create a new entry in booking payable to Shipping Company like Fedex, DHL, TNT, Aramex or any other shipping company. So upon payment, we only have to close the account "shipping Company" and credit to cash/cash in bank.

**Comment by SaiFi0102** [comment]
@nabinhait you said "Now to book specific expenses like "Port Charges", "Transport Charges" etc, you need to create different Purchase Invoice as they have different suppliers," however, it is not possible to make purchase invoices without adding the items again which will cause the invoice to bill the items again too. How do I achieve what you are suggesting?

**Comment by tiagos30** [comment]
Has this been implemented on an official version? If not, do we have an estimated timeline?

**Comment by fderyckel** [comment]
Yes I am not sure why such a common think is not working.  I am wondering how other business are doing / going around that.

**Comment by immueke** [comment]
@harshit-30 following the above discussion was this implemented as suggested by  @ai-erp " I suggest that instead of Automatically creating an entry of Credit to Expense included in Valuation in making LCV, why not have the option to select Shipping company Account so that there is no need to create a new entry in booking payable to Shipping Company like Fedex, DHL, TNT, Aramex or any other shipping company. So upon payment, we only have to close the account "shipping Company" and credit to cash/cash in bank."

**Comment by immueke** [comment]
@Support-at-erpgulf posting clearing company invoice when it is received. Does it amount to double posting of the cost since the landed cost voucher is already posted. How do you post the clearing company supplier invoice? Do you have any recorded demo in your tutorials?
