### ISSUE TITLE
Email Template None not found on submitting an RFQ with no Email Template selected.

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#37428]
### Information about bug

![image](https://github.com/frappe/erpnext/assets/1822868/38ac03e5-8a5d-410e-8c4b-18439b1051e0)

Alternative solution is to make Email Template mandatory
![image](https://github.com/frappe/erpnext/assets/1822868/977bfb5f-140f-47d9-b85d-651877550f52)

### Module

buying

### Version

ERPNext: v14.43.0 (HEAD)
Frappe Framework: v14.51.0 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @muchai,

We tried it out in the newest version 14, and we didn't come across any problems. So, please make sure to update or upgrade your version on Frappe Cloud, and then see if the issue persists. It's possible that the bug has been fixed in the updated version. 

Also, take a look at the video for further clarification.


https://github.com/frappe/erpnext/assets/141945075/dbce44f6-ca7a-4816-a8f5-50cc751f4608

Thank You!
