### ISSUE TITLE
Profitability Analysis to PnL statement Filters

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#37490]
### Information about bug

When we open profitability analysis report and click on one of the cost center  as shown below

![Screenshot 2023-10-13 at 10-17-23 Profitability Analysis](https://github.com/frappe/erpnext/assets/112148467/c1a3cab9-2743-474e-b5f0-30b2e2bba0ca)

the system is taking cost center field to project field in Profit and loss statement and its not showing proper values. 

![Screenshot 2023-10-13 at 10-18-06 Profit and Loss Statement](https://github.com/frappe/erpnext/assets/112148467/4f1c3324-e9f2-4ee1-bb03-92f4479d3aa2)

in above screenshot the cost center Fruits - El is populated in Projects Field of Profit and loss statement and throwing error.

### Module

accounts

### Version

V14

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Worked properly.

![image](https://github.com/frappe/erpnext/assets/141945075/41992fc8-5f22-467a-a278-5548b4c019ff)


![image](https://github.com/frappe/erpnext/assets/141945075/f0d6e984-d0ed-4078-913b-9402ea526fe5)
