### ISSUE TITLE
Payment Entry: References child table buttons should be on the same line

### ISSUE THREAD

**Issue by bosue** [frappe/erpnext#37504]
Unsure if this is a CSS issue or legitimately needs a CSS tweak. I expect the latter.

![IMG_1830](https://github.com/frappe/erpnext/assets/46800703/80afa961-a33b-4521-ba26-29da57b6a255)

**Comment by Nihantra-Patel** [comment]
Hi @bosue,

You can change things as you like in ERPNext. Just add a new column and a new section, then refresh the page to see how it looks.

![image](https://github.com/frappe/erpnext/assets/141945075/df4391ed-c519-4a57-a6eb-6306ef0d751f)

**Output:**

![image](https://github.com/frappe/erpnext/assets/141945075/2b43347c-bdc7-401e-9dc9-2f612f58acd6)


It's a small thing, If your issue is solved via column and section break from your side then please close the issue. Otherwise, we add the tag "feature request".

I hope this helps.


Thank You!
