### ISSUE TITLE
Invoicing for Multiple Sales orders related to different projects

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#37564]
### Information about bug

IN ERPNext for project invoicing we have provision to create invoice towards multiple project. but when we fetch multiple sales orders with different projects following errors happens.

>>>when we fetch salesorders related to different projects the project field is not getting populated in line item.

>>> Unable to submit invoice because the invoices validates project field in accounting dimension field instead of line item wise accounting dimensions. 

Use Case :
1. Create two sales orders for one customer
2. Create individual projects for each sales orders.
3. goto sales invoice
4. Select Customer
5. click on get items from sales order 
6. select recently created sales order
**7. Issue A** in line item its not fetching linked project for each sales order
8. select the appropriate projects manually for each line item
**9. issue B** system is validating Invoice level accounting dimension field for project instead of line item wise dimension field when we try to save.

Additionally. 
when you create standalone invoices by manually giving project reference to each line items instead of fetching items from sales order the system works fine. and also proper accounting entries are generated. 

### Module

accounts, selling, projects

### Version

issue is there in both V13 and V14

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @maveezmh,

Instead of adding the project in the sales order, just add it to each item in the sales order. This way, if you have multiple projects with the same customer, you can keep track of them separately at the item level. When you create the sales invoice, all items with their respective projects will be automatically included, reducing the chances of errors.

However, it's currently difficult to implement your scenario in erpnext because it's not set up to handle determining which project to include in the invoice at a given time. It's not practical to do this at the moment.

I know the project field is not available in the Sales Order Item but available in the Sales Invoice, but you can create a custom field project in the Sales Order Item. When you create a Sales Invoice and Get the Sales Order data then project will automatically fetch without any coding. Try it.

Thank You!

**Comment by maveezmh** [comment]
@Nihantra-Patel but its not prcatical when client deals with multiple projects and everytime we need to goto each item in item table and update project manually. i tried the same but there was error happening. also if the item list is big in each sales order it is very difficult to update all the line items
