### ISSUE TITLE
Enhancement: Handle accounts that can either be assets or liabilities based on their balance

### ISSUE THREAD

**Issue by citizen-khan** [frappe/erpnext#3764]
There are two scenarios in my business where accounts can be either a current asset or current liability depending on the accounts balance:

1) Bank Accounts
2) VAT Liability

In order that these are shown correctly in the balance sheet accounts should the ability to set set a flag to show that they can float and thus handle that account correctly based on its balance.

You would still have one account it would just be a matter of checking floating account balances to determine where it appears on the financial statements and showing in it's correct position.

This is important because accounting ratios are the very foundation of accounting reporting whether internal or external and balances not handled correctly affects ratios thus affecting the ability to accurately report.

Of course we can handle these all ourselves however that limits the usefulness of having an Accounting package in the first place if we have to fiddle things to just make it right.

**Comment by rmehta** [comment]
https://erpnext.com/pricing/paid-feature-development ?

**Comment by parito-ltd** [comment]
Not sure if I should open a new thread or reopen this one, but just to be sure, is this not a possibility in ERPNext?

I am trying to switch away from dolibarr to ERPNext and have mostly managed to make the ERP fits into our needs however I cannot find a way to handle this.

Why is this important? In french accounting (and subsequently, in accounting of countries that follow the french accounting standard including mine), most accounts of class 4 can be either asset or liabilities depending on the current context, wherea in the excel spreadsheet to fill the account for ERPNext, that is not an option, you have to pick either one.

Is there a way to do this since 2015 or is this still under "paid feature development"?
