### ISSUE TITLE
Sales Invoice data not changing

### ISSUE THREAD

**Issue by lfirewall1243** [frappe/erpnext#38270]
### Information about bug

Bug occures when you have a multi company setup.

When you create a Sales Quotation and change the company from your main company to another one. Then tax, tax number, letter head is changed to the company settings.
Same when you create a Sales Order...

When you create a sales-invoice only  the tax number is changed, tax, letter head is staying default.

### Module

selling

### Version

Frappe: v15.2
ERPNext; v15.3

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @lfirewall1243,

Kindly upgrade to version 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest version 15.

Please check it.


https://github.com/frappe/erpnext/assets/141945075/2f5dd188-7f94-4dcc-8716-874fda5028d9
