### ISSUE TITLE
Feature request: Merging support tickets

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#3832]
Many times customers send multiple emails relating to a single case within our company. All helpdesk systems allow merging tickets. This would move ERPNext closer to fully fulfill helpdesk needs.

**Comment by dottenbr** [comment]
Is now in new issue #3877 where a couple of requests are combined.

**Comment by federicocalvo** [comment]
Hi @dottenbr, shouldn't we reopen this issue, since it is a punctual task that is very useful for the ticket system and the ticket you link to was something big and old?

reading the excellent issue of 2015 where you propose many questions for a complete ticket system, which today are resolved, today we are about to move from freshdesk to tickets in the erpnext module.

It would be good that from your experience you redefine again points to try from our side to attack some from the development.

Things that limit us a little when passing from freshdesk is the high quality of the help articles and how to reference it in the ticket, and the mobile app, fast and intuitive.
