### ISSUE TITLE
Auto close PO when SCO is Closed

### ISSUE THREAD

**Issue by precihole** [frappe/erpnext#38658]
### Information about bug

Hello @rohitwaghchaure ,

When I return from the supplier, the subcontracting order is closed, but the purchase order remains unchanged.

### Module

buying

### Version

Frappe Framework: v14.58.0 (HEAD)

### Installation method

None

**Comment by ophl55** [comment]
I dont't think the PO should be closed automatically in that case. Also the SCO should not be closed automatically.
The docs should be set "Completed" automatically if everything went fine and all the required Receipts have been submitted.

The user should decide to close a pending business process and the user should do it manually.
There might be a lot of reason why you don't want the SCO to be closed automatically on SCO Return. 

One example: 
Maybe you need the material yourself or for another supplier and you will send the subcontractor new material as soon as possible so that he can fulfill his PO/SCO. In that case it would be wrong to close the SCO automatically by returning the material.

What do you think? @s-aga-r @precihole

**Comment by ophl55** [comment]
Please also check here: https://github.com/frappe/erpnext/issues/38702

**Comment by ophl55** [comment]
Also automatically closing a preceding document is nowhere else done in ERPNext.
So to me this implementation appears heavily counter intuitive, it doesn't match with the rest of the design/ux.

It might be alright if the SCO gets closed when the user closes the PO because the SCO depends much more on the PO than the other way around.
