### ISSUE TITLE
Asset: Make depreciation entry does not work when there are mandatory accounting dimensions

### ISSUE THREAD

**Issue by rvbd** [frappe/erpnext#38661]
### Information about bug

If we have a custom accounting dimension, for example Branch. When we manually create depreciation entry of the asset, the we will get an error even if the accounting dimension is already specified in the asset document.

This is possibly because of an issue in the JS call where it doesn't send the accounting dimensions to the API.
![image](https://github.com/frappe/erpnext/assets/1558550/92b27f61-7e3f-4806-98b8-a0a2f895a9b8)
![image](https://github.com/frappe/erpnext/assets/1558550/06be6578-8983-4c15-ab9f-04b9cf51a667)

### Module

accounts, assets

### Version

ERPNext: v14.50.0 (version-14)
Frappe Framework: v14.57.0 (version-14)

### Installation method

manual install

**Comment by GursheenK** [comment]
Since a custom mandatory check has been added to the field in Journal Entry, there is no way to programmatically determine which values are required while generating the Journal Entry. 

Custom fields like these need to be handled explicitly since they are optional. You can either add a default value for the field or remove the mandatory check to avoid running into this error.
