### ISSUE TITLE
Purchase Order / Subcontract Order V15

### ISSUE THREAD

**Issue by krishnanhemanth** [frappe/erpnext#38708]
Hi
The creation of Purchase Order for subcontracted items is pretty confusing
     Case .
I have a part called **Wheel Hub** - created an item 
for the above part, it under goes multiple operations to finally become a **Wheel Hub**
So i create separate items for all the operations ---- all these are **Stock items** - and categorized as Work In Progress
1> Wheel Hub Raw Material cutting
2> Wheel Hub CNC Machining
3> Wheel Hub Heat Treatment
4> Wheel Hub Grinding
5> Wheel Hub Plating 
All the above are used to create separate BOM Operation wise
Example
Bom1> Parent -  Wheel Hub CNC Machining
             Child  -   Wheel Hub Raw Material cutting
Like wise BOM has been created for all the above
Now when creating Purchase Order for the above, for Example, i need to send **Wheel Hub CNC Machining** to subcontract
**How does the creation of Non Stock item help the process**
The price list mentions the rate of **Wheel Hub CNC Machining**
But the price in the Purchase order form is looking for the price of the non stock item
Do i have to create a non stock item for all the Work in Progress Items?
The term Finished goods Used in the PO is again Confusing
Since every process is separately entered as an item, Item would have been a more suitable name
The PO workflow of V13 was perfect and straight forward
The creation of a Non Stock Item for every process is duplicating and confusing
Or have I missed out something on this
It would be kind enough if somebody can create a Purchase order along with a subcontract order for the above case 
The above case is a very common use case in manufacturing
[
![PO V15](https://github.com/frappe/erpnext/assets/13927972/655cc95c-17be-4ab6-8f20-f93a76ab3b19)
](url)
In the above image, at the top - under the finished goods section
there is option to enter the finished goods qty
the non stock item - item code and item name is shown below
below Description
there is again qty and rate
what qty is this?
in the rate column, the rate is picked up from the price list ( for non stock items)- i had to create a separate non stock item  for all the work in progress items and create a pricelist for the non stock items
Please guide
With Thanks and Regards
Hemanth

**Comment by krishnanhemanth** [comment]
Hi
Continuing from the above
The below is a print for the PO
![po qty](https://github.com/frappe/erpnext/assets/13927972/149dcc99-2281-44f6-9f1e-473fa45853ea)
the total qty shown below is by default the Item code Qty
There is no option to show the Finished goods qty
And
When i Create a Subcontract Order , 
the total qty shown is finished goods qty
not the itemcode qty
so whats the relation between these two quantities 
Hemanth

**Comment by SvbZ3r0** [comment]
> So i create separate items for all the operations ---- all these are Stock items - and categorized as Work In Progress
> 1> Wheel Hub Raw Material cutting
> 2> Wheel Hub CNC Machining
> 3> Wheel Hub Heat Treatment
> 4> Wheel Hub Grinding
> 5> Wheel Hub Plating

All of these should be non-stock items. They are operations and they won't exist in your inventory. You should create WIP stock items for every stage, for example:
1) Wheel hub - Raw material
2) Wheel hub - Cut raw material
3) Wheel hub - Machined
4) Wheel hub - Heat-treated
5) Wheel Hub - Ground
6) Wheel Hub - Plated

These are the items that will actually exist on your shop floor. Then you create a BOM for each stage (this will not include the operation, since it is a Bill of **Materials**). 
If you are on v15, you should create a Subcontracting BOM that will specify what operation is performed for each WIP Item. This will make it easy to select items when you are creating a Subcontracting PO. If you are on v14, you will have to select the service and the finished item for each PO manually.

The finished goods in the Subcontracting PO is the Item you expect to get back from your supplier after they have done their work. The raw material in the PO is the Item you send to them to be processed into a finished good. In your example, you would send "Wheel Hub - Machined" to your supplier who will perform the heat treatment and send you "Wheel Hub - Heat Treated". They will bill you for "Heat Treatment" which is a non-stock Item.

Hope this makes things clearer.

**Comment by s-aga-r** [comment]
@krishnanhemanth 

Subcontracting is a service not a direct purchase you did via Purchase Receipt/Invoice. 

Item Code = Service performed by the supplier ex. Painting.
Raw Material = Materials which get processed by the subcontractor ex. Unpainted Chair.
Finished Good = Finished Item you will receive from your subcontractor ex. Chair.
Rate = Service Charge you agreed with your subcontractor.
Valuation Rate of Finished Item = Raw-Material + Service Charge. 

> How does the creation of Non Stock item help the process

It helps in GST, as the GST should be applicable on Service Charge not on the Valuation Rate of the Finished Item.

> But the price in the Purchase order form is looking for the price of the non stock item

Yes, the Service Charge. The Raw Materials cost will be added in the next step Subcontracting Order.

> Do i have to create a non stock item for all the Work in Progress Items?

No, Service Items need to be created for the Subcontracted Items. You can also you one Service Item for different Finished Goods as well.

> Since every process is separately entered as an item, Item would have been a more suitable name

Agreed, but correctly it is not possible. Item Code should be shown as Service Item for Subcontract Purchase Orders.

> what qty is this?

Consider an example where you have a bulk service that means 1 Service Item: 100 Finished Goods.

> There is no option to show the Finished goods qty

Again it's a service, the Service Item and Qty should be mentioned.

**Comment by krishnanhemanth** [comment]
Hi 
Thank you s-aga-r and svbz3ro for your detailed explanation
brought in more clarity 
If time permits, shall do a video for the same so that it would be helpful for others
One of the issue that still remains is
If i need to get price from pricelist then all work in progress(finished goods) items have to be separately created as non stock items and then define price for the non stock items
The module already allows multiple finished goods to be selected for a single Non stock item
For example
Heat treatment - non stock item
I have 10 different items that needs to go for heat treatment
so presently, i have defined heat treatment as non stock item and select the finished goods from the pop up window
rates are being entered manually
Any chance that price list rates can be fetched from finished goods
Thanks and Regards
Hemanth

**Comment by SvbZ3r0** [comment]
Currently, I dont think there is a way to automatically fetch prices based on fg-item. Definitely a good feature to have. Please open a feature request so that somebody can pick it up when they have the time.
As a work around, I currently have the service item as a template item and the give it a new variant for each fg-item. Not ideal, but it should work well enough.

**Comment by krishnanhemanth** [comment]
Thanks SvbZ3ro for your quick reply
Yes, as you said, that's the way around
But Imagine creating a non stock item for every Work In Progress(finished Goods) item just to get the rates is duplicating and time taking for large number of items
Presently entering the rates manually
This as a feature would definitely make tasks much easier and error free
Thanks and Regards
