### ISSUE TITLE
Feature: Turning Support into a real Help Desk

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#3877]
As per the discussion on the forum these are steps to take the Support DocType into a real Help Desk.
- [x] **Merging Tickets:** the ability to merge two tickets into one and automatically put the merged conversations in by date so that both ticket become one also in the overview. Already raised as feature implementation ticket in frappe. For this we would need a possibility to see other issues from that customer so we can select what to merge with.
- [ ] **Customer Satisfaction Rating:** already raised as feature implementation ticket in frappe.
- [ ] **Quick Reassign:** when writing a reply or internal note you should be able to select a “reassign to” when you click send. This will allow adding notes and reassigning or sending a reply like “Thank you for your email, Umair will contact you shortly” while then reassigning to Umair. Not raised yet.
- [ ] **Make tags searchable in omnibox search:** the tags are sweet in the support ticket, however they can not be searched for in the omnibox search. I believe this would be a very strong feature for all of frappe. Not raised yet.
- [x] **Attach Documents to email message:** as far as I can see the documents attached to a ticket can not be sent to a customer. I recommend moving away from just global attachments to message attachments that then become global attachments but only the message attachment will be sent to the customer. This is important because internal notes could have files attached that the customer may not see but are important for company internal communication.
- [x] **Change the style of a note:** It's important to distinguish messages and notes quickly. This relates to the general activity stream. I propose a white background for emails, a light yellow background for messages (like a post-it note) and a light grey background for the activity stream like “created” or “reassigned to …”
- [ ] **Create sidebar:** create a sidebar on the right where user information like Company name, region code, contact language, phone number and email are displayed. Underneath list all support tickets raised by this user and open them as modal for quick preview or merging. The status of the ticket “Open”, “Replied”, etc. should be visible and color coded.
- [x] **Enable CC and BCC:** The ticket is addressed to the customer, however lets assume the customer writes to support@erpnext.com and CCs his colleagues on the ticket. It would be very important that a reply is also CC’d to those contacts so they know its being resolved and don’t question our responsiveness. Regardless of that when prompting the email you should always and frappe-wide be able to specify indefinite CC and BCC addresses. Probably its best to store those in a database because they might not be customer related. The CC and BCC would have to be remembered. BCC and CC should be listed in the Activity Stream.
- [ ] **Forwarding tickets:** You should be able to forward a ticket, for example to a non ERPNext user such as a supplier or subcontractor. We need a way of forwarding an email just like a comment to maybe a colleague or a supplier, this should be highlighted as forwarded email but whats written should not become part of the normal customer conversation.
- [x] **Basic analytics:** Show average time until tickets are answered, make a report for unanswered tickets, create an email alert when a ticket hasn’t been dealt with for 5 days etc. Many ideas here.
- [ ] **Forwarding to helpdesk from email:** Assume a customer sends you an email to your company email address. Now what you want to create that as a ticket in the helpdesk. The way to do this should be forwarding the mail from your Gmail or other mail account to "service@myerpnext.com" and you just write "@assign me" or “@assign Rushabh" to assign it. If you want to add a note to it you just write something and the system will recognize it.
- [ ] **Assigning** on the left there is a "Assigned to me", how about we add an "assigned" and "unassigned" to so we can see what is this users, other users and unassigned at the moment.
- [x] **Rich text and functionality** instead of popup the functionality (CC, and formatting) should be provided right in the input field.
- [ ] **Make it more email like looking**
- [ ] **Attachments in its right place** rather than being attached to the whole thing they should be in the part where the email was sent.

**Comment by dottenbr** [comment]
@rmehta push

**Comment by mhbu50** [comment]
+1

**Comment by alv000h** [comment]
Hi all,

It would be interesting to add support for "ticket priority" and SLA management.

I was thinking in something more ITIL oriented.

Nothing too complicated, but with some features like:
- Lead escalations when too much time for first response occurs...
- Different levels of priority (high, normal, low)
- Different resolution times based on priority (high priority, 1h; medium priority 4h, something like that)

**Comment by borcan79** [comment]
+1

**Comment by alv000h** [comment]
@rmehta @anandpdoshi @dottenbr
Any plans on this things?

**Comment by DanielHowe** [comment]
Hi,
   I hope I am not reviving a detached thread, if there is any updates to this I am very interested in learning more.
   Our organization is in need of some of the features mentioned earlier.  Any help or guidance is greatly appreciated!

**Comment by rmehta** [comment]
@DanielHowe spec out your requirements into separate issues. The next step is to wait for someone to build them for you or build / sponsor them yourself.

**Comment by OneiricIT** [comment]
@dottenbr just came across this.
I have been outlining requirements for a helpdesk system - actually came across another open source project the other day which is fantastic (https://zammad.org/), however I prefer a single pane of glass approach as opposed to integration based on 1) their current time accounting and 2) ticket management from within web portal of ERPNext. 

Have started locally on the design of the app, and then just need to get the more advanced development work done from an external source. Will post up my outline / design structure and if anyone else has beneficial ideas to add please do.

For our perspective, time and billing is an important factor. We need time entries/activities to be recorded against a ticket, and then based on specifics against the client's agreement (included hours, billing increments, or certain overriding rates) the billing is generated and emailed. 

The design approach for billing would be similar to how the process payroll is at present - though I have already considered to generate a DataTable on the billing doc with all invoices accessible in one click (new window) in case they need items added to them quickly. 

The time entries/activities would use the timer functionality in v11 (when it is fixed - open issue against it at present). So this would allow fast entries quickly and to accurately capture time.

The introduction of Frappe Charts allows for very nice graphing also, so have considered for reporting / SLA analysis using these, with the inbuilt email alerting Frappe already has. Think some of your points can be crossed off already as is given the functionality is there, however just needs to be adapted to this particular section.

Anyway, will try to post some more details soon.

Cheers
Owz

**Comment by federicocalvo** [comment]
Hi @OneiricIT , any news for this?

**Comment by OneiricIT** [comment]
Hi @federicocalvo thanks for following up.

Actually we nearly have a usable base setup - been many delays on our end with it so far behind where we wanted to be.

Just started to use it internally to get rid of many issues. Will fix up our current issues at hand and then release on Github for others to also work on and possibly use components / workflows in core if it works as a whole. 

No documentation created for it, might find some time to map out functions that are operable.

No doubt there are many ways to do the coding side, so how our developer has done these is how they know how but if there are better / more efficient coding that can be contributed to it the better it will be 👍 

But always better when there are great ideas and multiple coders involved :D thanks for offering, will be great to see this grow exponentially outside of our current workflows / processes. 

Will post the repo soon!

**Comment by OneiricIT** [comment]
@federicocalvo I just noticed the merge of @hrwX SLA module!! We can look to integrating this in too if we cannot get much of this to the core - SLA was on the list but was down the track.

https://github.com/frappe/erpnext/pull/16828

**Comment by OneiricIT** [comment]
@federicocalvo apologies on the delay - soon turned out to not be soon.

In any case, we have just moved the current IT Services app up to Github! Be kind - first contribution to community so hope it is received well!

https://github.com/OneiricIT/IT_Services

There is no readme done yet or any written documentation however will eventually draft something up. There are some fields within which don't yet do anything, however it is usable and we have been using for over a month now fixing up issues along the way. Note though we have only done one invoice processing run which had a few issues we ironed out so the next one is in another 12 days so most likely will have a few more fixes for that.

Would be great to get other contributions to make this a million times better! Not certain if this is in any way eligible as a core product so not presenting it as such for now. 

Shout out to Paul (@mats) our developer for bringing it this far. 

Some Features:
- Sales Order to Ticket
- Delivery feature in ticket from sales order to capture receiving details and create delivery note based on sales order items delivered. It does not move you off to another area of ERPNext, just opens a modal then closes within ticket. Can do multiple deliveries based on part or full delivery of sales order. Signature and receiver info saved in Delivery note.
- Time entries in ticket have timer, and based on either the global item override settings in IT Services Setup, or the contract the ticket is affiliated with which has further override over global, the billable time is rounded.
- Ticket to Quotation
- Add products to tickets
- Invoice processing once a month for all billable activities in all tickets based on time frame. We only do invoicing once a month for tickets and contracts so didn't need to allow for weekly, quarterly etc.
- Invoice processing creates draft invoices allowing to be altered and reviewed, then button will send all out to listed contacts based on email template and default print format.
- Contracts allowing included hours per month, items which are included against the included hours per month, the allowance to make items not billable at all, and recurring charges billed monthly.

Notes:
- SLA not touched at all, so blank
-  Some fields in areas do nothing however are generally labelled so but there might be a few that are not (recipients in tickets for example don't)
- This is still a work in progress, so there are still things that need to be addressed as is on top of any new features coming. 

Reach out if you want to discuss this more - would be good to get a group in the industry working on it.

Some screenshots!

**Tickets**
![image](https://user-images.githubusercontent.com/22227933/57135198-e77d4700-6deb-11e9-99d3-dbb5b133fae7.png)
![image](https://user-images.githubusercontent.com/22227933/57135422-b3565600-6dec-11e9-9902-a365d3804b91.png)
![image](https://user-images.githubusercontent.com/22227933/57135459-d41eab80-6dec-11e9-8d99-a6ff8f8e5eed.png)
![image](https://user-images.githubusercontent.com/22227933/57135542-1811b080-6ded-11e9-8e2e-008ff4ec8a9a.png)
![image](https://user-images.githubusercontent.com/22227933/57135580-3d9eba00-6ded-11e9-9c22-7c87c3675d26.png)

**Contract**
![image](https://user-images.githubusercontent.com/22227933/57135816-15638b00-6dee-11e9-921a-855e8c70aeff.png)
![image](https://user-images.githubusercontent.com/22227933/57135897-4e036480-6dee-11e9-9559-0f500125c038.png)
![image](https://user-images.githubusercontent.com/22227933/57135917-67a4ac00-6dee-11e9-989d-27c55c8d5553.png)
![image](https://user-images.githubusercontent.com/22227933/57136378-fc5bd980-6def-11e9-9ec4-6d60a90be020.png)

**Invoice Processing**
![image](https://user-images.githubusercontent.com/22227933/57136462-4cd33700-6df0-11e9-95b0-65f47e47a2ea.png)
![image](https://user-images.githubusercontent.com/22227933/57136484-5c528000-6df0-11e9-89cf-553fa169a64b.png)

**Comment by wojosc** [comment]
We will have a look at your app when we finde the time and are happy to give feedback as we are in the same industrie. Meanwhile we have been working with @barredterra on https://github.com/wojosc/it_management to get the documentation/CMDB side of the job done.

**Comment by woakes070048** [comment]
I have been playing with both of these plugins. They are very well done. There is also this too. https://github.com/itsdaveit/ITSDoc

**Comment by OneiricIT** [comment]
> We will have a look at your app when we finde the time and are happy to give feedback as we are in the same industrie. Meanwhile we have been working with @barredterra on https://github.com/wojosc/it_management to get the documentation/CMDB side of the job done.

@wojosc @barredterra Great! Will take a look ourselves as this was something we were also going to take a look at eventually. We can easily link these within tickets and have a dashboard against the item relating to linked tickets.
Are you also going to look at encrypting data fields in DB (or create a encrypted field type in core) with critical information? Something with the ability to have the information hidden with asterisk's (for those with access to it) and button to show it on click. Also data at rest such as backup files generated? This is our primary concern when putting this data into ERPNext, as even the backups are not encrypted.

**Comment by wojosc** [comment]
Yes,We have noticed that IT would be nice to be able to störe Device passwords, confgurations, ssh keys etc directly to the User Account or Device in question, thus beeing configuration items. Though we are also concerned on where Data will be stored and how. For the Moment we have keepass databases for each customer.                                                                                                                                                                                                                Von: OneiricITGesendet: Montag, 13. Mai 2019 23:13An: frappe/erpnextAntwort an: frappe/erpnextCc: Wolfram Schmidt; MentionBetreff: Re: [frappe/erpnext] Feature: Turning Support into a real Help Desk (#3877)
We will have a look at your app when we finde the time and are happy to give feedback as we are in the same industrie. Meanwhile we have been working with @barredterra on https://github.com/wojosc/it_management to get the documentation/CMDB side of the job done.

@wojosc @barredterra Great! Will take a look ourselves as this was something we were also going to take a look at eventually. We can easily link these within tickets and have a dashboard against the item relating to linked tickets.
Are you also going to look at encrypting data fields in DB (or create a encrypted field type in core) with critical information? Something with the ability to have the information hidden with asterisk's (for those with access to it) and button to show it on click. Also data at rest such as backup files generated? This is our primary concern when putting this data into ERPNext, as even the backups are not encrypted.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/frappe/erpnext/issues/3877?email_source=notifications\u0026email_token=AFJ7LRKHSH2PVRJYJBBFFZDPVHKXZA5CNFSM4BNQ6UWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVJSQBA#issuecomment-491988996",
"url": "https://github.com/frappe/erpnext/issues/3877?email_source=notifications\u0026email_token=AFJ7LRKHSH2PVRJYJBBFFZDPVHKXZA5CNFSM4BNQ6UWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVJSQBA#issuecomment-491988996",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by barredterra** [comment]
Credentials can already be stored encrypted by ERPNext (fieldtype: `Password`) but they are not supposed to be displayed back to the user. ERPNext is not a password Manager (yet).

Regarding data security: data is encrypted in transit by TLS and stored in a Database, typically on your ERPNext server. As far as I know, passwords (data entered through `Password` fields) are encrypted symmetrically with a key that is stored on your server. Other data is stored in plain text on the server.

**Comment by wojosc** [comment]
@alv000h
> Hi all,
> 
> It would be interesting to add support for "ticket priority" and SLA management.
> 
> I was thinking in something more ITIL oriented.
> 
> Nothing too complicated, but with some features like:
> 
>     * Lead escalations when too much time for first response occurs...
> 
>     * Different levels of priority (high, normal, low)
> 
>     * Different resolution times based on priority (high priority, 1h; medium priority 4h, something like that)

This has been implemented in v12.

**Comment by sharmanakul** [comment]
@harshit-30 might be of your interest

**Comment by harshit-30** [comment]
@sharmanakul yes, have reviewed it already.
