### ISSUE TITLE
Error in importing group item (as parent-child)

### ISSUE THREAD

**Issue by bakhtari** [frappe/erpnext#39540]
### Information about bug

In version 15 of ERPNext, if we extract an Item Group with all its fields from one domain and import it into another domain with the same version, an error occurs. I think the reason is that during import, a child group may be read first, and then a few lines below, the parent information is entered. The system should be able to handle this point when exporting. I believe it can be controlled by adjusting the creation time.

### Module

stock

### Version

Frappe;15
Erpnext:15

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @bakhtari,

Actually, it's not a bug, when you import tree related master then first have to import the parent item group and then the child   item group because import time when import the first child item group then parent item group missing/error show in import log. So you have sort out the Excel (First parent and then child)and again import it. As per the my understanding, it's doesn't check the creation of time.

I hope this helps.

Thank You!
