### ISSUE TITLE
Rename debit_to and credit_to field to party_account in Sales / Purchase Invoice

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#3958]

**Comment by Tropicalrambler** [comment]
Nabin,  I wonder if this issue is the one that is causing the field "Credit To" in Purchase Invoice creation, from me being able to select the proper account.
![screen shot 2016-03-17 at 1 51 59 pm](https://cloud.githubusercontent.com/assets/16600935/13859135/7fac831c-ec47-11e5-922c-02e0de03d49d.png)

**Comment by nabinhait** [comment]
No, that is not the issue. I have listed a housekeeping task here, to rename those fields. We have purposefully redirect the creation of account to Chart of Accounts.

**Comment by Tropicalrambler** [comment]
Ok, should I open a new issue for this specific bug, or should I do that?

**Comment by harshit-30** [comment]
Please create a new issue if the problem persists.
