### ISSUE TITLE
(Paid Development) Buy Product Bundles

### ISSUE THREAD

**Issue by sliska** [frappe/erpnext#3969]
Hi,

The product bundle feature is very convenient. 

1. We'd like ERPNext to generate stock entries when a product bundle is purchased and received. 

2. Also, we'd like to be able to apply the cost of the bundle to one of the components so that it will register in the valuation of the inventory. 

Being able to do this would simplify our purchasing process. 

How much would it cost and how long would it take to make this feature?

thank you!!
Sofia

**Comment by rmehta** [comment]
@sliska sorry for the late reply

Can you explain the second point? You will have to set the valuation on each of the items on the product bundle. Or maybe we will have to have a % value column in product bundle that will split the cost.

**Comment by sliska** [comment]
Hi @rmehta ,

Thanks for your response. I think it would be simpler to set the valuation on each item rather than a percentage. 

We need to be able to give the components a value when we buy a product bundle but we need to be able to give the components another value when we buy them individually. 

For example, we buy product bundle A (PBA). It costs $100 and it includes components 1, 2, and 3. As components of PBA, I would divide the $100 as follows: C1 = $98, C2 = $1, and C3 = $1. But when we purchase C2 and C3 as separate items not part of PBA, we pay $10 for C2 and $10 for C3. 

I'd like to be able to buy the product bundle, apply the values based on the purchase of the product bundle, and in a separate line item be able to buy additional components with a different value. 

Is this possible?

thanks again,
Sofia

**Comment by rmehta** [comment]
@sliska sounds good. Here is what is required

- [ ] Add packed item table in Purchase Receipt and Purchase Invoice (either could be booked first)
- [ ] Wiring for valuation rate and qty from packed item table for Purchase Receipt
- [ ] Check impact on Purchase Invoice and perpetual inventory, landed costs etc.

This one seems tricky though specially with landed costs and booking of inventory + tax rules. 

Is $400 fine? Thanks!

**Comment by sliska** [comment]
hi @rmehta, 

Would you guys consider doing it for $300? We think it could be useful for a lot of other people as well. 

regards,
Sofia

**Comment by rmehta** [comment]
@sliska yeah we can do it. But we will be able to take it up next month, once the first issue is done.

**Comment by sliska** [comment]
@rmehta,

okay thanks, sounds good. We'll do that then. Please send the invoice.

**Comment by rmehta** [comment]
@sliska thanks! We will send you an invoice once the delivery note project is done. Thanks!

**Comment by rmehta** [comment]
@sliska Shall we send you the invoice for this? ETA will be next week. @PrakashH

**Comment by sliska** [comment]
yes please! excellent. thanks.

**Comment by sliska** [comment]
Hi Rushabh,

When can we have a look at the advances?

thanks,
Sofia

**Comment by rmehta** [comment]
@sliska This goes into development today. Some projects took longer than we anticipated.

**Comment by sliska** [comment]
Okay sounds good.

**Comment by saurabh6790** [comment]
- [ ] Add `Packed Item` table in PO, PR and PI
- [ ] Cosider packed items for inventory update for actual qty and ordered qty
- [ ] Stock Ledger Entry for packed items instead of bundle item
- [ ] Enter packed item manually and vilidate total cost of packed items with each bundle item
- [ ] Valuation related charges will be distributed proportionately on packed items and will be cosidered in incoming rate of sle.
- [ ] Check Landed Cost Funtionality related to this
- [ ] Add Rejected Serial No field in Packed Item table

**Comment by nabinhait** [comment]
@sliska I was working on the issue in the last week. After completion of almost all the things, I realised that the changes I made, is adding too much complication in the core logic. There is a huge chance to introduce new bugs in the core logic due to this. And maintenance of the new code will also be very difficult in the long run.

Then I discussed about this with all the team members and decided to scrap the work, as the feature will be used by very little number of users.

We are very sorry, that we could not be able to deliver the feature. We will surely refund the amount you have paid for the feature, please send an email to support@erpnext.com, with your bank details.
