### ISSUE TITLE
Maintain same rate in Purchase Cycle  Not working in v15

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#40159]
### Information about bug

https://github.com/frappe/erpnext/assets/21578167/78d4de3c-7f33-4d06-84e8-885e5ae403c9

The rate is auto-changing while making a Purchase receipt whereas in buying setting Maintaining the same rate is checked

### Module

buying

### Version

ERPNext: v15.14.6 (version-15)

Frappe Framework: v15.15.0 (version-15)

Frappe HR: v15.12.0 (version-15)

India Compliance: v15.5.3 (version-15)

### Installation method

manual install

**Comment by ishanloya** [comment]
I have the same issue

**Comment by Govind-Jangid** [comment]
Facing in Sales Cycle as well

**Comment by ishanloya** [comment]
Can confirm that this isn't fixed in 15.16.0 either even though #40241 is supposed to have fixed the issue

**Comment by ishanloya** [comment]
Could someone from the team please provide an update on this? Seems like a pretty important issue given that maintaining the same rate is critical in both sales and purchase cycles for most businesses.

**Comment by dineshpanchal93** [comment]
@ishanloya Issue not fixed yet

**Comment by casesolved-co-uk** [comment]
> The rate is auto-changing while making a Purchase receipt whereas in buying setting Maintaining the same rate is checked
> 

@dineshpanchal93 Your video example doesn't actually save the document so isn't really a great example. I agree this is a huge issue, but all validation takes place on Save, so you really need to show that in the video

**Comment by dineshpanchal93** [comment]
Its already resolved i think so

**Comment by Nihantra-Patel** [comment]
@casesolved-co-uk, don't create a multiple-issue, if issue is still open then you can paste the issue here. sorry @dineshpanchal93 you can track on new issue.

Maintain Same Rate Throughout Sales Cycle:
- It ensures that the same rate is maintained throughout the sales process. Once enabled, It will validate whether an Item's price is changing in a Delivery Note or Sales Invoice created from a Sales Order.

Action if Same Rate is Not Maintained Throughout Sales Cycle:
- You can configure the action that system should take if the same rate is not maintained in the "Action If Same Rate is Not Maintained Throughout Sales Cycle" field:
    - Stop: ERPNext will stop you from changing the price by throwing a validation error.
    - Warn: The system will let you save the transaction but warn you with a message if the rate is changed.

Note: This field will only be visible if [Maintain Same Rate Throughout Sales Cycle](https://docs.erpnext.com/docs/v13/user/manual/en/selling/selling-settings#2-maintain-same-rate-throughout-sales-cycle) is enabled.

Validation already set if you change the value or qty.

![image](https://github.com/user-attachments/assets/3ffd9e69-5bb2-4e2d-90fd-3e6afbf362fe)


@casesolved-co-uk, 
Before creating an issue, make a complete video of where the issue comes from. Read the documentation, see the validation, then create an issue.


And if you know about the issue, then simply raise the Pull Request, i know you are the contributor.

**Comment by casesolved-co-uk** [comment]
@Nihantra-Patel I don't raise pull requests any more because they are nearly always ignored and closed.

You'll notice my issue is for selling not buying, and is a different issue altogether.

I won't be making videos either, for the issues to be ignored and closed.
