### ISSUE TITLE
Add Stop / Close Status from in Sales Invoice

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#4070]

**Comment by sbkolate** [comment]
As we can keep track stop/close of Sales Order in comment, this issue can be closed.


Also can deprecate close or stop since both are same.
https://discuss.erpnext.com/t/what-is-the-difference-between-stop-and-close-action-in-sales-order-and-purchase-order/9040 

we can also add Stop button in Sales Invoice//Purchase Invoice to stop from making payment entry when user directly created Sales Invoice/Purchase Invoice

**Comment by Olawale1** [comment]
Hi,

Is this still in the works pls?

Kind regards,
