### ISSUE TITLE
Enable Prepared Report - Change Auto

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#41068]
### Information about bug

https://github.com/frappe/erpnext/assets/21578167/a3b0c852-052d-44ae-9155-3e2bb0eb77f2

### Module

other

### Version

ERPNext: v15.19.0 (version-15)

Frappe Framework: v15.20.0 (version-15)

Frappe HR: v15.16.0 (version-15)

India Compliance: v15.7.0 (version-15)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
https://discuss.frappe.io/t/we-have-migrate-from-v14-to-v15-with-no-customisation/121294/3
```

**Comment by Nihantra-Patel** [comment]
After untick the "Enable Prepared Report", please refresh the page (ctrl + shift + R)

Please check it out.


https://github.com/frappe/erpnext/assets/141945075/898f50ef-678d-43e4-bb67-e55d2564b188

**Comment by dineshpanchal93** [comment]
@Nihantra-Patel I know its working fine my end as well

If I set the new site with no data and having less data it worked fine

But if the report is too lengthy and anyone is migrated from v14 to v15 these problems arrives

I hope you can have a look into it.

**Comment by Nihantra-Patel** [comment]
Also, I tried with a general ledger and a stock ledger because, as you know, ledgers have a lot of data, but we haven't found the issue. and after your first message, i migrated the v14 data to v15, so no issue was found. but i will try multiple ways; if I find anything, then will update you.

**Comment by dineshpanchal93** [comment]
Sure thanks !!!

**Comment by dineshpanchal93** [comment]
I tried with updating the latest version

ERPNext: v15.20.5 (version-15)
Frappe Framework: v15.23.0 (version-15)

if you can find anything in below attached video even I am confusing

https://github.com/frappe/erpnext/assets/21578167/002366b6-91b7-4b0a-a748-34000178df13

I tried all settings somewhere i am wrong.

**Comment by Nihantra-Patel** [comment]
😅 This also occurs in version 14 and 15 if there is a lot of data, making it necessary to prepare data without generating a report. It's a common occurrence, which is why the Prepared Report feature is provided. When users generate a report, they can easily check it without wasting time.

For instance, if you have 5 years of data stored in the system and you disable the prepare report option, the report will take approximately 3-4 minutes to generate. However, if you enable the prepare report option, you first set the filters and generate the report, saving around 80% of your time.

hope this helps! 😉

**Comment by dineshpanchal93** [comment]
@Nihantra-Patel  I See.

This same data I have in v14 as well I won't get any auto option for the generate report. but anyway, we need to find some different solutions. if I have anything, I will let you know.

Thank you so much for getting back to me so quickly.
