### ISSUE TITLE
Employee Advance Status is not updating after payment Entry

### ISSUE THREAD

**Issue by rahmed-dev** [frappe/erpnext#41214]
### Information about bug

Employee Advance
![image](https://github.com/frappe/erpnext/assets/142441014/cbac9ef4-eef3-449c-9229-993854630aab)

Payment Entry
![image](https://github.com/frappe/erpnext/assets/142441014/a992056b-668d-4837-bd62-371dbd7f0f45)

### Module

accounts, HR

### Version

Frappe CRM: v0.0.1 (develop)

ERPNext: v15.17.0 (version-15)

Frappe Framework: v15.17.3 (version-15)

Frappe HR: v16.0.0-dev (develop)

KSA Accounts: v0.0.1 (main)

Frappe Lending: v0.0.1 (develop)

Payments: v0.0.1 (develop)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Issue has been already fixed: https://github.com/frappe/hrms/issues/1694
PR: https://github.com/frappe/erpnext/pull/41183


https://github.com/frappe/erpnext/assets/141945075/e2ccc691-02e2-42aa-86b2-9db1150b937b

I've shared a suggestion:
If you've installed ERPNext in version 15, make sure the hrms is also in version 15 to prevent errors.

If the hrms is in the development branch, switch to it:

```bash
bench switch-to-branch version-15 hrms
```

If you've uninstalled or installed the app, do this:

```bash
bench get-app --branch version-15 hrms
```

This is because the hrms app has a version 15 branch.

I hope this is clear and helpful.
