### ISSUE TITLE
Change Payment Tool to allow easier removal of invoices to pay

### ISSUE THREAD

**Issue by ekpaxp** [frappe/erpnext#4121]
When using the Payment Tool for a particular supplier that can have up to 300 invoices during a month, once "Get Outstanding Vouchers" is pressed, it can take quite a while to remove certain invoices that are not needed to be paid as each one needs to be edited and then removed.
To improve efficiency, is it possible to add a "Pay" tick box next to each line so that when the Payment is processed, only the lines with Pay flagged will be processed?
Thanks

**Comment by anandpdoshi** [comment]
Hi Ardan,

In this week’s release there will be a checkbox added “Set Payment Amount = Outstanding Amount” above the Get Outstanding Invoices. If not checked, all invoices will be fetched with Payment Amount blank. Then you just need to enter Payment Amount in the desired invoices and only those will be processed.

-- 
Anand Doshi
Sent with Airmail

On 5 October 2015 at 8:53:14 am, Ardan Peddell (notifications@github.com) wrote:

When using the Payment Tool for a particular supplier that can have up to 300 invoices during a month, once "Get Outstanding Vouchers" is pressed, it can take quite a while to remove certain invoices that are not needed to be paid as each one needs to be edited and then removed.
To improve efficiency, is it possible to add a "Pay" tick box next to each line so that when the Payment is processed, only the lines with Pay flagged will be processed?
Thanks

**Comment by ekpaxp** [comment]
Hi Anand, 

That sounds great. 

Look forward to the release :-) 

Best regards, 

Ardan 

----- Original Message -----

**Comment by ekpaxp** [comment]
Hi Anand, 

I just looked at the new functionality in the develop branch and it seems to me that it would make more sense to put the " Set Payment Amount = Outstanding Amount" checkbox against each row rather than an overall flag. 

Reason is that even if the " Set Payment Amount = Outstanding Amount" flag is not set, the user will still need to go into each row to set the payment amount - no difference in work from deleting the records that are not to be paid. 

In some cases we have seen, the user has over 300 payments to be made to a single supplier so you can imagine if say 2/3 of the records are to be paid, that is 200 individual edits to be done, - or 100 rows need to be deleted, as opposed to ticking a tick box for each line that is to be paid the outstanding amount? 

Any row edits would then be limited to editing any Payment Amounts that are not the Outstanding Amount. 

What do you think? 

Best regards, 

Ardan 

----- Original Message -----
