### ISSUE TITLE
Email not sent to xxx@xxxx.com (unsubscribed / disabled)

### ISSUE THREAD

**Issue by chanyork** [frappe/erpnext#41327]
### Information about bug

I have selected to send me a copy of the email send out in Sales Invoice.  However, when clicking send it give me an error above.

### Module

selling

### Version

ERPNEXT Version 13.55.2
FRAPPE 13.58..21

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Email not sent to xxx@xxxx.com (unsubscribed / disabled)
```

**Comment by Nihantra-Patel** [comment]
We tested in v14 and v15, Everything is working fine. No problems were encountered in the latest versions 14 and 15.

**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
