### ISSUE TITLE
Debit and Credit not equal for Sales Invoice

### ISSUE THREAD

**Issue by chanyork** [frappe/erpnext#41330]
### Information about bug

I am having issue to submit sales invoice #SINV-2405-02-1, when I have additional discount added it gives me an error.

Debit and Credit not equal for Sales Invoice #SINV-2405-02-1. Difference is XXXXX

### Module

selling

### Version

ERPNext: v13.55.2 (HEAD)
Frappe Framework: v13.58.21 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Debit and Credit not equal for Sales Invoice #SINV-2405-02-1. Difference is XXXXX
```

**Comment by Nihantra-Patel** [comment]
**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
