### ISSUE TITLE
Session Stopped

### ISSUE THREAD

**Issue by codexkenza** [frappe/erpnext#41410]
### Information about bug

Getting Session stopped Error

![Screenshot (75)](https://github.com/frappe/erpnext/assets/125698331/50afdde9-a72a-4a6b-838c-7bf01f7da23e)

### Module

other

### Version

ERPNext: v15.23.0 (version-15)

Frappe Framework: v15.26.0 (version-15)

Frappe HR: v16.0.0-dev (develop)

Print Designer: v1.0.0 (develop)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
      request = <Request 'http://192.168.100.137/api/method/frappe.realtime.get_user_info?sid=6cca860198f69c3129e6f72c2fe683658d1a79f741c7001187b12002' [GET]>
      response = None
      rollback = True
      e = SessionStopped('Session Stopped')
  File "apps/frappe/frappe/app.py", line 179, in init_request
    raise frappe.SessionStopped("Session Stopped")
      request = <Request 'http://192.168.100.137/api/method/frappe.realtime.get_user_info?sid=6cca860198f69c3129e6f72c2fe683658d1a79f741c7001187b12002' [GET]>
      site = 'erp.goldwala.pk'
frappe.exceptions.SessionStopped: Session Stopped
```

**Comment by Nihantra-Patel** [comment]
If the Frappe application is in maintenance mode and the configuration does not allow reads during maintenance, then the session is stopped by raising frappe.SessionStopped("Session Stopped").

This typically happens when the application is undergoing maintenance and reads are not permitted to avoid any potential inconsistencies in the data. During this time, only specific operations may be allowed, such as updates or administrative tasks, while regular users are prevented from accessing the system to ensure data integrity.


I've shared a suggestion:
If you've installed ERPNext in version 15, make sure the hrms is also in version 15 to prevent errors.

If the hrms is in the development branch, switch to it:

```bash
bench switch-to-branch version-15 hrms
```

If you've uninstalled or installed the app, do this:

```bash
bench get-app --branch version-15 hrms
```

This is because the hrms app has a version 15 branch.

I hope this is clear and helpful.
