### ISSUE TITLE
Purchase Invoice must update Stock Valuation

### ISSUE THREAD

**Issue by jof2jc** [frappe/erpnext#4182]
I found 'serious issue' which is....Purchase Invoice doesn't update stock valuation. There's some business facts we must understand:
1. Purchase receipt rate is not always same with invoice rate...due to rate changes, correction, final discount from supplier etc
2. Additional costs that may occur at invoice time.

We can do all above in the purchase invoice if allowance percent is allowed, but unfortunately it doesn't update valuation per stock item. This issue definitely will cause wrong valuation that affects wrong calculation of stock assets value, COGS & profit/loss calculation

I just wondering why no ERPNext customers who aware on this issue

See thread here https://discuss.erpnext.com/t/different-rate-between-purchase-receipt-and-purchase-invoice/7488/6

Please other users inputs...Thanks

**Comment by jof2jc** [comment]
Any comment from other users on this issue?

**Comment by nabinhait** [comment]
@jof2jc Thanks for your input, your point is very much valid. If there is any additional costs in tax table, that can be managed via Landed Cost Voucher. But as we are allowing to change rate in Purchase Invoice, there should be a way to update item valuation as per changed rate.

But as there is a multiple-to-multiple relationship between PO, PR and PI and those documents can be made in any order, it is a very difficult problem to solve. Anyway, we will discuss on it internally, and let you know how we can solve the issue.

**Comment by jof2jc** [comment]
@nabinhait Have you found any solutions for this? Thanks

**Comment by nabinhait** [comment]
@jof2jc We have discussed it internally, but did not found any easy solution yet, to fix the issue. Will update you as soon as we found any solution.

**Comment by jof2jc** [comment]
@nabinhait thanks for this, waiting for the solution....btw, sorry if this one is slightly out of this topic, BUT it's still related to wrong costing calculation. I'm using ERPNext for quite sometime for live environment so now I'm getting wrong stock calculation due to this issue as well. I believe many other customers don't aware too..

If you don't mind to get a chance to take a look at this too:
https://discuss.erpnext.com/t/fifo-does-not-work-on-repack-entry-for-batch-items/7963

**Comment by noetico** [comment]
@jof2jc Thanks for posting this; I also came accross this issue today; ERPNext is just amazing anyway; The possibilities just blow other software (+commercial) out of the water. Just some little issues; yes; even on posting purchase receipt and payments; your entries do not get featured in "stock expenses" for instances; you will see entries inside the trial balance and elsewhere; but looking at your Direct Expenses for stocks; you will not find your expenses in closing a purchase trail, order-receipt-payment-invoice. I am wondering why? I hope this gets serious attention as a core issue. But for the team; I say good work; wish I could donate something good for the good work so far. Outstanding.

**Comment by jof2jc** [comment]
@nabinhait any solution update? This is core related issue. Costing is crucial part in an ERP system..

**Comment by jof2jc** [comment]
Can we add 'update stock' option in purchase invoice..just lije in sales invoice.

If this option is checked:
- if the item has purchase receipt ref, then system will just update valuation if item rate changes at invoice time.
- if no purchase receipt ref, then system will also execute purchase receipt posting directly from invoice. Just like in sales invoice to update stock delivery/COGS when the option is checked.

Can we apply this solution for purchase cycle?

**Comment by jof2jc** [comment]
@nabinhait any update on this? Tks

**Comment by Devens** [comment]
@rmehta "Update Stock" facility for Purchase Invoice is very important. This can eliminate duplication of entries (Like first enter Purchase Receipt, and then Purchase Invoice), as majority of the times Purchase receipt (Delivery Challan from vendor) comes along with purchase invoice. 

Avoiding duplication of entry does not mean only time saving, But, it also eliminates one additional check-point. Previously we were using and getting quickly off the mark (Fast Deployment). One of the reason (now I realize) was that right from beginning, this feature was available. 

Please advise for your view/plan on this.

**Comment by rmehta** [comment]
@Devens  we will be merging the contribution by @jof2jc soon to "develop"

**Comment by nununo** [comment]
Any news on this "update stock" feature in the Purchase Invoice? 

Since most of my purchases are things I buy directly in a store and bring with me to my studio... I don't really see any advantage in having to enter both a Purchase Receipt and a Purchase Invoice. 

The Purchase Invoice with "update stock" option would be perfect.

Thanks!

**Comment by noetico** [comment]
‎Hello Nuno;What we do is simply make a purchase receipt straight on! I assume you get a hard paper invoice from the market. In our case; we make the the PR, from there we simply go through the pipeline and post the expenses involved. The purchase invoice with update stock may create some issues with organizations that require a strict adherence to workflow; but no doubt; it will be a fine feature! So fine. One feature we will like to have is also to be able to set the selling price of an item in the item doctype; a drop down to select the price list and then a text field for the price. For now; we use a workaround where we create a field to enter the price; then that data gets pulled using a custom script in the item price doctype. It's a little bit cyclic but it's proven quite effective.                                                                                                                                                                                                   Noetico Professional Services                                                                                                                                                                                                                From: Nuno GodinhoSent: Tuesday, July 12, 2016 00:15To: frappe/erpnextReply To: frappe/erpnextCc: noetico; CommentSubject: Re: [frappe/erpnext] Purchase Invoice must update Stock Valuation (#4182)Any news on this "update stock" feature in the Purchase Invoice? 

Since most of my purchases are things I buy directly in a store and bring with me to my studio... I don't really see any advantage in having to enter both a Purchase Receipt and a Purchase Invoice. 

The Purchase Invoice with "update stock" option would be perfect.

Thanks!

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by nununo** [comment]
Hello noetico, undestood. Thanks for your explanation.

**Comment by jof2jc** [comment]
Update Stock option in Purchase Invoice will be available in upcoming v7 by
end of july. You can test it on develop branch to try v7

**Comment by noetico** [comment]
Aha! Now that's good news! Simplifies a lot of things. @jof2jc; how about ability to enter selling prices in item doc and other stock receipt docs (PR, Invoice). ‎This will also be a great addition; just 2 fields; rate and drop-down for selling price list selection. Please! Thanks.                                                                                                                                                                                                                                                                                                                                        Noetico Professional Services                                                                                                                                                                                                                From: jof2jcSent: Tuesday, July 12, 2016 12:24To: frappe/erpnextReply To: frappe/erpnextCc: noetico; CommentSubject: Re: [frappe/erpnext] Purchase Invoice must update Stock Valuation (#4182)Update Stock option in Purchase Invoice will be available in upcoming v7 by
end of july. You can test it on develop branch to try v7

On Jul 12, 2016 6:18 PM, "Nuno Godinho" <notifications@github.com> wrote:

> Hello noetico, undestood. Thanks for your explanation.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/frappe/erpnext/issues/4182#issuecomment-232011798>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMPxjTIePAKM9vmLAP9oF8dBXM0j6d7Rks5qU3gGgaJpZM4GP_zB>
> .
>


—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jof2jc** [comment]
@rmehta @nabinhait I don't think currently Purchase Invoice updates stock valuation if item rate is changed to due discount etc at invoice stage..

Currently update stock option only acts to receive new incoming items..

Can you verify this? I'm on V7.1..

Thanks

**Comment by jof2jc** [comment]
@nabinhait This is 'critical' issue. Would you take some time to verify this? If on invoice the item price is changed, then valuation rate is not updated...

Many business cases require this...many times purchase receipt rate is not final price..

**Comment by SaiFi0102** [comment]
https://github.com/frappe/erpnext/pull/16659
