### ISSUE TITLE
Asset Depreciation Ledger Report Issue: Missing Data Without Financial Book Filter

### ISSUE THREAD

**Issue by Subramani830** [frappe/erpnext#41915]
### Information about bug

In the Asset Depreciation Ledger report, the "financial book" filter is optional. However, if this filter is not specified, the report fails to fetch any values and displays "nothing to show." This issue occurs despite the filter being non-mandatory, resulting in no data appearing in the report when left unfilled.
Find the SS attached below:
![image](https://github.com/frappe/erpnext/assets/75359186/7c8354d7-8c5a-4d68-84ad-261802980bfc)
![image](https://github.com/frappe/erpnext/assets/75359186/37f7634e-5158-444e-af39-602722ba79b8)

Thank You.

### Module

accounts

### Version
Frappe Framework: v15.29.2
ERPNext: v15.27.6

### Installation method

None

**Comment by khushi8112** [comment]
Hi,
The issue arises because, when the financial book filter is left unfilled, the current functionality of the report attempts to find assets that do not have any financial book specified at the time of depreciation. In your case, there are no assets without a financial book, which is why the report returns no data.
