### ISSUE TITLE
Send email from quotation send multiple time

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#41953]
### Information about bug

send quotation to 2 receivers
![image](https://github.com/frappe/erpnext/assets/62122640/b8be89db-9918-4312-ae45-0aa6698edfb0)
system send out 3 email to each receiver
![image](https://github.com/frappe/erpnext/assets/62122640/aec5a098-05e0-469b-90da-5455e5a4b95c)

### Module

accounts

### Version

Frappe : 14.68.2
ERPNext : 14.65.8

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hey, but how do you send mail? Triggered automatically, whether you send it yourself or send it from Communication.
We checked, but we didn't find anything like this, so please provide the step.

**Comment by thida-bcn** [comment]
> Hey, but how do you send mail? Triggered automatically, whether you send it yourself or send it from Communication. We checked, but we didn't find anything like this, so please provide the step.

from quotation >> email 
![image](https://github.com/frappe/erpnext/assets/62122640/4ac0ba36-fcbc-4106-ae2a-890b17ba27d8)

**Comment by Nihantra-Patel** [comment]
Kindly upgrade your version 14 because everything is working fine. No problems were encountered in the latest version 14.

![image](https://github.com/frappe/erpnext/assets/141945075/9a7860c3-122c-44af-a78f-d9146dbea599)

![image](https://github.com/frappe/erpnext/assets/141945075/4e35caac-1a07-4a4e-ad80-693eb411722d)

![image](https://github.com/frappe/erpnext/assets/141945075/3e9a9037-aa4c-41f7-ba5f-a009f5585ca7)

![image](https://github.com/frappe/erpnext/assets/141945075/92c869f5-c94b-4f5f-8259-6e2625f3e30c)

![image](https://github.com/frappe/erpnext/assets/141945075/973a208c-d3df-4322-b50c-9896489d4954)

![image](https://github.com/frappe/erpnext/assets/141945075/431b2f9e-2b03-4bb1-8268-748d386decdb)

![image](https://github.com/frappe/erpnext/assets/141945075/4a15af52-daec-481f-ad95-7590a1ad0561)
