### ISSUE TITLE
Default Bank Account

### ISSUE THREAD

**Issue by usman-alikhan** [frappe/erpnext#42039]
### Information about bug

When bank account is created for a Supplier (party) and default is checked in that bank account, at the time of creating a Payment Entry the party default bank account appears in field "Company Bank Account" instead of "Party Bank Account". 

### Module

accounts

### Version

latest version 15

### Installation method

None

**Comment by Nihantra-Patel** [comment]
I know this isn't a bug.

It's defined properly. If you want to set the party account, create a new bank account and select it when you create a payment entry. Otherwise, set it as default, and when you create the payment entry, it will automatically appear.


https://github.com/frappe/erpnext/assets/141945075/459ee84a-6841-42b7-9b48-66620a210bf7
