### ISSUE TITLE
Pricing Rules Not Applying to Delivery Notes Marked as Return

### ISSUE THREAD

**Issue by hassan-youssef** [frappe/erpnext#42121]
### Information about bug

I'm facing an issue where the pricing rules in ERPNext are not applying to delivery notes marked as returns. I've checked the configuration, and the rules apply to all relevant transactions. Despite this, the rules are not triggered for return delivery notes.

Has anyone else faced this issue? Any suggestions or custom scripts that could help apply pricing rules to return delivery notes would be greatly appreciated.

Thank you!

### Module

stock

### Version

ERPNext: v15.28.0 (version-15)

Expense Request: v0.0.1 (main)

Frappe Framework: v15.31.0 (version-15)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
pricing rule isn't applied in the return invoice. This behavior is by design and not considered a bug. If you wish to override this and apply pricing rules to return delivery notes, you can implement custom logic in your custom app. Otherwise, the default behavior where pricing rules do not apply to return delivery notes will remain unchanged.
