### ISSUE TITLE
Message showing "Please set the document name " in erpnext

### ISSUE THREAD

**Issue by rajubaghel** [frappe/erpnext#42295]
I am getting a message  "Please set the document name "

while I creating stock reconciliation.
![Screenshot 2024-07-12 111653](https://github.com/user-attachments/assets/70a1a408-a213-4fd8-955a-03e42bb712ab)

**Comment by Nihantra-Patel** [comment]
When this message appears, it means that the ID has not been generated.

https://github.com/frappe/frappe/blob/9194eaf80601319078b3b779042abc7d87e12b50/frappe/model/naming.py#L542-L549

Kindly upgrade your version 15 because everything is working fine. No problems were encountered in the latest version 15.


https://github.com/user-attachments/assets/25347847-9b04-457e-b820-b5dd1381e2c0
