### ISSUE TITLE
could not find warehouse type: transit

### ISSUE THREAD

**Issue by thesamug** [frappe/erpnext#42309]
### Information about bug

I installed ERPnext yesterday and plan to put my company information, Once I fill in every detail and save it, it shows the error message " could not find warehouse type: transit ". When I try to create a warehouse it requires the company. Somehow, both of these features are interlinked with each other. This is causing so much trouble that I cannot even put simple company information into the software.

### Module

stock

### Version

ERPNext: v15.29.3

Frappe Framework: v15.34.0

### Installation method

docker

**Comment by gursewak8642** [comment]
Could you please explain the issue briefly and in which doctype you are facing this issue?

**Comment by thesamug** [comment]
I don't have more knowledge about all that stuff.

![image](https://github.com/user-attachments/assets/7f92cb19-5c23-4049-b92a-eb572affb619)
Here is the screenshot for reference.

**Comment by Nihantra-Patel** [comment]
First, check if the "Goods In Transit" warehouse is available with the "Transit" warehouse type.

If not, create it. The Default In-Transit Warehouse is available in the company doctype, but it will appear only after saving the company. If any session default or user-specific(logged user) warehouse default is set, you need to remove it. This is because, at the time of creation, it sets the default warehouse in the Default In-Transit Warehouse.

We tested in v15 latest but we haven't found the this type issue.

**Comment by thesamug** [comment]
When I try to create a warehouse, it requires a company. Now please tell me how to remove the default warehouse.

**Comment by Nihantra-Patel** [comment]
I think the issue is, you haven't completed the setup wizard, So all such problems are coming. first complete the setup wizard

**Comment by thesamug** [comment]
How do I restart the setup wizard?

**Comment by Nihantra-Patel** [comment]
search like setup wizard
