### ISSUE TITLE
Print Format Error

### ISSUE THREAD

**Issue by Egerges-Support** [frappe/erpnext#42497]
### Information about bug

'NoneType' object is not iterable

### Module

selling

### Version

Email Delivery Service: v0.0.1 (HEAD)

ERPNext: v15.31.0 (HEAD)

Frappe Framework: v15.36.0 (HEAD)

Print Designer: v1.4.0 (HEAD)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
'NoneType' object is not iterable
```

**Comment by Nihantra-Patel** [comment]
Such an error can occur in many places, please let us know in detail where the problem occurs. Because no one will know anything in such a description, so please explain in detail. And if there is an issue with Print Designer, then go to the [Print Designer repo](https://github.com/frappe/print_designer/issues) and create an issue.
