### ISSUE TITLE
payment request not showing- Login id-vanaja29@daffygroup.com 

### ISSUE THREAD

**Issue by Daffygroup** [frappe/erpnext#42652]
### Information about bug

We are not showing payment request in the list in login id-vanaja29@daffygroup.com 

And also purchase order not showing  in purchase order list

All issue attached 
kindly resolve the same.
![Payment request-06 8 2024](https://github.com/user-attachments/assets/a0097b68-4284-4e46-8de8-50204f83fa56)
 

### Module

accounts, buying, portal

### Version

Our site,-daffygroup.erpnext.com,

33f276af904d8160079b3d2dd705948c056ff9b

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Ad also not showing  payment release option and not option for purchase order approval kindly do the needful.
```

**Comment by Nihantra-Patel** [comment]
Because something restrictions are applied to that user.

![image](https://github.com/user-attachments/assets/61d6a1ec-5dc6-4e4b-b135-10b6f4b4a59c)

Go to the [User Permission](https://docs.erpnext.com/docs/user/manual/en/user-permissions) doctype, check the user's permissions, remove unnecessary ones, then reload and verify.
