### ISSUE TITLE
Warehouse - Disable Rename Pop up / Modal

### ISSUE THREAD

**Issue by bibinqcs** [frappe/erpnext#42698]
### Information about bug

Rename option for warehouse is non existent in that case why allow the user to click the name to trigger the rename modal or pop up gives the wrong idea that you can rename the warehouse and after clicking rename it does not this gives the impression that rename function is not working.

Kindly disable the rename modal

### Module

stock

### Version

Frappe Framework: v15.37.0
ERPNext: v15.31.5

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hey, you understand a little bit of logic. If it is linked in a warehouse transaction/master, how to delete the warehouse. Check the video I have given below, there is one such warehouse, I have done transactions in it, so it cannot be deleted, but yes if it is not linked to anyone, you can delete it. I created a test warehouse and when I delete it it gets deleted easily. Because this has no transaction/master link. So it's not a bug.


https://github.com/user-attachments/assets/61b7024f-5b09-49f9-9c76-a2e5973414ef
