### ISSUE TITLE
Warehouse - Delete function is not working

### ISSUE THREAD

**Issue by bibinqcs** [frappe/erpnext#42699]
### Information about bug

Cannot delete a warehouse, while trying to delete a message shows up Warehouse [warehouse name] can not be deleted as quantity exists for Item [item name] even though all the transaction in relation to that warehouse have been deleted

### Module

stock

### Version

Frappe Framework: v15.37.0
ERPNext: v15.31.5

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hey, you understand a little bit of logic. If it is linked in a warehouse transaction/master, how to delete the warehouse. Check the video I have given below, there is one such warehouse, I have done transactions in it, so it cannot be deleted, but yes if it is not linked to anyone, you can delete it. I created a test warehouse and when I delete it it gets deleted easily. Because this has no transaction/master link. So it's not a bug.


https://github.com/user-attachments/assets/61b7024f-5b09-49f9-9c76-a2e5973414ef
