### ISSUE TITLE
Cannot Add Row on Timesheet Table

### ISSUE THREAD

**Issue by bobotdls** [frappe/erpnext#42884]
### Information about bug

When add row on Timesheet table... Nothing happens.
My Co-worker told me before we upgrade into Frappe Framework: v15.39.0  it's all working

### Module

projects

### Version

Installed Apps
ERPNext: v15.33.4 (version-15)

Frappe Framework: v15.39.0 (version-15)

Frappe HR: v16.0.0-dev (develop)

Print Designer: v1.4.1 (main)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
NA
```

**Comment by Nihantra-Patel** [comment]
We tested in the latest version but we haven't found the issue.


https://github.com/user-attachments/assets/d16bbf36-ae38-4a7d-a79b-da76ac599946

Any Error log then share it.

**Comment by bobotdls** [comment]
https://github.com/user-attachments/assets/b23bf3c4-01e2-4130-9c9a-65f074686284

I upload a video on my instance on Timesheet doctype. I cannot Add Row on Time sheet table

**Comment by Nihantra-Patel** [comment]
I've shared a suggestion:
If you've installed ERPNext in version 15, make sure the hrms is also in version 15 to prevent errors.

If the hrms is in the development branch, switch to it:

```bash
bench switch-to-branch version-15 hrms
```

If you've uninstalled or installed the app, do this:

```bash
bench get-app --branch version-15 hrms
```

This is because the hrms app has a version 15 branch.

I hope this is clear and helpful.


And also share the console error.

**Comment by lbrandh** [comment]
Same(?) problem here. Docker version of erpnext and frappe. No HRMS used. The error started to occurr after the update of either frappe or erpnext two days ago.

On adding a new row into the timesheet details the JS log shows the following errors:

Error evaluating the following expression: [utils.js:1085:11](https://xxxxxxx/apps/frappe/frappe/public/js/frappe/utils/utils.js)
let out =  parent.parent_project; return out [utils.js:1086:11](https://xxxxxxx/apps/frappe/frappe/public/js/frappe/utils/utils.js)
Uncaught InternalError: too much recursion
    show dialog.js:239
    msgprint messages.js:298
    throw messages.js:25
    evaluate_depends_on_value layout.js:785
    set_dependant_property layout.js:731
    refresh_dependency layout.js:719
    refresh_field grid_row_form.js:127
    refresh_field grid_row.js:1432
    refresh_field grid_row.js:1444
    refresh_field grid_row.js:1436
    refresh_field grid_row.js:1444
    refresh_field grid_row.js:1436
....

**Comment by bobotdls** [comment]
Thanks Ibrandh for supporting my issue, actually I really dont know where/how post the log.. Thanks again

**Comment by bobotdls** [comment]
I just update my hrms version into this
Frappe HR: v15.27.0 (version-15)
but the issue on not adding a row on Time Sheet table is still persist.

Below is my existing Version of all apps

ERPNext: v15.33.5 (version-15)
Frappe Framework: v15.39.0 (version-15)
Frappe HR: v15.27.0 (version-15)
Print Designer: v1.4.1 (main)

**Comment by Nihantra-Patel** [comment]
I've found the issue. The actual problem lies in the "read only depends on" condition. If the project is selected at the parent level, and the project field is also in the list view, you'll encounter this issue when adding a row. However, if you remove the project field from the list view, you can add rows without any problems. Otherwise, you'll need to remove the "read only depends on" condition to resolve the issue.


https://github.com/user-attachments/assets/1b083b4b-a469-4a37-885a-5560de8c76c5

**Comment by bobotdls** [comment]
Thanks @Nihantra-Patel , Now it's working
