### ISSUE TITLE
Mandatory Fields which are mandatory based on a condition are coming as mandatory in Bulk Edit.

### ISSUE THREAD

**Issue by rahmed-dev** [frappe/erpnext#43088]
### Information about bug

I have set Project as Non-mandatory when "is template" check box is checked.
![image](https://github.com/user-attachments/assets/5dd9be7a-a585-4c5a-9ad5-7adff7201c34)

But in Bulk Edit, system is showing this field as mandatory even though I am only selecting tasks which have project as non-mandatory.

![image](https://github.com/user-attachments/assets/c7f44111-49c1-42d5-994e-79a69e8edb89)

![image](https://github.com/user-attachments/assets/45ae10c4-5640-4532-ba72-08af1b0895d7)
 

### Module

projects

### Version

V15

### Installation method

None

**Comment by Nihantra-Patel** [comment]
If there is any condition in the "Mandatory Depends On" field, it will still make the field mandatory during a bulk update because it doesn't evaluate the condition. It simply marks it as mandatory. Bulk entry is designed for quick data updates, and while using it for fast data updates, no condition checks are performed. Let me explain why this happens.

Suppose you have 100 tasks, with "Is Template" selected for 60 tasks and not selected for the other 40 tasks. When you attempt to update all 100 tasks at once, the system cannot determine whether the field should be mandatory or not, leading to confusion. This tool is meant for fast updates without considering specific conditions.

If you need to update data in bulk with conditions, you can use the [System Console](https://frappeframework.com/docs/user/en/desk/scripting/system-console) instead.
