### ISSUE TITLE
Advance amount in Accounts Payable report is incorrect

### ISSUE THREAD

**Issue by venkat102** [frappe/erpnext#43604]
### Information about bug

Advance amount in Accounts Payable report is not correct when the advances paid to suppliers are marked as assets and reconciled later.

https://github.com/user-attachments/assets/2eeb530c-34cd-4c8b-84d7-da7b18ad1e8d

### Module

accounts

### Version

ERPNext Version: 15+

### Installation method

None

**Comment by Swethadevi-D** [comment]
The Accounts Payable Summary Report is functioning correctly, in the Payment Entry, when you pay an advance amount, it is posted to the creditors' account. However, when you create a Journal Entry, the amount is posted to the sales account, leaving no balance in the creditors' account. When using the Payment Reconciliation Tool, it fetches unreconciled data from the Payment Entry. After reconciling, the paid amount appears as a negative value because there is no balance in the creditors' account so only it shown negative amount in report

**Comment by venkat102** [comment]
@Swethadevi-D In the Payment Entry, the advance amount is posted in the advance account, not in the creditors' account
the issue happens when the reconciliation happens among advance and creditors' accounts.

**Comment by venkat102** [comment]
solved with PR #43728
