### ISSUE TITLE
Payment Entry : Unalocated Amount

### ISSUE THREAD

**Issue by incrusio21** [frappe/erpnext#43615]
### Information about bug

![image](https://github.com/user-attachments/assets/6c438688-57f5-45c0-97ba-6267996ae404)
![image](https://github.com/user-attachments/assets/80e9d9c2-19c9-47b7-9225-1edcbccadf03)

 encountered an issue when paying less than the allocated amount, and add a deduction with a negative difference, it was added to the 'Difference Amount' field instead. Is this code correct: and self.total_allocated_amount < self.received_amount + (total_deductions / self.target_exchange_rate)? Because in my opinion, it should be using the '-' operator instead of '+'.

### Module

accounts

### Version

v13.56.3 - v13.50.5

### Installation method

None

**Comment by Nihantra-Patel** [comment]
If it's a bug, it hasn't been fixed in version 13 because they stopped fixing bugs for that version. It might still have problems. It's best to upgrade to version 14 or 15.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
