### ISSUE TITLE
BoM - After cancellation, Amendment should be feasible

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4379]
As per standard functionality for all ERPNext Docs, BoM also should have next logical flow to "Amend" after "Cancel".

**Comment by cgpurbaugh** [comment]
This already is the case.

**Comment by rmehta** [comment]
Added "Duplicate" button

**Comment by marabsky** [comment]
Hello I have the same issue (would like to amend a cancelled BOM, via the amend button which is not present)
I see that "this is already the case", and that the "duplicate" button should be used.
Is there any documentation that would explain either of the above?

**Comment by cgpurbaugh** [comment]
@marabsky - I'm not sure about documentation, but to duplicate, hit the menu button on the top right of the screen.  To amend, you must first cancel the BOM, but in order to cancel, you must cancel all child BOMs.
![bom menu](https://cloud.githubusercontent.com/assets/13136405/14407223/d3c8991e-fe8e-11e5-885b-428c820379f4.PNG)
