### ISSUE TITLE
Sorting leads

### ISSUE THREAD

**Issue by jballaballa** [frappe/erpnext#43968]
### Information about bug

I selected the sorting method for leads as "Last Modified On".
When I modify any lead internally (e.g. I send an email from the lead) it became to the top of the lead list.
However when the lead is modified externally (e.g. the lead receives an email from partner) then the concerned lead does not go to the top of the list.

### Module

CRM

### Version

No idea how to check it.

### Installation method

None

**Comment by Nihantra-Patel** [comment]
The "Last Modified On" date updates only when a value on the form is changed. However, if you receive an email but don’t make any changes to the form, the "Last Modified On" will not update.

**Comment by jballaballa** [comment]
So, do you think "It is not a bug, it is a feature"?
I believe that the "Last Modified On" shall be updated if the Lead receives an email or I send and email from the lead.  It is a modification to the lead even if I changed nothing on the form.

**Comment by Nihantra-Patel** [comment]
No, I tried, if we send the mail from the lead then also "Last Modified On" not update. receiving and sending mail does not update the any doc. It has already been done like this.

**Comment by jballaballa** [comment]
My experience shows the same.  Sending and receiving email does not update the last modified on.  
And this is the problem.  Sending and receiving email should have been update the last modified on.
Can you amend the system to behave this way?

**Comment by jballaballa** [comment]
Can you see any chance to make the necessary modification in your system?

**Comment by jballaballa** [comment]
Dear Nihantra-Patel,
Some additional information.
If you just send and email from the lead it will not be "Last Modified On".
However if you send a quotation to the customer, the email with the quotation will be attached to the lead and the lead updated, it will jump on the top of the list.  Please note I did not modify anything in the lead, it just received an email with the quotation.

If the customer send me and email with address replies+...  (as it happened yesterday) it will be attached to the lead.  However I will not have information about that the lead received and email.  Should I recheck each lead every day to see if email has been received?  It is very much not user friendly, I hope you agree.
Please improve your system to make the lead "Last Modified On" if it receives an email or I just send an email from the lead.

**Comment by Nihantra-Patel** [comment]
It handles on the framework's side, not set for the particular doctype or event.

**Comment by jballaballa** [comment]
Your answer is totally unclear for me.  Please use terms of end users not developers.
Please answer these questions:
1. Are you agree the problem I described is a real problem for the users?
2. Are you agree your system does not work user friendly in this issue?
3. Will you improve it?

**Comment by Nihantra-Patel** [comment]
[scrnli_9Tfc1Rthp40l76.webm](https://github.com/user-attachments/assets/595ed1f4-4191-4287-bc11-54cb00e3dbb0)

Thank you for your detailed explanation. I understand your concern about the "Last Modified On" field not updating when emails are sent or received, even if the lead itself isn't modified.

From our side, we tested this behavior, and as it stands, the "Last Modified On" field only updates when an actual change is made to the lead's form (like updating a field or modifying information). For instance, when an email is sent from the lead, the system doesn't treat it as a form modification, so the "Last Modified On" remains unchanged.

However, when a quotation is sent and linked to the lead, the lead will update because the system recognizes the link as a form change. 

We’ve not encountered the specific issue you mentioned in our tests. To help us investigate further and potentially improve the system, could you please share a video? This will allow us to replicate the issue on our side and take the necessary steps to address it.

We appreciate your feedback and are always looking for ways to improve the user experience.

**Comment by jballaballa** [comment]
Here is a list of my leads:
![image](https://github.com/user-attachments/assets/77183a5e-d1b5-4dcc-a917-81622c0dc3ef)
Let suppose the 8-th customer (Alex Control System FZE) sent me an inquiry in email.  The email will be attached to the lead however the lead remain on the 8-th place. 
So that I have no information about his inquiry unless I check manually his lead.
To see if there is a new email attached to any lead I have to check manually ALL my leads.  Which is nonsense.
If the lead jumps on the top of the list I will know I have to check it because it has some news for me (it was modified few hours ago).
So my suggestion or request if you wish to modify the system in such a way that receiving or sending email to/from the lead taken as a modification and the last modified on field updated.
Is it clear now or should I put more explanation?
I cannot attach a video about some missed feature because it is missed.  No way to record it on video.

**Comment by jballaballa** [comment]
Any comment please.

**Comment by jballaballa** [comment]
Let me ask my previous questions:
Are you agree the problem I described is a real problem for the users?
Are you agree your system does not work user friendly in this issue?
Will you improve it?

**Comment by jballaballa** [comment]
Does somebody read my comments?
If yes, why do no respond in any way?
If not, then why this comment area provided?
