### ISSUE TITLE
Stock Workspace Permission

### ISSUE THREAD

**Issue by akashdubey22** [frappe/erpnext#44000]
### Information about bug

Stock Workspace is permitted only to role - Workspace Manager.

It should be associated with better meaningful ROLE.

### Module

stock

### Version

Frappe - v15.47.0
ERPNext - 15.40.0

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
You must have set it yourself because by default, it doesn't come set in ERPNext and secondly, there is no role link in the stock workspace. If you want to assign a particular role, set it in the role table.

![image](https://github.com/user-attachments/assets/ca4673cb-fb4d-4895-8c65-55c553176941)

If have a any doubt then raise the issue on the https://discuss.frappe.io
