### ISSUE TITLE
When item is delivered 100% then "Delivery" Button should not be displayed in Invoice

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4430]
When Invoice is made from Delivery Note (after 100% delivery made), Delivery Button should not be displayed in Invoice.

**Comment by pisethratanak** [comment]
I have the exact same issue. 

My company usually issue invoice to customer first before shipping. So when I go from Sales order to Invoice and then Delivery Note, the delivery note button is still there even after I have shipped everything.

**Comment by shachiTakalkar** [comment]
I can replicate the issue.
![screenshot from 2017-01-09 15 17 59](https://cloud.githubusercontent.com/assets/22912205/21762502/f6a91d14-d67e-11e6-9eb7-b7357ea7ee8d.png)

**Comment by shachiTakalkar** [comment]
I first created the Sales Order then made a Sales Invoice.
Still, I can see the Delivery Option!

**Comment by thosvesta** [comment]
Im also having the same issue. Thanks for reporting.

**Comment by tundebabzy** [comment]
Hello,
I don't think this is a bug since there are few use situations where the normal process of billing after delivery can occur. It will be extra work for the accountant though and audit will raise eyebrows but it happens.

However, I suggest we hide it by default and give the user to option to enable it

**Comment by tundebabzy** [comment]
Hello @Devens and all , thanks for reporting this even though its close to 2 years.
The option for delivery note is still available because ERPNext does not force a particular payment work flow. Usually, a delivery note should be processed before invoicing but in special cases, there can be need to invoice before shipping. Note that `sales order --> invoice` does not create any stock postings so ERPNext cannot know that items have been delivered except the delivery note is processed.
