### ISSUE TITLE
Renaming of Prospect not possible.

### ISSUE THREAD

**Issue by robinvolz96** [frappe/erpnext#44381]
### Information about bug

![image](https://github.com/user-attachments/assets/5d6826d2-2900-442c-91ca-02d7ade10873)
If I try to rename the Prospect name, it says saved, but the name stays same

### Module

CRM

### Version

ERPNext: v15.38.0 (version-15)
Frappe Framework: v15.43.0 (version-15)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Because allow rename is not enabled, you can't rename the id.

![image](https://github.com/user-attachments/assets/b49e723c-ef59-4089-b116-0d910e04bf27)


If you want to enable the allow rename then you have to use the property setter and enable it. you can find the reference in the [frappe forum](https://discuss.frappe.io)
