### ISSUE TITLE
Seperate Items from sales order including bundle product doesn't get transfarred to material request

### ISSUE THREAD

**Issue by inventobd** [frappe/erpnext#4459]
Hello

I have created a sales order which includes 2 types of items

```
Regular item for sales ( also Purchase item )
Bundle item (With packing list)
```

When I click on material request from that sales order, only items listed in packing list table transferred in create material request doc . Individual single item doesn't transferred to material request. Can anyone help ?

Thanks

**Comment by asbasawaraj** [comment]
@inventobd  I also ran into same issue today...

I think this issue is caused by below code

https://github.com/frappe/erpnext/blob/develop/erpnext/selling/doctype/sales_order/sales_order.py#L346

_item_table = **"Packed Item"** if so.packed_items else "Sales Order Item"_

@nabinhait  I want to fix this... can you tell me how  **"Packed Item"** copies content of packed items of sales order into item_table variable. "Packed Item" looks like a simple string to me!!

**Comment by rmehta** [comment]
Fixed
