### ISSUE TITLE
Allow for no items/suppliers/customers in the Setup Wizard 

### ISSUE THREAD

**Issue by vjFaLk** [frappe/erpnext#4506]
Currently you're forced to input data to proceed. Sometimes a user might want to input data later, or in a case where there are no "suppliers" . 

Examples : 

![Customer Page](https://i.imgur.com/BL2CnzH.png)

![Suppliers Page](http://i.imgur.com/k2F89Te.png)

**Comment by MaxMorais** [comment]
@vjFaLk I believe that this enforcement is because in the bottom of the Item page you can mark for the system to generate some demo data for you! without this the system can generate this information.

Maybe a good point to discuss here is:

Ask first for the user if him need some demo data, if the user say "Yes", so these 3 pages are showed for the user.

**Comment by vjFaLk** [comment]
If that is the reason, then maybe a cleaner solution would be to either disable or remove the checkbox for sample data in case the user has unconventional data (no supplier or customer), and notify the user of the same.
