### ISSUE TITLE
Feature Request – Default Warehouse and Is Sales / Manufacturing Item based on Item Group

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#4629]
I believe that the default warehouse and wether or not an item is a manufacturing item should be configured automatically based on the Item Group that is selected. Let's say we have a company manufacturing bracelets from stones we would have the bracelet category be a manufacturing item with default warehouse "finished goods" while the stones that are used for the bracelets would be in "stores". Likewise the stones would be "Is purchase item" while the bracelet wouldn't.

@rmehta do you agree with this? This would speed up the article creation process significantly.

Edit: when I look at this more closely other things must be configured by this too, such as wether or not an item has a serial number etc.

**Comment by Devens** [comment]
It's logical and useful.

**Comment by dottenbr** [comment]
Thank you @Devens

**Comment by LifeP** [comment]
Actually, if this could be generalized to all the fields in a form, it would add manifolds to the functionality of the ERPNext, making the workflow for end users much easier.

Sample use - In Sales order if a user puts in customer, defaults such as delivery warehouse for all items,accounts, cost centers, dates etc can be set. or if item and stock entry is selected to for manufacture, then then warehouse is automatically retrieved. Additionally, I can think of many applications in a multiple company scenario. depending on customers, users etc.

How this could work is -> In customize forms, where we have additional column for default value, this could be a link to doctype, and then should be able to set a valid value of that doctype as default.

Now, I am guessing that this could probably be done using customizations & scripts, however an out of the box feature would be much more hassle free. Would like to know what the ERPNext team thinks about this. @rmehta

**Comment by rmehta** [comment]
You can add `customer.delivery_warehouse` in options and check, but this only works for read-only type fields.

**Comment by adam-je** [comment]
At this moment, I find the need to set a default Finished Goods (FG) Warehouse for an individual (sub-assembly) item. 

My use case requires tracking sub-assembly stock which is manufactured in blocks rather than the needed quantity as provided for by Nesting the BOM. This default adds a layer of complexity for new users.

This feature would be a great addition, as I'd create an alternate Sub-Assembly item group. Whenever this is the case we'd have to override/automatically set the default warehouse in the Production Order to match the Item group's default FG Warehouse.
