### ISSUE TITLE
Task Notification popping at the web interface for all users

### ISSUE THREAD

**Issue by rainersg** [frappe/erpnext#4673]
Hi all,

I noticed that whenever I created tasks and assigned to one user, the rest of the users also get the same notifications. How will I set so that the user will get the notification for the task assigned to, not the rest of the users (including the system administrator)?

You can see the screenshot here. I am using the system administrator but I am getting all 150+ notifications even though I dont really have tasks assigned to me (admin), only the rest of the users. 

Really appreciate help on this because it is kind of urgent.

![screen shot 2016-01-22 at 11 06 10 am](https://cloud.githubusercontent.com/assets/16292330/12501467/735e917e-c0f8-11e5-98ad-e04376878349.png)

**Comment by rmehta** [comment]
@rainersg did you change permissions on tasks? You get notifications for your todos and todos you assigned (since you have to follow-up!)

**Comment by rainersg** [comment]
@rmehta which permission? Yes I know that we do have to follow up but, it is getting irritating.

 Let's say i have 4 users, A, B, C, D, I (system admin) assign a task to A, but user B, C and D get the notifications. It is supposed to be only A who is getting the notification, not the rest of the user (B, C, D).

So do i need to set it again in permission?

**Comment by rmehta** [comment]
No you should not get for all users, just go to User Permissions and reset permissions for ToDo

**Comment by adityaduggal** [comment]
@rmehta Even we are experiencing the same behaviour see my permissions for reference below.

Let me explain the issue:
If user A assigns a task to user B, then only userA and user B should get the notification but since SYSTEM MANAGER are not limited to view only their tasks hence I think they are getting the notification for all the tasks. But please note that resetting the permissions would not remove the issue of all the notifications since System Manager is allowed to view all the todos and hence would get the notification for all todos.

![image](https://cloud.githubusercontent.com/assets/1057509/12528491/9ca95b16-c1bd-11e5-871e-809a601cb1d9.png)

**Comment by rainersg** [comment]
@adityaduggal that's right! I even tried to reset the permission but it is default. And from what I see, it is more of user or role permission. But I dont see any step/guide to edit the permission so that those users whose tasks are assigned to, should be able to see the notifications only. But the rest of the users (not assigned to) should not see the notifications

**Comment by rainersg** [comment]
@rmehta not only I face this issue, but there are some users facing this too. Please explain how it works, at least, not reply to my question then close it abruptly. For your information, I did not change anything in the Task permission.

I get the impression that you are not friendly/helpful when a open source community is usually friendly and helpful.
