### ISSUE TITLE
Email Alert for Child Table (Like Sales Order Item, PO ite

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4703]
WE need to have Item-wise alert for large Sales order (Project SO with many items).

**Comment by rmehta** [comment]
Then you will have so many emails!

**Comment by Devens** [comment]
@rmehta - There will not be too many emails. Let me explain in detail. 

**Scenario 1 - Project (On site execution)**
There are more than 50 Line items in one SO. On a particular day only 2-3 items status would change. (Moreover, we have added custom fields for each line item. Our Site Engineers changes the status from their mobile everyday (for updating daily progress). PL see following "Sales Order Item" table fields listing. 

![screenshot_031716_085621_pm](https://cloud.githubusercontent.com/assets/10671911/13851070/b58c855a-ec82-11e5-8f14-03994a6b2f84.jpg)

**Scenario 2 - Manufacturing Item**
As we don't get any report for Sub-item procurement status, we have made a custom field, which our procurement team will update. Similarly, our production team will update the stage of item production. Please see following screen. Status update would be only for few items per day. Evenif they are many mails, it's important to know. (Unfortunately, we don't have any option for digest mail, so it would be ok, if there are 3-4 mails per day for getting important information). 

![screenshot_031716_090006_pm](https://cloud.githubusercontent.com/assets/10671911/13851200/3bc612c6-ec83-11e5-96fc-98e7f04581be.jpg)

There can be many such usages configured if alerts can be provided for Line Item modification.

**Comment by Devens** [comment]
@rmehta - We want to set a mail alert for Vendor for Purchase Order based on "required by Date".

**Comment by umairsy** [comment]
For scenario 1, can user create Installation Note (in Services module) for the specific Item? An Email Alert on the same will be simpler.

Scenario 2: Now Production Order has table for the raw-material items, with stock details for the Source Warehouse. Can you consider creating a report on this child item?

![screen shot 2017-07-11 at 12 23 51 pm](https://user-images.githubusercontent.com/910238/28054780-e979e246-6633-11e7-9d8c-907b555b8761.png)

Since feature suggestion of Email Alert on child items was not requested by other members in the community, we will be closing this issue for now.

**Comment by vwithv1602** [comment]
Adding this feature of getting control on fields from child table will really help us a lot. 

In our case, we need send emails (**different templates for different item groups**) to customers, on the creation of sales order and delivery note as well. While creating email alert on **sales order creation**, I can't place the condition on **item group**(which is present in child table - **item**) as I can't access it.

Any other alternatives to get this job done would be greatly appreciated..!
