### ISSUE TITLE
10% tax calculation error

### ISSUE THREAD

**Issue by samduff** [frappe/erpnext#4813]
I'm entering a purchase order, and 10% tax on $12.70 is being calculated as $1.28.

![image](https://cloud.githubusercontent.com/assets/668183/13043533/bf29d21c-d41c-11e5-82fc-282013905722.png)

Browsing with Chrome
ERPNext: v6.21.6
Frappe Framework: v6.22.7
Frappe Subscription: v0.0.1
Mandrill Integration: v0.0.1

**Comment by rmehta** [comment]
@samduff  what do you expect?

**Comment by anandpdoshi** [comment]
@samduff we will need to investigate this. Thanks for reporting it :+1:

**Comment by nabinhait** [comment]
May be tax rate defined in Item is different from 10 for one or more items. Please check "Show tax-breakup" under tax table for the details.

**Comment by samduff** [comment]
![image](https://cloud.githubusercontent.com/assets/668183/13233640/b0c5f588-da08-11e5-9962-980fbf82a32c.png)

That does show the problem, the extra 1 cent comes from the accumulation of rounding errors.  The item prices are $1.50, 0.78, 1.16, 1.47, 7.79.

**Comment by jwrober** [comment]
I can't seem to replicate in my v8 dev instance.

**Comment by umairsy** [comment]
@samduff can you please check and confirm if this issue is still replicating? Suggest you to make precision for the Currency field to 3 for more precise value in the decimal place. You can set precision for all the currency field at once from

Setup > Global Settings

If issue still prevails with 3 decimal places as well, feel free to re-open the issue.
