### ISSUE TITLE
Tax / VAT / GST calculation

### ISSUE THREAD

**Issue by limehalves** [frappe/erpnext#4829]
Hello,
there seems to be a bug in the Tax/VAT/GST calculation on the ERPNext demo system. VAT or GST is always calculated on the final sales price, including discounts. Even when applying a 100% discount (see screenshot), the tax remains unchanged.
Would you like us to submit a patch?

Installed Apps
ERPNext: v6.22.0, ERPNext Demo: v0.0.1, Frappe Framework: v6.23.0

![tax bug](https://cloud.githubusercontent.com/assets/17129732/13125998/005687dc-d5c9-11e5-9fb0-c22578d96a54.JPG)

**Comment by anandpdoshi** [comment]
I think it is a design decision. As you can see, discount is applied after tax and that reduces the tax amount to 0, but how would one know what the tax was before discount?

@nabinhait your thoughts?

Best,
Anand Doshi

ERPNext

**Comment by Devens** [comment]
I agree with @limehalves . Tax should be applied on discounted price and Tax also should have relevant effect.

**Comment by system19** [comment]
I agree with @limehalves as well. Any sales tax I have come across (NZ, AUS, GB and Europe) is always calculated after all the items and discounts etc have been calculated.

**Comment by Chris-Ames** [comment]
This is an important tax issue and needs to be sorted from an accounting and tax perspective

**Comment by nabinhait** [comment]
The problem is in POS-view only. Unlike normal form-view, there is no option to select whether discount is applied on net total or grand total. We will add some option to apply discount in net total on POS-view.

For now, you can switch to form-view to select discount on net total and then come back to pos-view to continue. If in your case, it is always on net total, you can set default value of "Discount Based On" to "Net Total" from Customize Form.
