### ISSUE TITLE
Access levels in printing

### ISSUE THREAD

**Issue by ahmederp** [frappe/erpnext#4833]
Team,

This year we ran our appraisals cycle through ERPnext. We customized the format, and added fields viewable only by managers and gave these access level 1, also some fields are only visible for the GM with access level 2.

Everything was fine until an employee decided to print his appraisal, and then we were surprised to see that all the feedback was visible on the print!!!! Even the GM comments were visible to a normal employee.

You can imagine the embarrassment this has caused to some employees.

Please look into this, and ensure that fields that are not visible to an access level in the form, should not be visible in a print as well.

Regards,
Ahmed

**Comment by anandpdoshi** [comment]
Thanks a lot for reporting this. We will fix it right away!

**Comment by impulsed** [comment]
Hi Guys,

I wanted to ask you both if you had performed any kind of End-to-End tests and Acceptance tests before delivering the funcitonality and using the system on the Production?

This is quite important to perform user acceptance tests not just for handing over the system, but also for making sure that the system is absolutely met your business critical processes. In the described case all the comments are visible for a user which is not supposed to see this kind of information. This actually might be a configuration or user permission issue, but you can imagine what kind of serious effects would be in case if a customer will get an access to any financial information of a partner company or something like that.

Making a long story short I wanted you to share the test strategy and approach for the modules/functionality if possible, because this process is pretty important for ERP system implementation and delivery. Also, if you need any help with improving the testing approach or at least review it, feel free to reach me out.

Thanks,
Ilya

**Comment by anandpdoshi** [comment]
@impulsed Developers perform one round of testing and a reviewer performs another. Unfortunately this bug escaped our efforts. We also have a develop branch that the community is free to use and test our bleeding edge changes. Sadly, this feature has been live for months and this is the first report we have had. And we are releasing a fix in a few minutes. 

It would be great if you can share / contribute in testing :+1:

**Comment by anandpdoshi** [comment]
@ahmederp if you have installed erpnext on your own server, you will need to update it. We will update our cloud servers tomorrow morning, as per Indian timezone.
