### ISSUE TITLE
BUG? Title Prefix in website setting

### ISSUE THREAD

**Issue by jyotinb** [frappe/erpnext#4848]
In website module in website setting Title-prefix. 

If we give a prefix it must show in browser, but it shouldn't. Why?

It is described as
Show title in browser window as "Prefix - title"
## Reason behind prefix requrement:

If am using 2 different sites for 2 different companies and i had open some tabs of both in browser
i can quickly identify and eliminate chance of cross entry. 
i will use differnt prefix for both

**Comment by MarvinSpyrka** [comment]
Still have the problem with the title prefix, as well as that "Home Page is Products" is not working. Might be because I've changed the identifier from "products" to "p". Any ideas?

**Comment by anandpdoshi** [comment]
Could be. What exact change did you make?

**Comment by jyotinb** [comment]
In website module in website setting Title-prefix.

If we give a prefix it must show in browser, but it shouldn't. Why?

It is described as
Show title in browser window as "Prefix - title"

**Comment by MarvinSpyrka** [comment]
Hey @anandpdoshi!
1. About the title prefix nothing I can think of right now. My settings should be pretty standard but when I change the title here at the "Title - Prefix" field nothing changes -> /desk#Form/Website%20Settings
2. When I mark the "Home Page is Products" box here, nothing changes -> /desk#Form/Website%20Settings That's why I put just "p" into "Home Page" field (my url prefix is p for products, because I like to have shorter urls).

**Comment by rmehta** [comment]
fixed
