### ISSUE TITLE
Change Stock Reconciliation limit to 500 rows

### ISSUE THREAD

**Issue by David-at-GitHub** [frappe/erpnext#4904]
Hi all,

the Stock Reconciliation Document (Stock - Tools) currently gives an error when trying to add more than 100 Items. I believe especially for Stock Reconciliations where you would want to correct all your stock 100 lines might not be enough. We corrected this by commenting out the following in the Code:

2 lines in file stock_reconciliation.py need to be commented:

75> if len(self.items) > 100:
76>   frappe.throw(_("""Max 100 rows for Stock Reconciliation."""))

If this could be added to the core version, I would much appreciate. Alternative for security reason I could imagine to add a parameter to the RESTful HTTP Call to avoid the restriction, or even to have a configuration setting.

Thanks, David

**Comment by rmehta** [comment]
Ideally this should be moved to a background job.

**Comment by graphskill** [comment]
Just been shocked to realise this limit. Not very good for any decent sized business. Because we sell via our own websites, Amazon, Ebay, factory etc we are currently doing stock control off ERPNEXT. I had thought I could just upload stock on a daily basis. We are not bothered about any financial aspect of this, simply to over write the stock values. So stock reconciliation seemed the way to go. Only to realise the file could only have 100 lines. We could have 2000. because we are on ERPNEXT hosted cloud we don't have access to modify core files. So a higher limit is required for lines in the CSV file

**Comment by rmehta** [comment]
If you are doing so many, you should setup an API script. The problem with allowing too many rows is that it will timeout.

**Comment by graphskill** [comment]
Is there a "simple" explanation as to why stock reconciliation is so heavy in use. Other CSV import allow 5000 rows

API scripting is probably beyond me, but is it possible to do API on ERPNEXT.COM cloud hosting?

**Comment by rmehta** [comment]
Yeah I agree 100 is too less. Maybe we can do 500? Will fix it in v7 (coming soon!)

Yes you can do API on erpnext.com too.

In my view it should be a 20 line Python script to import data from a CSV file. Someone in the community should be able to do it for you.

**Comment by David-at-GitHub** [comment]
The restriction in ERPNext: v7.0.26 and Frappe Framework: v7.0.19 is still to max 100 rows.
