### ISSUE TITLE
Workflow - User Permissions

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#5184]
Users can still edit a document, even though the workflow only allows a different role.

**Comment by rohitwaghchaure** [comment]
Can you please explain with some screenshots?

**Comment by tundebabzy** [comment]
@cgpurbaugh 
Any updates?

**Comment by cgpurbaugh** [comment]
I'm checking this.  Will update soon.

**Comment by cgpurbaugh** [comment]
Not sure what to take a screenshot of, but here's a sales order:
![image](https://user-images.githubusercontent.com/13136405/27286367-e5bc3fe0-54cd-11e7-8e47-e818f6ea47ca.png)
The user I am logged in as has the role 'Production User'.  The SO workflow shows as follows:
![image](https://user-images.githubusercontent.com/13136405/27286602-c662fea8-54ce-11e7-8aa0-892de6ad1e7f.png)

As you can see, 'Only Allow Edit For' shows as 'Sales User', yet 'Manufacturing User' can change the document.

**Comment by bohlian** [comment]
Guys, let me pick this up. I have some enhancements that I need to do with regards to workflow and this is one of them.

**Comment by rmehta** [comment]
@nabinhait why me 😢

**Comment by rmehta** [comment]
can someone validate this first? @umairsy

**Comment by nabinhait** [comment]
@rmehta You are the expert on Workflow 😅

**Comment by bohlian** [comment]
@nabinhait @rmehta so sorry guys, i actually have fixed it but couldnt find time to push it upstream, will get it done latest tmrw 😅

**Comment by rmehta** [comment]
@bohlian thank you 🙏 . Open source depends on contributors like you 😄

**Comment by bohlian** [comment]
Guys, this no longer exists based on testing done on the latest release. I believe it was fixed with https://github.com/frappe/frappe/pull/2477

Test done:
- Only Allow Edit for Sales Manager
- Right window is logged in as a Sales User
- Both users have read rights to Sales Order

![image](https://user-images.githubusercontent.com/8383249/30002084-3b54975e-90d3-11e7-9f35-927da76183e0.png)

@cgpurbaugh Do you still have this problem? and if you do can you screenshot the release / version?

**Comment by cgpurbaugh** [comment]
@bohlian I'm currently still running on V7.  Thanks for fixing this guys!
