### ISSUE TITLE
Adding Country to Supplier

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#5223]
I propose adding country to the Supplier DocType as a link since most companies have one headquarter country. Google, Apple, Intel and Cisco are all multinational companies but nobody would argue that they are in essence from the USA. I would like to ask @emakis to create a pull request and for Frappe to integrate this into stack.

I marked the best location in red in below screenshot:

![screen shot 2016-04-17 at 10 18 10 am](https://cloud.githubusercontent.com/assets/9136094/14585887/2cb8e28e-0486-11e6-9677-6741faa3df5c.png)

**Comment by dottenbr** [comment]
assgined to @kickapoo to fix and create pull request since this is interesting for EPRNext stack.

**Comment by dottenbr** [comment]
assgined to @kickapoo to fix and create pull request since this is interesting for EPRNext stack.

**Comment by kickapoo** [comment]
Updated Buying/Supplier DocType trying to find a proper Unit test for the change.
For Frappe Framework API, I see there is a 'frappe.test_runner.make_test_objects' that I think to use.

Anyone has a better idea?

**Comment by anandpdoshi** [comment]
1. https://github.com/frappe/erpnext/blob/develop/erpnext/buying/doctype/supplier/test_records.json
1. https://github.com/frappe/erpnext/blob/develop/erpnext/buying/doctype/supplier/test_supplier.py

**Comment by kickapoo** [comment]
@anandpdoshi  I have seen those file, in my previous comment I am asking if any built in `frappe.test_runner`  method is more suitable rather  than `frappe.test_runner.make_test_objects`.

**Comment by kickapoo** [comment]
@dottenbr  and @agusputra 

Currently (using 69d293db0814268c45c0bee26a65d5850bb379ba as HEAD in `develop` branch) , Supplier DocType has change its appearance since @dottenbrs screenshot

Iam attaching a screenshot below where my suggestion is that country is located under Supplier name
<img width="1181" alt="screenshot 2016-04-28 14 05 00" src="https://cloud.githubusercontent.com/assets/5064612/14884136/76184956-0d4b-11e6-828d-0e1b95da257a.png">

Also, Iam suggesting `supplier_country` as variable name.

**Comment by dottenbr** [comment]
love it!

**Comment by anandpdoshi** [comment]
Why not just 'country'?

**Comment by anandpdoshi** [comment]
Also what do you mean by "I am asking if any built in frappe.test_runner method
is more suitable rather thanfrappe.test_runner.make_test_objects.". What
are you trying to do? Can you explain in detail.

**Comment by kickapoo** [comment]
@anandpdoshi About the `why not just country?` , you are absolute right. 
Also let me note that this is my first pull request to ERPnext so I am bit confused due to low experience with the framework.

Now about the Unit Test: 
I have created the new field (I see the field inside `supplier.json`) and I want to create a simple test about it.  

My initial thought (and having experience with other python project) has to write a test that checks if `country` is included to DocType.Supplier fields. 
Searching documentation the only way that I found is by using `frappe.get_doc` so I have to update `test_records.json` with a proper Supplier record in order to `frappe.get_doc` to work. 

Looking in Frappe Module geo I saw Country test data and I have added the following to `test_records.json`
```
{
   "doctype": "Supplier",
   "supplier_name": "_Test Supplier with Country",
   "supplier_type": "_Test Supplier Type",
   "country":[{
      "country_name": "_Test Country",
      "doctype": "Country"
    }]
  }
```

Using `bench --site site1.local console` I am trying to see if I can the supplier object. 

```
from frappe.test_runner import make_test_records
test_records = frappe.get_test_records('Supplier')

# This works and wanted to test adding a country value
default_supplier = dummy_supplier = frappe.get_doc('Supplier','_Test Supplier 1')

# This fails DoesNotExistError: Supplier _Test Supplier with Country not found 
dummy_supplier = frappe.get_doc('Supplier','_Test Supplier with Country')

# Try to create the test_records fail TypeError: unhashable type: 'list'
# So I assumed 
from frappe.test_runner import make_test_records
make_test_records("Supplier")
````

**Comment by anandpdoshi** [comment]
Isn't Country a link field? Just set its value as `"country": "_Test Country"`
