### ISSUE TITLE
Multiple Active Salary Structures Should be Allowed if the Period is Not Overlapping

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#5368]
There is a VALIDATION in the salary structure which does not allow for active salary structures to be created is there is already a salary structure in active state. Now I am suggesting that an Employee can have multiple Salary Structures which are IN ACTIVE state provided their period don't overlap, for example:

Employee can Salary Structures as active for the following periods:
01-04-2010 to 31-03-2011
01-04-2011 to 31-03-2012
01-04-2012 to 31-03-2013
Since the above periods are not overlapping hence there should not be a problem for having multiple active salary structures. The use case is as below:

Every year the organisations would review the salary of their employees
Now if the Salary is reviewed and the Salary Structure changes then the HR people would have to FIRST make all the ACTIVE Salary Structures for Previous Year and then make NEW Salary Structures.
The problem would ARISE if an organisation wants to inform their employees of NEW SALARY STRUCTURE before the last Salary of their OLD period has been generated.

For example:
Salary for the month of March is generated on 31-Mar
Suppose if I want to create the Salary Structure for Period 01-04-2016 to 31-03-2017 before 31-Mar-2016 then I would have to make the SS for 01-04-2015 to 31-03-2016 INACTIVE and then make new SALARY structure
At the time of creation of Salary Slip I would again have to repeat the opposite step so as to generate the SS for march -2016

I hope this lengthy explanation would convince the team to change the validation and include the PERIOD. I would certainly agree with the validation if the period is OVERLAPPING but not for exclusive periods.

**Comment by adityaduggal** [comment]
@umairsy Created the issue for WN-SUP18573

**Comment by adityaduggal** [comment]
#5235 Is the same problem

**Comment by rmehta** [comment]
@rohitwaghchaure is this done?

**Comment by rohitwaghchaure** [comment]
@adityaduggal 
It's under development, first cut is ready please ([click here](https://www.dropbox.com/s/3fc81c9hg0xr7vq/multiple_salary_structure.gif?dl=0)).

**Comment by adityaduggal** [comment]
Well this seems fine but I really don't get the point of having to make a Salary Structure Default. Since if there is a Salary Structure in a period then Salary Slip should take that Salary Structure.

The system should never allow multiple salary structures for same period for an employee but I guess the default option is kind of making me think that you people are now allowing multiple Salary Structures as well for which I am unable to think of a USE CASE.

**Comment by rohitwaghchaure** [comment]
Thanks for your suggestion, Will keep the one salary structure for a period and deprecate the default functionality.

**Comment by felixvarghese** [comment]
I too agree that the default functionality is not a good idea - it is pretty similar to the "active" idea, which causes quite a few problems.

I ran into another edge case in creating salary slips in the same vein as I reported in #5235 .

Assume you have a salary structure from Jan 1 till April 6th. Then you have another structure from April 7 till date. When you attempt to generate a slip for the Month of April, the Process Payroll Tool will say there is no salary structure for the person.

One solution is to make sure salary structures don't start and end in the middle of a month (except for joining and resignation months). That is true, but was not feasible for us.

Our solution was to make the validation code more robust. Here is what we used.

https://github.com/frappe/erpnext/blob/develop/erpnext/hr/doctype/salary_slip/salary_slip.py#L54

We change this query to

`struct = frappe.db.sql("""select name from `tabSalary Structure`
    where employee=%s 
    and (from_date <= %s)
    and (to_date is null or to_date >= %s or to_date >= %s)""",
    (self.employee, m.month_end_date, m.month_end_date, relieving_date))`

The assumption is that the salary structure at the END of the month is what is used for the month. The query is simpler because there is no longer a need to check for joining date, and is actually more robust than the previous query.

**Comment by adityaduggal** [comment]
@felixvarghese I agree and its a very well thought out case that since ERPNext is currently only supporting making Salary Slips on Monthly basis hence it makes sense that the Salary Structure should also be for a month, so I think this validation of yours should also be included in this which honestly I missed while reading your post of #5235

**Comment by nabinhait** [comment]
Added in v7
