### ISSUE TITLE
Duplicate Delivery Note in Sales Invoice

### ISSUE THREAD

**Issue by mkumar9699** [frappe/erpnext#5509]
This should be a standard functionality in every ERP that check duplicate delivery note in Sales Invoice.

Please fix urgently. If this kind of functionality in th ERP then how can anyone use this ERP. I have already raised this issue but could not be fixed.
![image](https://cloud.githubusercontent.com/assets/16901262/16177302/ee6940a4-3645-11e6-9812-885bcccd46db.png)

Thanks
Mithilesh

**Comment by yashodhank** [comment]
@mkumar9699 , have anybody invited / forced you to use this ERP?

Always be polite with the community, its contributors and supporters. Because nobody here is working on your payroll.

If you seriously need some help, share information such as, what version you are using, since when you are facing this issue in reference to the frappe and ERPNext version.

If you are paid subscriber of ERPNext, then contacting support will be a better option AFAIK.

If you are free user, just like me, then why shy away from paying for priority support / hiring a developer to get your issues fixed? it can be good contribution to community as well, if you think its a huge issue!

**Comment by rmehta** [comment]
@mkumar9699 Duplicate Delivery Notes are not allowed in ERPNext unless you set your over-delivery limit very high. Check your over delivery limits.
