### ISSUE TITLE
Add Bulk Upload/Add Sales Order Item

### ISSUE THREAD

**Issue by gtejasvi** [frappe/erpnext#5570]
Having an Upload and Download Button similar to Stock Reconciliation in Sales order screen would ease out the process a bit. 
While there is a similar functionality available in Setup>Bulk Import>Sales order it should be reserved for master data only with limited access. Sales order will be executed by a person who is in sales and would only be responsible for entry and here having the upload feature will allow the user to quickly add about 100 items from an excel/csv into the system.

[Adding this as a requirement based on this link](https://discuss.erpnext.com/t/bulk-upload-add-sales-order-item/13677)

**Comment by fredluhamaa** [comment]
+1

**Comment by m-delvalle** [comment]
I second this, by presenting our use case:

In our company we produce (and sell) customized electrical panels. Even when there're some common features to all panels (or, at least, to all panels of the same "type"), every panel is _almost_ unique in a way.

So, each sale we make is a new BOM that has to be created from scratch. Leveraging the 'BOM' concept is still useful, because that way we can refer to the panel _as a whole_ with a single name.

But actually a single panel can be composed by several hundred items. It's really tedious to re-create them one line at a time. We use some spreadsheet macros to obtain BOM-like tables in csv format, so being able to copy & paste 'Code' and 'Quantity' would be _most_ useful.

If such code was already on the system, bring in 'price', 'description' or any other field required by the form. If not, leave extra fields blank, untill absolutely necessary (e.g.: leave 'price' blank until it's mandatory in order to send quotation).

**Comment by m-delvalle** [comment]
At risk of pointing the obvious, here...  :smile:

@strixaluco: you labeled this issue as a 'selling' feature, which is what was requested on the initial description. But this is actually a more "general" functionality that would be very useful on most (if not every) multi-item forms: creating BOMs for Production, managing/received goods on the Warehouse, creating POs, etc...

Is this an issue management requirement (to assign a single module label to each issue)? If that's not the case, could these comments be considered on the issue categorization? Thanks a lot for your work :+1:

**Comment by strixaluco** [comment]
@m-delvalle, you're perfectly clear with further explanation. As the issue is indeed about general functionality, just one `framework` label might be enough. I'm not aware of a strict requirement to use single label and it's better not to overuse them, so probably now the most important categories are covered.

**Comment by nabinhait** [comment]
You can enable "Upload" and "Download" feature in any child table by checking "Allow Bulk Edit" property for child table field from Customize Form.

<img width="1188" alt="screen shot 2017-09-18 at 12 27 13 pm" src="https://user-images.githubusercontent.com/836784/30531739-d57b057a-9c6d-11e7-9ce1-942629b4fc45.png">
