### ISSUE TITLE
[V7] Chart of Accounts - Tree View

### ISSUE THREAD

**Issue by Gleisson03** [frappe/erpnext#5676]
I can not see the Accounts list in the Chart of Accounts.
This problem is only when I use the language "Portuguese-Brazil," if I change the language to "English" appears normally.
![screenshot 2016-07-06 00 21 05](https://cloud.githubusercontent.com/assets/13992475/16606629/df5b8da2-430f-11e6-8e2f-0005d57c5b11.jpg)

**Comment by amandadtp** [comment]
Please stop sending all these JUNK EMAILS TO ME!

On Jul 6, 2016, at 17:53, Gleisson03 <notifications@github.com> wrote:

I can not see the Accounts list in the Chart of Accounts.
This problem is only when I use the language "Portuguese-Brazil," if I change the language to "English" appears normally.
 <https://cloud.githubusercontent.com/assets/13992475/16606629/df5b8da2-430f-11e6-8e2f-0005d57c5b11.jpg>

**Comment by yashodhank** [comment]
@amandadtp You simply select Ignore (login to your github.com account, go to [ERPNext](https://github.com/frappe/erpnext/)) if you dont want ERPNext issues emails filling up your inbox.
![image](https://cloud.githubusercontent.com/assets/1083792/16639383/b84f494e-440c-11e6-8091-6700615a9f0c.png)
