### ISSUE TITLE
Timesheet improvement

### ISSUE THREAD

**Issue by janlemontag** [frappe/erpnext#6053]
ERPNext is a great product! 
However, working with Timesheets is very painful and complicated. 

As a service oriented company we need to easily log time and description of work against each ticket/task. It is also very handy to see how long every ticket has taken. The time is then approved by a project manager and then all billable timesheets in a particular period (month, quarter) are sent together with the invoice as an attachment to clients.  Can you see improvement in this area? I know this function is partially there but the workflow is unusable. 

This will be very beneficial for all service oriented companies! Should you are interested, we can propose and discuss a better workflow. Thank you!

**Comment by kodybaker** [comment]
I think proposed workflows are always welcome as part of the ongoing discussion.

**Comment by PawanMeh** [comment]
Have you tried beta testing version 7 . Most of what you ask can be set up there. it would be great if you could test timesheets and let us know specific feedback

**Comment by aptech-admin** [comment]
Here's some feedback about Timesheet in v7.

I run a small service company and I use Timesheet a lot.  In version 7, there is no place to enter comments, but this is easily fixed by adding a custom field in the Timesheet Details doctype.  My suggestion would be to include this comment field by default in ERPNext.  It is true that we can create a project / task and put comments inside the task, but not every timesheets are related to a specific task or project.

Also, it is not possible to select an employee unless he is part of a salary structure.  This is just a filter and if you input your employee number directly, it does accept it.  I can't use ERPNext for payroll, so this is kind of annoying.  This relationship with payroll should be revised.

**Comment by PawanMeh** [comment]
Thank you for the feedback, we have a timesheet discussion thread on at [discuss](https://discuss.erpnext.com/t/v7-discussion-project-wise-billing-removed-with-timesheets/14157/17) ,kindly contribute your further thoughts on that forum.
