### ISSUE TITLE
Fleet Management Module

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#6171]
- [x] 'Vehicle Set Up' to set up vehicle information
- [x] 'Vehicle Log' to maintain Odometer, Refueling & Service details 
- [x] Reports with one stop view of all vehicle operating costs
- [x] Maintain seperate default 'Vehicle Expenses' account & 'Vehicle Expenses' claim type
- [x] Provision to create expense claim from submitted Vehicle Log

![fleet management](https://cloud.githubusercontent.com/assets/20460498/17987950/b2278832-6b40-11e6-9194-cc27632d0cbe.png)

**Comment by woakes070048** [comment]
this https://github.com/dalwadani/fleet_management might be a good start for a module.

**Comment by mhbu50** [comment]
+1

**Comment by dawoodjee** [comment]
Some companies use their own fuel stock. Would be good to have the option that links these two.

**Comment by jrubinos** [comment]
like @dawoodjee mentioned, it would be great to have an option to subtract the fuel from the companies own stock. At the company I am using erpnext, they buy their stock of fuel weekly.

Also currently we cannot add an older vehicle log, due to the odometer check which should be higher than the one previously saved.
