### ISSUE TITLE
 ERPNext Schools should be its own module 

### ISSUE THREAD

**Issue by jasonbrowne** [frappe/erpnext#6235]
Problem: ERPNext Schools is not currently its own module so its icons etc need to be hid from each user.

Solution: Make ERPNext an optional module so that we do not have to go through the extra work of hiding its icons, etc.

**Comment by yashodhank** [comment]
@jasonbrowne by design, core team decided to go with monolithic approach for keep track and release better stable releases for all software modules which are built / supported by core team.
So unfortunately, what you are asking can not be done for sake of simplifying deployment for non-technical person as well.
Yes, auto hiding of icons based on industry selected while setup is done already and if it does not work, kindly update.
Thanks

**Comment by rmehta** [comment]
@jasonbrowne you can remove "Academic User" from the user's roles so it will not show up.
