### ISSUE TITLE
Supplier status stuck at Open forever, even if nothing is pending

### ISSUE THREAD

**Issue by yashodhank** [frappe/erpnext#6430]
Recently been reported at forum: https://discuss.erpnext.com/t/why-do-all-my-suppliers-have-status-open/15455

Affected users are running ERPNext cloud version.

**Comment by Cheekoo80** [comment]
Hi, 

I just updated my Erpnext from Ver 6.22 to version 7.2, and then restored my last database file of ver 6.12

Everything went fine but for some reason my last supplier is showing open for unknown reasons. Please check this and advise how to change it to enabled blue status
![2017-01-26_23-44-11](https://cloud.githubusercontent.com/assets/17322703/22345293/7046471e-e421-11e6-81c6-236f8bdd7853.jpg) This is in ver 7.2
![2017-01-26_23-44-35](https://cloud.githubusercontent.com/assets/17322703/22345294/7063f868-e421-11e6-83ac-0c551d32981c.jpg) This is in ver 6.12

**Comment by yashodhank** [comment]
@Cheekoo80 have you executed, `bench migrate` command after the database restore?

**Comment by Cheekoo80** [comment]
Yes...!

On Jan 27, 2017 4:43 AM, "Yashodhan" <notifications@github.com> wrote:

@Cheekoo80 <https://github.com/Cheekoo80> have you executed, bench migrate
command after the database restore?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/frappe/erpnext/issues/6430#issuecomment-275549394>, or mute
the thread

**Comment by Cheekoo80** [comment]
Yes

**Comment by Cheekoo80** [comment]
I managed to fix it for the time being but by removing the advance payment for one of the recent purchase orders of the supplier,
