### ISSUE TITLE
Show or Hide Desktop Icons: Re-organize List

### ISSUE THREAD

**Issue by mwaigichuhi** [frappe/erpnext#6584]
Hi,
I recently setup ERPNext and had a rather embarrassing moment trying to demo with a prospect while looking to enable some more modules/features.

Basically, it would nice to group and sort the icons in a logical manner for better visibility and understanding. For instance, start with the module and list its features alphabetically below say as shown below:

**Human Resources** _(a module so perhaps bold and click-able)_
- Employee _(primary feature in module so it should stand out as well)_
- Other features _can follow in alphabetic order or alternatively all module features should be sorted alphabetically but perhaps highlight the primary feature somewhat (not so important though)_

As an addition just wondering what you think of non-industry related modules in the app after setup. Let me explain.

I setup the instance for Retail and as you know ERP's usually have an industry focus in feature sets so its kind weird to see the School modules (which I really like) after the setup is done and its clearly not for a school. Perhaps it would be nice to think of a way to re-run the setup preference to enable a different set of features or add others if cross-industry features are desired.

Either way sort School out as well in order described above e.g.

**School**
- Assessment
- Course
- Course Schedule
- Student
- Student Applicant
- Student Attendance
- Student Group

Regards,

**Comment by corbincavolt** [comment]
@rmehta How much development effort do you think it would take to implement being able to change the order (as in we can put them in whatever order we want) of the desktop icons?  I'm considering sponsoring this because I feel like it will be pretty confusing to my users in the sense that there doesn't seem to be any rhyme or reason to how the icons are ordered.  In addition, I like the idea of bolding (or somehow differentiating) the icons that represent an entire module.  Lastly, being able to change the order of the modules that you see when on a module's home page would be nice too (it looks like their current sort order is somewhat related).  I don't think setting the order on a per-user basis is necessary, a global sort order should be fine, at least for now.

**Comment by dalers** [comment]
I think it would be be less confusing for all if the behaviour to rearrange icons on the ERPNext desktop could simply mimic the iOS or Android desktop (or one or the other at least).

**Comment by rmehta** [comment]
Desktop icons are already sortable by dragging! Also schools is now effectively hidden. Closing this.
