### ISSUE TITLE
Asset Depreciation - Percentage and Date of Depreciation Entry

### ISSUE THREAD

**Issue by epochc** [frappe/erpnext#6679]
In the depreciation category screen, add a new field: 
Depreciation Approach: Options: Number of Depreciations, Percentage; 

Where the user selects, Number of Depreciations, the current screen is served; Where the user selects Percentage, display another field where the depreciation percentage is set.

Add another field: Depreciation Entries need to be calculate: Monthly, Quarterly, Half Yearly, Yearly

Add another field in the Asset List: Date of Asset Deployment

So on the last day of the Month/Quarter/Half Year or Year, the system calculates the Accumulatede Depreciation for the Year and the Residual Value of the Asset as per the following:

Accumulated Depreciation for the Year + {Purchase Value of Asset \* Depreciation Percentage \* (Lower value of .Number of Days since asset deployment. .OR. .Number of days since first Day of Depreciation Period.)/100/365}

Residual Value of Asset = Higher of {.(Purchase Value of Asset - Total Depreciation for the Asset). .OR. .(100 - Residual Value %). of asset.

**Comment by epochc** [comment]
Can you guys please address this? Without this, Indian companies cannot use the Fixed Asset Register feature at all.

Thanks

Jay

**Comment by adityaduggal** [comment]
Well @epochc is correct that the current schema of Depreciation does not give the user the option to have WDV method of calculating depreciation.

In our case we are using the SLM method in one organisation due to tax authorities and in the other organisation we are using WDV method.

For the WDV method depreciation the current depreciation functionality fails and I guess since erpnext is made for small organisations then I guess the above methodology is correct since most of the small users like us would be using WDV instead of SLM which is yet to be fully understood atleast for small users like us.

**Comment by Olawale1** [comment]
Hi @epochc I believe you can close this now. WDV is already implemented in V11

Kind regards,
