### ISSUE TITLE
Field overlapping above link field drop down

### ISSUE THREAD

**Issue by joezsweet** [frappe/erpnext#6704]
Hi all, 

the drop down link search is being ovelapped by the below field, if it's another link field:

<img width="526" alt="schermata 2016-10-25 alle 19 36 07" src="https://cloud.githubusercontent.com/assets/11652845/19697160/8b3807a4-9aea-11e6-9408-7eeb1d26543b.png">

can u please have a look?

**Comment by bcornwellmott** [comment]
This is an issue I've been experiencing for the past few weeks. I've had symptoms with drop down menus and child table dialogs.  For example:

![image](https://cloud.githubusercontent.com/assets/16806041/19697845/dfd49a64-9aa1-11e6-8faa-75a3b120d9d0.png)
With the above, depending on where I click the mouse triggers on the background item instead of the combo box selection.

Or with child tables, many of the buttons don't work (Add above, Add below, Delete).

The issue comes up only in Google Chrome 54.0.2840 (my co-worker on 53.0.2785 did not seem to have the issue, then he updated to 54.0.2840 and got the issue).  Not sure if other browsers have the same issue.

@joezsweet , can you report on your browser and version?

**Comment by joezsweet** [comment]
Chrome Version  54.0.2840.71

Safari Version 10.0 (12602.1.50.0.10)

**Comment by joezsweet** [comment]
another example:

<img width="805" alt="schermata 2016-10-26 alle 12 45 48" src="https://cloud.githubusercontent.com/assets/11652845/19723252/abc3b118-9b7a-11e6-8133-2a0d44c4714c.png">

**Comment by felixvarghese** [comment]
Some of this is fixed via https://github.com/frappe/frappe/issues/2176

**Comment by strixaluco** [comment]
I'm having this issue in Frappe Framework: v7.0.46 with Firefox ESR 45.4.0:

![overlapping](https://cloud.githubusercontent.com/assets/10875796/19996165/96b2c94c-a298-11e6-8730-d7d5419c7627.png)

**Comment by nabinhait** [comment]
The issue has been fixed in frappe version v7.1.5. If you don't want to update to v7.1, use v7.0.x branch (latest branch on v7.0).

**Comment by strixaluco** [comment]
I want to update, I just can't :) we're on official subscription and it's still on the 7.0.x branch.

**Comment by nabinhait** [comment]
We will update all cloud accounts to v7.0.x today. 
Will roll out v7.1.5 in the next week, still there are few hiccups in the latest version :(

**Comment by strixaluco** [comment]
No offense. This particular issue is not a big deal for us.
