### ISSUE TITLE
Updates to the Payroll

### ISSUE THREAD

**Issue by KanchanChauhan** [frappe/erpnext#6808]
### Frequency - Weekly, Fortnightly and Monthy

- [x] Add select field in Salary Structure, Salary Slip and Process Payroll for Frequency.
- [x] Number of days validation based on Frequency in Salary Slip.
- [x] Get Salary Structure based on frequency in Salary Slip and Process Payroll. 
- [x] Test cases

### Loan Management

- [x] New Doctype "Employee Loan" (Account details, employee details, loan details, repayment details)
- [x] On Salary Slip creation check if any pending loan repayments for that time period
- [x] Will be added as a Deduction in Salary Slip

### Employee as Party type

- [x] Allow loan payment to be linked to party "Employee"
- [x] There will be separate line-entry for Loan repayments against Salary Slip for each Employee

### Reports

- [x] change title from 'Monthly Salary Register' to 'Salary Register'

Please feel free to add to it and make more suggestions.
       
https://github.com/frappe/erpnext/issues/4422, https://github.com/frappe/erpnext/issues/6802, https://github.com/frappe/erpnext/issues/6729, https://github.com/frappe/erpnext/pull/6633

**Comment by nabinhait** [comment]
@adityaduggal already sent a pull request for loan management (https://github.com/frappe/erpnext/pull/6633). it is pending to merge, will check soon. Lets do gap analysis about loan management after that.

**Comment by KanchanChauhan** [comment]
@nabinhait yes, why re-do the work. We can make improvements on his PR.

**Comment by IAGAdmin** [comment]
The report needs to be improved as well:
- change title from 'Monthly Salary Register' to 'Salary Register';
- add a date picker to select the date range;
- insert a check box 'by Posting Date' to switch fetching date from Payroll Run and Payment date to suit respectively Accrual Accounting and Cash Accounting reports.

Let me know if you includes this change as well, or we'll pull a request as soon as it's ready.

Also user documentation needs to be updated please

**Comment by rmehta** [comment]
@KanchanChauhan start a pull request as soon as you have a rough system working and maybe have a setup quick call, gitter chat for giving feedback (?)

**Comment by Fredoluka** [comment]
The following should also be included:
1.payment option (Credit) Payment account -Salary and Wages Payable.i.e a payable account.This will enable warehousing processed payroll pending payment.
2.For salary slip based on time sheet hourly ,rate should be made variable per timesheet.In real life,an employee  (especially technical employee) hourly rate  sometimes  depend on project where he worked in a month.
EXAMPLE
Employee A (BASIC) hourly rate when he works in Project X is $10/hour while when he works in Project Y his hourly rate is $12.In October 2016,he worked for 60 hours in Project X and 90 hours in project Y..... 
Thanks

**Comment by adityaduggal** [comment]
I think the current employee loan which I have proposed has one flaw.

The flaw is that it does not cover a Use Case wherein an employee lets say takes a loan of 50k and instead of getting it deducted in their salary slip the employee returns the loan as a lumpsum amount.

That use case is not covered in my current employee loan details.

**Comment by KanchanChauhan** [comment]
@adityaduggal We can add field "repayment type" with option "deduct from salary", "payback lumpsum". Something like this.

**Comment by Fredoluka** [comment]
You should have repayment for the loan .In the repayment schedule it should be 50k at the end of the month.And if he pays before salary payment it should not be treated as loan but a mere advance.The employee as a party is debited when he takes the advance and bank is credited.When he pays,Bank is debited and the employee as a party is credited.That is simple.ThanksFred 

```
On Friday, November 4, 2016 8:40 AM, Aditya Duggal <notifications@github.com> wrote:
```

 I think the current employee loan which I have proposed has one flaw.The flaw is that it does not cover a Use Case wherein an employee lets say takes a loan of 50k and instead of getting it deducted in their salary slip the employee returns the loan as a lumpsum amount.That use case is not covered in my current employee loan details.—

**Comment by system19** [comment]
To allow more types of loans/advances and repayment options:
"Employee Loan" should just be called "Business Loan" or something like that. 
Put the Loan process back into the Accounts area with the option of print to Pay Slip. If thats possible?

**Comment by RobertSchouten** [comment]
also the holiday lists need an overhaul as they need to b able to overlap pay periods and have 2 lists apply and also stop duplicate dates on holiday dates

**Comment by Tropicalrambler** [comment]
Thanks for setting this up!  +1

**Comment by Tropicalrambler** [comment]
I find the Tax table functionality very convenient, since accounts can be specified for each line item.  In the same manner, a salary structure would benefit from each salary structure line item from an account.  Use case: 
For paying salaries in one country, an amount must be deducted from the salary, kept track of in an account, and eventually paid to the government. Another amount must be accrued as a reserve for severance pay upon the employee ending relationship with the company, ideally, these amounts ar handled Monthly, although Weekly and Fortnightly being able to accrue these amounts would certainly be wonderful, it makes ERPNext the most precise HHRR module I have ever seen.

**Comment by KanchanChauhan** [comment]
Just an update. First phase of Payroll updates is done. Please test out the Payroll Frequency in Salary Slip, Salary Structure and Process Payroll in develop branch.

**Comment by felixvarghese** [comment]
a bit of pedantic English - I believe it would be better to use "semi-monthly" rather than "bimonthly" for the payroll frequency. This is because bimonthly can also mean once every two months, even though it's more commonly used to mean twice per month. Semi-monthly only has one meaning though - twice per month.

Some thoughts available at http://blog.dictionary.com/bimonthly/

**Comment by dalers** [comment]
> On Dec 13, 2016, at 5:43 AM, felixvarghese <notifications@github.com> wrote:
> 
> a bit of pedantic English - I believe it would be better to use "semi-monthly" rather than "bimonthly" for the payroll frequency. This is because bimonthly can also mean once every two months, even though it's more commonly used to mean twice per month. Semi-monthly only has one meaning though - twice per month.
> 
True, although as a native English speaker (Canadian), I don't find "semi-monthly" at all intuitive and I still look up the definition when it's important (fwiw, I'm also more tech than finance). Personally I prefer "Twice Monthly", and it's only one additional character. 

Dale

**Comment by OneiricIT** [comment]
@KanchanChauhan am I able to suggest introducing a 'leave' salary component and formula section in salary structure for leave accrual? For example, leave is added to the employee's total leave allocation based on the formula specified in the salary structure. This would dynamically increase the allocated leave each pay cycle, which would suit better then allocating a new employee the maximum leave entitled in which they are not eligible for at that point - they build it up as they work. 

Also could it have the option (like for earning and deductions) to affiliate a liability account which will represent the total leave for the company? Given leave is paid out based on the rate the employee is on at the time they take (or are given it), I was thinking the monetary value should be calculated based on the total amount of leave hours by the last pay rate (or the employee's present base salary structure)?

In terms of visibility on the salary slip, it should then be available as 'total number of leave days' in the print format builder and can be added if required.

Also in regards to earning - can an option be available which excludes an earning or deduction entry from being calculated in the total - like a check box? Example being some earnings may not be directly deposited into the employees account (i.e. Superannuation in Australia).

Are there any other comments or recommendations regarding the above?

**Comment by system19** [comment]
RE: pedantic english:
@felixvarghese is totally correct but @dalers "Twice Monthly" is much clearer.  So  +1 for twice Monthly.

**Comment by KanchanChauhan** [comment]
@OneiricIT Really appreciate your suggestions, please can raise separate issue for each feature request so that we can take up one at a time and that way it is more clearer.

**Comment by OneiricIT** [comment]
@KanchanChauhan 
Thanks. 

https://github.com/frappe/erpnext/issues/7389
https://github.com/frappe/hrms/issues/209

**Comment by KanchanChauhan** [comment]
Closing this thread since most of the to do list seems to be done. If there is anything else, please raise a separate issue of it.
