### ISSUE TITLE
Same item multiple times in BOM

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#7104]
When we create quotes / sales we can have the same item on more than one line.

I can't see a way to do that on the BOM.

For example we make pipe clips from metal bar. The pipe clip is essentially in two halves. Two halves make one clip . So the BOM needs to have 2 lengths of metal bar, each one is 0.125 meters. We have the metal bar set up as meters, I don't want the BOM to say 0.25 meters (total) it has to to have 0.125 on two lines so the production guys know what lenght to cut the bar to

**Comment by Dbonejones** [comment]
I believe this issue was solved by creating "Half-clip" items and nesting 2 of them in the "Pipe clip" item BOM.

**Comment by jwrober** [comment]
@graphskill - did @Dbonejones suggestion work for you? If not, would you please add more commentary to this issue to help us better understand what it is you are trying to solve and need erp team to make a code change.

**Comment by graphskill** [comment]
The suggestion was one method, but ultimately not succesful. We have reverted to doing our "real" BOM external to ERP because of this

So we use ERP to create the production order and the BOM just has the one lenght of metal that is twice the length needed, but the actual production paperwork is now produced externally so the production guys no the real lengths
