### ISSUE TITLE
Setup Wizard Cleanups

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#7272]
Entering multiple customers

<img width="879" alt="screen shot 2016-12-20 at 11 12 23 am" src="https://cloud.githubusercontent.com/assets/140076/21339490/a87db548-c6a5-11e6-951b-93cc9fd40cb8.png">

Adding Products

<img width="876" alt="screen shot 2016-12-20 at 11 13 02 am" src="https://cloud.githubusercontent.com/assets/140076/21339496/b3bb03c0-c6a5-11e6-9194-5cf72289cb96.png">

**Comment by revant** [comment]
Common problem, Setup wizard fails and shows message
"There were errors".

This is a timeout error because setting bigger timeouts or using bench console solves the problem.

I believe as the project grows, Setup Wizard will be the entry point for Users to make ERPNext relevant.

Setup Wizard should not be "build huge list of args" > "http.POST on server" > "wait for response". Because as the arg list grows, server will take time to process.

Setup Wizard needs a re-design to handle:

 - Initialization Wizard, user creation, timezone, country etc. (Mandatory)
 - Localization Wizard, country selection, gst etc. (Mandatory)
 - Domainification Wizard, Service, Education, Healthcare etc (Optional)
 - Additional Wizards (Optional)

If args list is broken down in small chunks server can process and responds quickly?

Can Wizard be resume-able again? I vaguely remember v3/4 had a progress on setup.
These optional wizards can be there on setup/progress bar for later or disabled completely

**Comment by revant** [comment]
Update : https://discuss.erpnext.com/t/frappe-foundation-team-updates-for-august-2017/28187
There are change made in setup wizard.
