### ISSUE TITLE
Sales Invoice: Payments are not being recorded when I use advance payments

### ISSUE THREAD

**Issue by juliancms** [frappe/erpnext#7302]
Payments are not being recorded in the general ledger for the following scenario:
1 Creation of Journal Entry as advance payment
2 Creation of Sales Invoice without clicking "Is POS" and click on "Get Advances Received". Doing this the option to add payments appears.
3 Add a cash payment, save and submit.
Then I check in the General Ledger and only the advance payment is registered but the payment does not appears.

In the permissions of "Payments Section" says: eval:doc.is_pos===1||(doc.advances && doc.advances.length>0) . If I understand well that means it should work with advance payments greater than 0.

**Comment by rmehta** [comment]
@Arundhatii can you replicate?

**Comment by tundebabzy** [comment]
If `isPos` was not selected, you shouldn't have been able to add the cash payment as ERPNext is designed such that you can only enter a payment amount when `isPos` is selected.....or this has been fixed.

I tried to replicate the issue but I was not able to successfully add a payment before clicking save as expected (the payment table should not even appear since it would not be honoured). Closing this for now.
