### ISSUE TITLE
Previous Financial Year is not closed - Message

### ISSUE THREAD

**Issue by saidsl** [frappe/erpnext#7376]
Hello,

Have the following installed: 

ERPNext: v7.2.6
Frappe Framework: v7.2.5
Bench 4.1.0
Ubuntu 14.04.4 LTS (GNU/Linux 4.2.0-42-generic x86_64)

Did the the Period Closing Process and there does not seem to be any issues with the accounting side of things, all seem to be in order, but the error message below is showing.

![screen shot 2017-01-03 at 11 50 27 am](https://cloud.githubusercontent.com/assets/5009367/21599723/52bcb7fa-d1ac-11e6-93da-4a21414f6ff0.png)

Thanks & Regards
Said

**Comment by rmehta** [comment]
@umairsy can you replicate?

**Comment by umairsy** [comment]
Unclosed Fiscal Year: Screenshot suggests that your last fiscal year (probably 2016) is not yet closed. That's the reason when you are seeing the Balance Sheet for the current Fiscal Year, it is also showing Profit/Loss different availed for the year before that. Because the different of Profit/Loss statement is finally updated in the Balance Sheet account.

Provisional Profit/Loss amount is indicating the difference of Profit and Loss in the Current Fiscal Year.
