### ISSUE TITLE
Missing +/- Buttons in POS

### ISSUE THREAD

**Issue by felixvarghese** [frappe/erpnext#7420]
https://discuss.erpnext.com/t/pos-plus-and-minus-buttons-are-missing/19182

As explained in this thread, the + and - buttons in POS are not visible. The buttons are there and are clickable - they are just not visible.

I have replicated on the demo.

![image](https://cloud.githubusercontent.com/assets/3396162/21798661/b494b902-d73b-11e6-9812-9fdebbc54516.png)

**Comment by Olawale1** [comment]
Hi,

There was once an issue where clicking on either of those buttons caused the quantity to automatically change to zero (0) when dealing with serialized items. I noticed after that issue was fixed that the buttons were no longer visible. I'm not sure if they're related in any way but please do try to ensure that fixing this issue doesn't bring back any old issues!

Regards,
