### ISSUE TITLE
Temporary Autogenerated Warehouses

### ISSUE THREAD

**Issue by ccavolt** [frappe/erpnext#7457]
When we allocate items for a production order, we put all the items in one physical location in our warehouse.  To replicate this physical process in ERPNext, we were planning on creating Warehouses A-Z and just using them as the location where all the raw materials go for WIP for a given order.  Instead, would it be possible to autogenerate temporary warehouses based on either sales or production orders (you'd have to specify that you want it created so it wouldn't mess up anyone's current workflow) that would be automatically removed once said order was completed?

@rmehta We're willing to pay for this feature (if it's possible and the price makes sense), so a quote would be greatly appreciated.  Let me know if you need any additional information.

**Comment by rmehta** [comment]
@corbincavolt I am not sure temporary warehouses is a good solution. Why not create WIP warehouses per workstation?

**Comment by corbincavolt** [comment]
Well the problem is the supplies are not kept at workstations; we generally have too many outstanding orders for that.  Depending on the size of the order, the "virtual warehouse" could be anything from a container the size of a bathtub to several hundred square feet of warehouse space lined with pallets of supplies.  And even then, unless it's a huge order, a lot of times the virtual warehouse will be moved around depending on which order we're working on on a given day, so they don't stay stationary.  If you don't think temporary warehouses are a good solution I'm inclined to believe you.  So would the best solution be what I was initially thinking of then?  I was also thinking of creating a link to the sales/production order fields so I could see which virtual warehouse contains which order.
