### ISSUE TITLE
Manufacturing Overhead and Direct Materials Allocation

### ISSUE THREAD

**Issue by ccavolt** [frappe/erpnext#7471]
This feature request is kinda building off of #7458, but could probably be implemented without it.  We'd like to be able to allocate manufacturing overhead directly to production orders (which would be included along with direct materials and labor into the cost of the finished goods) and sales orders (would be added to the cost of goods sold for that transaction) based on a predetermined overhead rate that is set manually.  We'd like the overhead rate to be based on labor hours (so for example $2 per direct labor hour), but I imagine basing the overhead rate off machine hours, square footage or other metrics could be useful for other companies.  In addition, some companies have multiple overhead pools where multiple allocations could be necessary per production/sales order.  I'd be fine having this functionality start as simply as possible and then add more functionality if other companies are interested in this feature; I just didn't want to assume we'd be the only ones who would use it.

In addition, I'd like to be able to allocate packaging costs (direct materials), such as boxes, pallets, etc., to the cost of a sales order.  For orders where we can't charge the customer for shipping (government contracts), we'd also like the option of applying the shipping cost as a direct cost (rather than an indirect expense) on the sales order.  These costs would end up going into cost of goods sold for that order.

@rmehta We're willing to pay for this feature.

@epochc You can add this to the proposal.

**Comment by bcornwellmott** [comment]
Manufacturing overhead is currently covered with Production Orders if Operations are included. The Workstation doc has Operating cost fields which includes Electricity, Rent and Consumables, as well as direct labour costs.

The above said, I think this probably could be further expanded:

- Use a table instead of just these options so that each company could add their own costs
- Include better analysis tools so that pricing can get broken down by more than just operations and material costs in set reports

-

**Comment by corbincavolt** [comment]
@bcornwellmott I think having a table where you could make your own overhead allocations per workstation is a good idea.  As far as workstations and operations are concerned though, we're having several issues with their flexibility (or lack thereof), and if we can't fit all our processes into the structure by which overhead is currently allocated (workstations), then we're going to end up with an incomplete picture.  Here are some of the issues we're having:

- Not every operation makes sense to be allocated on the basis of how many units you're producing.  For example, if it takes us an hour or two to get an area ready (gathering all the supplies we need) for building a product, we'd like to record that time against the production order, since it's ultimately part of the cost of making the product.  Same with QC in the sense that not every product may be checked, but we'd still like to record the time we spend checking.

- Most of our employees have different hourly rates, and we'd like to account for that in the cost of the product (and depending on the customer, we may have to just for compliance purposes), so putting that cost in the "wages" field in the workstation document doesn't really work, unless you're just trying to get an estimate.  One potential solution would be activity cost, where you can assign the activity type on a per employee basis, but it doesn't seem like that can be utilized in the timesheet that's used for production orders currently.

**Comment by mobentec** [comment]
@corbincavolt We would love if there was a way to assign employees to production/manufacturing operations where:
1. the hourly wage of the assigned employee is automatically populated using their hourly pay rate from their HR record; 
2. a view in which employees can come into work and see an entire list view of what all production tasks/operations they are expected to work on that day.

This would help us manage and plan our production runs while also accurately accounting for COGS.

**Comment by sharmanakul** [comment]
@ccavolt has there been any development on this?
