### ISSUE TITLE
Item Price Feature Request

### ISSUE THREAD

**Issue by ccavolt** [frappe/erpnext#7472]
We’d like to add the following fields to the item price list which are currently stored in item details.  In order to not break the current functionality, I'm thinking that the values from the item price list would only override the item values if they are filled in, otherwise the item values will be used.

- UoM (and the associated Conversion Factor), so that we don’t have to make a separate price list per supplier when purchasing an item in a different UoM (which happens pretty frequently)
- Lead Time, because it's usually more dependent on the supplier than the product being ordered (or at the very least, would probably be a combination of the two)
- Supplier Part Number, because the supplier part number is sometimes different for the same item, depending on the UoM.

@rmehta We'll willing to pay for this feature.

@epochc You can add this to the proposal.

**Comment by bcornwellmott** [comment]
I'd make a few comments/suggestions on this:
1. Add UoM to the Item Supplier table instead of adding supplier part number to Item Price doc (easier to keep organized)
2. Lead Time is typically covered in a Supplier Quotation for an Item, as this can change frequently (even if the price doesn't). That said, there is a disconnect between the Supplier Quotation document and the Item Price document. If the Item Price was created/updated with every new Supplier Quotation, lead times could also be updated. 
3. There is also a weird situation of having mixed functionality between the Item Price and Pricing Rule, to the point where I just use Pricing Rules for everything so that I can have different prices for different quantities of items (similar to UoM, suppliers offer a different price based on qty).

**Comment by corbincavolt** [comment]
@bcornwellmott 

1. If you put UoM in the Item Supplier table, how do you assign different prices for different UoM of a given product without creating a price list for every UoM, pricing rules?
2. I didn't even think of the benefit of being able to update lead times from the Supplier Quote, but that would be pretty useful!
3. Unless I just don't understand price rules though (which is very much a possibility), it doesn't seem like they respect UoM.  When I was playing around with it, I had to use the Default UoM in order to get the pricing discount for a given quantity, which would be pretty confusing for the Supplier.  If we could get the price rules to respect UoM though, I think that could be a potentially viable solution.  It seems a bit more disjointed than what I was proposing, but would probably have a smoother transition for current users.

**Comment by bcornwellmott** [comment]
To clarify, I think making Item Price include Quantity (min/max) as well as UOM is the way to go. I was just pointing out that right now there is a weird split between the two options. I really want to move away from using Pricing Rules, but right now they are the only way of storing pricing for more than one quantity for a given supplier/item combo.

I'd suggest adding UoM to the Item Supplier table to keep track of the supplier part number. Adding the UOM to the Item Price to track the price is also a good idea. I'm just suggesting that the part number be kept on the Item page (as opposed to Item Price doc) to keep things easy to look up - sorry if I wasn't clear.
