### ISSUE TITLE
suggestion regarding help videos 

### ISSUE THREAD

**Issue by dufani1** [frappe/erpnext#7573]
I suggest to transfer help videos to help menu and remove them from master model page. As when assign the role for some user (like stock user) I noted all videos like (Setting up Employees, Leave Management and Processing Payroll) still existed in main HR model page although these videos not important for stock user and make no sense . I see if we remove all videos to help menu is better or make the showing of these videos as per permissions and roles given by system manager.

**Comment by dalers** [comment]
Strictly allowing users access only to "relevant" videos may not be best solution if it prevents someone from learning more.  A manager may ask an individual to learn more, or an individual may want to learn on their own, although they may not currently have the security role required in order to actually enter such a transaction.  

Also, is it possible for a company to add their own videos in a managed way, extending the library with company-specific videos (possibly even replace existing ones).

What about using use the item-and-bill-of-materials functionality to create a hierarchy of required training? I might want to include a training video for how to perform a procedure, on the bill of materials for the assembly itself.

Can the erpnext "education" module be used to document both required training (default training determined by company role, plus specific manager-assigned training) and manage completion status?

Instead of an integrated solution, ERPNext could have a formal interface to one specific training system, e.g. Moodle.  However, this area is a big deal for big company with big training departments, and I think a big deal for ERPNext if it was simple enough for someone at a project level to release "training" (a video, some reading material, possibly a quiz), either general company training, role-specific training, or process-related or manufacturing training. Companies operating in heavily regulated industries would love to have traceability from an item to the training procedures to make/use/test the item, to the use of the item to perform a procedure, use as a sub-assembly in a major-assembly, sell to a customer, etc.

**Comment by dufani1** [comment]
Thanks for your reply Dalers
My suggestion is about organizing and making erpnext better form UI design point of view not about preventing any user from learning. And if any person or employee need to learn more about erpnext he/she can access the documentation of erpnext easily by surfing the internet.

**Comment by ankush** [comment]
This is completely redone in new onboarding.
