### ISSUE TITLE
Drawer does not close on Android 4.x in mobile app.

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#7581]
Hi,

There's an issue when viewing ERPNext V7 from mobile devices running on Android 4.x. The drawer on the left side remains open permanently thereby obscuring the view of the main screen. For reference:

https://discuss.erpnext.com/t/mobile-view-issue/15616

Kindly help look into this

Thanks plenty

**Comment by netchampfaris** [comment]
This problem is occurring on stock browsers of Android phones with Kitkat.
The problem with stock browsers is that the javascript implementation is not very good compared to browsers like Chrome, Firefox and Safari.
If this problem can be solved using these browsers, I believe it is not worth the time debugging the problem for the stock browsers. Closing the issue.

**Comment by Olawale1** [comment]
Hi @netchampfaris 

Perfectly understood. Thanks for the effort

Cheers!
