### ISSUE TITLE
FEC compliant

### ISSUE THREAD

**Issue by qrevel** [frappe/erpnext#7665]
Hi,

It would be really nice for French companies to have the option to generate [FEC](https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000027788276&dateTexte=&categorieLien=id).

If we can't give it when financial authorities checks our accounts, we need to pay at least 5000€.

Thanks

**Comment by umairsy** [comment]
Hello,

Thanks for your interest.

Since ERPNext is an open source solution, you can get localization-related feature developed on priority by one of the ERPNext Service Provider.

https://community.erpnext.com/service-providers

You can post a job on the community portal to invite bids from the Service Providers.

https://community.erpnext.com/jobs

If you get it developed by third party, please consider contributing it to the core product, so that ERPNext community can benefit from it.
