### ISSUE TITLE
Overwriting value in Item Code should not be allowed

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7837]
Scenario:

1. Saved an Item.
2. Overwrote value in the Item Code field using Data Import Tool. Now, value in Item Code and ID is different.

The overwriting value in Item Code should not be allowed, but via Renaming.

Same could be applied in the following masters as well, if they are saved based in value entered by the user, and not based on Naming Series.

1. Customer
2. Supplier
3. Warehouse
4. Account

**Comment by Olawale1** [comment]
Hi @umairsy 

Trust you're doing great. We just ran into this same issue. A user updated hundreds of Item Codes using the Data Import Tool. Now the ID and Item Codes are different and when we try to upload other documents using the current Item Codes, we get error messages that they are not found!

I hope this issue can be fixed urgently so that other users don't encounter the same problem. I believe the Rename Tool is what should be used for these kinds of operations? Pls confirm

Thanks

**Comment by hujaifaibneomar** [comment]
hujaifaibne
