### ISSUE TITLE
Make Manufacturer Part Numbers a child table in Item instead of a data field

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8089]
- [ ] Add new Section "Manufacturer Details" and move the relevant fields out of "Supplier Details"
- [ ] Manufacturer and Manufacturer Partnumber should be editable grid child table
- [ ] write patch
- [ ] update documentation

**Comment by dottenbr** [comment]
@kickapoo please prioritize this because we need it for proper data migration

**Comment by dottenbr** [comment]
@nabinhait we would like to discuss this with you in a screenhero session if you can today

**Comment by dottenbr** [comment]
Fixed with https://github.com/frappe/erpnext/pull/8134

**Comment by vrms** [comment]
seems the merge https://github.com/frappe/erpnext/pull/8134 did not bring the desired functionality to v10, nor v11.0.3-beta.31 () (staging). 
![image](https://user-images.githubusercontent.com/7608112/50555643-87f11c80-0ccf-11e9-891f-7f79ca0fc333.png)


So the issue [still remains](https://discuss.erpnext.com/t/manufacturer-and-manufacturer-part-numbers/40922/6). Can it be somehow this did not makes it's way from develop to master since March 2017

**Comment by kennethsequeira** [comment]
Closing this as manufacturer and MPN are separate doctypes now. Reference v13.
