### ISSUE TITLE
Issues With Queue in New POS

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8112]
Hi,

Here are the immediate issues I encountered while checking the POS on demo.erpnext.com

There is a submitted transaction blocking the queue (not getting synced). The system was throwing up an error report which was subsequently forwarded to support. I however noticed that the customer for that particular sale did not exist (probably deleted before the sale could sync) so I went ahead to create a new customer with the same name. This resolved the first issue

After creating the customer, the error report stopped popping up but now there's an error message that says 'Due Date can not be before Posting Date'. The transaction is therefore still not getting synced and holding up the queue

Recommendations:

1. For the first issue, the system should have displayed an error message like 'Customer Not Found!' or 'Customer Does Not Exist!'

2. There should be a way to grant permission to certain categories of users to be able to delete submitted orders from the queue. This will come in handy for special situations like this so that transactions don't get held up until a bug-fix arrives!

Thanks for the awesome job you're doing

Kind regards,

**Comment by rohitwaghchaure** [comment]
Hi @Olawale1 
Have fixed the issue of 'Due Date can not be before Posting Date'.

**There should be a way to grant permission to certain categories of users to be able to delete submitted orders from the queue. This will come in handy for special situations like this so that transactions don't get held up until a bug-fix arrives!**

This is a specific requirement and it will not resolve the issue. If issue encounter during synchronization of an order, system will keep the invoice in draft mode.
