### ISSUE TITLE
Profit and Loss Period Monthly/Quarterly/Half-Yearly Period Range

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#8253]
Allow for the Profit and Loss Report's Monthly/Quarterly/Half-Yearly period range to be selected, so that if you wish to show accumulated monthly for only two months, you select a start date and an end date, and it displays only those months. Same for the printable report.

Instead of the "Start Year"  and "End Year"  fields, change them to "Start Date"  and "End Date", so the user enters a specific date, and the accumulated or monthly shows only for the selected portion.

**Comment by rohitwaghchaure** [comment]
Hi @Tropicalrambler 

Before adding start and end year, we were thought to add start date and end date.
But it was making a lot of problems, so we have added start year and end year instead of start date and end date.
We have encounter the issue as follow
If user has select start date as 1-1-2017 and end date as 1-5-2017 and periodicity as 'Quarterly' in filters. Then system will add the 2 column for period, in first column will show the data for period between 1-1-2017 to 31-3-2017 while for second it shows the data for period between 1-4-2017 to 30-4-2017 
User might be select the wrong date range, which will makes wrong calculation in P&L report.

**Comment by jwrober** [comment]
Could you add some checking logic into the report somehow to capture the issue where a person wants a quarterly view but only picks a couple days? 

Also with this, I think it would be great to also have an option to see the previous year's results from the same period. e.g if I want to see first quarter of 2017 (1/1/17 to 3/31/17), then with the check box checked I could see pro-forma comparison to same period last yer (1/1/16 to 3/31/16) with variance calculations done.

**Comment by PawanMeh** [comment]
![p l](https://cloud.githubusercontent.com/assets/20460498/25555712/4119a0d4-2d0b-11e7-9701-341456792d8d.png)
 
Closing this for now, other enhancements remaining can be managed as a separate issue.
