### ISSUE TITLE
Duplicated filtered results

### ISSUE THREAD

**Issue by mimiza** [frappe/erpnext#8299]
![duplicatedresults](https://cloud.githubusercontent.com/assets/20904034/24641486/6ec24b98-192a-11e7-8428-036853963f9e.png)

Filtered results are duplicated for Sales Order, Delivery Note, Invoices that have more than 1 item. Please add "GROUP BY ..." to its SQL query.

**Comment by joolsr** [comment]
yes, I have seen this issue too with 8.0.7

**Comment by adityaduggal** [comment]
Ideally I think users expect the filters to return one result  in case the filter is applied on the list view.
Hence list view should always show grouped values instead of each line item separately.

But the downside to this would be that in report builder if this behaviour is followed then it would not be acceptable to users.

So I think there is a trade currently with the way the system is designed and I guess the team would have to take a call whether to separate the 2 filtered behaviours or not.

I would suggest moving this to forums for discussion and once if there is a good consensus on this issue then probably we should re-open this issue.
