### ISSUE TITLE
Allow updates to raw material and manufactured quantity in production order

### ISSUE THREAD

**Issue by sathishpy** [frappe/erpnext#8436]
Raised as requested from https://discuss.erpnext.com/t/updating-manufactured-quantity-in-production-order/22377/1

In summary, some verticals like box manufacturing won't be able to stick to the listed quantity in BOM. As a result, they are likely to over produce than required manufacturing quantity. This request is to allow updating raw material and manufactured quantity based on a new setting or current 'Over Production' setting.

**Comment by sathishpy** [comment]
I don't see this issue anymore in my usecase, however I don't think the issue is fixed. I took a quick look and the code is still the same, so thinking the changes done at my custom app is taking a different path for production order, there by masking this issue. I will close the issue as it is not more affecting my usecase.

**Comment by tecnofoodmx** [comment]
Same issue.
We use ERP Next in a food manufacturing business.
Generally we have variable "raw material losses", which results in a slight variation on the final units produced vs the planned. 
In the case thre's an excess we cannot register the exceeded units. 
On the other hand, when we produce a lower amount vs planned quantity, the production order cannot be closed. Also, the raw materials are consumed proportionally to the amounts produced according to BOM. I would like to be able to assign the remaining raw materials to "material loss" in order to keep track of losses and precise tracking of stock levels. instead of using "stock recinciliation" every time.

Thanks for your support!

**Comment by federicocalvo** [comment]
Hi @tecnofoodmx , i have the same situtation whit a food industry. 

at the end of production, more or less may have been produced than originally established.

First of all, the overproduction option doesn't work for me. And secondly, I have the same problem when less is produced, they are open.

Were you able to work it out somehow?

Regards!
