### ISSUE TITLE
Issues With GL and Stock Ledger Entries in V8

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8492]
Hi,

It appears there are some issues with GL entries in V8. Steps to replicate:

1. Create a sale using the POS with 'Update Stock' option enabled in the POS Profile
2. View the accounting ledger and stock ledger from the generated Sales Invoice

Issues:

1. There is no accounting entry for stock even though 'Update Stock' is checked in the invoice
2. There are 2 entries in the stock ledger instead of one. One is a negative entry and the other is positive!

Please help look into these urgently!

Thanks

Kind regards,

**Comment by Olawale1** [comment]
Please look into this on priority as V8 is already released and being used in production. The implication is that financial reports and stock reports for users on V8 are grossly inaccurate!

Kind regards,

**Comment by rohitwaghchaure** [comment]
Hi @Olawale1 

See my comments inline

1. There is no accounting entry for stock even though 'Update Stock' is checked in the invoice
Can you please check [Perpetual Inventory](https://frappe.github.io/erpnext/user/manual/en/stock/accounting-of-inventory-stock/perpetual-inventory) is enabled

1. There are 2 entries in the stock ledger instead of one. One is a negative entry and the other is positive!
Can you please share the screenshots?

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

1. That was the first thing I checked. Yes, it's enabled
2. Please find screenshots below

![ledger entries issue 1](https://cloud.githubusercontent.com/assets/9269337/25173805/65657ec0-24ed-11e7-9489-c7842a8ba95e.png)
![ledger entries issue 2](https://cloud.githubusercontent.com/assets/9269337/25173806/656fe07c-24ed-11e7-819e-68c3a20fd354.png)
![ledger entries issue 3](https://cloud.githubusercontent.com/assets/9269337/25173807/6573d9de-24ed-11e7-95ab-b2d9ebf0c143.png)
![ledger entries issue 4](https://cloud.githubusercontent.com/assets/9269337/25173808/65a48f84-24ed-11e7-9dc3-a219fd4bf15d.png)

Thanks

**Comment by rohitwaghchaure** [comment]
Hi @Olawale1 

Thanks for sharing the screenshots
Can you please check **Ignore User Permissions** is enabled for the field **Customer Warehouse (Optional)** on the sales invoice item

![screen shot 2017-04-19 at 3 15 14 pm](https://cloud.githubusercontent.com/assets/8780500/25173870/4eba1106-2513-11e7-902b-e6c24fc9d684.png)

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

Yes, it is enabled

![ledger entries issue 5](https://cloud.githubusercontent.com/assets/9269337/25174609/d1e915d2-24ef-11e7-9838-2ccd76bb540e.png)

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure

Could you please confirm if you were able to identify the issue?

Thanks

**Comment by nabinhait** [comment]
@Olawale1 Yes, we have identified and fixed the issue, will release it soon. There was a problem with User Permissions, even though "Ignore user permissions" was checked for "Customer's Warehouse", it was setting warehouse based on users permission. That's why, there was 2 SLE and no GL Entry posed.

**Comment by Olawale1** [comment]
Thanks @nabinhait and @rohitwaghchaure for your quick response in getting this fixed. Could you please let us know as soon as this is released? As you can imagine, we're quite eager to have this patched

Also, I guess this means we have to cancel all invoices done after the upgrade and re-post them? Pls confirm 

Thanks

**Comment by nabinhait** [comment]
@Olawale1 Released the fix.

Regarding the correction of the affected entries, if you have only few entries which are affected, then better to cancel and amend them manually.
Otherwise, I had written a script a long time ago, when this issue was crept in for the first time after releasing the Customer's Warehouse feature. You can use the script to repost and correct the entries. Note, the script is outdated, you need to check it manually once, may be run the script in local once before running into production.

The steps are written in the script/patch itself. Please check https://github.com/frappe/erpnext/blob/develop/erpnext/patches/v6_12/repost_entries_with_target_warehouse.py

**Comment by Olawale1** [comment]
hi @nabinhait 

sorry for commenting on a closed issue but not sure if this should be a new one. After updating to the latest version, I tried Cancelling and Amending existing Sales Invoices as discussed. I noticed that the accounting ledger from the amended invoice gets updated properly but the Stock Ledger still has 2 entries (positive and negative)

Please advise

Kind regards,

**Comment by nabinhait** [comment]
@Olawale1 Amending the invoice, might not remove the automatically selected warehouse from Customer's Warehouse field. Please check once by making the field visible from Customize Form, if it's not removed, you need to remove it manually.
