### ISSUE TITLE
Will this run on PostgreSQL?

### ISSUE THREAD

**Issue by raarts** [frappe/erpnext#8725]
I searched the issue list, but apparently nobody ever asked this question. So here it is.

**Comment by vrms** [comment]
hi raart. Thanks for your contribution. 2 things

1. I don't think think this is no issue though but would sit much better in the [ERPNext Forum](https://discuss.erpnext.com)

2. where did you conduct your research? I think you can get some insights in this discussion here https://discuss.erpnext.com/search?q=postgresql

So, I'm closing this now due to the aforementioned

**Comment by wahello** [comment]
Postgres is a better match to erpnest.
