### ISSUE TITLE
Item Variant has Image, do not Copy image from Template Item

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8774]
Currently, image updated for the Template Item is updated for the Variant Items as well. If Variant Item already has image updated for it, then updating image in the Template Image should not have any impact on the image of Variant Item.

**Comment by stelden** [comment]
Item Variant should inherit or override Item Template image

**Comment by adityaduggal** [comment]
@umairsy How would the system handle the scenario when someone wants to override the item variant's image.

Suppose, variant has an image same as template but later stage there is a new improved image and user wants to update the image for variants then if your logic is applied then it would mean that the user has to update the image for all items individually instead of in the template.

This is a question of perspective, either way one of the 2 users would have to upload the image for all items.

I think if we have an option to import image into a variant without manually doing it then it should not be an issue.

**Comment by umairsy** [comment]
When uploading an image in the template item, perhaps we can ask if they want to update same item for all the variant items as well or no. Also notify that images uploaded in the Variant Items will be over-written.

Updating images manually forthe Variant Item is always an open option.

**Comment by adityaduggal** [comment]
Well ideally I think that the users should have an option to make the file as NO_COPY in customize form view and then if they made the image field NO COPY it would not get copied from the template to the variant.
I think this ways we could get best of both worlds

**Comment by stelden** [comment]
I believe the logic would be:

If Template has image, new Variant inherits Template image.
If existing Variant has custom image (user replaces inherited image) then changes in the Template image should not affect Variant with custom image i.e. change variant image if and only if it has the Template image. Like OO inheritance.

**Comment by umairsy** [comment]
Now, it's manageable via Item Variant Settings.
