### ISSUE TITLE
Manage Goals in ERPNext

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#8777]
Most businesses / organizations are driven around goals. There must be a way to manage these in ERPNext. Common goals are

#### Sales

1. Increase sales
1. Increase number of customers
1. Increase renewal / retention

### Operations

1. Speed of delivery
1. Speed of response
1. Speed of task completion
1. Better resource allocation
1. Increase customer satisfaction
1. Increase employee satisfaction

### Finance

1. Lowering expenses
1. Lowering inventory
1. Speed of collection of payments
 
### Quality

1. Fewer issues
1. Faster replies
1. Fewer rejections

---

- [ ] DocType Goal
  - [ ] Frequency (weekly, monthly, quarterly, annual)
  - [ ] Source (doctype eg. Sales Invoice)
  - [ ] Source filter (by fieldname, eg. company etc)
  - [ ] Type of aggregation (sum, count or average)
  - [ ] Sum field (eg. grand_total)
  - [ ] Target (eg +10%)
  - [ ] Public or Private
  - [ ] Goal owner (or group, child table?)
- [ ] DocType "Goal Performance"
  - [ ] Goal, Date, Value
- [ ] When a new goal is created, create "Goal Performance" for the last 3 months
- [ ] Email notifications for goal, if weekly, monthly etc
- [ ] UI notifications for goal
  - [ ] When relevant DocType is updated, show the user the progress
  - [ ] Goal dashboard :man_facepalming: 
  - [ ] Timeseries view of goal performance over time

**Comment by mhbu50** [comment]
+1

**Comment by vladucoju** [comment]
+1

**Comment by joolsr** [comment]
Especially true for sales, in terms of Quote / Sales Order win percentages etc

**Comment by agritheory** [comment]
I propose status fields so these can be incorporated into Kanban tool

**Comment by rmehta** [comment]
This was just the vision for the generic feature. Sales target goals have been implemented #9723 

Lets raise specific issues for specific goals.

**Comment by mhbu50** [comment]
@rmehta I need this to be generic feature, I want to be able to use it for any kind of doctype

**Comment by Olawale1** [comment]
Hi @rmehta 

Trust you're doing great. This has to be generic! Goals are very widely varied across organizations. The importance of flexibility (and dashboards) in this feature cannot be over-emphasized. I think you already laid out a great baseline in your original post here and it generated a lot of positive interest - Please consider following through as earlier outlined

Many thanks!

**Comment by Olawale1** [comment]
Hi @rmehta 

Trust you're doing great. I observed that @pratu16x7 had already started some work on this as highlighted in your Open Day report for the month of June:

![goals card 1](https://user-images.githubusercontent.com/9269337/29008277-3fee2550-7b0c-11e7-8f20-b7d38f82e342.png)

![goals dashboard 1](https://user-images.githubusercontent.com/9269337/29008279-4c7ad7e6-7b0c-11e7-9c0a-4795ae932bd5.png)

I believe the major part that's left for the Goal DocType is the Source Filter (i.e. fieldname) and also a 'Goal Category' field which I'd suggest should have a Tree structure similar to Item Groups 

The Goal Performance could be achieved using a format similar to the one currently used for analytics (which I think would serve this purpose beautifully). All Goals would be represented graphically on the 'Goal Analytics' chart and grouped according to the 'Goal Category' mentioned above. Goal Value would have to be in terms of percentage achieved (as this would be the common denominator across all types of goals)

Of course, the analytics chart would only display goals with the same frequency (i.e. Daily, Weekly, Monthly, Quarterly, Yearly) simultaneously so there may have to be a select field for this somewhere at the top

This would be an **extremely** valuable tool for Management in any organisation. Please consider reopening or let me know if you think it's better to open a new issue

Thanks a lot

Kind regards,

**Comment by rmehta** [comment]
@Olawale1 we had a lot of discussion on this and decided that it is best to build analytics as a use case rather than general tool. If you have specific use cases for analytics, please search on the issues list an upvote with a 👍 or raise a new issue.

**Comment by Olawale1** [comment]
Hi @rmehta 

Thanks for your response. I'm not sure if the explanantion was very clear but this is for a specific use case! I'm saying we should have a 'Goals Analytics' based on the Goal DocType just like we have 'Sales Analytics' based on Sales Order/Invoice DocType

I'm happy to open a new issue for this as per your suggestion but what about the underlying 'Goal DocType' on which the analytics is based? Will @pratu16x7 or anyone else be finishing work on this? It might not make much sense to open an issue for Goals Analytics when the Goal DocType is not ready

Looking forward to your feedback

Thanks plenty

**Comment by Olawale1** [comment]
> we had a lot of discussion on this

Just in case you were referring to the Goal DocType here, I'm wondering if your discussion included any input from the community? It's hard for me to think of any end user who wouldn't prefer this as a generic feature since it's practically impossible for you to satisfy the requirements of every user

For example, I have a goal in my organization to ensure a certain number of podcasts are downloaded this year. I also have a separate target for distribution of Newsletters and E-Magazines. Are you going to create those as standard Goals for all users in ERPNext? What about some of my friends who have goals to attain a certain number of translations for their widely circulated publications and those who have goals to increase their website membership or blog viewership to a certain number? Will you create separate Goal DocTypes for them too? These are just people around me! What about the peculiar needs of hundreds of other ERPNext users?

Personally, it would be Ideal for me to just open up a New Goal form and select my custom 'Downloads' form as the source with the 'Number Downloaded Today' field as the Sum field. Other options like Frequency, Filters, Category will be selected accordingly and the graph automatically gets displayed in the Dashboard at the top of the form (Just like in the Company DocType). This would be fantastic and everyone can just go ahead and manage their own goals individually rather than wait for you to build every imaginable kind of Goal into the core of the system

I really think you should get a broader view on this from the community

Kind regards,

**Comment by rmehta** [comment]
@Olawale1 the design what I proposed seems ideal but was not feasible. Its best to build blocks and reuse. If anyone from the community wants to go for it, let them do it. Lets not re-open this unless we have new information.

**Comment by Olawale1** [comment]
> the design what I proposed seems ideal but was not feasible

This seems to suggest some form of technical restriction and not just opinion... if that's the case then it's fine. Unfortunately, the greatest limitation will still fall on ERPNext cloud users when they need to implement Goals that aren't common to everyone 'sigh...'

Kind regards,
