### ISSUE TITLE
Quotation Lost Reason - from "Small Text" to "Link"  

### ISSUE THREAD

**Issue by mosabamf** [frappe/erpnext#8820]
in Quotation Form we need to change **Quotation lost reason** Filed Type from **Small Text** to **Link**  to be linked to Custom DocType called **Quotation Loss Reason** in Selling module setup, in this Quotation Loss Reason you can add whatever reasons you've  

![image](https://cloud.githubusercontent.com/assets/21178114/26031036/5782e858-386e-11e7-8223-5c4d8b7f57d3.png)

![image](https://cloud.githubusercontent.com/assets/21178114/26031027/32b3c22c-386e-11e7-8aba-8375cd1a8085.png)

**Comment by mosabamf** [comment]
Hi, any update or comment?

**Comment by umairsy** [comment]
Hi,

Nice feature suggestion. Hope you will understand that we receive any such suggestions but have limited resources to implement them. Would you be interested in sponsoring this feature development, so that we can look at doing it on priority?

Since ERPNext is an open source application, you can also contribute this feature or get it done by one of our Service Providers, and get it contributed in the ERPNext.

**Comment by mosabamf** [comment]
Many thanks for reply, I think it's simple and I can do it myself if I've access to change field type as already custom DocType made

**Comment by AleCVERP** [comment]
Hi 
Your help please
Maybe you know how to increase a combo box in the Quotation Lost Reason form? I was trying to place it manually but it tells me that I do not have permits for that action.
