### ISSUE TITLE
Suggestion For students result

### ISSUE THREAD

**Issue by xcell009** [frappe/erpnext#9017]
I would like to suggest the following:
1. It should be possible to make an assessment plan for more than one course (or for the program specified in a student group based on batch) if all the courses will be using the same Assessment criteria.
2. The assessment result should contain fields for academic year, term and course.
3. It should be possible to generate some kind of report card for the student, listing the courses in rows where for each course, the score for the various criteria​, the total score and grade is shown in the same row.
4. As already suggested, the assessment result tool could use a save/submit/create button.

**Comment by manassolanki** [comment]
Hi @xcell009,
Thanks a lot for your suggestions. Changes in the assessment result tool are currently WIP. We have already decided to add save/submit button in the assessment result tool and related field in the assessment result. Additionally, reports for the assessments are also in WIP.
One thing I am not sure about is assessment plan for more than one course. Currently, we can have assessment plan against the student group (based on batch) but since that also includes scheduling of the assessment plan so that will be a problem if we are considering multiple courses in a single assessment.
We have already created an issue (https://github.com/frappe/erpnext/issues/8737) for this discussion, so I think it will be better if we can continue this discussion on that thread.
