### ISSUE TITLE
User Permissions: Child Warehouses Automatically with Group Warehouse

### ISSUE THREAD

**Issue by LifeP** [frappe/erpnext#9411]
Present: Have to set User permissions for each child warehouse individually.
Selecting parent warehouse does not show child nodes.

Proposed: On selecting Parent Warehouse, All child warehouses should be automatically selected and permissions be set accordingly.

**Comment by Olawale1** [comment]
Hi

This affects all DocTypes with a tree structure and not just Warehouse. There should be an option to set hierarchical permissions so that there is no need to set permissions for all child nodes

If I give a user access to view 'Customer Group A' and Customer Groups A1 - A10 are all children of Customer Group A, then the user should be able to view them as well (if hierarchical permissions are enabled for Customer Group). Right now, we must set permissions for every single Customer Group individually

I'm just using Customer Group as an example here. This is applicable to all documents with a tree structure as mentioned earlier

Thanks

**Comment by manassolanki** [comment]
@Olawale1 , This applies to all structure except the FILE doctype where we need to set the permission for all individual files also.(PS. File is also a tree structure)

**Comment by Olawale1** [comment]
Hi @manassolanki 

You're absolutely right! Very good of you to note that

Thanks

**Comment by Olawale1** [comment]
Hi @manassolanki 

Actually, now that I think about it, there's no need to specify that the File DocType should be excluded. As mentioned in my first post above, there should be an option to enable/disable hierarchical permissions on each DocType so the user can decide where they want it applied or not

Thanks
