### ISSUE TITLE
Workflow issue for payment approvals

### ISSUE THREAD

**Issue by manivk** [frappe/erpnext#9464]
Hi

ERPNext has a single payment entry whether it is a receipt or payment. Receipt entries are entered directly by the accounts user whenever a we receive money in our bank. These entries do not need any approval.

But for payments to be made to suppliers, partners, vendors, employees etc., we need to go through a payment approval process where the manager / director needs to approve the payment before it can be made to the supplier. 

But, when I set up a workflow to do this, unfortunately even the receipts have to go through the same payment approval process which does not make sense.

There is a document called payment request but that is only for requesting payments from Customers. 

So there is no way right now in ERPNext to get approvals for payments before they are made. This is a very important functionality for any organization to ensure payments are tightly monitored. 

We are ready to fund this feature as a paid development if it can be implemented. Request you to look into this.

Thanks
Mani.

**Comment by umairsy** [comment]
Hello Mani,

Thanks for elaborating your use-case. The feature of conditional application of Workflow is already on our todo list. Please followup with us via following Github Issue to get this feature implemented.

https://github.com/frappe/erpnext/issues/6749

Also, you can consider sponsoring this feature, so that we can check into it on priority. Further followup via Github Issue shared below please.
