### ISSUE TITLE
Variants not Updated when Item Master is Updated

### ISSUE THREAD

**Issue by somicoito** [frappe/erpnext#9482]
If Item Variants are not updated when you update Item Template there is no need to use Variants anymore.
Are you willing to reintroduce this function? Why did you remove it?
I chose ERPNext instead of Odoo also because I preferred the way variants were managed.
Last I think you should let also users of Hosted Plan to be able to decide which fields can be set as NoCopy.

**Comment by tundebabzy** [comment]
Hello @somicoito 
#4253 for the history of the change of behaviour. Because ERPNext is completely open, if you can put up a convincing argument and get a lot of community members in your support, the present behaviour can be reverted.

Please start a new discussion on https://discuss.erpnext.com as we don't use github for discussions. You can mention @rmehta in your post.

Closing this for now.

**Comment by adityaduggal** [comment]
@rmehta I think this is a valid ERROR in  ERPNext.
Old Behaviour. For example there is a template T1 and it has 100 items (variants) under it then if we need to change the default warehouse of all the variants then we only had to change the default warehouse of T1 but now its not possible.

I think this feature was removed in the last 20~30 days only. And I believe that doing so is a very BAD idea.

**Comment by adityaduggal** [comment]
I have tried to resolve this issue in my custom app till there is a decision by maintainers on this.
I have added 2 fields to the Stock Settings as below:
![image](https://user-images.githubusercontent.com/1057509/28450896-cf7dd36c-6e07-11e7-9dac-26a4a81da3ec.png)
Now the 2 fields are:

1. First is checkbox to want to be able to run the HOURLY cron to update variants from templates.
1. Second is the limit to the cron job on the number of fields to update in one hour this is done to ensure that the cron job not fails the first time and small changes can be made initially since any validation errors would fail the code.

I have added the commit https://github.com/adityaduggal/rigpl-erpnext/commit/55709a1080d901da8f9b1e0506b4410dd9f404f6

Now I know it might not be the best of the ways to implement it but if the team wants I could send a pull request for the same. If they want to review the code.

I would also like to test it on my live server before I commit to its feasibility and correctness for errors.

**Comment by somicoito** [comment]
@adityaduggal thank you for this! I agree that updating variants is crucial, otherwise there is no sense to use them, better to copy from other items so you don't have to create a template...
I also think that every company has different needs for fields to set NoCopy, maybe this is why they simply removed the Copy function? Don't know but in my case... I need to set some fields as NoCopy but can't as I am on a Hosted Plan and have no access as Admin.

**Comment by GiorgioKN** [comment]
I agree completely with @somicoito @adityaduggal

**Comment by GiorgioKN** [comment]
Hi,
any update about this? I have just imported 100 items + variants and I´m having quite a bad time in uploading images to all of 700 products.

**Comment by rohitwaghchaure** [comment]
Fixed via https://github.com/frappe/erpnext/pull/10595

**Comment by GiorgioKN** [comment]
Hi,
Thank you for the good news.

When this will be available for the cloud version?

Best regards,

Giorgio Alessio
Marketing Director
Jorretuote Oy – Kn Collection
www.kncollection.fi<http://www.kncollection.fi/>
email: giorgio.alessio@kncollection.fi
Tel: +358 45 1832448
