### ISSUE TITLE
Barcode scanning in stock reconciliation

### ISSUE THREAD

**Issue by gbard** [frappe/erpnext#9557]
Is it me or we can't use the barcode scanner in the stock reconciliation form? Isn't it a feature that would be useful? Would be a lot quicker than having to type each item codes.

Thanks!

G.

**Comment by umairsy** [comment]
Hello,

Currently, Barcode field is only available in the transactions like Purchase Receipt, Delivery Note etc. This is based on the idea that when creating a transaction, will you have item physically available for scanning? Does that apply for Stock Reconciliation?

**Comment by LifeP** [comment]
@umairsy Yes, stock-reconciliation is generally physical verification of the stock.

**Comment by johnlongland** [comment]
Good day. I see V12.29 has just been released. Thank you ! Is it not possible to add this feature to the next release?
Thank you

**Comment by ikslavok** [comment]
As @umairsy said, reconciliation is usually the physical validation of stock. So best workflow would be: scant barcode > insert value + enter > insert qty + enter. Looking at the stock entry doctype I noticed it uses this function scan_barcode.

So **this is how you make the scan field work in stock reconciliation**:

1. Customize stock reconciliation. Add before Items Scan Barcode Data field with `Barcode` as the value in options. Uncheck translate. Optional: Move customizations to your app "export customisation option"so that it stays permanently there.
2. Next, edit this file add this function to `apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.js`. Add this function after refresh function:

```
scan_barcode: function() {
		let transaction_controller= new erpnext.TransactionController({frm:this.frm});
		transaction_controller.scan_barcode();
	},
```
Next thing we should figure out is how to allow multiple rows of the same item. Because, at least in our workflow, we sometimes have same items in different places in store or warehouse. And when we scan same item again and click save it warns there is a duplicate. So than we scroll back to find where we first scanned it. This was a big no no for our team and they went back to old system of reconciliation. This was mentioned in #26337 BTW.

**Comment by ankush** [comment]
Just doing those code changes isn't enough. Currently, on picking warehouse, we are resetting the quantity and value to available qty (so user can update the new count)

I tried this around a week ago, not sure how to integrate this without breaking other's workflow. 😐 

Maybe by adding a "scan mode" which will disable previous behavior and only add data based on scans. That way those who want to use scanning exclusively can use that while old workflows can still be maintained.

**Comment by ikslavok** [comment]
Ha, you are right. I have warehouse set in session default when I am in a specific warehouse. And it works great on mobile. Fills instantly valuation rate and qty available per warehause. But when on PC it won't fill those things.

I have to correct myself regarding the duplicate rows thing, it does update qty automatically if using scan_barcode and actually feels smooth to work with. But when adding by item code it prompts duplicate. Its good for now, but would be nice when the barcode is not available to be able to update qty by item code.

**Comment by ikslavok** [comment]
This is a bit off-topic regarding this issue. But if we are talking about how to furthermore improve Stock Reconciliation, there are two more features that would improve the experience. Newest added on top instead of on bottom and autosave.

**Comment by ankush** [comment]
@ikslavok @johnlongland 

can you check out https://github.com/frappe/erpnext/pull/30446 and share feedback if any :)
