### ISSUE TITLE
Shipping and billing party different

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#9569]
We can have different billing and shipping address in our system, but it is linked to just one party. In many cases, we may be required to deliver to different party, 

In that case billing party is different from shipping party.

We can link address of shipping party with billing party, but that is not the best way to go with that, as name of party to whom we are delivering is required in invoice.

**Comment by adityaduggal** [comment]
This is a not an issue and can be easily handled by erpnext. Post it on forums since it does not belong to github.

If I am understanding correctly you want to raise an Invoice to One Customer but want to ship to another customer and for this you can link the address correctly as rightly pointed out linking a Sales Invoice to 2 customers would be a big mistake according to me. 
Request you to close this issue as I don't believe it belongs to github.

**Comment by snvora** [comment]
U are right. I can fetch address. True.

But the issue is different.

In such scenario it is also required to mention name of shipping party along with address. That is not possible right now as there is no field as shipping party. Currently we are shipping with the name of billing party on it... Completely wrong I feel.

About linking it with 2 customers... It may be good in a way... Because query may come from either party and we should be able to trace it. 

It's about how best we can deal with this complexity.

If you still feel I should close this issue, I would surely do that...:-)

**Comment by adityaduggal** [comment]
Well we generally have a custom field which fetches the ADDRESS title in our organisation and that is shown in the print format.

We are already using this feature the only issue is that you are unable to show the name of the customer in your PRINT FORMAT, which can be easily achieved by printing 
`{{ frappe.db.get_value ("Address", doc.shipping_address_name, "address_title") }}`


So I don't think there is a need to link it to 2 customers.
