### ISSUE TITLE
Missing payments for clearance

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#9610]
Hi,

When a payment is included in an invoice, no payment entry is generated and  therefore this payment is considered as cleared automatically.

It is not correct for cheques for example, since you still need to deposit your cheques on your bank account  and clear the payment at a later date.

Currently, the report "Update Bank Transaction Dates" only supports payment entries and journal entries. It should also fetch data from directly paid sales invoices.

**Comment by umairsy** [comment]
Thanks for the details. The feature of payment in the sales invoice has been added for POS invoices where payment generally comes in Cash or Card (bank). For the cheque payment where you need acknowledgment details and bank reconciliation, please create Payment Entry separately.

Keeping this issue open for sometime, so that we can gauge demand from other users on it.

**Comment by chdecultot** [comment]
Hi @umairsy,

Thanks for your feedback.

I will also try to find some time to work on a solution for this issue since it is important for people working with the POS. In France, unfortunately, a lot of people still pay with cheques... :wink:

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
