### ISSUE TITLE
Negative permission rules

### ISSUE THREAD

**Issue by alejandroc2003** [frappe/erpnext#9822]
Hello. 

Is there any way to prevent a user see any activity of a specific Supplier?

The problem is that the permission available is only to define "allowed supplier" to a user. I want the opposite. 

Regards.

**Comment by umairsy** [comment]
Hello,

This feature is not available for now.

Perhaps you can define Supplier Types which will allow you to assign group restriction. For the Users, you can apply restriction based on Supplier Type, instead of specific Supplier. As per this system, if new Supplier is added, based on it's Supplier Type (or any other link field based on which permission restriction is applied), restriction will be applied on that new Supplier as well.
