### ISSUE TITLE
Payable Account filteration

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9867]
As per the current validation, Payable Account in the Expense Claim filtered based on Root Type as well.

https://github.com/frappe/erpnext/blob/develop/erpnext/hr/doctype/expense_claim/expense_claim.js#L229

Can we remove this validation and allow selection of all the Payable Accounts. That will be helpful for the Company who use ERPnext for imprest management as well.

**Comment by rohitwaghchaure** [comment]
Hi @umairsy 
Payable Account head always be liability account therefore added filter of root type. I think imprest management will not get by just removing the filters. Can you please brief more?

**Comment by umairsy** [comment]
Imprest money is an advance given to the Employee for managing expense, hence it should come on the Asset side. Though Expense Claim is not optimize for the imprest management, but we generally suggest using Expense Claim for it.

https://frappe.io/blog/erpnext-features/managing-imprest-in-erpnext

On the same lines, user is trying to select an Asset account in the payable account field, hence the issue related to Root Type of an account. Can we just validate the Account Type and not the Root Type?

**Comment by pkmuqthar** [comment]
Hi All,
I would like to provide my input here our original request was to have the option or selecting both payable or receivable account from the expense claim module. Since the system does not have any other option for imprest management we are using expense claim module for both payable and receivable cash.
If this is not possible when we ask for the alternate option to select from current assets also as payable account. This way at least we can overview the employee cash status and adjust it in the final statement.
Current setup does not allow us to overview the money owed by the employee to the company unless we make manual journal entry without any records or references, which is not good practice.

Regards
Muqthar

**Comment by pkmuqthar** [comment]
Still doesnt show up account in expense claim module(Account type: payable,
Root type: Assets, report type: Balance sheet)

Regards
Muqthar

**Comment by umairsy** [comment]
We have made changes from our end which will be released in your ERPNext account by Wednesday.

**Comment by pkmuqthar** [comment]
Great. Many Thanks

Regards
Muqthar
