### ISSUE TITLE
GST Queries

### ISSUE THREAD

**Issue by neuralaccounts** [frappe/erpnext#9901]
Hi,
Actually i am having 2-3 queries regarding GST Application in ERP system
1. We have to pay GST on Reverse Charge Basis for transactions entered into with Unregistered Dealers how to show such transactions in ERP
2.  We have to pay tax on all expenses exceeding Rs.5,000 per day but in system only for item codes HSN and SAC bifurcation is made mandatory. Then how we can make expense entries in system & it is not preferable to prepare purchase invoice for each and every expense. I think we should have one more report for expense.
3. Now we can claim input credit for all expenses entered with registered dealers provided our GST TIN number is quoted on it (Eg. Electricity Expenses, Corporate Mobile, Telephone expenses incurred for company ) How such transactions are to reflected under system
4. In GST Advance received & paid , both the transactions are to be reflected with tax on it , how to capture this in ERP
5. Additional Import expenses charged with GST were earlier reflected under landed cost but now even for those expenses we can claim input credit

**Comment by umairsy** [comment]
Hello,


We have to pay GST on Reverse Charge Basis for transactions entered into with Unregistered Dealers how to show such transactions in ERP

**Please explain your use-case with an example on support@erpnext.com**

We have to pay tax on all expenses exceeding Rs.5,000 per day but in the system, only for item codes HSN and SAC bifurcation are made mandatory. Then how we can make expense entries in system & it is not preferable to prepare purchase invoice for each and every expense. I think we should have one more report for the expense.

**Create Purchase Invoice for all kinds of expenses. You can create an Item Code and assign it HSN/SAC code, if not available. You can also set Purchase Invoice as "Is Paid" so that no need of creating separate payment entry against it.**

Now we can claim input credit for all expenses entered with registered dealers provided our GST TIN number is quoted on it (Eg. Electricity Expenses, Corporate Mobile, Telephone expenses incurred for company ) How such transactions are to reflected under system

**May be you can maintain separate GST Account for the input credit and use it in your purchase transactions. This shall work just like it used to in VAT regime.**

In GST Advance received & paid , both the transactions are to be reflected with tax on it , how to capture this in ERP

**Create Sales Invoice for the Advance Payment Received as well and share that invoice with the party.**

Additional Import expenses charged with GST were earlier reflected under landed cost but now even for those expenses we can claim input credit

**When you create Purchase Invoice for the import charges, mention GST account for the input credit in it.**
